### PR TITLE
Proposal for consensus in tla plus from Informal Systems

### PR DESCRIPTION
**Pull request by ebuchman**
This is a proposal from [Informal Systems](https://informal.systems) to begin work specifying Polkadot's consensus system (ie. Grandpa + BABE) in TLA+ and verifying it's properties. This initial proposal is focused on high level properties of Grandpa to lay the ground work.

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. Could you change the payment to BTC (according to the current market price) and also integrate the three first bullet points of the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#open-grant-proposal)?

**Comment by ebuchman** [comment]
Fixed!

**Review by Noc2 — APPROVED** [review]
Thanks for updating this. Looks good to me and I would be willing to go ahead with it.

**Review by Noc2 — APPROVED** [review]
Thanks for all the additional information, also via email. I’m happy to support the project and will ask the rest of the committee to take a look at the proposal.

**Review by mmagician — APPROVED** [review]

**Comment by Noc2** [comment]
Hi @ebuchman, it seems we don’t get the necessary approval for this grant. Everyone seems to be more or less interested in the project, but the main concern is that the grant on it’s own isn’t so useful and the overall project will become very expensive based on your current day rate. So, would it be possible to reduce the price further (also knowing that you have a certain flexibility on when you want to work on the project).

**Comment by Noc2** [comment]
On-hold for now, see email.

**Comment by Noc2** [comment]
@ebuchman would you still be interested in this? A lot of things have changed since we last discussed this and I think we would now fairly easily get the necessary approval.

**Pull request closed without merging**
