### PR TITLE
project mod

### PR DESCRIPTION
**Pull request by subtly**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by subtly** [comment]
Thank you for reviewing.

Project mod is to implement CLI tools written in Rust; you can see example commands for mod at the end of milestone 2. One benefit is being able to create, validate and sign transactions from an offline terminal.

It isn't an educational grant application; I've made updates to reflect that and fixed the links to previous code. As per your other questions, we were advised by several people to apply for a grant here.

Is there something specific about the team you'd like to better understand?

**Comment by Noc2** [comment]
To be honest, I was expecting a CLI tool written in rust as part of your previous grant and if I remember correctly you told me that you potentially would switch to a rust CLI (or otherwise you need to integrate rust bindings) for your second milestone. Together with the fact that you haven’t updated the repos of your current ongoing grant since the delivery, looks to me like if you basically want to receive a grant to work on something, for which you already received a grant. So, I think you should finish your current grant first and after this potentially reapply for another grant.

**Comment by subtly** [comment]
Again, I don't understand what you mean by receiving a grant for work which we've already received a grant for. _That is definitely not the case_. As can be seen on github, our previous development efforts consisted entirely of JavaScript.

> To be honest, I was expecting a CLI tool written in rust as part of your previous grant and if I remember correctly you told me that you potentially would switch to a rust CLI (or otherwise you need to integrate rust bindings) for your second milestone.

It very much sounds like you would like us to implement a CLI tool written in rust. If you agree that that would be useful, then what is wrong with this grant, which proposes to do just that?

Regarding not updating our repos: I'm sorry, David. I'm afraid you may not understand why we applied. We read that the approval and payment for the Open Grants program would be faster and without a lot of bureaucracy. Given our needs, we feel its a good fit, and it seems like a good idea compared to our prior experience with other grant programs. I do hope you'll reconsider.

**Comment by Noc2** [comment]
> Our previous efforts consisted entirely of JavaScript. So I don't see this as receiving a grant for work which we've already received a grant for.

This application also consisted of javascript, until your last commit [9924158](https://github.com/w3f/Open-Grants-Program/pull/18/commits/9924158761af3cd4c8bf2720aa4c39ad897d3c51), which you added after your commented and it wasn’t clear to me that your previous application was about javascript. As I said before, I think at this point it makes a lot of sense that you finish your previous grant, before we discuss any follow-up grant (especially if they are so closely related). I therefore will close this application for now. Of course, anyone from the committee can reopen it, in case they think, we should go ahead with the application at this stage.

**Pull request closed without merging**
