### PR TITLE
ZK Rollups CLI

### PR DESCRIPTION
**Pull request by SotaWatanabe**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by mmagician** [comment]
@SotaWatanabe Thanks for the application. At the moment there's a discrepancy between total cost and M1 cost. Furthermore, I assume the quoted 0.35 was meant to be BTC (and not DAI) - please note that as of recently we only support Open Grants with DAI - please adapt accordingly.

**Comment by SotaWatanabe** [comment]
Thanks @NoCtrlZ for the update. We have updated the DAI amount. Given that the original amount of ZK Rollups milestone 2 was 1.45 BTC (79100 DAI),  I think we have dramatically reduced the amount. @mmagician

**Comment by mmagician** [comment]
@SotaWatanabe What do you mean by `restart the whole network`? Are you referring to the L1 (i.e. an evm-compatible substrate chain)?
In my view this should be decoupled from the zkRollups functionality. I would think that users either deploy the contracts to a public network or a local testnet - either of which should be independent of deploying a rollup layer. Please correct me if my thinking is off here.
Unless you are referring to the server/operator - which, as far as I understand, would consist of restarting the appropriate docker container, right?

Overall, I would like to support further progress with the ZKRollups project, although in my view the price of the proposed milestone is not adequate to the scope. I find it hard to imagine how building a CLI tool with the suggested functionality would take 2 months, especially given the work done for the previous grant, where it was already possible to launch all the containers. I understand that you'll have to do testing of the tool, but unless I'm missing something, it's a wrapper for underlying docker commands.

---
> Given that the original amount of ZK Rollups milestone 2 was 1.45 BTC (79100 DAI), I think we have dramatically reduced the amount.

True, although I feel like it's comparing apples to oranges, since the scope is completely different (development of zkp infrastructure in substrate vs. wrapper).

May I suggest reducing the price? Perhaps 5000 DAI would be more realistic.

**Comment by mmagician** [comment]
@SotaWatanabe Any updates on this? I'm happy to jump on call if you want to discuss this further.

**Comment by mmagician** [comment]
@SotaWatanabe Sounds good, I sent you an email to coordinate that better.

**Comment by mmagician** [comment]
Update: After a discussion with the team, we keep the application open until the costs are updated.

**Comment by alxs** [comment]
@SotaWatanabe are you still interested in this? Otherwise we'll close the PR soon due to inactivity.

**Comment by NoCtrlZ** [comment]
@alxs 
Sorry for the late response.
We are preparing a new proposal!
We'd like to reopen this PR when we propose again.
Thank you!

**Comment by Noc2** [comment]
Thanks. I will close the PR.

**Pull request closed without merging**
