### PR TITLE
Add ares protocol proposal 

### PR DESCRIPTION
**Pull request by jiyilanzhou**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few questions:

- How exactly is your oracle module different from existing solutions like the [oracle module implementation by acala](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle) or in general chainlink?
- How do you plan to integrate the randomness? 
- The estimated duration of your first milestone is 3 week (FTE = 3) and the costs are 0.5 btc, why does the second milestone with 5 week (same FTE) costs 4 times the amount
- Could you clarify which of the deliverables (e.g. scanner) will be implemented as a substrate pallet and which potentially will be integrated separately and if so how do you implement these features (e.g. programming language/framework).

**Comment by jiyilanzhou** [comment]
> Thanks for the application. I have a few questions:
> 
> * How exactly is your oracle module different from existing solutions like the [oracle module implementation by acala](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle) or in general chainlink?
> * How do you plan to integrate the randomness?
> * The estimated duration of your first milestone is 3 week (FTE = 3) and the costs are 0.5 btc, why does the second milestone with 5 week (same FTE) costs 4 times the amount
> * Could you clarify which of the deliverables (e.g. scanner) will be implemented as a substrate pallet and which potentially will be integrated separately and if so how do you implement these features (e.g. programming language/framework).

Thanks for the review

*  It may similar with chainlink, acala not parse quest event, lack of flexibility.  chainlink no have feeder manager.
* Ares will use VRF to manager aggregator implement randomness, In this grant no plan to implement this. 
* milestone estimated duration has update.
* I will use golang implement scanner and provider. it may use [go-substrate-api](https://github.com/aresprotocols/go-substrate-rpc-client), aggregator,validator,council implement as substrate pallet,  written in Rust as substrate customized module.

**Comment by jiyilanzhou** [comment]
Hi @Noc2 , I has updated the questions。

**Comment by Noc2** [comment]
Thanks for the update. A few follow-up questions/comments:

- I would replace the word parachain in the deliveries with substrate chain or something similar
- How will the oracle data be validated? Or a fraud proof generated? Which is a general issue with oracles are do you proof that the provided real world data is correct or incorrect? 
- What’s a feeder manager? 
- Could you add the following to the deliveries: “I will use golang implement scanner and provider. it may use go-substrate-api, And aggregator,validator,council implement as substrate pallet, written in Rust as substrate customized module.”
- Is it possible to reduce the price further, also given the current BTC price. In general it might be easier to accept a small initial grant and potentially later follow-up with another grant

**Comment by jiyilanzhou** [comment]
> Thanks for the update. A few follow-up questions/comments:
> 
> * I would replace the word parachain in the deliveries with substrate chain or something similar
> * How will the oracle data be validated? Or a fraud proof generated? Which is a general issue with oracles are do you proof that the provided real world data is correct or incorrect?
> * What’s a feeder manager?
> * Could you add the following to the deliveries: “I will use golang implement scanner and provider. it may use go-substrate-api, And aggregator,validator,council implement as substrate pallet, written in Rust as substrate customized module.”
> * Is it possible to reduce the price further, also given the current BTC price. In general it might be easier to accept a small initial grant and potentially later follow-up with another grant

@Noc2 

Thank you for your review.

* If parachain want use the oracle services,  It need to integrate oracle services with deliveries substrate chain example. I wonder if this is the question you want to ask.
* Each running node(Validator) can verify the block on the chain. If the data submitted by the Aggregator is found to be defective, Validator needs to pay a small fee to submit the transaction contained in the problem block and the correct value  to the Council for review, if Council approve  of this , it will reward Validator and slash Aggregator.
* Because the Aggregator needs to submit the correct data to theparachain,  Feeder manager need mark who has permission to submit data to the parallel chain.
* The document has been updated.

**Comment by Noc2** [comment]
Sorry for the late reply and thanks for the response. I still have quite a few questions: 

- Regarding parachains: I was trying to point out that parachains are chains that are deployed on polkadot/kusama as a parachain. Whereas your solution can potentially be integrated into any substrate chain, correct? 
- I still don’t understand how you exactly detect if certain real world data is wrong or correct? Could you give a concrete example (e.g. the result of a football match or something similar)? If I understand it correctly you have a council that basically says this data is correct or wrong on an individual basis. And you also have a “validator” that needs to check the data manually, correct? It seems a lot of work for a lot of people. How would you incentivize the participants?  
- In general please add as many details to the deliveries as possible (programming language, functions, etc.) For example how does the reputation model for the council work? Do you maybe have a whitepaper or something similar that explains this in more detail.

**Comment by jiyilanzhou** [comment]
> Sorry for the late reply and thanks for the response. I still have quite a few questions:
> 
> * Regarding parachains: I was trying to point out that parachains are chains that are deployed on polkadot/kusama as a parachain. Whereas your solution can potentially be integrated into any substrate chain, correct?
> * I still don’t understand how you exactly detect if certain real world data is wrong or correct? Could you give a concrete example (e.g. the result of a football match or something similar)? If I understand it correctly you have a council that basically says this data is correct or wrong on an individual basis. And you also have a “validator” that needs to check the data manually, correct? It seems a lot of work for a lot of people. How would you incentivize the participants?
> * In general please add as many details to the deliveries as possible (programming language, functions, etc.) For example how does the reputation model for the council work? Do you maybe have a whitepaper or something similar that explains this in more detail.

* Yes,  Current solutions require parachains integration,  When the contract parachain  comes online, we will deploy this capability on the contract parachain, Oracle calls within the contract parachain will be called in the same way as Ethereum calls. When XCMP comes online, we may use XCMP to solve the cross-chain of Oracle data.
* Normally, the council doesn't care about the result of a football match。When a validator which role is similar to the fisherman  finds that a football match result is wrong,  The validator has to pay for the challenge via sending transactions， That's when the Council gets to work, Council members will vote on the challenge by querying result of a football match locally,  If the validator cheats, the council will split the cost of the validator's challenge equally，Otherwise，aggregators will be slashed,  The forfeited assets will be rewarded to the validator and the council.
* I use golang and rust substrate blockchain , I'll give you more implementation details.  Reputation models require honest work or the pledge of large amounts of tokens.  whitepaper are in the works, which may have little to do with engineering implementation.

**Comment by Noc2** [comment]
Thanks again for the quick reply. To be honest I still have a few questions/concerns regarding the implementation. But maybe the simplest/fastest solution is to go ahead with milestone 1 initially to learn more about your project and follow-up with funding of milestone 2 and 3 potentially at a later stage. Would you be interested in this? In this case you could simply remove milestone 2 and 3 for now.

**Comment by jiyilanzhou** [comment]
> Thanks again for the quick reply. To be honest I still have a few questions/concerns regarding the implementation. But maybe the simplest/fastest solution is to go ahead with milestone 1 initially to learn more about your project and follow-up with funding of milestone 2 and 3 potentially at a later stage. Would you be interested in this? In this case you could simply remove milestone 2 and 3 for now.

Thank you,  I already remove milestone 2 and 3,  we will achieve milestone 1 as soon as possible.

**Review by Noc2 — APPROVED** [review]
Thanks. Looks good to me. I will share it with the rest of the committee.

**Review by mmagician — APPROVED** [review]

**Comment by laboon** [comment]
I have a lot of questions about the tech, especially as there is nothing in the github repo at the moment, but I think they'd be answered by seeing milestone 1.

**Review by laboon — APPROVED** [review]

**Comment by alxs** [comment]
Hi @jiyilanzhou. May I kindly ask you to remove the grants badge from your [website](https://www.aresprotocol.com/)? The guidelines above explicitly state that the badge should not be displayed on your team's landing page but only in project-specific settings, i.e. only in direction relation to the deliverables included in this grant.

**Comment by jiyilanzhou** [comment]
Thanks for the reminder, I will fix this problem as soon as possible.



---Original---
From: "Aleixo ***@***.***&gt;
Date: Sun, May 16, 2021 02:27 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [w3f/Open-Grants-Program] Add ares protocol proposal  (#71)




 
Hi @jiyilanzhou. May I kindly ask you to remove the grants badge from your website? The guidelines above explicitly state that the badge should not be displayed on your team's landing page but only in project-specific settings, i.e. only in direction relation to the deliverables included in this grant.

**Comment by Noc2** [comment]
@jiyilanzhou the logo is still on the website. Could you please remove it? Otherwise we might need to take additional steps to get this resolved.

**Comment by jiyilanzhou** [comment]
@Noc2 Thanks for reminding me again.
 The Ares Protocol [website](https://www.aresprotocol.com/)  I have already can't control. We've upgraded our website to new [link](https://www.aresprotocol.io/), updating the .com domain name to .io. 
I'm sorry for the negative impact on Polkadot. This is a [statement](https://andyray123.medium.com/official-statement-of-ares-protocol-986ec0edc258) of our team. I will update some information of the [website](https://www.aresprotocol.io/), As soon as I have updated, I will remind you.
All the negatives of Ares Protocol come from a villain who doesn't understand blockchain. I'm sorry for this.

**Pull request merged**
