### PR TITLE
kotlin-scale-codec

### PR DESCRIPTION
**Pull request by polkadot-code**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by polkadot-code** [comment]
Sorry for the late reply.I just adjusted the period and estimated period, and the repo.
We decided to use kotlin and swift (of course, we can also start the swift version). It is just that emerging apps and developers use them more. And we did find many kotlin advantages in some aspects (Security and other comparisons are not mentioned here): Less code, Multi-Platform Development, Easy to Learn. It enables us to carry out the same tasks with less time and effort. When the code is simple and easier to understand, errors are harder to make and much easier to find and thus their chances are reduced significantly.

I think this is more important in polkadot. Now polkadot is more difficult for developers to learn than other projects. Many blockchain developers expect to use polkadot. When they do n’t know how to develop, or they lack a simple and easy-to-understand tool library, This can reduce ecological access requirements.

**Comment by gautamdhameja** [comment]
It seems to propose only a codec implementation, and not a complete API and client library for sending extrinsics and receiving a response (listening to events). Without a full client-side library, it would be an incomplete solution for others to use. 

Moreover, Kotlin does not seem to be a super high-priority language to target, at this time, imo.

**Comment by RouvenP** [comment]
thank you for the application. from a legal / an accounting point of view we would require you to disclose more information about your company such as official name, address, etc. is that an option for you?

**Comment by polkadot-code** [comment]
> It seems to propose only a codec implementation, and not a complete API and client library for sending extrinsics and receiving a response (listening to events). Without a full client-side library, it would be an incomplete solution for others to use.
> 
> Moreover, Kotlin does not seem to be a super high-priority language to target, at this time, imo.

we'll make these functions into an rpc client

**Comment by polkadot-code** [comment]
> thank you for the application. from a legal / an accounting point of view we would require you to disclose more information about your company such as official name, address, etc. is that an option for you?

we are a team of individuals, so we set Personal liability in Legal Structure
If individual teams are not allowed, maybe I will close this pr and look for a suitable company to submit later, but we will continue the project.

**Comment by polkadot-code** [comment]
> It seems to propose only a codec implementation, and not a complete API and client library for sending extrinsics and receiving a response (listening to events). Without a full client-side library, it would be an incomplete solution for others to use.
> 
> Moreover, Kotlin does not seem to be a super high-priority language to target, at this time, imo.

update in Milestone 3

**Comment by RouvenP** [comment]
> > thank you for the application. from a legal / an accounting point of view we would require you to disclose more information about your company such as official name, address, etc. is that an option for you?
> 
> we are a team of individuals, so we set Personal liability in Legal Structure
> If individual teams are not allowed, maybe I will close this pr and look for a suitable company to submit later, but we will continue the project.

We are fine with a team of individuals but would require at least name and address of one person. Is that possible?

**Comment by polkadot-code** [comment]
> > > thank you for the application. from a legal / an accounting point of view we would require you to disclose more information about your company such as official name, address, etc. is that an option for you?
> > 
> > 
> > we are a team of individuals, so we set Personal liability in Legal Structure
> > If individual teams are not allowed, maybe I will close this pr and look for a suitable company to submit later, but we will continue the project.
> 
> We are fine with a team of individuals but would require at least name and address of one person. Is that possible?

Of course, the information about the individual has been updated.

**Comment by Noc2** [comment]
Sorry, for the late reply here and thanks again for the application. As you might be aware, we recently signed the [Java client lib](https://github.com/w3f/Open-Grants-Program/pull/12), since at this stage this sounded overall more interesting to us and we are generally not so interested in kotlin at the moment. However, this might change in the future and maybe you are able to reuse parts of the Java implementation. Therefore, it might make sense to reapply in a few months from now, once the Java implementation is done and we have generally a bigger interest in kotlin in our ecosystem.

**Pull request closed without merging**
