### PR TITLE
Update dorahacks-quadratic-funding.md

### PR DESCRIPTION
**Pull request by zhangjiannan**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by Noc2** [comment]
@zhangjiannan Thanks for the PR to amend the original contract. Are you aware that the updated ethereum address still isn’t the same as on the invoice? So are you also going to send us a new invoice?

**Comment by zhangjiannan** [comment]
@Noc2 Hi David I just updated the payment address to a new address, and we have uploaded a new invoice to reflect the address change.

**Review by Noc2 — APPROVED** [review]
Thanks again for uploading the invoice and the amendment. Looks good to me.

**Comment by zhangjiannan** [comment]
@Noc2 Thanks! An update -- we completed frontend integration with HackerLink. However due to tight schedules we didn't create a demo page based on the substrate-frontend-template (task #2 of Milestone-2). Another reason why we didn't create the simple page is that HackerLink has a complete infrastructure for user registration, project upload / display, etc. The HackerLink code base is not open source. Do you have any suggestions on how we can deliver milestone-2?

**Review by semuelle — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Comment by alxs** [comment]
Hey @zhangjiannan, you can submit another amendment (like this one) in which you remove the deliverable and reduce the price accordingly

**Comment by zhangjiannan** [comment]
@alxs cool, I will do it. Thanks!

**Comment by Noc2** [comment]
@zhangjiannan Hi. The invoice team just pinged me and wrote the following: “Looking at the invoice I see that the name is wrong. It says 'TWENTY-SECOND CENTRUY DORA', but i guess it is ' TWENTY-SECOND CENTURY DORA'.” Could you update this and send us a new invoice? Thanks!

**Comment by zhangjiannan** [comment]
@Noc2 thanks for letting us know! We re-submitted the invoice.

**Comment by Noc2** [comment]
@zhangjiannan Thanks. I just shared it with the invoice team.

**Pull request merged**
