### PR TITLE
Remove the BTC address, leave the ERC20 only

### PR DESCRIPTION
**Pull request by kevingzhang**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by mmagician — APPROVED** [review]
Not strictly needed as the denomination is already in USD, but sure, it will keep the document cleaner 👍🏼  Thanks @kevingzhang

**Comment by alxs** [comment]
Thanks. Can you please submit a new invoice that specifies one currency and in which `USTD` has been fixed to `USDT`?

**Comment by Noc2** [comment]
I guess we no longer need to merge this, because of https://github.com/w3f/Open-Grants-Program/pull/447. Let me know if this is not the case and I will reopen it.

**Review by Noc2 — APPROVED** [review]

**Comment by Noc2** [comment]
Ah, sorry. I was confused. Reopened and approved.

**Review by semuelle — APPROVED** [review]

**Pull request merged**
