### PR TITLE
Polk-auction

### PR DESCRIPTION
**Pull request by CrommVardek**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by mmagician** [comment]
@CrommVardek This looks good! It does seem that you pushed commits with two different accounts, and they will both need to sign the CLA License before we can proceed.

**Comment by mmagician** [comment]
In addition, the PR header contains some check-boxes which seem unchecked now. Please ensure they're ticked, as it shows us that you read & understood the conditions of the process.

**Comment by CrommVardek** [comment]
Hello @mmagician, indeed the boxes were not checked, still have one to check. Thanks for the tips about the CLA, I'll squash the commits and force push with my github account later today.

**Comment by alxs** [comment]
Hey @CrommVardek, thanks for the application. I think you've correctly identified the need for such a website, but unfortunately so have others in the ecosystem before. See https://www.parachains.network/ or https://www.subvis.io/, and I expect more similar websites will appear in the near future. For this reason I'm sorry to say I'd rather not support the application, but maybe you could combine efforts with @jhonalino to work on parachains.network? I don't know if his work is currently being funded at all and he may be happy to apply for a grant as well.

**Comment by CrommVardek** [comment]
Hi @alxs, thanks for your feed-back. I was indeed expecting others to be faster than I am to publish similar websites. Even though when I started the project none were released yet (well polkadot.js was... but that is not its focus). As I previously discussed by e-mail with @Noc2 , my application for an open-grant was mainly to be able to financially support the hosting costs on a dedicated server. My plan is still to continue this project or, as you suggest - and that is a good idea - join efforts made by faster developers :)

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general I personally think it makes sense to support multiple UI focused projects. But I have a few questions. 

- Why do you want to work on a HTTP Rest API in Kotlin? You can take a look at existing solutions here: https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md So far, we only had one other Kotlin based project. That’s said a full kotlin client could potentially be a separate grant project (would you be interested in this?). 
- Do you already have an initial designs for the UI? Or potentially other UI focused projects, which you can share? To be honest, the drawings are not really nice looking at the moment ;-)

**Comment by CrommVardek** [comment]
Hi @Noc2, thanks for the feed-back, to answer your questions : 

* Regarding the choice of Kotlin, at first I planned to use Java then realized Kotlin is easier to read and write, lightweight to deploy. And Kotlin feels (to me at least) closer to Rust or Go than Java. Indeed, a kotlin client could be a good idea for a separate project, however isn't there already a java client ? (I mean, both could co-exists, but it feels less useful to have a kotlin client when a java one is maintained).
* I've not worked on the ui yet, and sadly the UI-focused projects I've worked on are not public neither open-source, so I cannot share them. I'll focus on a first draft of the UI, commit & push the code and update this application with screenshot(s) to give you a better idea of the UI. 

Hope this answer your questions !

**Comment by Noc2** [comment]
Thanks for a quick response. You can find the java client [here](https://github.com/emeraldpay/polkaj) and indeed it might make more sense to contribute to this client instead of creating your own client. But we generally are interested in supporting a wide variety of implementations. Let me know once you added a screenshot to the application.

**Comment by mmagician** [comment]
> it is not intended to integrate functionalities such as:
Using the website as a way to participate in crowdloans
Using the website to participate to the auction

That's a shame. Maybe as my colleagues have suggested, more net utility could be achieved by teaming up with another existing project and integrating the "interactive" functionality of the parachains

**Comment by jhonalino** [comment]
> Hey @CrommVardek, thanks for the application. I think you've correctly identified the need for such a website, but unfortunately so have others in the ecosystem before. See https://www.parachains.network/ or https://www.subvis.io/, and I expect more similar websites will appear in the near future. For this reason I'm sorry to say I'd rather not support the application, but maybe you could combine efforts with @jhonalino to work on parachains.network? I don't know if his work is currently being funded at all and he may be happy to apply for a grant as well.

hey @alxs, thank you so much for the mention of my project parachains.network I'm definitely happy and been planning to apply for a grant. @CrommVardek I've read your application. it looks like your stack requires a layer of a backend server. I'm mostly focusing parachains.network to be a static client like polkadot.js where it connects directly to a polkadot/kusama node via websockets. but message me if you'd like to work together. I'll be happy to rethink the structure for a better UX. (I'm mostly a frontend dev.) 

I also have another project if you're interested like 
https://polkaview.network/dot/identities to browse Polkadot/kusama identities
https://www.stakingrewards.network/ to calculate staking rewards. 
both require indexing to traditional databases to dramatically improve query performance.

**Comment by CrommVardek** [comment]
@mmagician : TBH I don't have the needed skills to develop a solution to add such functionalities - but of course, I can learn and later add those features that, as you mention, are not present in other project (outside of polkadot.js app). So it's something I might consider in the future but that's definitely out of the scope of this application.

Hi @jhonalino, thanks for your reply, indeed the UI would need a back-end, the reason is to facilitate the (indirect) connection to the nodes and add off-chain information, so the UI has only one API endpoint to connect to. I've take a look at your repo already, and indeed I noticed that you connect to the public nodes directly (in that you avoid running a backend which avoids some hassle). As I'm mostly a back-end developer, working together would be nice. I'll message you in a few days to see how we can work together and what I can do.

**Comment by mmagician** [comment]
@CrommVardek Sure, I see your point. Seeing that there is potential for a collaboration between yourself and @jhonalino, I'll put this PR on hold, does that make sense?
Perhaps the two of you decide to unite forces and leverage back+frontend skills. I would rather fund the addition of a back-end to the existing solution.

Let us know if in the end you prefer to continue with the current scope and we'll resume the evaluation.

**Comment by alxs** [comment]
@jhonalino https://www.stakingrewards.network/ looks really good. Are you aware of [this RFP](https://github.com/w3f/General-Grants-Program/blob/master/rfps/staking-rewards-collector-front-end.md) and matching [proposal](https://github.com/w3f/Open-Grants-Program/pull/429)? We could potentially also fund improvements to it. Also tagging @jonasW3F who developed the original staking rewards collector, he may not even be aware of it. 

Also regarding https://polkaview.network/dot/identities: see https://github.com/w3f/Open-Grants-Program/pull/255. You should consider applying for grants more often ;)

**Comment by CrommVardek** [comment]
Hi @alxs, I've updated the application with a some UI to give you a better idea of what I had in mind. This is for now very basic UI. I'll keep updating as I'm working on the UI (also, feel free to take a look at the corresponding repositories).

@jhonalino I've sent you an email - however I'm not sure it was the right channel to message you. So I'm tagging you here... ^^'

@Noc2 I've taken a closer look at the java client, I must admit I'm not really fan of the implementation, so I'm going to develop a kotlin WS client for the Polkadot nodes specifically for this project. And I  plan to extend it later to have something that could be used like the @polkadot/api, and eventually making an application for it.

**Comment by mmagician** [comment]
@CrommVardek Thanks for the updated mock ups.
As I already mentioned, I would still rather support the integration of a backend to an existing implementation, since I don't see additional benefits of another implementation if it has the same functionality as other existing pages.
However, given that you are willing to work on the Kotlin client implementation alongside the webpage, I would be open to go ahead with a project that uses it as the backend. With the current status of the application, I don't fully understand whether you'll be developing **some** parts of the Kotlin client in parallel, or whether they'll be done afterwards?
Perhaps you could specify the functionality of the client that you're planning to finish by each milestone?

**Comment by CrommVardek** [comment]
@mmagician Thanks, indeed I was probably not clear.

My intent is to continue developing the back-end but add a kotlin client that I would develop some parts only (parts that I'd need for the backend) and in the scope of this application. Later on - if I believe that client can be usuful, I'd like to develop a more complete version of it, but I keep that outside of the scope of this application. 

However, as you suggest, I'll update the application to be more specific about that kotlin client so you know where it's going and what I plan to do.

**Comment by CrommVardek** [comment]
@mmagician I've updated the application to clarify the way I intend to develop and use a kotlin WS client for Polkadot/Substrate nodes. I may have missed some points, so if you still have question, doubts or just want more information, feel free to ask :)

**Review by mmagician — APPROVED** [review]
Alright, sounds good. Then I wish you good luck and I will be looking forward to your deliverables!

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]
I would like to see a complete Kotlin client, so I'm approving this in hopes of a follow-up grant. :)

**Comment by CrommVardek** [comment]
@Noc2 , @mmagician , @semuelle Thanks for trusting me and approving this application : )

**Comment by semuelle** [comment]
Hey @CrommVardek, how is the project progressing? Are you still on track for the second milestone?

**Comment by CrommVardek** [comment]
Hi @semuelle , yes, the second milestone is almost done actually, I need to finish a few things, add tests and documentation. I do not have much time for this project sadly, but I plan to end the second milestone before the end of this year, and then the last milestone should be relatively trivial.

**Comment by semuelle** [comment]
That's great to hear. It's no problem if it's postponed by a few weeks, we'd rather see things done well than fast. :) Feel free to post here if you want to give an update outside milestone deliveries.

**Comment by alxs** [comment]
@CrommVardek friendly reminder, what's the status on your end?

**Comment by CrommVardek** [comment]
Hi @alxs , some UX testing and small changes are still made to have a finer working UI (milestone 2). Basically it is done (except for the dockerfile - deliverable 0d.), but I'd like to change few thing before publishing the next delivery. If it becomes an issue to delay further the milestone 2, I'll publish it this week and make my small changes later on another release.

**Comment by alxs** [comment]
Thanks for the update. No worries, feel free to take care of those changes before you submit.

**Comment by CrommVardek** [comment]
Hey, for information I've almost finish polishing UI, however I'm dependent of this issue to be solved to regarding the backend : https://github.com/paritytech/substrate-api-sidecar/issues/814 (as I use sidecar for some of the information related to the auction). Once this is resolved I should post for the 2nd delivery milestone a few days later.

**Comment by Noc2** [comment]
Thanks a lot for the update.

**Comment by semuelle** [comment]
Hey @CrommVardek, just checking in here. Based on your Github activity, I can assume that you are still working on milestone 3?

**Comment by CrommVardek** [comment]
Hi @semuelle , that's correct, milestone 3 is close to be done, the project is already online at [www.polkauction.io](http://www.polkauction.io), but there are a few things I'd like to verify and change before submitting the 3rd milestone (most important is setting up SSL and correcting a UI bug). I should open the 3rd delivery by the end of this month.

**Pull request merged**
