### PR TITLE
DeCredit - Add Scoring and Matching modules

### PR DESCRIPTION
**Pull request by Maedamoto**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by mmagician — CHANGES_REQUESTED** [review]
@Maedamoto Thanks for your application. In order for us to consider your proposal, we require some more information. For example, I can't see any specifications of your credit scoring/matching algorithms. For an idea of the type of requirements needed, you can consult the lists in the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and the [guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md)

**Comment by Maedamoto** [comment]
@mmagician Thanks for the advice. Just added Scoring & Matching specification links in ### Project Details

**Review by RouvenP — APPROVED** [review]

**Comment by Lederstrumpf** [comment]
Can you point me to the target market for a credit rating/matching platform where all financial information of users is strictly public?

Your website http://decredit.io/#/ claims privacy protection, but your grant application and specifications do not back up this assertion, nor in any way suggest that this is part of the delivery.

Also, https://github.com/Credit-chain-org/algorithm does not exist.

**Comment by Maedamoto** [comment]
@Lederstrumpf Thank you for your response. We are an internet company and we’ve launched our credit business for some years. Now, we are switching our solution on the blockchain.

We want to implement our project in 3 stages. 

In the 1st stage, we are building ‘Scoring’ and ‘Matching’ modules and user data is off-chain - We store the data in DB and cloud system. We just upload hash onto the chain. This grant application is according to this stage specifically. 

In the 2nd stage, we will keep all user data on-chain. And we will implement Privacy and Distributed storage solution in this stage.

In the 3rd stage, we will implement smart contracts. Thus, users can customize the Matching module so that demands and supplies could meet each other according their own requirements.

So back to the questions,

>Can you point me to the target market for a credit rating/matching platform where all financial information of users is strictly public?

All financial information of users is not public. In the 1st stage, the information is stored in DB/Cloud. And in the 2nd stage, all information is on-chain and the privacy is protected.

>Your website http://decredit.io/#/ claims privacy protection, but your grant application and specifications do not back up this assertion, nor in any way suggest that this is part of the delivery.

The privacy protection is in the future plan while not in this application scope. 

>Also, https://github.com/Credit-chain-org/algorithm does not exist.

Some configuration error, please try again.

**Comment by mmagician** [comment]
@Maedamoto Thanks for answering @Lederstrumpf 's questions.
Just so that you're aware, it might be difficult to get approval for your grant at the current stage, as it relies heavily on centralised service to function and mostly serves only your specific purpose, rather than a community as a whole (at this point at least)

Since this is just my own point of view, I will leave the "ready for review" label so that other members are free to approve / comment - in the end, other Grant Committee members might have different priorities and might want to proceed with your application.

**Comment by Lederstrumpf** [comment]
Hi @Maedamoto, thank you for your response.

> The privacy protection is in the 2nd stage while not in this application scope.

Without the privacy protection features, your proposal is not compelling in the slightest: your first stage's solution does not require a blockchain: the hashes you store on-chain are worthless to anyone without access to the data, which is only your company, which does not benefit from these hashes either. Unless this data you store "on the cloud" is accessible to all users, which, again, is not a viable solution.

However: My primary concern is that, since there is no indication how you plan to add privacy protection features (even on your website), I'm assuming you have not worked out a solution for this either. 

> > Also, https://github.com/Credit-chain-org/algorithm does not exist.

> Some configuration error, please try again.

Thank you, but this repository only contains binary `.class` files.

**Comment by Noc2** [comment]
Thanks for the application and all the effort you put into this. I also agree that stage 1 (according to your website) doesn’t provide a lot of value on it’s own. I therefore suggest reapplying with stage 2, once you specified the implementation. Let me know if this sounds good to you or you have any questions.

**Comment by Noc2** [comment]
I’m closing the grant application for now, since it doesn’t seem like we get the necessary approval for it. As I said above, feel free to reapply with an update proposal.

**Comment by Maedamoto** [comment]
Thanks @Noc2 , will do some update and apply later.

**Pull request closed without merging**
