### PR TITLE
PolkaOracle

### PR DESCRIPTION
**Pull request by PolkaOracle**
# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for resubmitting, but the application is still missing the necessary details. Please take a look at the [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md).

**Comment by mmagician** [comment]
@hitomi500 You have opened 4 incomplete PRs by now & under different names: [1](https://github.com/w3f/Open-Grants-Program/pull/139) [2](https://github.com/w3f/Open-Grants-Program/pull/132) [3](https://github.com/w3f/Open-Grants-Program/pull/147) [4](https://github.com/w3f/Open-Grants-Program/pull/146). Please do not spam our repositories.

**Comment by PolkaOracle** [comment]
Our sincere apologies for this situation as for now. The reasons are: 1, we are unaware of the detailed rules of making proposals, so we did redundant applications by mistake; 2, The most important reason is that team has been working on the perfection of our proposals to the Foundation as we do attach grant importance to this matter as we long for making contribution to Polka ecology as a member. Please kindly consider our sincerity and please reopen.

**Comment by mmagician** [comment]
@PolkaOracle you can reopen one of the applications, but please first make sure it adheres to our application process, which is clearly explained in the repo README. Please focus on one application & only re-open that one **once it is completed and polished**.
Also, why are you using so many github accounts (@PolkaOracle @hitomi500 @InPolka) to submit PRs?

**Comment by PolkaOracle** [comment]
Hello Sir, according to your feedback, we decided to reopen our project PolkaOracle first, while we had no permission to reopen on our side,so we need your help

**Comment by Noc2** [comment]
I reopened the PR. Please update the application.

**Comment by mmagician** [comment]
Your application lacks technical detail. It seems that rather than defining your own project's features, you're listing the current capabilities of Polkadot, e.g. `Off-chain Workers is a new feature in Substrate 2.0, allowing developers to integrate data safely and securely onto the blockchain applications`

With other milestones the description is too generic, e.g. `The Data Source Layer is the bottom layer of the entire oracle system`.

This is yet another time when your team has submitted an incomplete application. Please refrain from applying again until you've polished & defined your proposal.

**Pull request closed without merging**
