### PR TITLE
ECDSA for Polkadot JS

### PR DESCRIPTION
**Pull request by akru**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi akru. Thanks for the application. Could you add a little bit more details and things like (delivery) documentation as well as tests to the application? Also, we just signed a grant with nodefactory for a metamask plugin yesterday. Therefore, maybe it makes sense that you initially only focus on the first milestone. Let me know if you need any help with signing our terms via the cla assistant.

**Comment by akru** [comment]
Hey David @Noc2,
oh, really! But I happy that it will be implemented soon.

So, I've remove milestone 2 and extend milestone 1 detailed derivations like tests and documentation with demo video. Please let me known if you have any questions.

**Comment by Noc2** [comment]
Thanks for integrating the changes. The table in the document currently doesn't render correctly (you probably need to remove one "|"). Apart from that, the application looks rather expensive to me and I'm not sure you actually need two weeks for this. Could you reduce the price a little bit more?

**Comment by akru** [comment]
Got it! 
@Noc2  I've fix table rendering and decrease payment rate a bit to make more comfortable price for W3F.

**Comment by akru** [comment]
Oh, yes, fixed!

Thank you so much! @Noc2 @gavofyork

**Pull request merged**
