### PR TITLE
OAX Foundation application for grant

### PR DESCRIPTION
**Pull request by OAXFoundation**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by OAXFoundation** [comment]
We've signed the CLA and clicked the [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=4) several times but it still says the CLA isn't signed yet.

Help?

**Comment by Noc2** [comment]
Waylandc needs to sign it since he has created the application.

**Comment by OAXFoundation** [comment]
> Waylandc needs to sign it since he has created the application.

waylandc is a contributor who made the commits to our repo but doesn't this mean that OAXFoundation created the PR? FWIW, it's our intent that the grant is being applied by OAX, not waylandc.

`
OAXFoundation wants to merge 5 commits into w3f:master from OAXFoundation:master`

**Comment by Noc2** [comment]
> FWIW, it's our intent that the grant is being applied by OAX, not waylandc.

The bot needs to be signed by all contributors. All contributors are later able to deliver the milestones (including the OAX foundation). However, the payment will always go to the original BTC address in the application. So as long as waylandc as no problem to agree to our terms and condition and the foundation is in control of the BTC address, I think the easiest solution is that waylandc simply signs it as well. The alternative is to resubmit the application with the OAX foundation as the only contributor.

**Comment by Noc2** [comment]
I recently learned that the OAXFoundation already received support from us for potentially creating a parachain. Therefore, at this stage, I would personally be inclined to not support your current proposal, unless you can clearly justify why you would need additional resources at this stage.

**Comment by OAXFoundation** [comment]
> I recently learned that the OAXFoundation already received support from us for potentially creating a parachain. Therefore, at this stage, I would personally be inclined to not support your current proposal, unless you can clearly justify why you would need additional resources at this stage.

There may be a misunderstanding, as to this day, OAX Foundation has not received any financial support from Web3. The only support we've received for this project has been technical support via Riot and emails.  We are happy to provide further explanation for this point if necessary. I hope you can reconsider our proposal in light of this clarification.

**Comment by zhangyaxing12** [comment]
All checks have passed

**Comment by Noc2** [comment]
I close the pr/grant application. The reasons were explained by Dieter via an email. Feel free to reach out to him for further clarification.

**Pull request closed without merging**
