### PR TITLE
add shadows-nerwork

### PR DESCRIPTION
**Pull request by ShadowsNetwork**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few questions/comments:

- What is unique about your Ingester Module compared to the existing oracle modules and the work done by acala (see for example https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle)? Could you not simply reuse their work? I’m also not sure how your solution ensures decentralization. 
- Also what are the unique features of your Exchange and MintX modules (see https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md for other solutions)?  
- Could you reduce the price? It’s currently above the 30k limit.

**Comment by ShadowsNetwork** [comment]
@Noc2 #Thank you for your comments. The following is the answer to your question

> What is unique about your Ingester Module compared to the existing oracle modules and the work done by acala (see for example <https://github.com/open-web3-stack/open-runtime-module-library/tree/master/oracle>)? Could you not simply reuse their work? I’m also not sure how your solution ensures decentralization.

We use off-chain-workers to implement the Ingester Module (see https://substrate.dev/docs/en/knowledgebase/learn-substrate/off-chain-workers), which is completely different from the existing oracle modules. We cannot reuse their work for the following reasons:
1. When we need to synthesize relatively unpopular assets on the chain, such as the global movie box office index, chainlink and other oracle service providers do not provide the asset price, then we need to request trust agency data through the off-chain-workers HTTP client.
2. In the future, we may add community voting functions in the Ingester Module to reduce the risk of external data. For example, we can query the prices of the same assets issued by three institutions at the same time, If the data deviation of these three data sources exceeds a certain threshold, the voting process will be triggered. let the community vote to decide which price to use, and give DOS rewards to the winner of the vote. Of course, this mechanism requires that our dependence on external data is not so real-time.

> Also what are the unique features of your Exchange and MintX modules (see <https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md> for other solutions)?

Unlike the existing DEX based on order book or liquidity( Such as acala exchange is based on liquidity, and Polkadex is based on an order book), we are based on the debt pool model. All trades are executed against the contract, known as P2C (peer-to-contract) trading. This provides infinite liquidity up to the total amount of collateral in the system, zero slippage, and permissionless on-chain trading. For details, please refer to our white paper System Architecture chapter. (https://github.com/ShadowsNetwork/whitepaper/blob/main/ShadowsNetworkWhitePaper.pdf)

> Could you reduce the price? It’s currently above the 30k limit.

Sorry, the calculation is wrong here, it has been corrected.

**Comment by ShadowsNetwork** [comment]
@Noc2 
Is there anything unclear that I need to describe?

**Comment by Noc2** [comment]
Okay. Thanks a lot for the additional information and update. In this case you should take a look at the [ares protocol](https://github.com/aresprotocols/ares). It seems you are right Acala is using [off-chain worker](https://github.com/AcalaNetwork/Acala/blob/master/modules/cdp_engine/src/lib.rs#L431), but it’s not used for laminars [synthetic-protocol](https://github.com/laminar-protocol/laminar-chain/blob/master/modules/synthetic-protocol/src/lib.rs). Just one more question from my side: Could you also integrate unit-test into the deliverables for both milestones as well as some kind of medium article or tutorial.

**Comment by ShadowsNetwork** [comment]
@Noc2 
Thank you for your suggestions, the functions provided by aresprotocols are amazing. We will consider using it to obtain external data. But currently aresprotocols are also under development, so we currently plan to continue to develop our Ingester Module. I look forward to cooperating with aresprotocols to strengthen ecological links in the future.
We have added Tutorial and Testing to the milestone.

**Review by Noc2 — APPROVED** [review]
Looks good and thanks for the update. I will share it with the rest of the team.

**Review by RouvenP — APPROVED** [review]

**Comment by laboon** [comment]
Can you provide some details on the debt pool model?  I am not familiar with this and could not find any detailed information in the white paper.

**Comment by ShadowsNetwork** [comment]
@laboon Hi! Here are some descriptions about the mortgage pool:

The debt pool is the core design of the shadows network and one of the biggest highlights. The debt in the debt pool is generated by stake DOS, which is the native token of the shadows network.

When users stake DOS to create synthetic assets (such as synthesizing xUSD), "debt" is generated. The sum of debts of all DOS stakers is called the "debt pool".

Let's take an example of minting xUSD and buying xBTC to illustrate what a debt pool is. Here it is assumed that the price of DOS is the same as USD, the stake rate is 800%, and the initial debt of the system is 0.

1. Alice used 800 DOS to mint 100 xUSD. At this time, the total debt of the system is: 100 xUSD, and Alice's personal debt in the entire debt pool accounts for 100%.
2. Bruce used 2400 DOS to mint 300 xUSD. At this time, the total system debt becomes: 400 xUSD, and the total supply of xUSD is 400.
   Alice's personal debt in the entire debt pool becomes 25%, and Bruce's personal debt is 75%.
3. If Alice intends to use all 100 xUSD to buy 1 x BTC (assuming that the price of BTC is 100$ at this time), the steps involved in the transaction are as follows:
   3.1. Destroy 100 xUSD, including reducing the xUSD balance of Alice's wallet address and updating the total supply of xUSD,
   3.2. Destroy 100 xUSD debt
   3.3. Mint 1 xBTC and update the xBTC balance of Alice wallet address to 1
   3.4. Add 1 xBTC debt
   At this time, the total debt of the system is 300 xUSD and 1 xBTC. The total supply of xUSD is 300 and the total supply of xBTC is 1.

It can be seen from the above process that the transaction of synthetic assets is mainly to interact with smart contracts, there is no order book, and no counterparty. Synthetic asset transactions only exchange debt from one synthetic asset to another synthetic asset, and use the debt changes in the debt pool to cast or destroy synthetic assets, so that users don’t have to worry about liquidity issues, and there is no slippage problem. It is the essence of the debt pool.

**Comment by laboon** [comment]
Interesting, thank you for the explanation!

**Review by laboon — APPROVED** [review]

**Comment by Noc2** [comment]
@ShadowsNetwork Could you please remove the web3 foundation grants badge from your website. You are only allowed to use this once you successfully delivered the first milestone, see : https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md

**Comment by ShadowsNetwork** [comment]
@Noc2 
Sorry for not paying attention to the news. There was a misunderstanding about this before, but it has now been removed.

**Comment by Noc2** [comment]
Thanks!

**Comment by alxs** [comment]
This grant has been terminated due to copyright infringements. See [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/95#issuecomment-794343113).

**Pull request merged**
