### PR TITLE
polkacash.md

### PR DESCRIPTION
**Pull request by polkacash**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by alxs** [comment]
Hi @polkacash and thank you for your application. We currently have a high number of application and are thus pretty busy, but we'll get back to you as soon as possible.

A few comments from looking at the application at first sight:
- We've recently updated the application [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) to reflect the fact that grants now need to be denominated in USD. Could you update your proposal accordingly?
- Deliverables are numbered separately for each milestone. Also note that deliverables 0a-d need to be included in all milestones. Besides, milestone 1 currently doesn't contain any actual deliverable. Could you please update this?
- We need a more detailed specification in order to assess your application and also to evaluate the milestones in the event of a grant. You may treat this it as a contract; the level of detail must be enough to later verify that the software meets the specification. You can find some examples of details we're interested in for different grant categories [here](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md). In general, it is a good idea to list the languages/technologies that you will be using to implement each deliverable along with a detailed summary of the expected functionality.

**Comment by polkacash** [comment]
Hi @alxs, thank you for your comments.

Yes I just read about the USD denomination and have changed my application accordingly.

I have shifted 2 substrate modules into milestone 1, thanks for the suggestion it does make sense to spread out the dev work across milestones like this. 

I have added more technical details in the 2nd milestone as well which makes it more of a contract, upon studying the various other projects as you suggested.

Please let me know if any portion is still unclear.

Thank you again!

**Comment by alxs** [comment]
Thanks for updating your application and apologies for the delay.

I'm sorry to inform you that we're updating our policies to no longer provide funding to teams that have launched their own token, since that usually means we can be pretty confident that they could fund the development themselves. You'll see this reflected in the README by tomorrow.

**Comment by Noc2** [comment]
> Thanks for updating your application and apologies for the delay.
> 
> I'm sorry to inform you that we're updating our policies to no longer provide funding to teams that have launched their own token, since that usually means we can be pretty confident that they could fund the development themselves. You'll see this reflected in the README by tomorrow.

**Comment by Noc2** [comment]
Just to add something here: We can make exceptions to this rule, if there is a clear reason for it. So let me know if you want to reopen the application, once we have updated the readme.

**Comment by polkacash** [comment]
Hi!

Thanks for the explanation.

Just to clarify, the Polkacash token that we have launched on the Ethereum
network was a failed experiment and is now defunct.

With this grant application, we hope to have the support we need to
relaunch and to make it work this time round!

We did manage to garner some support from the community when we launched
but unfortunately some tech mistakes and high gas fees caused the
project to eventually fail.

Really do hope we manage to get approved for this application as we are
super excited about Polkadot, please let me know what you think and if
there's anything I could do to raise our chances!

Thank you.

**Comment by Noc2** [comment]
Okay. I’m happy to reopen the application, but you should be aware that we already have a few existing solutions in the ecosystem. For example Ampleforth also wants to join our ecosystem and we recently funded [AlgoCas](https://github.com/w3f/Open-Grants-Program/blob/master/applications/AlgoCash.md). What is unique about your solution? Could you provide more technical information?

**Comment by alxs** [comment]
Closing due to inactivity. Feel free to reopen the application with a proposal that contains more technical details and highlights an innovative approach in relation to existing solutions.

**Pull request closed without merging**
