### PR TITLE
Substrate startkit GUI Grant application

### PR DESCRIPTION
**Pull request by ivorrr**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by ivorrr** [comment]
Thanks for the quick answer. The target users would definitely be beginners and even people that wanna play a bit and not really start a production-ready blockchain. Experienced blockchain devs beginning to build a project with Substrate are probably familiar with how to start, and whoever has to deep dive into the code so they are not the ones that will benefit the most. We didn't consider the possibility of online chain running in this phase of the project, but it could be an option for some future version.
Looking long term, this GUI would be the place for everyone to quickly get informed on runtime pallets so it should be periodically updated with new information.
So the primary purpose is educational but also promotional. We added in the deliverables features focused on education such as: 
tooltips/popups with an explanation of every pallet 
links to the substrate docs
video tutorial on how to use the app
Documentation with a feature list and written tutorial
Please feel free to suggest another one.

The UX/UI of the app will be an essential part. So let me share with you some of our previous work on dribbble -https://dribbble.com/mvpworkshop.

**Comment by Noc2** [comment]
Thanks for the update and explanation. I have two more questions/suggestions: 
Are you aware of the substrate marketplace: https://marketplace-staging.substrate.dev/? Could you also potentially add tests as well as documentation for milestone 1.

**Comment by ivorrr** [comment]
Just added documentation and test to the 1. milestone, Thanks.
Regarding the marketplace, we didn't know about this particular one, but we saw a couple of community-driven similar marketplaces. We still think our project makes sense because it will interact with the user to warn him or give him suggestions. That would be beneficial for someone to grasp the whole picture of substrate pallet possibilities.

**Comment by Noc2** [comment]
Thanks. I have one last question: Given that we have already similar solutions in our ecosystem, I think it would be easier to accept your application if you could reduce the cost of it. Would this be possible?

**Comment by ivorrr** [comment]
Unfortunately not. We can argue about what 'similar' exactly means and add or change some features. However, it doesn't change our costs to build it.

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grants.communications@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by adebak** [comment]
Hey @Noc2, we are about to kick off the work on this grant so I would like to ask what is the process moving forward? We have sent e-mail to grants.communications@web3.foundation last week with our plan and proposal on how to approach the milestone #1 but received no feedback so far. 

Any guidance on the process would be highly appreciated, just to be sure we are aligned on expectations on both sides. Thanks a lot once again!

**Comment by Noc2** [comment]
Hi @adebak. The grants communication email is mostly about announcements. Also the new email address is grantspr@web3.foundation. Sorry for this. 
Regarding the process, feel free to start working on the grant and stick to the process described in the readme: https://github.com/w3f/Open-Grants-Program#pencil-process So basically once you finish a milestone, you can submit it to the milestone delivery repo and we will start looking into it. Once the milestone is accepted, the delivery document will be merged and the payment will be issued. Btw. if you have any questions, you can also contact me on riot directly: @david:web3.foundation

**Pull request merged**
