### PR TITLE
Create PredictDao.md

### PR DESCRIPTION
**Pull request by PredictDao**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. We recently updated the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and we ask teams now to denominate the grant amount in USD. Once we accept the milestone, we would either pay you in BTC or DAI (which is usually easier). Could you update the application accordingly?

**Comment by PredictDao** [comment]
> Thanks for the application. We recently updated the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and we ask teams now to denominate the grant amount in USD. Once we accept the milestone, we would either pay you in BTC or DAI (which is usually easier). Could you update the application accordingly?

Thank you for you advice, we have updated the application according to the new template and your information.

**Comment by PredictDao** [comment]
Greetings Web3 Foundation, we would very much like to change our project name for better embodiment of our goal, which is to achieve the predcition market. Is it possible for us to modify the pull request? If that is a yes, should we close this pull request and initiate a modified one ?

**Comment by PredictDao** [comment]
> Thanks for the application. We recently updated the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and we ask teams now to denominate the grant amount in USD. Once we accept the milestone, we would either pay you in BTC or DAI (which is usually easier). Could you update the application accordingly?

Greetings Web3 Foundation, we would very much like to change our project name for better embodiment of our goal, which is to achieve the predcition market. Is it possible for us to modify the pull request? If that is a yes, should we close this pull request and initiate a modified one ?

**Comment by Noc2** [comment]
Feel free to update the PR or to close this one and to create a new pull request. Whatever you prefer.

**Pull request closed without merging**
