### PR TITLE
Application for Apron Network

### PR DESCRIPTION
**Pull request by Apron2050**
* Add Application for Apron Network

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This is quite an interesting project. In general I’m willing to support it, but I have two questions:

- How do you try to prevent fraud or misbehaviour? E.g. querying his own node, reporting wrong stats. This isn't something you already need to have resolved fully (filecoin still hasn’t solved it), but it would be nice to hear your thoughts about it. 
- I think the biggest problem with infura is also that it’s highly subsidized by consensys. Do you think this is problematic from a business perspective?

**Comment by Apron2050** [comment]
Thank you for your comments.

> Thanks for the application. This is quite an interesting project. In general I’m willing to support it, but I have two questions:
> 
> * How do you try to prevent fraud or misbehaviour? E.g. querying his own node, reporting wrong stats. This isn't something you already need to have resolved fully (filecoin still hasn’t solved it), but it would be nice to hear your thoughts about it.
Yes, it's not so easy to solve it with tech since everything is open sourced in blockchain projects. So my thought is to introduce a DAO to make judgements if there is some conflicts happen between node runner and dapp developer.

The node runner have to stake $ANT to let his services listed on the decentralized services market. The DApp developers can pay $ANT to use the API, and the DApp developer can ask node runner to refund if the DApp developer think the services is not working or node runner makes fraud. The refund request will be listed on the decentralized services market, and the DAO will ask members to make a judgment of such conflicts.

Also, the DApp developer can use Apron SDK to call the API provided by node runners to generate more evidences of usage statistics. The fee of using API services will be paid periodically, such as once per week or month. 

> * I think the biggest problem with infura is also that it’s highly subsidized by consensys. Do you think this is problematic from a business perspective?

This is the typical business model to provide free or cheap products to prevent other competitors in some area. Consensys subsidize infura.io to provide free API service is nice to all the DApp developers, but on the other hand it will prevent other node runners to run a node or provide similar services. Monopoly is not what blockchain world wants. For each area, there should be at least two or three competitors. And I think Apron Network would one of the competitors in blockchain infrastructure services area.

**Comment by Noc2** [comment]
> The refund request will be listed on the decentralized services market, and the DAO members will make judgments of such conflicts.

Could you integrate this into the deliverables? I think this is actually the only way to solve it at the moment and we have quite a few times working on dao projects recently. Maybe you can leverage some of their work. Thanks

**Comment by Apron2050** [comment]
> > The refund request will be listed on the decentralized services market, and the DAO members will make judgments of such conflicts.
> 
> Could you integrate this into the deliverables? I think this is actually the only way to solve it at the moment and we have quite a few times working on dao projects recently. Maybe you can leverage some of their work. Thanks

Thank you @Noc2 

The deliverables updated.

**Review by Noc2 — APPROVED** [review]
Looks good to me. I will share it with the rest of the team.

**Comment by Apron2050** [comment]
> Looks good to me. I will share it with the rest of the team.

Thank you!

**Comment by mmagician** [comment]
@Apron2050 Could you please specify:
- the contracts you're planning to deliver as part of Milestone 1.2: `Apron Market Contracts Repo`
- what exactly will be included in the JS `Apron SDK Repo`, i.e. what functionality will be available to the user to interact with the nodes
Thanks!

**Comment by Apron2050** [comment]
Thank you for your comments!

Sorry for late reply that I was in hospital yesterday.

> @Apron2050 Could you please specify:
> 
> * the contracts you're planning to deliver as part of Milestone 1.2: `Apron Market Contracts Repo`

Apron Market Contracts Repo is the code repo for `the contracts of Apron Market`. Apron Market is a smart contract based API services market to connect API providers and DApp developers.
The contracts of Apron Market contain such functionalities as below:

1. Staking tokens to register API service for node runner
1. Register and unregister API service for node runner
1. Define the price of API service for node runner
1. Apply API service access key for node runner and DApp developers
1. Billing System of the API usage for node runner and DApp developers
1. Interface to integrate with a DAO to solve dispute between node runner and DApp developer

> * what exactly will be included in the JS `Apron SDK Repo`, i.e. what functionality will be available to the user to interact with the nodes

Apron SDK Repo is the code repo for `Apron SDK`. The main idea Apron SDK is to let DApp developer use Apron Network more easily. DApp developer can dynamic switch API service endpoint according to the availability of API services. For web dapps, it's much easier to switch API service endpoint than native dapps. Apron SDK provides the following functionalities:

1. Dynamic switch

>   Thanks!

**Comment by mmagician** [comment]
@Apron2050 Thanks for the answer and I hope you are feeling fine!
Could you please integrate the above lists into the application milestones?

**Comment by Apron2050** [comment]
> @Apron2050 Thanks for the answer and I hope you are feeling fine!
> Could you please integrate the above lists into the application milestones?

Updated.

Thank you! Much better now. Hope COVID could be ended soon.

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by RouvenP — APPROVED** [review]

**Comment by mmagician** [comment]
@Apron2050 I've amended the original contract [here](https://github.com/w3f/Open-Grants-Program/pull/323), as per the discussion in the [Grants Delivery Repo](https://github.com/w3f/Grant-Milestone-Delivery/pull/112#issuecomment-801213242). Please let me know whether this is fine with you

**Comment by Apron2050** [comment]
> @Apron2050 I've amended the original contract [here](https://github.com/w3f/Open-Grants-Program/pull/323), as per the discussion in the [Grants Delivery Repo](https://github.com/w3f/Grant-Milestone-Delivery/pull/112#issuecomment-801213242). Please let me know whether this is fine with you

@mmagician  Thank you for your efforts.

**Comment by jimmychu0807** [comment]
Thanks @mmagician and @Apron2050 for the update

**Pull request merged**
