### PR TITLE
pantera project

### PR DESCRIPTION
**Pull request by pantera612**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed (pantera.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by pantera612** [comment]
> # Grant Application Checklist
> * [x]  The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed (pantera.md`) and updated.
> * [x]  A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.
> * [x]  I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
> * [x]  The software delivered for this grant will be released under an open-source license specified in the application.
> * [x]  The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
> * [x]  The initial PR contains only one commit (squash if needed before submitting your PR).
> * [x]  The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

**Review by pantera612 — COMMENTED** [review]
ok

**Comment by alxs** [comment]
Thank you for the application @pantera612. I'm sorry to say that your application does not meet our standards and hence I'm closing the PR. The technical documentation you provide is simply an overview of a few Substrate/Rust components and the application itself is generally poor and hardly conveys any information about what you intend to achieve. The Web3 Foundation grants programs focus on technical grants and hence we expect that our grantees have a considerable level of technical expertise. I hope you're indeed able to find a solution for this pressing issue with the help of Substrate, but please understand that we unfortunately won't be able to support you.

**Comment by Noc2** [comment]
Just to add something here. Feel free to reapply with an improved application. The provides concrete technical details and not just “Substrate module: X”

**Pull request closed without merging**
