### PR TITLE
Polkadot-Dart

### PR DESCRIPTION
**Pull request by cyaolong**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks interesting. Could you provide a little bit more your interest in potentially maintaining/using this library in the future? The application also currently is above 30k and in general rather expensive for these kinds of implementation. Could you reduce the price? Additionally, I’m not sure why you attached all the images and want to merge them into the src folder.

**Comment by neeboo** [comment]
> Thanks for the application. This looks interesting. Could you provide a little bit more your interest in potentially maintaining/using this library in the future? The application also currently is above 30k and in general rather expensive for these kinds of implementation. Could you reduce the price? Additionally, I’m not sure why you attached all the images and want to merge them into the src folder.

Hi, @Noc2  

Thanks for point our problems, we have done some fixes.

1. Updated the future plans part, and if you feel they are still vague, we can draft some more and reduce content on the overview part.
2. Cleaned up the PR and remove images mistakenly included before. Sorry for our careless.
3. Reduced the price

Anythings are needed, please do tell us. Thank you!

**Review by Noc2 — APPROVED** [review]
Looks good to me. Thanks for the changes.

**Review by RouvenP — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Comment by semuelle** [comment]
@cyaolong @neeboo, are you still planning on submitting further milestones for this grant in the near future? Otherwise, we can terminate this agreement.

**Comment by neeboo** [comment]
> @cyaolong @neeboo, are you still planning on submitting further milestones for this grant in the near future? Otherwise, we can terminate this agreement.

We are working on it, dart and flutter had been upgraded a lot recently, we have to make sure the Null safety can be applied to this library. 

Will pick it up in a few weeks.

**Comment by alxs** [comment]
Hi @neeboo. Seeing as the duration of milestone 2 is one month and it's already delayed by half a year, I'd suggest submitting an amendment via PR with the expected delivery date. Otherwise the grant might be terminated before you submit, depending on what you mean by a few weeks.

**Comment by neeboo** [comment]
> Hi @neeboo. Seeing as the duration of milestone 2 is one month and it's already delayed by half a year, I'd suggest submitting an amendment via PR with the expected delivery date. Otherwise the grant might be terminated before you submit, depending on what you mean by a few weeks.

Sure, will do in two days.

**Comment by cyaolong** [comment]
> Hi @neeboo. Seeing as the duration of milestone 2 is one month and it's already delayed by half a year, I'd suggest submitting an amendment via PR with the expected delivery date. Otherwise the grant might be terminated before you submit, depending on what you mean by a few weeks.

Sorry for the delay. We have submitted an amendment via PR #451 . In order to express our greatest sincerity, we hope that we earn the rewards after finishing this project which means milestone 2, 3 and 4.

**Comment by alxs** [comment]
Many thanks @cyaolong @neeboo, we appreciate the gesture. Looking forward to your deliveries.

**Comment by alxs** [comment]
@cyaolong @neeboo any updates here? The [project repo](https://github.com/Pocket4D/Polkadot-Dart/branches) looks like it's been dead for the past ~2.5 months. If we don't hear anything from you in the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Pull request merged**
