### PR TITLE
PolkaJ Android Support proposal

### PR DESCRIPTION
**Pull request by nschwermann**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @nschwermann, thank you for your patience. I have reviewed your application and I'd be happy to share it with the rest of the team. The only thing that might stand in the way is the price tag. I might have to have someone more knowledgeable with PolkaJ and Android to look into this, but I 20k would be closer to what I would assume. 

I will share this with the rest of the team, let's see what they say. In the meantime, if you want to share anything with regard to the price, feel free to comment here or update the .md file!

**Comment by nschwermann** [comment]
> Hi @nschwermann, thank you for your patience. I have reviewed your application and I'd be happy to share it with the rest of the team. The only thing that might stand in the way is the price tag. I might have to have someone more knowledgeable with PolkaJ and Android to look into this, but I 20k would be closer to what I would assume.
> 
> I will share this with the rest of the team, let's see what they say. In the meantime, if you want to share anything with regard to the price, feel free to comment here or update the .md file!

Hey @semuelle that range sounds reasonable, definitely some wiggle room on my end.  I also noticed I had left in BTC instead of DAI for the total. Should I tweak prices now or wait to hear from the rest of the team?
Thanks!

**Comment by mmagician** [comment]
@nschwermann The application looks good, I'd be happy to support it. So if I understand correctly, one will be able to use the same codebase to run natively and in Android, right? Would there be any configuration needed on behalf of the user to distinguish which target they're building on, or do you envision it to be ready-to-use in any environment?

> Should I tweak prices now

Yes please, we would appreciate it if all was denominated in DAI.

**Comment by nschwermann** [comment]
> @nschwermann The application looks good, I'd be happy to support it. So if I understand correctly, one will be able to use the same codebase to run natively and in Android, right? Would there be any configuration needed on behalf of the user to distinguish which target they're building on, or do you envision it to be ready-to-use in any environment?
> 
> > Should I tweak prices now
> 
> Yes please, we would appreciate it if all was denominated in DAI.

@mmagician you are correct this will be the same code base and now it will generate 4 artifacts (jars) one for each platform windows, osx, linux, and android. Currently it is able to generate a jar for windows, osx, and linux but it only generates the jar for the platform you are building from. Now it will generate all 4 if you run the full assemble script or you can specify the target. Documentation will be updated on how to specify your target. No additional configuration will be required, they will just be separate gradle tasks. I will update BTC to DAI shortly.
Thanks!

**Comment by mmagician** [comment]
@nschwermann That sounds good, thanks for the info. As my peers have mentioned above, the price seems fairly high for the amount of work proposed. I would be happy to proceed with a cost closer to 20k DAI. If you could still find some room for adjusting the price then we could move this forward rather quickly - let me know.

**Comment by nschwermann** [comment]
@mmagician I have adjusted the cost to 7k per milestone for a total of 21k, does that sound fair?

**Review by mmagician — APPROVED** [review]
Perfect, thanks for the flexibility!

**Review by semuelle — APPROVED** [review]
I approve.

**Review by Noc2 — APPROVED** [review]

**Comment by nschwermann** [comment]
Great I am thrilled to be involved! I will be starting work this week. Once complete, how will I submit the deliverables for milestone one? @semuelle

**Comment by semuelle** [comment]
Congrats, Nathan.

Head over to our [milestone delivery repo](https://github.com/w3f/Grant-Milestone-Delivery) and follow the guidelines there. 

I'd recommend to also look at some merged PRs to see what kind of issues we tend to comment on or have requests about.

**Comment by alxs** [comment]
Hey @nschwermann! Care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery about 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but if you're no longer interested we would terminate the grant.

**Comment by nschwermann** [comment]
> Hey @nschwermann! Care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery about 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but if you're no longer interested we would terminate the grant.

Hey thanks for following up with me! I did run into some delays but I am nearly finished! I should have the first milestone complete within 2 weeks.

**Comment by alxs** [comment]
Hey, thanks for the quick reply. I see, happy to hear that! In that case, just submit whenever you're ready.

I don't know the details of what you're referring to, but just a reminder to amend the application via PR if this represents a significant change (which generally means if you need to remove one of the deliverables in the application). 

Looking forward to the delivery.

**Comment by nschwermann** [comment]
Just a quick update should be one more week.

**Comment by alxs** [comment]
@nschwermann if you can't submit within the week, I'd like to ask you to please submit an amendment.

**Comment by nschwermann** [comment]
Ok thank you I will submit an amendment on Sunday. Thanks for your patience.

**Comment by nschwermann** [comment]
I have submitted an amendment. I am very sorry for the delay and am ready and excited to finish the project. 
https://github.com/w3f/Grants-Program/pull/573

**Comment by alxs** [comment]
@nschwermann I [agree](https://github.com/w3f/Grants-Program/pull/573#issuecomment-1032720085) with your [comment](https://github.com/w3f/Grants-Program/pull/573#issuecomment-1124111892) that it doesn't make much sense to complete this grant, since PolkaJ is no longer being maintained. We'll go ahead and terminate it in the next few days unless you have anything against it.

**Pull request merged**
