### PR TITLE
Create nirvanasystem.md

### PR DESCRIPTION
**Pull request by nirvanasystem**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application, but we only pay out BTC via the open grants program. So you would need to change the cost to BTC. Additionally, we don’t pay for everything listed in milestone 1 (especially when it’s already considered done). In general, we only support the development of open source software that doesn’t already exist in our ecosystem. Furthermore, I took a look at your whitepaper and it contains very few technical, we would need a lot more information. Each milestone should ideally contain a list of what functionality you plan to implement.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application, but we only pay out BTC via the open grants program. So you would need to change the cost to BTC. Additionally, we don’t pay for everything listed in milestone 1 (especially when it’s already considered done). In general, we only support the development of open source software that doesn’t already exist in our ecosystem. Furthermore, I took a look at your whitepaper and it contains very few technical, we would need a lot more information. Each milestone should ideally contain a list of what exactly you plan to implement.

**Comment by nirvanasystem** [comment]
@Noc2 Thank you for your reply, we have modified as required, please check.

**Comment by ByKeks** [comment]
Hi @Noc2, I updated the proposal. Please check it, thank you

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. However, as I said before, we would not fund milestone 1 with our grants program as well as things like “Initial token distribution completed”. For other things like “Alpha” we would require a lot more technical details about the actual product, the implemented functions, tests, documentation, etc.  The grants program only focuses on supporting the development of open source software, which potentially can be leveraged by others and doesn’t already exist in the ecosystem.

**Comment by Noc2** [comment]
I’m closing the PR due to inactivity. Feel free to reopen it.

**Pull request closed without merging**
