### PR TITLE
Quadratic Funding Module and Dapp Application

### PR DESCRIPTION
**Pull request by chrisli30**
* Added quardratic funding proposal

* Finalized quadratic funding open grant proposal

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by chrisli30** [comment]
Hi guys, 

First time creating a proposal here! The funding amount of milestone one is a little bit over $30K. Of course I can break down the milestone but then the first deliver will hardly be in a feature-complete state. Could you take a look at it and let me know what you think?

Thanks!

- Chris

**Comment by Swader** [comment]
I can take a look next week at the earliest, going OOO in 2 days and lots to handle before then. Thanks for the proposal and sorry I can't be more timely with it!

**Comment by chrisli30** [comment]
> I can take a look next week at the earliest, going OOO in 2 days and lots to handle before then. Thanks for the proposal and sorry I can't be more timely with it!

That sounds good, Bruno. Thanks!

**Comment by semuelle** [comment]
@chrisli30, the USD 30k limit applies to the total of the grant. You will have to apply through the [General Grants program](https://github.com/w3f/General-Grants-Program) _or_ limit this one to 30k. Follow-up grants in the Open Grants program are not bound to that limit.

Other than that, some (inofficial) suggestions:

- could you add the `finalize` function to Deliverable 1 of Milestone 1? I know it's implied, just for completeness.
- if pallet and UI are part of one grant, submit the designs with M1 so there is time to discuss and iterate.
- I'm all for supporting studies and evaluations (M2 Deliverable 4), but I'm not sure the committee agrees with me there (@Noc2?). Either way, I personally would want to know in advance:
   - how do you choose subjects (what is the target audience)? What is the target size?
   - do you have specific questions you want answered or variables to measure?
   - are you planning on making the results or your conclusion(s) public? Will this be part of M2?

**Comment by chrisli30** [comment]
> @chrisli30, the USD 30k limit applies to the total of the grant. You will have to apply through the [General Grants program](https://github.com/w3f/General-Grants-Program) _or_ limit this one to 30k. Follow-up grants in the Open Grants program are not bound to that limit.
> 
> Other than that, some (inofficial) suggestions:
> 
> * could you add the `finalize` function to Deliverable 1 of Milestone 1? I know it's implied, just for completeness.
> * if pallet and UI are part of one grant, submit the designs with M1 so there is time to discuss and iterate.
> * I'm all for supporting studies and evaluations (M2 Deliverable 4), but I'm not sure the committee agrees with me there (@Noc2?). Either way, I personally would want to know in advance:
>   
>   * how do you choose subjects (what is the target audience)? What is the target size?
>   * do you have specific questions you want answered or variables to measure?
>   * are you planning on making the results or your conclusion(s) public? Will this be part of M2?

@semuelle, thanks for the input. Here's my response regarding your comments.

> the USD 30k limit applies to the total of the grant.
My mistake. I thought it only applies to M1 and at the time of writing 1 BTC was $30K, therefore I asked for 1 BTC for M1. I can squeeze in a simiple UI implementation(M2) to the program within $30K. 

> could you add the finalize function to Deliverable 1 of Milestone 1? I know it's implied, just for completeness.
Just to confirm. Do you mean when the referendum is voted and passed, a finalize() function to make the funds available for withdrawal?

> If pallet and UI are part of one grant, submit the designs with M1 so there is time to discuss and iterate.
Got it, I have been sketching the UI design and will add a wireframe.

> how do you choose subjects (what is the target audience)? What is the target size? do you have specific questions you want answered or variables to measure? are you planning on making the results or your conclusion(s) public? Will this be part of M2?
I think those questions are to the reviewers of this PR? A staightforward use case would be similar to Gitcoin's, in which the subjects are small open-source programs(for example, this project 😃 ) that would benefits the Polkadot ecosystem. You guys are already asking questions and measuring variables in this open grant program. If the LR fulfills the same purpose then the measurements wouldn't be much different. I personally would like to see if the LR approach could work, that is to attract more dev talents as well as public attention for donation.

**Comment by semuelle** [comment]
Hi @chrisli30, 

> Just to confirm. Do you mean that when the referendum is voted and passed, a finalize() function to make the funds available for withdrawal?

Yes, the diagram in your application mentions it. 

> Got it, I have been sketching the UI design and will add a wireframe.

Is that the extent of what you want to build in M2? Because that looks like quite a bit of work.

> I think those questions are to the reviewers of this PR? 

No, sorry, that was a bit confusing from me. What I meant to say was: to fund a study, I would like to know more details about the study. For example, how many people would you interview? What would be the questions/problems you are looking for? What are you going to do with the results?
However, since this is now one deliverable of many for 0.15 BTC, I wouldn't demand to know these things in advance.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply here. I have an additional request: Could you change the denomination to USD. We recently updated this in the template. Once you deliver the milestone we would then pay you in DAI or BTC according to the current price. Therefore the payment in DAI is usually easier. Also do you already have any plans regarding Sybil resistance or anti collusion? You should probably also take a look at the following project, which we recently signed: https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/nuclei_governance_os_voting.md Regarding the UI, do you have any previous work, which you could share?

**Comment by chrisli30** [comment]
@semuelle, regarding your comments Sebastian,
> Yes, the diagram in your application mentions it.

The finalize() function is added to M1 delivery. Thanks for pointing it out.

>Is that the extent of what you want to build in M2? Because that looks like quite a bit of work.

Yes, the schedule does seem a bit tight, but it's manageable. The goal is to build a MVP to show beta users what's this product is about. We probably need to cut corners, for example, using Google Forms for all the project submission instead of building fancy pages. Besides, this design doesn't include user profile & history component, which could be important to UX and should be considered in future plans.

> No, sorry, that was a bit confusing from me. What I meant to say was: to fund a study, I would like to know more details about the study. For example, how many people would you interview? What would be the questions/problems you are looking for? What are you going to do with the results? However, since this is now one deliverable of many for 0.15 BTC, I wouldn't demand to know these things in advance.

Yeah, you are right. The details of the user study wasn't clear at all, but since we are trying to squeeze all work into this open grant I think it's better to take it out from M2. I've moved it to Future Plans and listed all your questions for reference.

**Comment by chrisli30** [comment]
> Sorry for the late reply here. I have an additional request: Could you change the denomination to USD. We recently updated this in the template. Once you deliver the milestone we would then pay you in DAI or BTC according to the current price. 
Therefore the payment in DAI is usually easier.
Sure, updated payment into DAI.

> Also do you already have any plans regarding Sybil resistance or anti collusion? You should probably also take a look at the following project, which we recently signed: https://github.com/w3f/General-Grants-Program/blob/master/grants/speculative/nuclei_governance_os_voting.md

That's a great question! So far my best reference of Sybil resistence is Vitalik's post [Minimal anti-collusion infrastructure](https://ethresear.ch/t/minimal-anti-collusion-infrastructure/5413). I don't know if you have read it, but in order to prevent Sybil attack, a relationship map of any two participating wallets need to be stored and examined. The map could be in a quite large size, but considering that the donation funds will not be withdrawn until after finalize(), we can save the map off-chain(using IPFS) and only examine it during finalization. In addition, such implementation requires wallet identity, so that is up for future experiments, whether we choose strict identity, or tolerate collusion to a certain degree. Since donating to open source community is a great thing, my guess is that probably 99% of participants have no trouble disclosing who they are.

Regarding Nuclei governance-os, it's a great reference. However, I don't see the quadratic voting method in their delivery notes. I might need to go through their code commits and ask some questions.

> Regarding the UI, do you have any previous work, which you could share?
Yep, I've added the link to design files to **Update 2: UI Examples**, but you can visit from here.

https://drive.google.com/drive/folders/1nZPg4PmWSBxbfHuMyuAlw8UVXSybjTHG?usp=sharing

**Comment by chrisli30** [comment]
Hi @Noc2 , do you get time to take look at the changes this week?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick response. You also need to update the payment address at the top: “Payment Address: BTC, 141Y9sybQKH6rfCj6DhDeRFR9Ja7rAWKjw”. Are you planning to implement MACI? I mostly shared governance-os because they plan to use a commit reveal mechanism to deal with this, which might also be useful for you. Regarding sybil attack, it would be great if you could support the on-chain [identity module](https://github.com/paritytech/substrate/tree/master/frame/identity) of substrate, which is currently used for kusama as well as polkadot as part of this grant.

**Comment by chrisli30** [comment]
Hi @Noc2 , no worries and those are good suggestions. My reponse is below.

> Thanks for the quick response. You also need to update the payment address at the top: “Payment Address: BTC, 141Y9sybQKH6rfCj6DhDeRFR9Ja7rAWKjw”.

Oops, my mistake. I've updated the recipient address to ERC20 DAI.

> Are you planning to implement MACI? I mostly shared governance-os because they plan to use a commit reveal mechanism to deal with this, which might also be useful for you.

I tend not to re-invent wheels, so it would be great if we can re-use the solution with which the governance-os project comes up. I'll keep my eyes on that project. Besides, MACI has been added to the future roadmap of this proposal, so yes if we feel it needed we will go ahead implement it.

> Regarding sybil attack, it would be great if you could support the on-chain [identity module](https://github.com/paritytech/substrate/tree/master/frame/identity) of substrate, which is currently used for kusama as well as polkadot as part of this grant.

Yeah, I agree. I think being able to interact with identity module is essential. Our module should be able to filter participants based on their identity information. I've added that requirement to M1 delivery.

Thanks for the recommendations David 👍

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I’m happy to go ahead with it and will share the application with the rest of the team.

**Comment by chrisli30** [comment]
@Noc2 That's awesome! Thanks for the feedback, and yeah let's see if others have questions too.

**Comment by Swader** [comment]
I have reviewed this and it sounds good to me.

**Comment by semuelle** [comment]
Hi @chrisli30, some more questions:

1. Gitcoin, as far as I know, applies quadrating funding to CLR *rounds*, where the resulting contributions are calculated and paid out for all participating projects at the same time after a fixed runtime. Buterin et al. use a *monthly* payment schedule as an example. How do you envision payouts being scheduled in your project?
2. What are `projects` and `proposals` in this context (see Milestone 1, Deliverable 1)? I assume a project is what is being funded and what is proposed for possible funding to the council by a developer. But what is a proposal then? Maybe you could integrate projects and proposals into the UML diagram you already provided?

**Review by BenWhiteJam — DISMISSED** [review]

**Comment by chrisli30** [comment]
Hi @semuelle, thanks for your feedback. I gave some thoughts to your questions over the weekend and here're my answers.

> Gitcoin, as far as I know, applies quadrating funding to CLR rounds, where the resulting contributions are calculated and paid out for all participating projects at the same time after a fixed runtime. Buterin et al. use a monthly payment schedule as an example. How do you envision payouts being scheduled in your project?

That's a great question. As you mentioned, there are two types of payment, lump sum and installments. Lump sum is a sum that paid in a single payment all at once, while installments are funds divided up and paid out over time.

Currently the payment type can be set in two ways,
1. When submitting a project, the creator is required to define a payment schedule. This is to make sure the funding of the project is thought through at the time of initiation.
1. After the contribution period ends but before finalizing, the CLR council can update the payment type with a Revision proposal. This gives the council an opportunity to adjust the payment type.

> What are projects and proposals in this context (see Milestone 1, Deliverable 1)? I assume a project is what is being funded and what is proposed for possible funding to the council by a developer. But what is a proposal then? Maybe you could integrate projects and proposals into the UML diagram you already provided?

Similar to Polkadot, decisions or changes of CLR need to be voted upon. Since there are a variety of decisions, we need different types of proposal. In my current design, there are 3 types of proposal.

1. Governance, to change global configuration or member of council.
1. Regular, which is the most common type and includes below 3 sub-types,
    1. Admission, to approve or deny a project's application.
    1. Revision, to update project settings such as payment schedule before finalization.
    1. Finalization, to finalize a project, making contribution available for dispense.
1. Appeal. Anybody can challenge a result by creating an appeal proposal within a certain period of time (48 hours). The proposal needs to be approved by the majority of the council in order to pass. This is to ensure that the platform is monitored and challenged by the public.

The governance is quite staight-forward compared to Polkadot's two-lane referendum implementation, but I think it will lay a working foundation for the CLR. @semuelle if you need to add anything please let me know. I also updated the UML chart to include the concepts of Project and Proposal. Now you can comment on the chart directly by clicking on Request Access.

**Comment by chrisli30** [comment]
Oops, I updated the UML chart link but didn't know that the approvals would be dimissed by a new commit.

Sorry @BenWhiteJam and @Noc2 , but could you guys review again? 😅

**Comment by semuelle** [comment]
The updated diagram makes things a lot clearer. Thanks. 

No more questions from me.

**Review by semuelle — APPROVED** [review]
lgtm

**Review by Noc2 — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Comment by chrisli30** [comment]
Thank you guys! Your feedback is super helpful for sorting out the details. Time for us to work!

**Comment by Noc2** [comment]
@chrisli30 Sorry, it seems I deleted the message on the wrong PR. Here is the message again:
"Congratulations! As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly. To that end, we’ve created a [badge for projects](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md) that successfully delivered their first milestone. Please observe the  [foundation’s guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/announcement-guidelines.md) when making any announcements; in particular, <b>don’t announce the grant publicly before you've completed at least the first milestone of the project.</b> <br/><br/>  At that point, we will be happy to collaborate on an announcement about the work you’re doing.  Please get in touch with us at grantspr@web3.foundation in case you're interested (at least two weeks notice is preferred)."

**Comment by chrisli30** [comment]
@Noc2 Thanks, that's awesome! Sure, let me propose it with an email from chris@forgelab.io.

**Comment by alxs** [comment]
Hey @chrisli30, I saw your comment on Medium. Could you create a PR and update the team's name and website, as well as add the repo or organisation on which the project will be located? Then we'll update the grants accepted list and the article.

**Comment by chrisli30** [comment]
@alxs, thanks for pointing it out. 👍  I have submitted a PR #377 to address the change. Please take a look to see if the changes are fine.

**Comment by semuelle** [comment]
Hi @chrisli30, are you still working on the second milestone? According to the roadmap, this was projected for July.

**Comment by chrisli30** [comment]
> Hi @chrisli30, are you still working on the second milestone? According to the roadmap, this was projected for July.

@semuelle , yes we actually completed the work in July. Thanks for following up. We'll write a report and submit the result in 2 days!

**Comment by alxs** [comment]
@chrisli30 friendly reminder.

**Pull request merged**
