### PR TITLE
Zenlink: dex smart contract

### PR DESCRIPTION
**Pull request by v-van**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by v-van** [comment]
@mmagician @Noc2 Please take your time to have a look at it. Thanks!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Hi. Thanks for the new proposal. I have a few questions:

- Could you integrate the medium article/tutorial into the deliverables? 
- Could you specify that you are using ink! as part of the deliverables? 
- Could you reduce the price or add additional functionality like an interface? 0.5 btc seems quite expensive to me, given that you previously already implemented a similar functionality in the form of a pallet.

**Comment by v-van** [comment]
> * Could you integrate the medium article/tutorial into the deliverables?
> * Could you specify that you are using ink! as part of the deliverables?
> * Could you reduce the price or add additional functionality like an interface? 0.5 btc seems quite expensive to me, given that you previously already implemented a similar functionality in the form of a pallet.

**Review by Noc2 — DISMISSED** [review]
Thanks. I’m happy to go ahead with it and I will share it with the rest of the team.

**Review by mmagician — APPROVED** [review]

**Comment by v-van** [comment]
@mmagician 
I've integrated the new changes of the application template into this pr.

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Review by RouvenP — APPROVED** [review]

**Pull request merged**
