### PR TITLE
API Protocol

### PR DESCRIPTION
**Pull request by AlexDevAPI**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, the application is currently above the 30k limit of initial grant applications. Furthermore do you have any technical specifications or code, on which you already worked? You probably want to implement something similar to https://api3.org/, correct?

**Comment by AlexDevAPI** [comment]
> Thanks for the application. However, the application is currently above the 30k limit of initial grant applications. Furthermore do you have any technical specifications or code, on which you already worked? You probably want to implement something similar to https://api3.org/, correct?

I don't think we are the same as API3.org, API3.org is more about helping blockchain contracts to use off-chain data, somehow listing services for contracts, our starting point is to help developers to develop Dapp faster, if I say similar, it may be a bit similar to keep3r network, similar to Web 2.0 enterprise services rapidapi similar, we can apply for less than 30K, currently our project is still in the perfect and team components.

**Comment by Noc2** [comment]
Thanks for updating the price. However, we would still need to have more technical details (programming languages, specification, potentially some initial code, etc.).

**Comment by AlexDevAPI** [comment]
> Thanks for updating the price. However, we would still need to have more technical details (programming languages, specification, potentially some initial code, etc.).

OK, I will organize it, and then submit the PR

**Pull request closed without merging**
