### PR TITLE
Bwarelabs Decentralized API - Web3 grant application

### PR DESCRIPTION
**Pull request by eradus**
# Grant Application Checklist

- [X] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [X] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by eradus** [comment]
> [CLA assistant check](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=394)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/w3f/Open-Grants-Program?pullRequest=394) before we can accept your contribution.
> 
> **Radu Enoiu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/w3f/Open-Grants-Program?pullRequest=394) it.

Signed the cla and added the email to the commit. Not sure if the comment from the CLA assistant should update, refresh doesn't seem to be working

**Comment by alxs** [comment]
@eradus is `renoiu@fitbit.com` an email address on your account?

**Comment by eradus** [comment]
> @eradus is `renoiu@fitbit.com` an email address on your account?

hi! yes, I have 3 emails attached, do I need to remake the commit with the bwarelabs email?

**Comment by alxs** [comment]
That shouldn't matter. I don't know what else could be going wrong, try closing the PR and creating a new one.

**Comment by semuelle** [comment]
The user that committed the .md file to your own fork (`Radu Enoiu`, **not** `eradus`) seems to have had no email address and thus no Github account attached. You can still do that, but [it doesn't affect previous commits](https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user#commits-are-not-linked-to-any-user). So @alxs is right, it'd be easiest to create a new fork, add your .md file and create a new PR here. Just make sure your local `git` user has an email address associated that you (can) use on Github.

**Pull request closed without merging**
