### PR TITLE
Substrate package manager

### PR DESCRIPTION
**Pull request by clearloop**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission. 

---

The usage of [sup](https://github.com/clearloop/sup) starts with:

```
$ cargo install sup
$ sup new <your-substrate-based-chain>
```

### CODE REVIEW

**Comment by Noc2** [comment]
It seems you are still working on the application (e.g. you need to integrate a bitcoin address). Let us know once it’s ready for review. In the meantime, you might want to take a look at https://github.com/gantree-io, or https://github.com/Blockdaemon/bpm-sdk or general the open source tech stack: https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md

**Comment by clearloop** [comment]
> It seems you are still working on the application (e.g. you need to integrate a bitcoin address). 
>
> Let us know once it’s ready for review.

It's ready, @Noc2 , btw, does `the application` above means `the application` in this pull request...

**Comment by 4meta5** [comment]
This project description looks cool! I appreciate tools that make maintaining substrate repos easier :)

**Comment by mmagician** [comment]
@clearloop What is the added benefit of `sup new <your-awesome-substrate-based-project>` vs. cloning the node template  with : `git clone https://github.com/substrate-developer-hub/substrate-node-template.git`?

Regarding M2, could you provide an example command & an example of what would change (I assume in Cargo.toml?) as a result of running the command?

I think what David^ meant was that this PR seems incomplete, e.g. milestone 3 still needs definition. If you don't know what to do for M3, simply remove it from `sup.md` from this PR. You don't need to complete the project in order to get accepted to the Open Grants Program, but you need to have more details of what you propose in the milestones.

**Comment by clearloop** [comment]
> What is the added benefit of `sup new <your-awesome-substrate-based-project>` vs. cloning the node template with : `git clone https://github.com/substrate-developer-hub/substrate-node-template.git`?

## Generating a new node

| tool |command |
|-|-|
| sup |  new node-template |
| git | clone https://github.com/substrate-developer-hub/substrate-node-template.git |

As a result, `sup` is really easy to prompt and remember.

Just saw that substrate published all crates to crates.io XDD, but It was a long time that we only can build `node-template` with a million of http links to `substrate.git`, and `sup` is designed for managing substrate-based node with substrate git registry.

I didn't start my own substrate `node-template` when I know the substrate project for the first time a year ago, even the doc said I can clone a `node-template` from `https://github.com/substrate-developer-hub/substrate-node-template.git`.  Because I know it is **NOT THE LATEST ONE**. 

I had tried to migrate a `node-template` from `https://github.com/paritytech/substrate.git`, but I give up when I realized that I have to replace all relative paths to `https://github.com/paritytech/substrate.git`, it is too complex.

The development and iterating speed of the substrate project are too fast that even we publish them all to crates.io, it hard to keep updating, and new developers always need **THE LATEST SUBSTRATE DEPENDENCIES**.


## Upgrading a substrate node

It's a nightmare for substrate developers to upgrading their substrate node, the `replacing dependencies` work —— it upsets me every time I'm trying to do it or seeing my friends doing it.

Including the version control, it's a big problem.

And `sup` and upgrading or reverting your substrate node just in one command, just exec `sup upgrade <tag>`.


## Contributing to the substrate project

The big benefit of `node-template.git` above is it's using crates.io, but what will happen if a team finds that one of the substrate dependencies have BUGs?

Developers will raise an issue to the git repo of the substrate project, and the maintainers will reply to them: "Your node is outdated, please replace them to the latest one using `git`", after they try to catch up the `git` version of the substrate project, they hardly can back to the `crates.io`, because the substrate dependencies served on crates.io should not and hard to upgrade for a developer or a team, if the BUG or modification is little to substrate and big to the developer or the team.

On the other hand, using `sup` to start a new `node-template` from git registry, if developers find some issues, they might PR to substrate directly without thinking, lots of awesome open source project are managed directly using `git`, for example, `spacemacs`, `brew`, even the index of crates.io is using git.

It's so important for developers themselves to contribute to an open-source project, and it's the same for the maintainers.

## Developer node based on substrate-based node

`sup` supports replacing the `substrate.git` registry to other substrate-based projects if they are using the same arch of the substrate project, if helpful for substrate-based nodes as well~ 

`sup` is a choice for managing substrate dependencies, and it's sup.

**Comment by clearloop** [comment]
> Regarding M2, could you provide an example command & an example of what would change (I assume in Cargo.toml?) as a result of running the command?

Yep, it's in `**/*Cargo.toml`, modifying all dependencies of the substrate project, for example, 

<details>
<summary>Before sup, clone a node-template from <code>substrate.git</code></summary>
<pre><code>
[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
description = "A new FRAME-based Substrate node, ready for hacking."
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
structopt = "0.3.8"

sc-cli = { version = "0.8.0", path = "../../../client/cli", features = ["wasmtime"] }
sp-core = { version = "2.0.0", path = "../../../primitives/core" }
sc-executor = { version = "0.8.0", path = "../../../client/executor", features = ["wasmtime"] }
sc-service = { version = "0.8.0", path = "../../../client/service", features = ["wasmtime"] }
sp-inherents = { version = "2.0.0", path = "../../../primitives/inherents" }
sc-transaction-pool = { version = "2.0.0", path = "../../../client/transaction-pool" }
sp-transaction-pool = { version = "2.0.0", path = "../../../primitives/transaction-pool" }
sc-consensus-aura = { version = "0.8.0", path = "../../../client/consensus/aura" }
sp-consensus-aura = { version = "0.8.0", path = "../../../primitives/consensus/aura" }
sp-consensus = { version = "0.8.0", path = "../../../primitives/consensus/common" }
sc-consensus = { version = "0.8.0", path = "../../../client/consensus/common" }
sc-finality-grandpa = { version = "0.8.0", path = "../../../client/finality-grandpa" }
sp-finality-grandpa = { version = "2.0.0", path = "../../../primitives/finality-grandpa" }
sc-client-api = { version = "2.0.0", path = "../../../client/api" }
sp-runtime = { version = "2.0.0", path = "../../../primitives/runtime" }

\# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.0.0"
sc-rpc = { version = "2.0.0", path = "../../../client/rpc" }
sp-api = { version = "2.0.0", path = "../../../primitives/api" }
sc-rpc-api = { version = "0.8.0", path = "../../../client/rpc-api" }
sp-blockchain = { version = "2.0.0", path = "../../../primitives/blockchain" }
sp-block-builder = { version = "2.0.0", path = "../../../primitives/block-builder" }
sc-basic-authorship = { version = "0.8.0", path = "../../../client/basic-authorship" }
substrate-frame-rpc-system = { version = "2.0.0", path = "../../../utils/frame/rpc/system" }
pallet-transaction-payment-rpc = { version = "2.0.0", path = "../../../frame/transaction-payment/rpc/" }

\# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", path = "../../../frame/benchmarking" }
frame-benchmarking-cli = { version = "2.0.0", path = "../../../utils/frame/benchmarking-cli" }

node-template-runtime = { version = "2.0.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", path = "../../../utils/build-script-utils" }

[features]
default = []
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
]
</code></pre>
</details>

<details>
<summary>After sup, new a node-template with <code>sup</code></summary>
<pre><code>
[package]
name = "node-template"
version = "2.0.0"
authors = ["Anonymous"]
description = "A new FRAME-based Substrate node, ready for hacking."
edition = "2018"
license = "Unlicense"
build = "build.rs"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "node-template"

[dependencies]
structopt = "0.3.8"

sc-cli = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git", features = ["wasmtime"] }
sp-core = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-executor = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git", features = ["wasmtime"] }
sc-service = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git", features = ["wasmtime"] }
sp-inherents = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-transaction-pool = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus-aura = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sp-consensus-aura = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sp-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sc-consensus = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sc-finality-grandpa = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sp-finality-grandpa = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-client-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-runtime = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }

# These dependencies are used for the node template's RPCs
jsonrpc-core = "15.0.0"
sc-rpc = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-api = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-rpc-api = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
sp-blockchain = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sp-block-builder = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
sc-basic-authorship = { version = "0.8.0", git = "https://github.com/paritytech/substrate.git" }
substrate-frame-rpc-system = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
pallet-transaction-payment-rpc = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }
frame-benchmarking-cli = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }

node-template-runtime = { version = "2.0.0", path = "../runtime" }

[build-dependencies]
substrate-build-script-utils = { version = "2.0.0", git = "https://github.com/paritytech/substrate.git" }

[features]
default = []
runtime-benchmarks = [
	"node-template-runtime/runtime-benchmarks",
]
</code></pre>
</details>
 
---

> I think what David^ meant was that this PR seems incomplete, e.g. milestone 3 still needs definition. If you don't know what to do for M3, simply remove it from sup.md from this PR.

I've got some idea about `M3`, like developing `sup` like `cargo` in rust, `pip` in python, `pub` in dart, even `npm` in javascript, but I'm not sure if it is necessary and if it is welcomed, so I need some advice.

**Comment by mmagician** [comment]
@clearloop Thank you very much for a detailed explanation.
I find some discrepancies/outdated references though:
- You say that `before sup` the dependencies had hardcoded relative paths. You will find that since the latest v2 substrate release 7 days ago, there are no relative paths anymore in the default template. 
- Even in the release candidates before the official release, (e.g. rc6) the dependencies already specified git repos

Here I really struggle to see how your tools differs from the node template that one can readily clone. Perhaps you might want to take a look at the recent developments in substrate.

That said, I could potentially see the use of your tool for the upgrade command. I am not entirely sure how this differs from `cargo upgrade` (which is an external tool itself: see [here](https://github.com/killercup/cargo-edit)). Have you used cargo-edit` yourself perhaps and can you provide some insights?

Let me know your thoughts!

**Comment by clearloop** [comment]
> @clearloop Thank you very much for a detailed explanation.
> I find some discrepancies/outdated references though:
> 
> * You say that `before sup` the dependencies had hardcoded relative paths. You will find that since the latest v2 substrate release 7 days ago, there are no relative paths anymore in the default template.

The node-template in your mind is [substrate-developer-hub/substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template), which is not always the latest one, and sup uses the `node-template` directly in [paritytech/substrate](https://github.com/paritytech/substrate/tree/master/bin/node-template), which is always the latest.

| node-template | commits |
|-|-|
| substrate | 4543 |
| substrate-developer-hub/substrate-node-template | 68 |

the `substrate-developer-hub/substrate-node-template` is for the beginners who are totally new to substrate, and sup is for the developers who develop substrate.

> * Even in the release candidates before the official release, (e.g. rc6) the dependencies already specified git repos

The is like...if we can ride a bicycle from Beijing to New York, why we take an airplane?

Seriously speaking, `sup` is a choice, which is much better convenient than find the `substrate-developer-hub/substrate-node-template` repo and type a long `https://github.com/substrate-developer-hub/substrate-node-template.git` downloading it.
 
> Here I really struggle to see how your tools differs from the node template that one can readily clone. Perhaps you might want to take a look at the recent developments in substrate.
>
> That said, I could potentially see the use of your tool for the upgrade command. I am not entirely sure how this differs from `cargo upgrade` (which is an external tool itself: see [here](https://github.com/killercup/cargo-edit)). Have you used cargo-edit` yourself perhaps and can you provide some insights?

For `cargo upgrade`, which has no updates in 6 months, it depends on the crates.io which only updates when you `cargo push`(It hard to substrate to cargo push on every commit), and limited by it, not the latest registry as above...and for repo so much big like substrate, run `cargo upgrade` is a mess, what if you only want to upgrade substrate dependencies?

**Comment by mmagician** [comment]
@clearloop Ok, I see that you're targeting the repository from https://github.com/paritytech/substrate.

You are right in saying that the `substrate` repo is more recent (i.e. less stable) than the one in `substrate-developer-hub`, but honestly, comparing the number of commits there is like comparing apples to oranges - the former is a development repo for substrate, whereas the latter contains only the node template, so obviously it will get less frequent commits. 

Also, `cargo upgrade` has an option to specify which dependencies you want to upgrade:
```
ARGS:
    <dependency>...    Crates to be upgraded
```

Now, the decision of whether to accept the grant or not is not solely mine to take. I would, however, ask you to remove milestones 3 & 4 which are not precise. We can only support specific & well-defined deliverables. If later on you wish to add more features to `sup` & you know exactly what to add, you are welcome to apply for a follow-up grant.

In addition, please format your milestones 1 & 2 by following this [development roadmap](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#development-roadmap-nut_and_bolt). It might seem like a lot of formalities for the small scope of `sup`, sorry about that - but this way we ensure that all applications can later be judged fairly & against the same criteria.

**Comment by clearloop** [comment]
sup is some project that makes the ecosystem more elegant and efficient, not the project adding functions the ecosystem can not reach in result before.

> Comparing the number of commits there is like comparing apples to oranges - the former is a development repo for substrate, whereas the latter contains only the node template, so obviously it will get less frequent commits.

The commits part wanted to describe the fresh level of the two repos in the impression of the substrate project to developers, it affects on if people will try the substrate project, not just setting up a latest `node-template`.

> Also, `cargo upgrade` has an option to specify which dependencies you want to upgrade:
> 
> ```
> ARGS:
>     <dependency>...    Crates to be upgraded
> ```

The `cargo upgrade` can accept regex to match dependencies, it requires developers to find out which dependencies are belong to the substrate project themselves, which is like, `cargo upgrade /frame-.+|substrate-.+|node-.+|pallet-.+|sc.+|sp.+/`, and they must make sure if they upgraded something wrong in the regex.

Besides, `cargo upgrade` only can upgrade dependencies served on crates.io, they aren't always the latest, as we know.

> Now, the decision of whether to accept the grant or not is not solely mine to take. I would, however, ask you to remove milestones 3 & 4 which are not precise. We can only support specific & well-defined deliverables.

No problem, I just want to verify that I have written something valuable and it makes things better, slim the milestones will let me move on to the next project of mine soon, I'll update the application later tonight, and thanks for reading my long explanation patiently, sometimes I'm a guy who cares about the particulars of projects extremely, and my attitudes were awful when I think that others can not get my ideas XDD

**Review by mmagician — CHANGES_REQUESTED** [review]
Pending changes, see conversation above.

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by clearloop** [comment]
Recorded in [substrate-developer-hub/awesome-substrate](https://github.com/substrate-developer-hub/awesome-substrate#ecosystem-tools).

**Review by laboon — APPROVED** [review]

**Pull request merged**
