### PR TITLE
DipoleOracle for OpenGrant

### PR DESCRIPTION
**Pull request by renyanduo**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by renyanduo** [comment]
> Thanks for the application. This sounds really interesting. Could you maybe point out how your oracles are different from other existing solutions: [Oracle by Laminar](https://github.com/laminar-protocol/open-runtime-module-library/tree/master/oracle), [Oracle by Katal Chain](https://github.com/katalchain/blockchain/tree/master/modules/oracle). Also, could you add information regarding the Full-time equivalent (FTE), see our latest template [here](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and the total cost of the application is currently above 30k. But from looking at the milestones, I think we would be mostly interested in funding milestone 1 at the moment. It might be too early to fund the second milestone and this milestone might be too specific to your solution to be used by others. And finally something to be aware of, is that we currently only pay out BTC via the open grants program. If you are interested in other payments, especially DOTs, you might want to take a look at the general grants program.



> Thanks for the application. This sounds really interesting. Could you maybe point out how your oracles are different from other existing solutions: [Oracle by Laminar](https://github.com/laminar-protocol/open-runtime-module-library/tree/master/oracle), [Oracle by Katal Chain](https://github.com/katalchain/blockchain/tree/master/modules/oracle). Also, could you add information regarding the Full-time equivalent (FTE), see our latest template [here](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and the total cost of the application is currently above 30k. But from looking at the milestones, I think we would be mostly interested in funding milestone 1 at the moment. It might be too early to fund the second milestone and this milestone might be too specific to your solution to be used by others. And finally something to be aware of, is that we currently only pay out BTC via the open grants program. If you are interested in other payments, especially DOTs, you might want to take a look at the general grants program.

Thanks for your inputs! We have updated the latest version, especially please find the advantage part for the difference from Oracle by Laminar and Oracle by Katal Chain. Please have a look and let's know what's next.

**Comment by renyanduo** [comment]
> Thanks for the update. First of all it seems like you increased the price for the first milestone. Could you explain why you did this? I also can tell you that the current day rate based on your FTE is more than double what we usually pay, so I don’t think that the operations team is going to accept this. Additionally, could you clarify if all modules are actually substrate modules/pallets and potentially describe their functionality more detailed, because currently some of the functions you describe for the different modules seem less ideal for on-chain storage and execution. One solutions for this is usually to only put certain hashes on-chain (and for example to use IPFS).

Thanks for your replay. 
Based on the background data you provided, we have updated the application.
Onchain data is just for recording and updating  latest status of hardwares. Compare with other program, there is no massive onchain data.

**Comment by renyanduo** [comment]
> hi @renyanduo. Thanks for the application. The day rate per FTE still seems fairly high in comparison to what we usually pay. Could you come down with the price?

Hi, @RouvenP. Thanks for you reply. We learned the back ground information of FTE from previously replier and reduced the price to acceptable one. At the same time, we go through other familiar projects, compare with them we currently think our price is reasonable. However we understand different people may have different thoughts on same project, thus we are likely to know your suggested price if it's fine with you. Thank you very much!

**Comment by RouvenP** [comment]
> > hi @renyanduo. Thanks for the application. The day rate per FTE still seems fairly high in comparison to what we usually pay. Could you come down with the price?
> 
> Hi, @RouvenP. Thanks for you reply. We learned the back ground information of FTE from previously replier and reduced the price to acceptable one. At the same time, we go through other familiar projects, compare with them we currently think our price is reasonable. However we understand different people may have different thoughts on same project, thus we are likely to know your suggested price if it's fine with you. Thank you very much!

Thanks for your reply @renyanduo. In addition to FTEs we also consider amount of work days, location of the team and the current USD valuation of the BTC price. I would have suggested a price of 0.8 BTC - this is still above our usual rates. Let me know what you think.

**Comment by renyanduo** [comment]
> > > hi @renyanduo. Thanks for the application. The day rate per FTE still seems fairly high in comparison to what we usually pay. Could you come down with the price?
> > 
> > 
> > Hi, @RouvenP. Thanks for you reply. We learned the back ground information of FTE from previously replier and reduced the price to acceptable one. At the same time, we go through other familiar projects, compare with them we currently think our price is reasonable. However we understand different people may have different thoughts on same project, thus we are likely to know your suggested price if it's fine with you. Thank you very much!
> 
> Thanks for your reply @renyanduo. In addition to FTEs we also consider amount of work days, location of the team and the current USD valuation of the BTC price. I would have suggested a price of 0.8 BTC - this is still above our usual rates. Let me know what you think.

Thanks for your reply, @RouvenP.  We carefully calculated the labor cost in our company which based in Shanghai, and considered the USD valuation of BTC price together with the exchange rate, we can accept 1 BTC as minimum and we have updated the latest version. Thanks.

**Comment by renyanduo** [comment]
> @renyanduo Thanks for reducing the price further. Taking the short time frame into account we can pay above our usual rate this time.

Thanks for your approval, would you please let us know what can we do to make it go to next step? Thanks a lot!

**Comment by Noc2** [comment]
Sorry for the delay. Everyone is extremely busy. I pinged the rest of the committee again in order to get their feedback/opinion.

**Comment by renyanduo** [comment]
Many thanks 🎉

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grantspr@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by renyanduo** [comment]
Thanks a lot! We do interested in making announcement and I will send the contact email to the address above. Anything need me follow up please just let me know.

**Comment by renyanduo** [comment]
One more question, when is estimated for us to get the grant?

**Comment by Noc2** [comment]
Hi @renyanduo  You get paid once you deliver the milestone and it’s accepted, according to the process here: https://github.com/w3f/Open-Grants-Program#pencil-process

**Pull request merged**
