### PR TITLE
Substrate based BIP 32

### PR DESCRIPTION
**Pull request by riodefi-dev**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by riodefi-dev** [comment]
> Thanks for the application. But your PR currently contains two files. Could you remove the application-template.md? Also your application currently contains total costs of 0.5 BTC as well as 23000 USD. And are you aware that HD wallet addresses are integrated in polkadot js: https://stackoverflow.com/questions/57867105/in-polkadot-js-is-there-a-method-to-create-hd-wallet-addresses

The extra file has been deleted.

**Comment by Noc2** [comment]
Thanks for the update. What I don’t understand is why you want to implement it in rust, when you plan to use a web application anyway. Couldn’t you just use the existing polkadot.js solution for it?

**Comment by riodefi-dev** [comment]
> Thanks for the update. What I don’t understand is why you want to implement it in rust, when you plan to use a web application anyway. Couldn’t you just use the existing polkadot.js solution for it?

To help implement BTC Derive related logic on the blockchain or client side, especially some cross-chain solutions may need this feature.

**Comment by Noc2** [comment]
> To help implement BTC Derive related logic on the blockchain or client side, especially some cross-chain solutions may need this feature.

Could you be more specific about this?

**Comment by mmagician** [comment]
This functionality that @Noc2 mentions is also available via the `subkey` cli, so any client side application should be able to use the `subkey` binaries to perform key derivation. E.g.:
```
subkey inspect "<my mnemonic>/soft/testing"
```
or
```
subkey inspect "<my mnemonic>//hard//testing"
```
What you're suggesting in your proposal has already been implemented. Therefore I'm closing this PR.

**Pull request closed without merging**
