### PR TITLE
DEIP - IP Management/Governance Module

### PR DESCRIPTION
**Pull request by aliakseikulik**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. As I said before, this looks really interesting. Could you specify the programming language/framework, which you are planning to use as part of the deliverables (table)? Also would it be possible to reduce the price a little bit further?

**Review by Noc2 — DISMISSED** [review]
Thanks for the update. I’m happy to go ahead with it. But I’m not sure how you plan to use С++ to be honest. I will share the application with the rest of the team.

**Review by RouvenP — DISMISSED** [review]

**Comment by mmagician** [comment]
@aliakseikulik I have a couple of comments regarding your milestones:

> M1.1: Create, manage members (invite, exclude), access control, decision-making via group voting

Have you checked out other teams building DAOs on Polkadot? Perhaps you could leverage their work instead of reinventing the wheel, thus saving yourself extra effort. There are teams which have applied for building DAO using [smart contract approach](https://github.com/w3f/Open-Grants-Program/pull/90) as well as [pallet/submodule approach](https://github.com/w3f/Open-Grants-Program/pull/96) + even hardware based DAOs. If there are features which these approaches are missing, could you please explain the differences & advantages of your approach?

> M1.3: Register (timestamp) a fact of creation and/or ownership of specific IP asset on the blockchain.

This is implied by the immutability property of the blockchain & the transaction authorship. Each Polkadot block already has a timestamp included. I don't quite see what is your contribution to this milestone.

> M1.4: Manage access permissions to specific IP asset with unique Proof of Share entries that confirm a specific user was granted access to an asset.

Could you elaborate please on the details of `Proof of Share`? I haven't encountered this term before & I wonder how this would be implemented.

> M1.5: Web-based UI

Are you planning to re-use the existing MVP front-end? I imagine that mostly you will need change the storage system that is used, from a centralised DB and instead read data from the chain - am I right?

Thank you!

**Comment by aliakseikulik** [comment]
@mmagician 

> Have you checked out other teams building DAOs on Polkadot? Perhaps you could leverage their work instead of reinventing the wheel, thus saving yourself extra effort. There are teams which have applied for building DAO using smart contract approach as well as pallet/submodule approach + even hardware based DAOs. If there are features which these approaches are missing, could you please explain the differences & advantages of your approach?

Thank you for the suggestion. We are indeed very interested in reusing the work of Polkadot ecosystem members as much as possible. The pallet/submodule approach looks really interesting, but I do not see any activity in their repository. We will definitely contract the team to clarify the current state. 
One of the reasons we want to join the Polkadot ecosystem is that we strongly believe that most good solutions will be or already are members of the ecosystem. And references to valuable projects that can speed up our development are much appreciated. We will try to integrate as many ecosystem projects as possible to build a platform for Intellectual Property management. We are sure that delivering and promoting real use-cases will also help to drive adoption not only of our project but also of other ecosystem members too. 

> This is implied by the immutability property of the blockchain & the transaction authorship. Each Polkadot block already has a timestamp included. I don't quite see what is your contribution to this milestone.

Registration of IP assets is much more than just timestamping a hash of asset actually. In many cases, IP assets are owned by an organization. Furthermore, there are usually several people who were involved in the process of the creation of such assets, and they all should be credited when registering assets. Thus, a timestamp only is not sufficient and not futureproof and we should add more metadata. All this data will be used for tokenization, reward distribution by incentive system,  ownership transfers, and many more once we proceed with the future development of the platform.

> Could you elaborate please on the details of Proof of Share? I haven't encountered this term before & I wonder how this would be implemented.

Proof of Share is a term we use for a special cryptographic proof that a sender actually sent, and the receiver has actually received an encrypted payload and a key to decrypt it. Please refer to the attached image.

image_2020-12-14_13-59-47

> Are you planning to re-use the existing MVP front-end? I imagine that mostly you will need change the storage system that is used, from a centralised DB and instead read data from the chain - am I right?

You are partly right. We will definitely re-use the existing MVP frontend. It works with our own custom blockchain, so most of the work will be updating the libraries to change the way we communicate with the blockchain.

**Comment by mmagician** [comment]
@aliakseikulik Thanks for your answers.

1. You're right that the other DAO projects have not yet got tangible results. I wonder, would it be possible for you to leave out the DAO part for the moment and perhaps mock up the functionality required for other components to function? This way your team can focus on the core logic of your proposal & hopefully at some point plug-in the DAO capabilities from other community pallets? And if, by the time you're done with the IP management part, no DAO modules have yet been delivered, you could apply for another small grant to finalise that work. (I'm also aware that even if another team delivers a DAO module, integration work might potentially be needed). Let me know how this sounds. And of course feel free to reach out to teams as you suggested.
2. > Thus, a timestamp only is not sufficient and not futureproof and we should add more metadata.

Would you mind specifying what other metadata you'd be including during the registration of an IP asset please?

3. That's an interesting protocol. Two questions there:
- From a conceptual point of view, why would you only want to provide specific users with the access rights to an asset, vs. making the encrypted version public and only revealing the AES keys when convenient? Or are you trying to provide both private (user-specific) & public access?
- There seem to be two ways of communicating between the sender & receiver, on-chain & off-chain. How are you planning to support the off-chain (Secure channel) exchange of information? Is this a separate communication protocol?
I am thinking that at least in theory this could all happen on chain as well, since the sender could just encrypt the `AES Encrypted Payload` with the receiver's public key (and the second exchange over the secure channel is already encrypted with that public key). Would that work?

**Comment by aliakseikulik** [comment]
> You're right that the other DAO projects have not yet got tangible results. I wonder, would it be possible for you to leave out the DAO part for the moment and perhaps mock up the functionality required for other components to function? This way your team can focus on the core logic of your proposal & hopefully at some point plug-in the DAO capabilities from other community pallets? And if, by the time you're done with the IP management part, no DAO modules have yet been delivered, you could apply for another small grant to finalise that work. (I'm also aware that even if another team delivers a DAO module, integration work might potentially be needed). Let me know how this sounds. And of course feel free to reach out to teams as you suggested.

It sounds reasonable, but we need some way to at least minimally manage organizations because assets are owned by organization initially. Let's do next, we will implement a minimal needed governance operations for IP assets, but will also implement an adapter, which will allow to connect any DAO pallets in the future. 

> Would you mind specifying what other metadata you'd be including during the registration of an IP asset please?

I believe we have a little bit of misunderstanding regarding timestamping. For sure we reference timestamp in Polkadot block as a timestamp for IP assets registration, but we also put a hash of digital IP asset to the blockchain. Together with hash of the IP assets we also enable a set of metadata, like 1) reviews, which reference an asset by hash to ensure that the review is relevant to this specific IP asset; 2) tokenization - security tokens attached to the IP asset and represent ownership of IP asset and allows to share/sell/exchange it’ 3) references to other IP assets which were used to produce this specific asset; 4) set of rules describing how the IP asset is transferred or licenced; 4) reference to the bundle of IP assets this specific asset belongs to.
The abovementioned features will be implemented in future phases after we create an infrastructure for this in the initial phase.

> From a conceptual point of view, why would you only want to provide specific users with the access rights to an asset, vs. making the encrypted version public and only revealing the AES keys when convenient? Or are you trying to provide both private (user-specific) & public access?

We want asset owner to have options to setup access options for each specific asset. It means, that there could be both public and private assets. The problem with always public access is that the Proof Of Share protocol proves that a specific user shared assets with another specific user and registers this fact on the blockchain (the fact that the receiver has both encrypted payload and a key). Therefore, every time anyone shares an asset with anyone else, a new AES key is generated.

> There seem to be two ways of communicating between the sender & receiver, on-chain & off-chain. How are you planning to support the off-chain (Secure channel) exchange of information? Is this a separate communication protocol?
I am thinking that at least in theory this could all happen on chain as well, since the sender could just encrypt the AES Encrypted Payload with the receiver's public key (and the second exchange over the secure channel is already encrypted with that public key). Would that work?

You are right, the "secure channel" in the diagram could be any communication protocol, even public one. Proof Of Share is agnostic to what exact communication channel is used. We are still exploring and deciding regarding the actual way we will implement it, but we will have a suitable solution designed prior to starting the implementation stage. And yes, in theory, it could happen on-chain as well.

**Comment by mmagician** [comment]
> It sounds reasonable, but we need some way to at least minimally manage organizations because assets are owned by organization initially. Let's do next, we will implement a minimal needed governance operations for IP assets, but will also implement an adapter, which will allow to connect any DAO pallets in the future.

@aliakseikulik Could you integrate that into your application please? 

The rest sounds good. Lastly, I would like to ask you to reduce the price of the milestone, first of all because of the lesser scope of DAO delivery; second, due to the BTC spike the current price is above our Open Grants limit.

**Comment by aliakseikulik** [comment]
Application is updated

**Review by mmagician — APPROVED** [review]
Thank you for the updates!

**Review by Noc2 — APPROVED** [review]

**Review by RouvenP — APPROVED** [review]

**Comment by aliakseikulik** [comment]
Thank you for your approval! We are looking forward to making our contribution to the Polkadot ecosystem.

**Comment by alxs** [comment]
@aliakseikulik just checking in: when do you roughly expect to deliver M2?

**Comment by aliakseikulik** [comment]
@alxs hello. We are planning delivery in September

**Comment by alxs** [comment]
@aliakseikulik checking in again - no worries about the current delay, though if you can't submit within the next 2-3 weeks, we'd ask you to please submit an amendment to update the duration or include an ETA in the application.

**Comment by alxs** [comment]
@aliakseikulik please [submit the amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval). Thanks in advance. It should add a final delivery date to your application and also update the price to an appropriate USD amount, as we no longer accept grants denominated in BTC.

**Comment by semuelle** [comment]
Hey @aliakseikulik. Are you still planning on finishing Milestone 2? There hasn't been any activity on the pull request in over two months.

**Comment by alxs** [comment]
@aliakseikulik please note we'll assume you're no longer interested and terminate the grant unless we hear from you within the next 2 weeks.

**Comment by aliakseikulik** [comment]
Hello guys. Unfortunately due to conditions on the market we had to stop activities on web UI that is deliverable for milestone 2 and focus on our core protocol features for now.

**Comment by alxs** [comment]
Sorry to hear that. In that case, shall we terminate the grant or would you like to submit an amendment?

**Comment by alxs** [comment]
I'm putting the grant up for termination since milestone 2 is delayed by 5 months according to the last amendment, and you said you stopped working on it. Feel free to reapply if you want to work on a grant again.

**Comment by Noc2** [comment]
> Hey @alxs, I am following up on the grant program. we would like to continue. should we make an amendment on the current program or submit a new one? and what exactly do you require as information? Thanks

It’s nice to hear that you want to continue to work on it. It depends a little bit on what you want to work. Does it still make sense to continue with the old grant or do you want to maybe define new milestones, etc? I usually would recommend creating a new grant application after such a long time, but it’s up to you. In any case, we need the council's approval for this.

**Comment by FlorianVanGoethem** [comment]
Hey,
thanks for your feedback. Makes sense to create a new application. However what is the best approach, we can't fork the application since it has already been forked.

**Pull request merged**
