### PR TITLE
Update SubGame Milestone

### PR DESCRIPTION
**Pull request by xtony77**
After a period of effort, our team has developed the requirements in the proposal, but we found that there is room for improvement in some of the items, so we would like to propose changes to the proposal to better match the description of the finished product we have implemented.

Modify items:
- Modify token symbol SGT to SGB.
- We have modified the pallet to make the pallet function complete.
- Optimize front-end UI.

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @xtony77, thank you for your application. Could you please have a look at our application template and add all the other required information to your pull request?

**Comment by alxs** [comment]
Hey @xtony77. Could you also reduce the price since you removed some deliverables? Also is there any particular reason you removed the Dockerfile? We generally require it since it makes it easier for us to test the delivery.

**Comment by xtony77** [comment]
@alxs . Originally we removed Docker because we thought it would be enough to provide a showcase website, but after our discussion we finally decided to let the engineers provide the Docker environment.

About the application fee may not be reduced because we still provide the finished product according to the original specification, but we just optimize the idea we proposed at the beginning.

**Comment by alxs** [comment]
Let me know if I'm missing anything, but in the original application you proposed to deliver:
- A `pallet-gamecenter` to manage game templates.
- A `pallet-gametemplates` library along with 
- A first game template, listed also under the `pallet-gametemplates` deliverable

However, now you intend to deliver only the last of those, the first game template. How is that not reducing the scope?

**Comment by xtony77** [comment]
We condensed the function into the guess hash pallet during development, but forgot to match the proposal description, The original pallets has been added back to the proposal.

**Comment by alxs** [comment]
Thanks. So to summarise with this amendment you're only
- Changing the ticker
- Removing the token from the deliverables
- Specifying the first game template deliverable
- Updating the mockups

Correct?

**Comment by xtony77** [comment]
> Thanks. So to summarise with this amendment you're only
> 
> * Changing the ticker
> * Removing the token from the deliverables
> * Specifying the first game template deliverable
> * Updating the mockups
> 
> Correct?

Yes!

**Review by alxs — APPROVED** [review]
Thanks for clarifying. I don't think an amendment is strictly necessary, but I see no problem with it.

**Review by semuelle — APPROVED** [review]
lgtm

**Review by mmagician — APPROVED** [review]
Thanks for the update & good luck with finishing the work!

**Pull request merged**
