### PR TITLE
Sunrise DEX application

### PR DESCRIPTION
**Pull request by johnwhitton**
# Sunrise DEX

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks like an interesting project. The [milestone overview](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#overview-1) seems to be missing in your application. Also 1.5 BTC are currently above the open grants 30k limit and could you describe the SWAP functionality a little bit more detailed. In general we will use the specification (these are basically the requirements of our contract) to evaluate your delivery, so details or links as part of the specification/tables are highly appreciated.

**Comment by johnwhitton** [comment]
@Noc2 Thanks for the feedback and quick turnaround. I have added in the milestone overview and adjusted the costing.
I will also add in more detail for the SWAP functionality and provide more details on the specification and will let you know once it is ready for review.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I have just one more question: Would it be possible to replace the GPL v3 License with Apache, MIT or the unlicense? Also could you update the BTC price again?

**Comment by johnwhitton** [comment]
@Noc2 I have added in more detail for the SWAP functionality, updated the License to Apache and updated the BTC price. It is now ready for review. Thanks for all your work on this.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. Looks good to me.

**Review by mmagician — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Comment by alxs** [comment]
Hey @johnwhitton. Are you still working on this project? Milestone 1 is by now delayed by 5 months and the last public commit on the Sunrise [organisation](https://github.com/sunriseprotocol) dates back to February. Unless we hear something from you soon, the grant will be terminated due to inactivity.

**Comment by alxs** [comment]
This grant is being terminated due to inactivity. Feel free to apply again if you're still interested.

**Pull request merged**
