### PR TITLE
CRYPTOINDUS

### PR DESCRIPTION
**Pull request by ganok321**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by ganok321** [comment]
> Thanks for the application. I have few comments/questions:
> 
> * First are you aware of the following nft parachain project: https://github.com/usetech-llc/nft_parachain and how is your project different from it or maybe could you use some of their work?
> * In general, could you add more details to your milestones? For example, what are the exact functions of your runtime? Documentation and tests for each milestone.
> * The polkadot.js extension integration is currently listed under the first milestone as well as the second milestone.  What’s the difference between these?
> * Are you planning to develop your own mobile wallet as part of milestone 2? Which technologies are you planning to us (e.g. Flutter)?
> * The running of nodes of milestone 3 is usually something we don’t support. Also how will your ipfs implementation look like? We have signed already few projects that leverage ipfs.
> * And finally do you want to receive DOTs as part of your grant? In this case, I would suggest to apply via the general grants program for now.

**Comment by ganok321** [comment]
Thanks for your reply！！@Noc2
- Most NFT creation logic is very similar, but we trade art NFT, which has certain requirements on the ability of the creator and requires a certain art foundation, rather than just some basic operation to upload NFT. This is equivalent to OpenSea relative to SuperRare. We use the NFT feature to make more artists independent，Of course, we are building in the Polkadot ecology, building Web3 together.

- Thank you for your reminder, we will update more detailed information.

- The first milestone user can use polkadot.js extension to  interact with chain ,but cannot manage his Artvenus
Second milestone we will add the Artvenus management in polkadot.js extension so that the user can see his artvenus in polkadot.js extension

- We will consider to develop our own wallet by useing ReactNatice ,but if we have some existed opensource wallet template ，that would be better.

- On Christmas Eve last year, Gavin Wood was AMA on Twitter, "looking for an initial storage solution as a parachain. Whatever we do it will likely be integrated into IPFS ”
The nft artwork on the chain is inseparable from the cid of ipfs.
If the infrastructure does not support this now, but in the future we will follow the development of the Substrate, as well as product changes to support this feature, we will also independently upload the artwork to the IPFS network.

- We have a huge market for digital art transactions in China, and we believe this will be an active DApp with a large number of users in the Polkadot ecosystem. So we want to apply for an open grant, let countless artists around us become independent as soon as possible, and then become active in the polkadot ecosystem.

**Comment by ganok321** [comment]
Thank you. We are a Team from China and it is the first time for us to apply for Open Grant for Web3. What kind of process are we in? 😃

**Comment by ganok321** [comment]
We started to build the website in early May. I am the designer of the website, and I have updated some design details in these two days. However, I am afraid that our website in China will be slow to open in Germany 😭

**Comment by Noc2** [comment]
Closing this PR due to inactivity. Let me know if I should open it again.

**Pull request closed without merging**
