### PR TITLE
Application: wrapp3d LTC

### PR DESCRIPTION
**Pull request by surged-finance**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "wrapp3d.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by surged-finance** [comment]
0a-0d updated.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you provide a link to your related or previous open source work? You say you want to leverage the XCLAIM design. In this case, I think it might make sense to wait for interlay to finish the implementation and potentially leverage their work: https://github.com/interlay If you don’t want to leverage interlays work, how is your solution different? In general could you provide more details, for example: What are the exact details of your Litecoin Parachain (e.g. functions), or the Wrapp3d LTC Smart Contract (e.g. programming language, is this an ink! Smart contract)? What do you mean with “Infrastructure Development” or how are you planning to integrate the relayer (e.g. programming language)?

**Comment by surged-finance** [comment]
Thanks for reviewing our application. This will be the first open-source work we will be working upon besides the ERC20 Smart contracts we have created for our DEFI Project. 

_You say you want to leverage the XCLAIM design. In this case, I think it might make sense to wait for interlay to finish the implementation and potentially leverage their work: https://github.com/interlay If you don’t want to leverage interlays work, how is your solution different?_
_What do you mean with “Infrastructure Development” or how are you planning to integrate the relayer (e.g. programming language)?_

It indeed makes sense to leverage the work of interlay. That's why we have kept it in the second milestone. Interlay is expected to launch its Beta version sometime in January 2021. Before that we will work on Infrastructure development that includes the launching of Litecoin para chain on test net, developing wrapp3d LTC smart contract, and deploying it on Kovan. 
Substrate & Rust will be used for Litecoin Parachain and solidity for creating wrapp3d Litecoin Smart contract. Although, Ink! can also be used for the development of smart contracts.  

_could you provide more details, for example: What are the exact details of your Litecoin Parachain (e.g. functions), or the Wrapp3d LTC Smart Contract (e.g. programming language, is this an ink! Smart contract)?_
The Litecoin para chain functions are relaying messages to the WLTC contract on the ether chain for 
a. the minting of LTC and issuing it to the address provided by the user.
b. Redeeming user's Litecoin on provided address after receiving wLTC burn confirmation message.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Could you integrate the technical details into the specification of the milestones (also for the UI, etc.)? These are basically the requirements of the contract and need to be as detailed as possible.

**Comment by mmagician** [comment]
Closing due to inactivity. Feel free to re-open the application with a more complete proposal.

**Pull request closed without merging**
