### PR TITLE
Kylin Network Application

### PR DESCRIPTION
**Pull request by kylin-dev**
Add Kylin Network

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Still looks good to me and thanks for submitting the application again.

**Comment by kylin-dev** [comment]
> Still looks good to me and thanks for submitting the application again.

@Noc2 

Apologize for the inconvenience.

**Comment by kylin-dev** [comment]
> @kylin-dev Thanks for the explanation.
> 
> So if I understand correctly, your milestone 1 will provide two substrate pallets: Oracle Node & Data Feeding? Or would these be part of the same pallet?
> 
> Regardless, could you please include the technical specifications for each pallet that you propose, to include the following details:
> 
> * List the publicly exposed methods
> * For each method, specify (to the best of present knowledge):
>   
>   * Method signature (incl. parameters with their types, return type)
>   * Short description (code template)
> * Runtime Storage defined by your module
> 
> Also, you have the diagrams for your final proposed solution, which includes elements such as the Arbitrator Node that are not part of M1. Could you also supply a use case diagram demonstrating how system components & external users interact with one another, but targeting the state of your solution at the point of completion of milestone 1?
> 
> Why exactly do you need the `Datasource Sample Repo` and what is its functionality? Am I right in understanding that the `Data Feeding` module will interact with it? Couldn't the off-chain worker reach out directly to the off-chain source via an http request? I just fail to grasp the purpose of this sample repo.
> 
> Many thanks!

@mmagician 

> So if I understand correctly, your milestone 1 will provide two substrate pallets: Oracle Node & Data Feeding? Or would these be part of the same pallet?

The original idea is to have separate substrate pallets: Oracle Node and Data Feeding.

> Regardless, could you please include the technical specifications for each pallet that you propose, to include the following details:
> 
> * List the publicly exposed methods
> * For each method, specify (to the best of present knowledge):
>   
>   * Method signature (incl. parameters with their types, return type)
>   * Short description (code template)
> * Runtime Storage defined by your module

> Also, you have the diagrams for your final proposed solution, which includes elements such as the Arbitrator Node that are not part of M1. Could you also supply a use case diagram demonstrating how system components & external users interact with one another, but targeting the state of your solution at the point of completion of milestone 1?

In terms of technical specifications and use-case diagram, we will update the related information in application.

> Why exactly do you need the `Datasource Sample Repo` and what is its functionality? Am I right in understanding that the `Data Feeding` module will interact with it? Couldn't the off-chain worker reach out directly to the off-chain source via an http request? I just fail to grasp the purpose of this sample repo.

In our first version, we would like to use market data from exchanges. To access the API of exchanges, the API key and API secret are required. Each exchange will have its own way to secure the API access, so it's not convenient to access those APIs directly with the off-chain worker, and we will provide a component to handle such API access related stuff.

**Comment by kylin-dev** [comment]
> @kylin-dev Great! I'll be waiting to see the specs then 👍
> 
> > Each exchange will have its own way to secure the API access
> 
> But it's not in the scope of your project (or is it?) to make a connector to each of the exchanges & host those in a separate repp, right? This is purely for the demonstration purposes, if I understand you correctly?
> Anyway, how will it exactly work, then? Will you host an intermediary service which accepts easy-to-code requests from off-chain workers & then in that service, create the full request to the data provider, with added authentication?

@mmagician 

To be precise, it's not in the scope of Kylin Network project, but for demonstration purposes to let anyone can REALLY use the deliveries. We will not host any service but let anyone who wants to use the demonstration to run the service by themselves. The process is like what you mentioned. We will provide the Datasource sample repo, the hacker use that repo and run the service by only fill in the API key & API secret. The service will accept easy-to-code requests from off-chain workers, and the service will handle the rest.

**Comment by kylin-dev** [comment]
> @kylin-dev Thanks for the explanation.
> 
> So if I understand correctly, your milestone 1 will provide two substrate pallets: Oracle Node & Data Feeding? Or would these be part of the same pallet?
> 
> Regardless, could you please include the technical specifications for each pallet that you propose, to include the following details:
> 
> * List the publicly exposed methods
> * For each method, specify (to the best of present knowledge):
>   
>   * Method signature (incl. parameters with their types, return type)
>   * Short description (code template)
> * Runtime Storage defined by your module
> 
> Also, you have the diagrams for your final proposed solution, which includes elements such as the Arbitrator Node that are not part of M1. Could you also supply a use case diagram demonstrating how system components & external users interact with one another, but targeting the state of your solution at the point of completion of milestone 1?
> 
> Why exactly do you need the `Datasource Sample Repo` and what is its functionality? Am I right in understanding that the `Data Feeding` module will interact with it? Couldn't the off-chain worker reach out directly to the off-chain source via an http request? I just fail to grasp the purpose of this sample repo.
> 
> Many thanks!

@mmagician 

We updated the application proposal and add 'Pallet Design and Implements'. It shows the  technical specifications and use-case diagram.

##### Pallet Design and Implements

The main pallet will allow smart contract request off-chain data by Kylin oracle nodes. There has three main functions.

**1. requestOffChainDataByHttp**
- `desc:` smart contract request off-chain data by using http protocol, later oracle nodes will send data to kylin chain through OCW.
- `params:` http url
- `return:` dataId

**2. getOffChainData**
- `desc:` smart contract fetch expected data from oracle storage.
- `params:` dataId
- `return:` expected data

**3. getDefaultOffChainData**
  - `desc:` smart contract fetch expected data that is loaded by default from oracle storage, like BTC price.
  - `params:` predefined dataId
  - `return:` expected data

img

**Comment by mmagician** [comment]
@kylin-dev Thanks for providing the requested details! Just two final questions from my side:
1.  Are you planning to provide a sample smart contract that would call `requestOffChainDataByHttp`, or at this stage would you just have automated tests?


> The original idea is to have separate substrate pallets: Oracle Node and Data Feeding.
2. The three methods you provided are for the `Oracle Node` pallet, from what I understand? Could you also briefly summarise the similar attributes of the `Data Feeding` module, please?

Otherwise I'm happy with the application 👍

**Review by laboon — APPROVED** [review]

**Comment by kylin-dev** [comment]
@mmagician 

> Are you planning to provide a sample smart contract that would call requestOffChainDataByHttp, or at this stage would you just have automated tests?

Having automated tests is the bottom line of this stage. To have a sample smart contract is the goal we hope to achieve definitely.

> The three methods you provided are for the Oracle Node pallet, from what I understand? Could you also briefly summarise the similar attributes of the Data Feeding module, please?

Sorry for not clear addressed in description. The oracle node has two pallets, the `Oracle Node pallet` and the `Data Feeding pallet`. The `Oracle Node pallet` provides method `requestOffChainDataByHttp` to handle contract's requests. The `Data Feeding pallet` provides method `getOffChainData` and method `getDefaultOffChainData` to process off-chain data.

**Review by mmagician — APPROVED** [review]
Sounds good!

**Pull request merged**
