### PR TITLE
StandardProtocol application

### PR DESCRIPTION
**Pull request by hskang9**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Are you aware of [laminar](https://github.com/laminar-protocol/laminar-chain) and their oracle module? In general there are quite a few other teams currently working on oracle modules, see https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md and your applicaiton seems rather expensive too me at the moment (from looking at the current deliveries). Could you reuse potential other oracle modules and focus on improving these? Could you provide more information regarding the cron job and potentially add unit tests and in general additional details about your deliveries (e.g. programming language).

**Comment by hskang9** [comment]
I see that laminar's oracle module overlaps the milestone 1. I should focus on building oracle client with for getting market datas from [binance-rs](https://github.com/wisespace-io/binance-rs) or [coinbase](https://docs.rs/coinbase-api/0.2.1/coinbase_api/) and [substrate runtime api](https://github.com/scs/substrate-api-client) with cheaper request. There is a trading bot implementation to start with [here](https://medium.com/swlh/build-a-scalable-trading-bot-with-rust-over-the-weekend-9fd781940360) For milestone 2, I agree that I think there is some improvement that can be done with pos in the existing laminar oracle module. I will try to improve the existing oracle module with cheaper request. I will put some more details on each milestone this week.

**Comment by hskang9** [comment]
I can start with laminar's oracle module and storage, but the reporting xt should be different in that standard protocol identifies an asset with an [id number](https://github.com/digitalnativeinc/standard-substrate/blob/9f1314b515efbd01d9725c8424599491a81fa9a5/pallets/token/src/lib.rs#L337). The price report for oracle client to send will be like 
```
fn report(origin, asset_id: T::AssetId, price: T::Balance) {
// check origin is oracle account
let origin = ensure_signed!(origin)?;
ensure!(<Oracles<T>>::get(origin).is_some(), Error::T::NotOracle);
// record price for certain asset from oracle
....
}
```

**Comment by hskang9** [comment]
I also found some differences in orml's oracle module. I think orml considers oracle as controlled network participant, however, Standard's oracle module considers oracles as network participants as same as validators. I think this grant's oracle module diifferentiate from other projects by rewarding oracle providers as same as network validators for maintaining a blockchain.

**Comment by hskang9** [comment]
If you need more details on this, please let me know.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and the additional information. I’m generally interested in the application. Do you also accept DAI as a payment? I think we currently don’t pay teams in USDT. And could you potentially add unit tests to the deliveries?

**Comment by hskang9** [comment]
Dai is also fine, and I will do unit tests in the deliveries, it will be fun to build this.

**Comment by Noc2** [comment]
> Dai is also fine, and I will do unit tests in the deliveries, it will be fun to build this.

Cool. Could you integrate the unit test into the deliverables?

**Comment by hskang9** [comment]
Yes, for the runtime module in oracle, I think I am supposed to provide unit test in each module with `test.rs` file, am I right? unit tests can be done with era progression using `start_era()` or session with `start_session()`. I will write some details for unit test on each milestone.

**Comment by Noc2** [comment]
Yes unit test for the runtime module would be useful. Let me know once you updated the application.

**Comment by hskang9** [comment]
ok done. please check.

**Review by Noc2 — APPROVED** [review]
Looks good to me. I will share it with the rest of the team.

**Comment by hskang9** [comment]
Hello @Noc2, Is there any update or comment?

**Review by mmagician — APPROVED** [review]

**Comment by hskang9** [comment]
@Noc2 @mmagician Is there any update or comment regarding the proposal? if it is, please let me know.

**Review by Lederstrumpf — APPROVED** [review]
Hi @hskang9, lgtm!

**Comment by hskang9** [comment]
Hello @Noc2 @Lederstrumpf @mmagician , for doing a milestone1, I  said that I would make oracle client based on rustlang, but happened to make oracle client with typescript to ship the protocol as people were so interested in this. I kind of felt nervous if the performance of fetching, but it turns out it fetches pretty fast and I have to be careful of axios and polkadot-js package. Using javascript also had advantages on fetching datas regarding parsing the result from stock apis too. Due to these, Would it be okay to change oracle client implementation for the grant to be done in javascript instead of rust? I will make optimized one for rust as a separate grant to improve performance.

**Comment by hskang9** [comment]
By the way, the oracle implementation is called lumen, you can see the recent code here at https://github.com/digitalnativeinc/lumen

**Comment by Noc2** [comment]
Hi @hskang9 sounds good to me. Feel free to create a PR to amend the original contract. Also don’t forget to deliver the milestone: https://github.com/w3f/Grant-Milestone-Delivery ;-)

**Comment by hskang9** [comment]
ok I will try to finish the milestone 1 in this month ;-).

**Comment by alxs** [comment]
@hskang9 just checking in - where are you with your progress? Also a reminder that if you want to submit the TypeScript implementation for M1 you'd need to submit an amendment via PR first.

**Comment by alxs** [comment]
@hskang9 given your recent grant application https://github.com/w3f/Open-Grants-Program/pull/438, am I correct in assuming you're no longer interested in this project? In that case, we would terminate the agreement. Note that we generally don't award multiple grants in parallel to the same team.

**Comment by hskang9** [comment]
Incorrect. We have been interested in this oracle architecture, but had to partner with oracle providers to get data sources and validators for participation. Now that we have a standalone testnet deployed in [polkadot-js](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.opportunity.standard.tech#/explorer) have channel for validators, we have been finishing building the environment to demo milestone 1. We are currently thinking to apply milestone 1 in kusama parathread as we have finished parathread deployment in local rococo deployment as well. For #438, as bridge off-chain client is an extension of the oracle in this grant, it is general practice to finish this grant's milestones and proceed to bridge. We expect to launch We wanted to be agile, want to publicize our research, and appreciate the review process of w3f grant team, so we made multiple grant proposals. If it is a general practice to finish one grant at a time, we respect the policy and are willing to follow the rules.

**Comment by hskang9** [comment]
ETA for milestone 1 demo is second~third week of July, and submission will follow.

**Comment by alxs** [comment]
Sounds good and yes, that is the general policy. In case it clearly makes more sense for you to work on both grants in parallel, let me know and we can discuss your case on an individual basis. Otherwise I recommend you close the other application and focus on delivering this grant first.

**Comment by hskang9** [comment]
So the bottleneck was that the application had to build a new reward logic and reward curve, but after investigating the staking module and session module, it seems creating new reward logic is not preferable way to do it. All callbacks regarding progression of era is managed by the dependancy injection trait of `pallet-session` and `pallet-staking` 's `SessionManager` implementation. if the grant milestone 2 leverages that, I think the grant can be delivered much sooner than I expected. By the way, the grant submission for milestone 1 is ready in  [runtime](https://github.com/digitalnativeinc/standard-substrate/tree/open-grants-milestone1) and oracle client is ready [here](https://www.npmjs.com/package/@digitalnative/lumen).

**Comment by hskang9** [comment]
#514 is the amend considering the session callbacks.

**Comment by alxs** [comment]
Thanks @hskang9, makes sense. Feel free to submit the first milestone following the [delivery process](https://github.com/w3f/Grant-Milestone-Delivery#mailbox-milestone-delivery-process) as soon as the amendment has been accepted.

**Comment by semuelle** [comment]
Hi @hskang9. Are you still working on the grant? Could you give us a quick update? Anything holding you back?

**Comment by alxs** [comment]
@hskang9 could you give us an update on your progress? Note that since the current milestone is already very delayed and we previously asked you for an update, if we don't hear from you in the next 2 weeks we will assume you're no longer interested and terminate the agreement.

**Comment by hskang9** [comment]
Sorry for late updates, After facing market and bugs in parachains, I think I will contract grant milestone 2 to interoperate with evm precompile that we can ship it for real use case. After market research, current infrastructure in market are focused on for evm now, and it seems evm integration is immediate. Would it be ok to edit grant milestone 2 and finish with new design and impl of evm in [standard-evm](https://github.com/digitalnativeinc/standard-evm)?(I estimate this would take 1 or 2 months after kusama parachain lease, I believe it will be shipped with canary market solution).

**Comment by hskang9** [comment]
I will add milestone 3 as the current milestone 2 for wasm integration. Anyway, I still have interest in oracle grant, and want to finish milestone 2 to be usable in the real market.

**Comment by hskang9** [comment]
new PR to add milestone will come by this weekend.

**Comment by hskang9** [comment]
#732  is out for amendment @Noc2 @semuelle

**Comment by alxs** [comment]
@hskang9 please note that since we're still waiting for your reply on the amendment and we haven't heard from you in over a month, we'll assume you're no longer interested and terminate the grant if we don't hear from you in the next 2 weeks.

**Comment by hskang9** [comment]
Sorry for late response, I have been busy with our first product launch, and I missed that. I think grant is good to be terminated as we try to approach implementing standard in polkadot ecosystem through evm, so I will post new one soon with shorter milestone.

**Pull request merged**
