### PR TITLE
Create MaslowLifeNetwork.md

### PR DESCRIPTION
**Pull request by m21917**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the application @m21917. We'll look into it as soon as possible.

Adding a link to your last application for reference https://github.com/w3f/Open-Grants-Program/pull/352

**Comment by semuelle** [comment]
Hi @m21917,

thanks again for your application. A couple of questions:

- What is `the problem of messy information on social networks`?
- What is `open logic`? How does it `determine community content`?
- Why NFTs? The primary purpose of tokens is their exchange, who would I exchange "posts" with?
- `we will first make three pallets with personal information/friendship/posts` -- does that mean all my personal data, like my name and friends list, is stored on any and all nodes on the network?
- Why is there an upper limit on friendships? Who would I pay to expand it?
- Please fill out the `Total Costs:` entry in your document.
- Are you familiar with the [`identity` pallet](https://crates.io/crates/pallet-identity)? It has no dedicated `birthday` or `gender` fields, but it has fields for avatars and legal names, as well as `set_identity` and `set_fields` functions. There is also [`pallet-did`](https://github.com/substrate-developer-hub/pallet-did).

Regarding the deliverables:

- What are `the relevant specifications and design`? Can you be more concrete and list what specs and designs you mean?
- `Fork the substrate framework and analyze how to use it` - this falls beyond what the Web3 Foundation Grant program funds. I'm afraid you would have to do this before starting the grant.
- What function does `sign_in` serve? What does it do?

Please add the information here as a comment and/or to the document in this PR. If you push your changes to the same branch, the PR will update automatically.

Thanks!

**Comment by guanfantech** [comment]
Hi @semuelle,
thanks for the comments.

**1.What is the problem of messy information on social networks?**
A : In view of the fact that traditional social platforms (such as Facebook) are often overwhelmed by spam/centralized advertising information/unreviewed posts, we will try to use “open logic” and “posts need to pay a certain fee” to make users post more careful consideration will make more valuable information surface.

**2.What is open logic? How does it determine community content?**
A : In the future, we may use the number of likes or other relatively fair methods to surface valuable posts, make the sorting logic public and gradually optimize. But this will not be implemented in the first phase.

**3.Why NFTs? The primary purpose of tokens is their exchange, who would I exchange “posts” with?**
A : As mentioned in the previous opening, there are too many messy messages in current decentralization, such as spam/centralized advertising information/posts that have not been reviewed. We use blockchain features to generate posts as NFTs (this A certain fee will be incurred). This model will allow users to deliberate before posting messages, and only generate more “valuable” post information, just like the first post of the founder of Twitter, which will be open to users in the future These NFTs can be traded, but our first stage is mainly to make them output, and there will be no trading functions for the time being.

**4.we will first make three pallets with personal information/friendship/posts – does that mean all my personal data, like my name and friends list, is stored on any and all nodes on the network?**
A : In the first stage, all information will be put on the database first, but in the future we will consider user privacy rights and conceal specific information that is highly related to personality rights with our own encryption methods.

**5.Why is there an upper limit on friendships? Who would I pay to expand it?**
A : As mentioned in the previous opening, social platforms are flooded with dummy accounts, and people who are interested may use dummy accounts to spread spam/advertising. Therefore, we need to pass friend restrictions (a fee must be paid to increase the upper limit), blockchain procedures Fees and other systems are once again strengthened to eliminate these situations, and we can also save and optimize chain resources more effectively.

**6.Please fill out the Total Costs: entry in your document.**
A : OK, it has been made up.

**7.Are you familiar with the identity pallet? It has no dedicated birthday or gender fields, but it has fields for avatars and legal names, as well as set_identity and set_fields functions. There is also pallet-did.**
A : The identity pallet does not have fields such as birthday and gender. We may add functions or refer to the identity pallet to write a new pallet.

**8.What are the relevant specifications and design? Can you be more concrete and list what specs and designs you mean?**
A : The milestones have been revised to be more specific, as follows:

User interface design mockup
User guidelines
Pallet usage guidelines
Software Build guidelines
Test methods guidelines

**9.Fork the substrate framework and analyze how to use it - this falls beyond what the Web3 Foundation Grant program** funds. I’m afraid you would have to do this before starting the grant.
A : Our team understands this matter and just clarifies the work process.

**10.What function does sign_in serve? What does it do?**
A : After our detailed consideration, it seems that the sign_in method is not used. The milestone has been corrected. Thank you for your reminder!

**Comment by m21917** [comment]
Hi @semuelle,
thanks for the comments.

**1.What is the problem of messy information on social networks?**
A : In view of the fact that traditional social platforms (such as Facebook) are often overwhelmed by spam/centralized advertising information/unreviewed posts, we will try to use “open logic” and “posts need to pay a certain fee” to make users post more careful consideration will make more valuable information surface.

**2.What is open logic? How does it determine community content?**
A : In the future, we may use the number of likes or other relatively fair methods to surface valuable posts, make the sorting logic public and gradually optimize. But this will not be implemented in the first phase.

**3.Why NFTs? The primary purpose of tokens is their exchange, who would I exchange “posts” with?**
A : As mentioned in the previous opening, there are too many messy messages in current decentralization, such as spam/centralized advertising information/posts that have not been reviewed. We use blockchain features to generate posts as NFTs (this A certain fee will be incurred). This model will allow users to deliberate before posting messages, and only generate more “valuable” post information, just like the first post of the founder of Twitter, which will be open to users in the future These NFTs can be traded, but our first stage is mainly to make them output, and there will be no trading functions for the time being.

**4.we will first make three pallets with personal information/friendship/posts – does that mean all my personal data, like my name and friends list, is stored on any and all nodes on the network?**
A : In the first stage, all information will be put on the database first, but in the future we will consider user privacy rights and conceal specific information that is highly related to personality rights with our own encryption methods.

**5.Why is there an upper limit on friendships? Who would I pay to expand it?**
A : As mentioned in the previous opening, social platforms are flooded with dummy accounts, and people who are interested may use dummy accounts to spread spam/advertising. Therefore, we need to pass friend restrictions (a fee must be paid to increase the upper limit), blockchain procedures Fees and other systems are once again strengthened to eliminate these situations, and we can also save and optimize chain resources more effectively.

**6.Please fill out the Total Costs: entry in your document.**
A : OK, it has been made up.

**7.Are you familiar with the identity pallet? It has no dedicated birthday or gender fields, but it has fields for avatars and legal names, as well as set_identity and set_fields functions. There is also pallet-did.**
A : The identity pallet does not have fields such as birthday and gender. We may add functions or refer to the identity pallet to write a new pallet.

**8.What are the relevant specifications and design? Can you be more concrete and list what specs and designs you mean?**
A : The milestones have been revised to be more specific, as follows:

User interface design mockup
User guidelines
Pallet usage guidelines
Software Build guidelines
Test methods guidelines

**9.Fork the substrate framework and analyze how to use it - this falls beyond what the Web3 Foundation Grant program** funds. I’m afraid you would have to do this before starting the grant.
A : Our team understands this matter and just clarifies the work process.

**10.What function does sign_in serve? What does it do?**
A : After our detailed consideration, it seems that the sign_in method is not used. The milestone has been corrected. Thank you for your reminder!

**Comment by semuelle** [comment]
Hi @m21917, thanks for the follow-up. 

> we will try to use “open logic” [...] to make users post more careful consideration will make more valuable information surface.

How does making the sorting logic incentivize users to most more carefully? Making the sorting logic open will only cause people to game it (see Google & YouTube). That's why PageRank is not public. Anyway, I would recommend to separate these problems (`spam/centralized advertising information/unreviewed posts`), because a public sorting logic will not solve the spam problem. It might make it worse.

> A certain fee will be incurred

So what you really mean by `these posts can be cast into NFT to solve the problem of information value` is that `posts incur a fee to solve the problem of information value`. This can be achieved without stuffing it into an NFT and frankly, I don't see the point of turning social media posts into NFTs.

> in the future we will consider user privacy rights

I would prefer seeing a data privacy concept before funding this grant. 

> and conceal specific information that is highly related to personality rights with our own encryption methods

How are you planning to conceal this data? What encryption methods? Do you have any previous work or publications on this matter?

> Our team understands this matter and just clarifies the work process.

Can you please remove it as a deliverable then, because we don't want to give the impression that it would be part of the grant.

**Comment by m21917** [comment]
Hi @semuelle,

**1. How does making the sorting logic incentivize users to post more carefully? Making the sorting logic open will only cause people to game it (see Google & YouTube). That's why PageRank is not public. Anyway, I would recommend to separate these problems (spam/centralized advertising information/unreviewed posts), because a public sorting logic will not solve the spam problem. It might make it worse.**
A : It is true that public logic may make the situation worse, but we may set standards that are difficult for users to control, such as the number of likes in posts, because the problem of dummy accounts has been solved by the cost of creating accounts, so there is no such doubt. Of course, non-disclosure logic has its advantages, but it also creates doubts about the traditional centralized platform control algorithm. However, our team will refer to both methods (public or non-public) and make adjustments when they go online. Hope this part can be there is more flexibility for the team to try.

**2. So what you really mean by these posts can be cast into NFT to solve the problem of information value is that posts incur a fee to solve the problem of information value. This can be achieved without stuffing it into an NFT and frankly, I don't see the point of turning social media posts into NFTs.**
A : It is true that there is no need to cast into NFT, and only need to pay a fee to publish the post to solve the problem of the value of the article, but our team hopes that this platform will also have the opportunity to develop NFT transactions in the future to have this plan. This part I also hope to be flexible for the team to develop, thank you!

**3. I would prefer seeing a data privacy concept before funding this grant. How are you planning to conceal this data? What encryption methods? Do you have any previous work or publications on this matter?**
A : Our first step is to store it in a centralized database, because maintaining privacy on the blockchain is an important and difficult thing and requires rigorous testing, so this is not we will arrange things in the first phase. But we will actively continue to try this one, thank you!

**4. Can you please remove it as a deliverable then, because we don't want to give the impression that it would be part of the grant.**
A : Okay, the file has been updated.

**Comment by semuelle** [comment]
Hi @m21917, thanks for the follow-up. Could you add some more details on the last deliverable ("Dapp implementation")? For UIs, we usually expect the team to already have some wireframes or designs ready. And will it cover all pallets and functionalities?

**Comment by m21917** [comment]
OK, the wireframe is [here](https://956dkl.axshare.com/) (Dapp contains the current pallet). This is also a low-fidelity prototype, you can click directly to have a preliminary experience (of course, the actual design will be more exquisite, this is just a wireframe). And more details have been updated in the mileston :
* Users can create virtual personalities
* Establish friendship
* Post social posts

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for sharing the mockup. I have a few questions: 

- The mock-ups show a metamask integration. Did you initially plan to deploy this on ethereum or do you already have an ethereum version live?
- Do you potentially have some code, which you could share? 
- How does your solution compare to https://subsocial.network/, which already supports [posts](https://github.com/dappforce/subsocial-node/blob/master/pallets/posts/src/lib.rs)?
- Do you plan to integrate off-chain storage?  
- In general, I currently don’t see too much value in the pallets, which you are suggesting or at least it doesn’t seem to be worth 25k to me (given that there is the identity pallets and the work done by subsocial). Are there potentially other things you might want to work on?

**Comment by alxs** [comment]
Closing due to inactivity and since it seems there's no interest from the rest of the committee. Feel free to try for a different grant!

**Pull request closed without merging**
