### PR TITLE
Decentralised reputation systems and social networks

### PR DESCRIPTION
**Pull request by DarkingLee**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks really interesting and something we would like to support. I actually wanted to write an RFP for an on-chain reputation system, which for example could be used to judge the reputation of parachains/dapps etc. and therefore help others to make the right investment decisions. I have a few questions: 

- How do you ensure that the hall of fame isn’t malicious. Did you choose a random number of “famous” people? Ideally this group is also somehow decentralized to increase the risk of collusion. 
- You say TIR is difficult to compute, how do you plan to incentivise people to actually compute it in a decentralized way.   
- For the other implementation, it seems you used thegraph. Potentially the following is helpful for you: https://github.com/Joystream/hydra

**Comment by DarkingLee** [comment]
@Noc2  Thank you for your reply.

1. In socircles, I combined several centrality values to select "famous" people. We will implement community elections in the next milestone, which will be decentralised and secure. In socircles, only 20 users out of 100,000 were selected and the system already works well. That means that on average 5,000 users oversee a famous people, which is safe. But elections need to be secure in combination with reputation to ensure that an attacker without a reputation, cannot attack the election. However at the moment we do not have a reputation. Also to take into account options such as MACI or privacy computing, which I note some teams in the ecology are already working on. Given the above points, I think it would be better to implement it in the next milestone.

2. TIR is really difficult to compute on-chain. But it is much easier to compute off-chain. Users updating the results to the chain will get a percentage of the user's social currency as a fee.

3. Thanks for sharing.

**Review by Noc2 — APPROVED** [review]
Thanks for the quick reply. I mostly ask about TIR, because it seems it’s currently not part of your deliverables. But I guess you want to look into it in the future as part of “Optimize economic system design”. In general I’m happy to support the proposal and I will share the application with the rest of the team.

**Review by BenWhiteJam — APPROVED** [review]

**Comment by DarkingLee** [comment]
Hi @Noc2  thanks for your great effort! As you said, we have plans to provide a client for TIR. But we are not ready yet. For now we are only verifying it on-chain.

**Review by alxs — APPROVED** [review]

**Comment by alxs** [comment]
Hey @DarkingLee, care to share a quick status update along with an ETA if possible? We expected to receive your first delivery a bit over 2 months ago now. As long as you're actively working on the project, delays aren't a big problem, but please keep us in the loop.

Note that if we don't hear from you within the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Comment by DarkingLee** [comment]
Hey @alxs, Very sorry for the delay in delivery. Due to the completeness of the project we have added a seed selection algorithm which has taken a long time. Development is now almost complete and we are preparing to refine the documentation for delivery in the next 2 weeks at the latest.

**Comment by alxs** [comment]
@DarkingLee ping.

**Comment by DarkingLee** [comment]
@alxs Delivery this week.

**Pull request merged**
