### PR TITLE
Fundaria Grant Application

### PR DESCRIPTION
**Pull request by Fundaria**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
Currently we don’t fund the development of Solidity smart contracts. The reason is that we are no experts when it comes to Solidity and it’s very difficult to judge what is new and what already exists at this point.

**Comment by Fundaria** [comment]
> Currently we don’t fund the development of Solidity smart contracts. The reason is that we are no experts when it comes to Solidity and it’s very difficult to judge what is new and what already exists at this point.
> Let me know if you are willing to develop your contract in ink! instead.
> Also some of your google docs are private.

The fact is that I have already created a full version of the smart contract on Solidity and not looking funding for it. I'm very frustrated about current transaction costs on Ethereum and this moved me to look on alternative ways, so it would the great magical chance to participate in this grant program and swap Solidity and Ethereum to ink! and Polkadot finally which will allow to adopt Fundaria to normal desired state, where startup teams can use smart contract for their daily business operations.
I changed access to file https://docs.google.com/document/d/1zOKRpq_9PJGUuaD4QoC5LQ2CYZhF6GSZbAk50hDLTVA/edit from private to "comment for all", thanks.

**Comment by mmagician** [comment]
Apologies for a late response.

---
Since you haven't provided any code samples or github repos to check your previous work and I'm no solidity expert, I've done a quick security check of your `.sol` contract using [publicly available tools](https://tool.smartdec.net/scan/0c3d5d1098d64d18a5477b1049b8682a) and found a number of issues. Now, I understand that this is still unpolished code so it might not be perfect - but since I don't have access to other work of yours, this is the only thing I can evaluate at this stage.

---
Furthermore, I couldn't find the MVP that you mentioned.

---
I don't see the point of including `share for Fundaria` in your contract's variables. Why would anyone give even 1% to a third-party just for providing the smart contract, when they could deploy that contract themselves? I am not sure that your business model works in this case, especially that giving these shares to Fundaria doesn't seem to provide any extra utility to the users (for comparison, if e.g. Uniswap were to start taking a cut on each trad, and that money went to the Uniswap founders, the users would simply switch to another platform - unless that extra percentage was used for utility of the platform such as further development, governance etc.)

---
Lastly, the mechanism for auditor selection seems easily gameable: `The number of votes corresponds to the number of shares which belong to the investor.`
Clearly, the person with the majority stake (which could be the startup itself) is going to be able to have a free hand in deciding how funds are spent.

---
Given the current state of the proposal and the above mentioned points, I wouldn't support the grant. If you think I missed something or you would like to address the above comments, we will wait about 2 weeks - and otherwise close the PR. Thanks again for the interest in the Web3 Foundation Grants Program!

**Comment by mmagician** [comment]
Closing due to inactivity. Feel free to re-open the application with a more complete proposal.

**Pull request closed without merging**
