### PR TITLE
Ethense by #aQ

### PR DESCRIPTION
**Pull request by siqaqz**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @siqaqz, thank you for your application.

I'm afraid it does not become clear what it is that you are applying for. Please provide _much_ more detail on everything, including the ecosystem fit, your previous experience with Substrate and blockchain tech in general, as well as the technical specifications. This grants program is for technical grants, so we expect grantees to already have a good understanding of what the are going to implement and how.

Also, please review the markdown syntax in your document and feel free to remove the template texts.

**Comment by siqaqz** [comment]
thx for your reply -- the notes of fewer notes and coded just an only to
present what can be solved will be up to the communities which encode and
adopt themselves, and more whimsical authoring on that

https://www.publish0x.com/ethense/emotive-concurrency-of-ethense-xomxeql

where the grant funds would surely be built into the models which pay the
Encoders to provide for the ongoing payment of like kind successes of these
milestones and the nextwork, as planned to sustain as operable for the
grant term and heady onward.

More on the PR as writing goes
//
-- #aQ

**Comment by semuelle** [comment]
Thanks for the follow-up, @siqaqz, but I'm afraid the article also doesn't provide much useful information. Please add technical details to your application as per our application template. Otherwise this PR will be closed.

**Comment by semuelle** [comment]
Closing due to inactivity. Happy to reopen if needed.

**Pull request closed without merging**
