### PR TITLE
Proposal DID:PAID Identifier of PAID Network, for PAID Smart Agreements Protocol

### PR DESCRIPTION
**Pull request by alfredolopez80**
# Grant Application Checklist

- [x ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "paid.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [ x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have two questions/comments regarding the application: 

- First of all, what do you mean with Plasm Modules (Deliverable 1 to 3) and could you describe the technical implementation? Are these solidity smart contracts? Because in this case we won’t support them. The grants program focuses on funding new software development and research efforts related to Polkadot, Kusama and Substrate. We currently don’t have the capability or the knowledge to judge the uniqueness of solidity smart contracts and the contribution to the ecosystem.  
- You also need to provide a btc address as well as the total cost need to be in BTC and not fiat.

**Comment by alfredolopez80** [comment]
Hi, @Noc2 

The requested adjustments have already been made @ Noc2, better explaining our vision of the development of the PAID Smart Contract fro PAID Protocol, which is more focused on providing Substrate with a more complete management layer of digital signature algorithms for electronic documents, and these have validity against CA of any indole Root 1 and Root 2, in addition to offering a `chain of trust` protocol for legal contracts on-chain in Substrate.io/PolkaDOT.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have a few additional requests/remarks: 

- In general you should be aware that our research team has a lot of concerns regarding the current version of the W3C DID standard. It basically can be attacked to collect the user data. I know it’s not part of this grant proposal, just something you should be aware of. 
- Could remove delivery 3, “Plasm module” and in general “Plasm” from the deliveries. On the one hand, web3 tries to be objective regarding potential parachains. On the other hand, we are uncomfortable with funding solidity smart contracts, since we don’t have an overview of the existing solutions and the uniques of your contribution. 
- Could you maybe reduce the price a little bit more or maybe already integrate the privacy layer into the deliveries?

**Comment by alfredolopez80** [comment]
Hi, @Noc2 

Thanks for the update. I have some additional requests / comments:

* In general, you should know that our research team has many concerns regarding the current version of the W3C DID standard. Basically, it can be attacked to collect user data. I know it is not part of this grant proposal, just something you should know about.
R = Thanks for the advice, we will take it into account, however we are at the design level and a security system is being considered to reduce these risks, such as data encryption, PKI signature system, in addition to a future verification scheme of Zero Knowledge for the verification and access to the user's data, carrying the implementation of the current version of W3C DID, a little more has its current security status.
* Could remove delivery 3, "Plasma Module" and generally "Plasma" from deliveries. On the one hand, web3 tries to be objective in terms of possible parachutes. On the other hand, we are not comfortable with robustness smart contract financing as we do not have an overview of existing solutions and the unique characteristics of their contribution.
R = Removed the Plasm modules, and it is not only smart contracts that are going to be deployed, it is a new way of handling these smart contracts that allows handling templates that later through Meta Transactions and a data conversion scheme based on JEXL, allows to alter the values ​​of each Instance of these Smart Agreements templates to be executed in the specific cases and conditions of said contract, encapsulated in that Smart Aggrements, which is completely innovative. Therefore, they are not smart contract as such, it is a whole workflow for this that will later be migrated to ink! within the Substrate.io/PolkaDOT platform
* Could you reduce the price a bit more or maybe already integrate the privacy layer in the deliveries?
R = The price was adjusted to the BTC level, in addition to that delivery 2 is integrating the runtime module that would handle the electronic signature of documents, such that it allows its verification by public CAs within the PKCS11 or PKCS12 standard as applicable.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Okay thanks for the update and sorry for the late reply. I personally have quite a lot of concerns regarding systems that put personal data and contracts on-chain, but I will share your application with the rest of the team. However before I do this, could you just update the “Total Costs: 25K” to “Total Costs: 1.3 BTC”.

**Comment by molekilla** [comment]
After reviewing with the team we will need to change our assumptions . Thanks

**Comment by Noc2** [comment]
Okay, I will close the application for now. Let me know if you want to reopen it or feel free to submit an updated application.

**Pull request closed without merging**
