### PR TITLE
UpLink Open Grant Proposal

### PR DESCRIPTION
**Pull request by AndreFratelli**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by AndreFratelli** [comment]
Hi, @mmagician,

Thank you for the feedback; forgot abou those TODOs, I'll fix it.

Regarding the CLA, the link tells me that I have already agreed, but the status is not updating. Any recommendations?

**Comment by mmagician** [comment]
It seems like your commit has two author accounts. I imagine one of them hasn't signed the CLA?

**Comment by alxs** [comment]
Looks like the commit was made using an email address that isn't associated with your account. Adding `andrefrancisco@MBP-de-Andre.hype` to your GitHub account should do the job. The shared authorship is odd, I don't see where GitHub is picking this up.

**Comment by AndreFratelli** [comment]
@alxs that's my macbook, I have no idea how to add that to github :| where did you even find that?

**Comment by alxs** [comment]
It's the email address used to create the commit, which I found by looking at its [patch file](https://github.com/w3f/Open-Grants-Program/commit/bc83d96357dd3a668e94686c42564a2f5c6e079c.patch). Here are [instructions](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address) on both adding an address to your GitHub account and modifying your commit email address on Git.

**Comment by AndreFratelli** [comment]
@alxs thank you, that helped a lot. Still had to figure out to squash everything with the new email, and then it was the user name. But it seems good now. Do I need to do anything else to trigger a new review?

**Comment by AndreFratelli** [comment]
Hi, @alxs , @mmagician ,

Is there anything else that I should do? All seems complete for now, but I'd rather make sure.

Kind regards.

**Comment by alxs** [comment]
Thanks André, looks good. I'll try to get this ready to review for the rest of the team quickly as I remember you wanted to start ASAP.

Right now the biggest problem I see is what @mmagician mentioned previously, i.e. it's not very clear how most of these deliverables relate to Substrate/Polkadot. For milestones 2 and 3 this is particularly unclear. The Hype SDK server port sounds very general-purpose (also what platform are you porting it from?) and it would be good if you could explain how exactly it will interoperate with Substrate. For a milestone this large we would also expect a more precise specification, i.e. could you describe what "cryptographic processes, authentication" and "business logic to configure and manage communication links" exactly this will provide? Assuming it does interoperate with Substrate. If otherwise this would in principle be an endpoint that can be used to relay Substrate transactions as much as anything else, it could be hard to get it accepted. Our grants are pretty focused on Substrate/Polkadot.

Also maybe I'm missing something, but I'm a bit puzzled by the order of the milestones. Wouldn't the Android app depend on the other milestones?

**Comment by AndreFratelli** [comment]
@alxs thank you for your feedback, it's very helpful.

The system we're proposing does not directly integrate with Substrate/Polkadot, but rather enables devices without Internet to connect to those networks. In other words, this is technology that works mostly on the end devices, meaning that those without Internet can still process transactions. As you seem to have understood, this is done by relay.

If I understand correctly, this isn't something that you'd expect to be accepted, is that correct?

**Comment by alxs** [comment]
I'd say it depends on the degree of coupling. If the system was tailored to Substrate and _only_ allowed such devices to connect to Substrate chains, we may be interested. However as I understand it, it would simply allow devices without internet to connect to the internet, in which case we would most likely not be able to fund the entire project. However we can still fund the parts of it that concern the integration with Substrate.

What I'd initially understood was that you would implement this system with an embedded pay-as-you-go scheme that would be processed directly on some Substrate chain. That's also something we'd potentially be interested in. Hope this makes sense.

**Comment by AndreFratelli** [comment]
@alxs, makes perfect sense.

The system we're proposing is deeply coupled with Substrate. Notice that this is not meant to provide general Internet reachability; it does not enable users to go on Facebook, or process transactions with MasterCard. What we're proposing enables a device without Internet to process transactions on a Substrate network, and nothing else. The use case is that if I don't have Internet I can still communicate with the Substrate network, check my balances and process transactions. Your second interpretation is closer to what we're proposing. I'll try to make that clearer.

Thank you once again.

**Comment by alxs** [comment]
Thanks for the clarification. Let me know when you're done with the changes and don't forget to address the feedback in my [comment above](https://github.com/w3f/Open-Grants-Program/pull/412#issuecomment-843348324).

**Pull request closed without merging**
