### PR TITLE
Quadratic Crowdfunding Pallet and GUI grant application

### PR DESCRIPTION
**Pull request by pajicf**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I was actually working on an RFP for this. Feel free to take a look at this and leverage some of the ideas: https://github.com/w3f/General-Grants-Program/blob/master/rfp-proposal/on-chain-quadratic-funding.md How are you planning to deal with Anti-collusion and Sybil resistance? I also recommend to take a look at http://clr.fund/

**Comment by pajicf** [comment]
Thanks @Noc2 , we will take a look at RFP that you have been working on and come back with the proposal

**Comment by Noc2** [comment]
@pajicf Any updates on this? You might also want to take a look at https://github.com/w3f/General-Grants-Program/pull/381

**Comment by pajicf** [comment]
Hi @Noc2 , we are working on the grant application with considerations of the RFP you provided and will submit a new request very soon

**Comment by pajicf** [comment]
Hi @Noc2 , sorry for the late response,

[Here's](https://docs.google.com/document/d/1ogj8S1NpsdqgGKP9dF4rinQEgfk3BH5IoOVKvFaPOjM/edit#) our overall plan on how to create "Quadratic Funding" platform as an answer to your RfP. While we were working on the general grant application, we realized that the work can be separated into multiple smaller Open grants. Hence we would like to hear your opinion if we should proceed with the Open Grant approach, where the first Grant would be to make the "maci" pallet, or should we stick to the general grant?

Also if you have any other feedback regarding to the general idea, be free to share, we are open to adapting our proposal.

**Comment by Noc2** [comment]
Thanks for the update. I suggest applying via open grants. It’s much faster and easier on our side. Also something you should be aware of, we now allow follow-up grants up to 100k via the open grants program (and the payment in DAI or BTC). Given that you already worked on multiple grants you would be allowed to apply for a grant above the 30k limit via open grants.

**Comment by pajicf** [comment]
Hey @Noc2, we submitted a new application on this link: [https://github.com/w3f/Open-Grants-Program/pull/232](https://github.com/w3f/Open-Grants-Program/pull/232)

**Comment by Noc2** [comment]
Thanks. In this case I will close this application.

**Pull request closed without merging**
