### PR TITLE
Add Polconeth

### PR DESCRIPTION
**Pull request by MotoYS**
Polconeth is state channel for EVM and Substrate based balance transfer

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you share potentially any previous projects/work? Are you directly involved in connext? What are the benefits of connext compared to [celers implementation](https://github.com/celer-network/cChannel-substrate) and could you provide more technical details regarding the implementation.

**Comment by MotoYS** [comment]
@Noc2 Thank you for your comment.
>Could you share potentially any previous projects/work? Are you directly involved in connext?

I'm not in Connext but I've been long after [XUD](https://github.com/ExchangeUnion/xud), which is a Lay2 DEX integrating Context for EVM balance swaps.

>What are the benefits of connext compared to celers implementation?

I don't know Celer much. Afaik, Celer is more targeting to gaming while Connext is focused on cross chain transfers and micropayments. Furthermore, Connext is production ready while I haven't seen any major product/app using Celer so far.

>Could you provide more technical details regarding the implementation?

We want to integrate Connext API with Substarte off-chain Worker. Through the configuration, it can call methods from a node either maintained by Connext team remotely or installed locally by docker.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply. Could still please integrate more technical information into the application? Also a comparison with existing solutions provided by celer would help. For example currently your delivery only says “We will create a pallet to enable state channel transfer on Substrate chain”. Theoretically you could just deliver celers solution and you would fullfill the current requirements. What are the functions? Do you need to adapt the off-chain part or will it be completely integrated as off-chain workers? Etc.

**Comment by MotoYS** [comment]
> Sorry for the late reply. Could still please integrate more technical information into the application? Also a comparison with existing solutions provided by celer would help. For example currently your delivery only says “We will create a pallet to enable state channel transfer on Substrate chain”. Theoretically you could just deliver celers solution and you would fullfill the current requirements. What are the functions? 

On functionality side, Vector of Connect is very similar with cChannel of Celer. If it's just to fulfill layer-2 channel transfer requirement, yes - we could use Celer solution as well.

However, Connext is more production ready on cross-chain transfer and micro-payments while Celer is focusing more on gaming. Besides, Connext has more implementations.

Server-node, which uses docker to package up core logic and exposes http and gRPC interfaces. 

Browser-node, which is distributed via npm and exposes a typescript/javascript interface.

Routing node, where you forward transfers between different channels. This way, peers can transfer to each other without needing channels directly to one other, but instead by "hopping" value across many different channels through the network. Routing nodes run server-node with an automated module - a router - to forward transfers.

>Do you need to adapt the off-chain part or will it be completely integrated as off-chain workers? Etc.

In the 1st milestone, we'd like to package the server-node in the image and integrate APIs into off-chain workers. Namely, completely integrated as off-chain workers.

If the delivery of 1st milestone is workable and adoptable, we're going to convert Connext smart contract logic into substrate modules in the 2nd milestone.

**Comment by Noc2** [comment]
Thanks. Could you update the application accordingly? You haven’t updated the PR, since the original pull request.

**Comment by MotoYS** [comment]
@Noc2 Thanks. Updated the application according to the conversation.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have some follow-up questions. Could you link to the “Connext smart contract logic” as part of the deliverables? And as part of milestone 1, you basically just want to connect to [Vector](https://github.com/connext/vector) via API requests without any on-chain logic or do you want to implement the [rest-api-client](https://github.com/connext/rest-api-client) into the off-chain worker?

**Comment by MotoYS** [comment]
Added [Connext contract](https://github.com/connext/vector/tree/main/modules/contracts/src.sol) link to the delivery item 2 of MileStone 2 - 'Polconeth Module'.

And we want to implement the rest-api-client into the off-chain worker in milestone 1.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. Looks good to me. I’m happy to go ahead with it.

**Comment by alxs** [comment]
Could you clarify what you mean by "I've been long after XUD"? The repo you link to doesn't contain any commits made by yourself and there are no repositories on either your or your organisation's account. I'd need to see some of your prior work to approve this.

**Comment by MotoYS** [comment]
I'm not core dev of this project. However, I was involved from day 1 - like I participated in the design and feasibility analysis of this project. Also, I translated white paper and tech white paper for XUD and published some tech articles. 

So I'm very clear why XUD switched from Raiden to Connext as their state channel an how Connext works with and benefit this project.

**Comment by mmagician** [comment]
At the current state of the project, I would be wary about supporting a Connext integration. A couple of reasons for this:
1. Their [audit](https://docs.connext.network/faq#z9-is-connext-audited) is missing. This is a red flag to me
2. They claim to work in a trust-less manner, yet the [Protocol Primer section](https://docs.connext.network/protocol-primer) has zero information about how that is achieved. To me, this is a key question that should be asked about such a cross-chain protocol.

Now, I'm not sure whether or how your team is affiliated with Connext, but regardless of it - I wouldn't be comfortable supporting an integration to, what seems, a shady project (see above points).

**Comment by alxs** [comment]
Thanks @MotoYS. I hope you understand that given the technical nature of the project, I'd prefer to see some code produced by you and your colleague. I also agree that @mmagician's concerns are worrying so all in all, at this point I would rather not give my OK.

**Comment by alxs** [comment]
Since your application has been open for a month and failed to raise interest from our side, we will now consider it final in its current state and will give it two more weeks to gather the necessary approval. If no 3 members of the committee approve it within this time, the pull request will be permanently closed. Thank you for your understanding.

**Pull request closed without merging**
