### PR TITLE
Add Perun channels proposal

### PR DESCRIPTION
**Pull request by matthiasgeihs**
Co-authored-by: Sebastian Stammler <seb@perun.network>

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Matthias, thanks for your application. Looks very good. We will look into it as soon as possible.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks a lot for the application. In general it looks really good. However, I’m a little bit confused that the following is covered by the application: “Off-chain component, i.e., the Golang component that connects the on-chain logic with the client logic.”.  Isn’t this part  blockchain-agnostic anyway? And it looks to me like you are implementing the abstraction layer together with milestone 1 (Core Types). So to clarify, once this grant is finished, is it possible to use it as full payment channel solutions (without app and sub channels) or would this require additional work?

**Comment by sebastianst** [comment]
Hey @Noc2 @semuelle thanks for your swift reply and feedback!

The focus of this proposal is the on-chain/conensus part in form of a Substrate Pallet _only_. We unfortunately wouldn't be able to also include the development of the go-perun _backend_ within the scope of this first proposal, as it is limited by $30k. It is correct that the off-chain _protocols_ are already implemented in an abstract way by go-perun, owing to its blockchain-agnostic architecture, but the connection between the abstraction and the Pallet still needs to be done in form of a _go-perun backend_, which we would like to build in the scope of a follow-up proposal to this one. You can have a look at our [Ethereum backend](https://github.com/hyperledger-labs/go-perun/tree/dev/backend/ethereum) to get a feel for what that means.

The payment channel protocols will already be visible in the form of tests of our Pallet. But in order to easily use payment channels via the go-perun SDK, we first need to also build the backend.

**Comment by semuelle** [comment]
Have you considered applying through our [General Grants Program](https://github.com/w3f/General-Grants-Program)? It's up to US$ 100k. We usually encourage teams to apply for an Open Grant, but if you are already set on implementing both components (pallet + backend), it might give you and us more planning reliability. I would just encourage you to work on both ends simultaneously, so we're not left with a loose end in case the grant is never completed, for whatever reason.

**Comment by alxs** [comment]
Sebastian has a point. While we generally encourage teams to apply to Open Grants, a General Grant might make more sense here (for the above reason, and the application also looks strong enough to me for Council approval). The only thing to consider is that the process would take a bit longer and the earliest acceptance date you'd be looking at would be in around a month. This is up to you, I'd also be willing to support the application as is and trust that you'd apply for the back end in the future.

**Review by Noc2 — APPROVED** [review]
Thanks for the response. I think it makes not much difference for us, if we support it via open or general grants. In both cases, we rely on you to actually finish the project. I’m therefore going to accept this grant.

**Review by semuelle — APPROVED** [review]
In that case, I won't dissent. :)

**Review by mmagician — APPROVED** [review]
Thanks for putting in the extra effort to polish the deliverables, the level of detail is much deeper than the initial proposal you shared by email! I'm happy to proceed.
Also you can safely ignore my last email :)

**Comment by sebastianst** [comment]
Awesome, thanks a lot! We're looking forward to working on the project 🎉

**Pull request merged**
