### PR TITLE
Application: Bounce Protocol

### PR DESCRIPTION
**Pull request by seiya1192**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@seiya1192 Thanks for the application, it looks interesting. I've got a few questions:
1. Could other parachains simply integrate one of the auction modules into their runtime (e.g. an NFT parachain that wants to trade the assets on a Dutch auction)? What would be the advantage of running your own separate parachain?
2. Does the auction manager (e.g. the collator for the parachain) receive any fees for hosting the auctions? Are there any "hidden" fees at all?
3. How much of the existing UI are you planning to re-use? I imagine that you will simply need to change the endpoints that you query (and perhaps parse the response slightly differently), but there shouldn't be too much work there, am I right in thinking so?
4. Are there advantages of developing your solution using substrate modules, vs. deploying smart contracts using the same functionality? Could your current solution on Ethereum be deployed as-is to Substrate using the [evm module](https://substrate.dev/docs/en/knowledgebase/smart-contracts/evm-pallet) or the [solang compiler](https://github.com/hyperledger-labs/solang)?

**Comment by rbtcool** [comment]
> @seiya1192 Thanks for the application, it looks interesting. I've got a few questions:
> 
> 1. Could other parachains simply integrate one of the auction modules into their runtime (e.g. an NFT parachain that wants to trade the assets on a Dutch auction)? What would be the advantage of running your own separate parachain?

* Yes, we will supply open source modules to help anyone who wants to integrate auction modules to their own chain. We will support assets that are compatible with ERC20/ERC721/ERC1155 protocols.

* According to the successful experiences on Ethereum we've got, our team will develop a new substrate-based blockchain, to extend our business to Polkadot ecosystem.


> 2. Does the auction manager (e.g. the collator for the parachain) receive any fees for hosting the auctions? Are there any "hidden" fees at all?

* It depends on the economic model of the chain who integrate Bounce modules into it. As an open source module, our team will make the design generic, flexible and configurable.

> 3. How much of the existing UI are you planning to re-use? I imagine that you will simply need to change the endpoints that you query (and perhaps parse the response slightly differently), but there shouldn't be too much work there, am I right in thinking so?

* Currently, Bounce's UI is not very user friendly, we will do a lot of work including re-design, improving user experiences, integration, and make it compatible with Substrate-based blockchain.

> 4. Are there advantages of developing your solution using substrate modules, vs. deploying smart contracts using the same functionality? Could your current solution on Ethereum be deployed as-is to Substrate using the [evm module](https://substrate.dev/docs/en/knowledgebase/smart-contracts/evm-pallet) or the [solang compiler](https://github.com/hyperledger-labs/solang)?

* For smart contracts on Ethereum, users themselves need to trigger a certain action. For substrate modules, some of those actions can be triggered automatically by the function on_finalize or offchain_worker.

* e.g. No one will know who wins/loses the bid until sealed bid auction ends. And users on Ethereum must claim their tokens manually. But, users on substrate don't need to do that, as it will be triggered automatically.

**Comment by seiya1192** [comment]
> @seiya1192 Thanks for the application, it looks interesting. I've got a few questions:
> 
> 1. Could other parachains simply integrate one of the auction modules into their runtime (e.g. an NFT parachain that wants to trade the assets on a Dutch auction)? What would be the advantage of running your own separate parachain?

* Yes, we will supply open source modules to help anyone who wants to integrate auction modules to their own chain. We will support assets that are compatible with ERC20/ERC721/ERC1155 protocols.

* According to the successful experiences on Ethereum we've got, our team will develop a new substrate-based blockchain, to extend our business to Polkadot ecosystem.

> 2. Does the auction manager (e.g. the collator for the parachain) receive any fees for hosting the auctions? Are there any "hidden" fees at all?

* It depends on the economic model of the chain who integrate Bounce modules into it. As an open source module, our team will make the design generic, flexible and configurable.

> 3. How much of the existing UI are you planning to re-use? I imagine that you will simply need to change the endpoints that you query (and perhaps parse the response slightly differently), but there shouldn't be too much work there, am I right in thinking so?

* Currently, Bounce's UI is not very user friendly, we will do a lot of work including re-design, improving user experiences, integration, and make it compatible with Substrate-based blockchain.

> 4. Are there advantages of developing your solution using substrate modules, vs. deploying smart contracts using the same functionality? Could your current solution on Ethereum be deployed as-is to Substrate using the [evm module](https://substrate.dev/docs/en/knowledgebase/smart-contracts/evm-pallet) or the [solang compiler](https://github.com/hyperledger-labs/solang)?

* For smart contracts on Ethereum, users themselves need to trigger a certain action. For substrate modules, some of those actions can be triggered automatically by the function on_finalize or offchain_worker.

* e.g. No one will know who wins/loses the bid until sealed bid auction ends. And users on Ethereum must claim their tokens manually. But, users on substrate don't need to do that, as it will be triggered automatically.

**Comment by mmagician** [comment]
Sounds good. Could you please include a comparison between your current deployment on Ethereum & the planned improvements in Substrate (like the automatic payout) in your application `.md` file?
Regarding the new UI, do you have any mockups available already?

**Comment by seiya1192** [comment]
> Sounds good. Could you please include a comparison between your current deployment on Ethereum & the planned improvements in Substrate (like the automatic payout) in your application `.md` file?

Added some comparison between Ethereum contracts and Substate modules.

> Regarding the new UI, do you have any mockups available already?

Not yet, still in design.

**Comment by mmagician** [comment]
@seiya1192 Thanks for the updates. 

> Not yet, still in design.

Mockups are usually a requirement for us to accept a grant. However, since the second milestone (app & UI work) is actually independent of the first one, perhaps it makes sense to first apply only for M1. Afterwards, once you've completed it & have mockups available, feel free to apply for a follow up Milestone 2. 
Also, is it possible to reduce the price? At the moment it seems high compared to the scope of proposed development.

**Comment by seiya1192** [comment]
> @seiya1192 Thanks for the updates.
> 
> > Not yet, still in design.
> 
> Mockups are usually a requirement for us to accept a grant. However, since the second milestone (app & UI work) is actually independent of the first one, perhaps it makes sense to first apply only for M1. Afterwards, once you've completed it & have mockups available, feel free to apply for a follow up Milestone 2.
> Also, is it possible to reduce the price? At the moment it seems high compared to the scope of proposed development.

 @mmagician Thanks for your reply, It’s a pity that BTC has risen a lot recently, I've changed the price. Should I remove Milestone2 or just keep it in .md file. We will provide Mockups ASAP the design work is done.

**Comment by mmagician** [comment]
Yes please remove M2 if you don't have the mockups yet. Also the price for m1 should be adjusted, it doesn't make sense to reduce only the m2 price if you're removing it.

**Comment by seiya1192** [comment]
> Yes please remove M2 if you don't have the mockups yet. Also the price for m1 should be adjusted, it doesn't make sense to reduce only the m2 price if you're removing it.

@mmagician Milestone 2 removed and total costs adjusted

**Review by mmagician — DISMISSED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Looks interesting. Could you remove the ERC721 pallet, since it already [exists](https://github.com/danforbes/pallet-nft) and instead focus on the ERC1155 implementation?

**Comment by ark930** [comment]
> Looks interesting. Could you remove the ERC721 pallet, since it already [exists](https://github.com/danforbes/pallet-nft) and instead focus on the ERC1155 implementation?

@Noc2 Thanks for your advice, removed ERC721 implementation.

**Comment by seiya1192** [comment]
> Looks interesting. Could you remove the ERC721 pallet, since it already [exists](https://github.com/danforbes/pallet-nft) and instead focus on the ERC1155 implementation?

@Noc2 Thanks for your advice, removed ERC721 implementation.

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Comment by Noc2** [comment]
@seiya1192  What’s the status of this grant? Are you still working on it?

**Comment by Noc2** [comment]
@seiya1192 We will terminate the grant due to inactivity. Feel free to apply again in case you still want to work on the project, see https://github.com/w3f/Open-Grants-Program/pull/443

**Pull request merged**
