### PR TITLE
Graviton application

### PR DESCRIPTION
**Pull request by DeFi-Evangelist**
# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few initial questions/comments:

- All contributor need to sign the Contributor License Agreement 
- The description of SuSy doesn’t describe susy in detail: https://arxiv.org/pdf/2008.13515.pdf 
- The way I understand it currently, is that it’s basically an oracle, which takes care of token transfers. 
- I don’t fully understand the connection between a parachain and the use of pBFT consensus. 
- You say Bifrost website doesn’t work/github closed, but both seem to work for me.

**Comment by DeFi-Evangelist** [comment]
*** The description of SuSy doesn’t describe susy in detail: https://arxiv.org/pdf/2008.13515.pdf**

Thanks for noticing, the detailed explanation of what is happening "on-chain" will be added in a few hours.

**> * The way I understand it currently, is that it’s basically an oracle, which takes care of token transfers.**

You're right this is basically an oracle with additional components (single sided liquidity AMM LP for wrapped tokens + liquidity mining/fees for network actors). But, gravity-network represents decentralized/distributed oracles which works via threshold (augmented multisig tx) signature with 3-steps verification including commit-reveal and on-chain parameters verification from signers.

And, to gain actuall traction we need fancy UI on top of it integrated with metamask/parity signer.

So, there are 3 milestones: 1 - substrate/parachain ingeration into gravity net, 2 - demo UI with single sided AMM for wrapped tokens, 3 - production release with liquidity mining functionality for wrapped tokens.

Third step depends on how fast we can see parahcains functionality available in kusama or polka mainnets (hope we'll see this soon). At least it can works as not ancored Parity-based chain with pBFT consensus from consuls of gravity network.

And after polka/kusama update we'll design and implement migration to replace substrate chain validators to polka relay chain validators (parachain slot registration without bridge).

**> * I don’t fully understand the connection between a parachain and the use of pBFT consensus.**

Sorry, it wasn't clearly explained. I'll try to explain in a few hours.

**> * You say Bifrost website doesn’t work/github closed, but both seem to work for me.**

ops, it was strange glitch of github or my internet. Thanks, I'll describe this more detailed soon.

**Comment by DeFi-Evangelist** [comment]
@Noc2 Thanks for your comments! 
The application has been updated according to your comments. Please, review it again.

In a frame of this grant application we want to develop two things which are core components for graviton project:

_**- polka/kusama cross-chain transfers gateway infrastructure and service**_

_**- on-chain single sided liquidity service for wrapped tokens**_

P.S.: We're not experts in Polka tech yet, so we can't propose comprehensive tech explanation of how exactly integration and ssAMM service will look like. Also, there aren't much functionality with parachains working in Polka or Kusama networks at the moment, so we're expecting some dependencies from release dates or trade-offs between final properly designed solution and temporary solutions.


Looking forward for the feedback!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and sorry for the late reply. I’m currently on vacation. It’s nice that you started to look into our tech stack. But for a successful grant application, we would need more details about your implementation and how it compares to existing solutions. Also, we mainly fund the development of open source software. For example we wouldn’t support something like parachain integration. Additionally, we are currently funding multiple teams, like interlay or snowfork, which are working on trust minimizing bridges and it probably makes sense to wait until they have delivered their solutions at this stage (see [grants accepted list](https://github.com/w3f/General-Grants-Program/blob/master/grants/accepted_grant_applications.md)).

**Comment by DeFi-Evangelist** [comment]
Hello @Noc2 !
I hope you enjoyed your vacation, and we're ready to resume a productive discussion on the current proposal.

* Everything we suggested is an open-source and we'll write tech articles and tutorials to let developers join/test it or integrate into their apps. Btw, thanks for mentioning of "milestones" format. We'll change milestones part of the proposal today, to make it as "ecosystem fit" proposal.

* There are 4 projects already supported by ecosystem grant which look similar on graviton functionality:

- Bifrost - EOS interoperable bridge (GitHub)
- Interlay - Polkadot/BTC bridge specification (RFP) (GitLab)
- Snowfork - Ethereum Bridge (GitHub)
- Equilibrium.io - All-in-one Interoperable DeFi hub. (GitHub)

We’re preparing a comparison table/research between those projects and graviton to emphasise a role of graviton app within polkadot ecosystem.

We'll update description within 1-2 days. Thanks for the feedback!

**Comment by Noc2** [comment]
Thanks for keeping me posted. Btw. it’s still not clear to me why you use pBFT (Tendermint). Also the whole setup seems very specific to your current tech stack at the moment and not so much beneficial for the polkadot ecosystem itself (for example open source code, which could potentially be used by others in our ecosystem).

**Comment by DeFi-Evangelist** [comment]
Thank you @Noc2  for you assistance and feedback!

As far as I understand, there are two important things supported by current program: 1 - libs/frameworks which "potentially be used by others in our ecosystem", 2 - infrastructure services like wallets/explorers/bridges/DEXes which can be reused by another teams as a part of their infrastructure.

Despite the status of grant for the current proposal, graviton project is aiming to build an infrastructure (gateways, single sided AMM DEX, substrate chain, parachain and etc) and integrations with polka tech as well.

So, let me close this PR and create another one which will have an ecosystem fit (that you mentioned in comments).

P.S.: This program and team's assistance is very helpful to go deep into tech/code details of polkadot as a starting point.

**Pull request closed without merging**
