### PR TITLE
multisignature management tool

### PR DESCRIPTION
**Pull request by carlhong**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi. Thanks for the application. subscan.io is a nice explorer. I just added it to the [tech stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md). Are you willing to get paid in BTC? If not I suggest to apply via the [general grants program](https://github.com/w3f/General-Grants-Program). Regarding the multisignature module, could you link to it? I think there are multiple versions. Also are you aware of the following psp https://github.com/w3f/PSPs/pull/7

**Comment by carlhong** [comment]
We are very excited that you like subscan, and we are constantly updating it to make it better. Because we hope that users can use the multi-sign tool as soon as possible, so this time we applied for Open-Grants-Program, and we accept BTC payment. About multiple versions, subscan has the function of scanning source code for version confirmation, which can be automatically adapted to the matching version. What we are currently doing is non-cryptographic multisig pallet, which will follow the standards of the community. We are also interested in developing and supporting other methods. If there is an opportunity, it may be put in a new grant later.

**Comment by carlhong** [comment]
Thank you for your interest in subscan! We have added the BTC address to the document and revised the project description. We are currently link to [as_multi] (https://github.com/paritytech/substrate/blob/v2.0.0-alpha.4/frame/utility/src/lib.rs#L321>) module, and will follow community standards in the future, such as [w3f/PSPs#7] (https://github.com/w3f/PSPs/pull/7).

**Comment by Noc2** [comment]
Sorry for the late reply here. I think in general we are interested in the application. But, as you already pointed out, you should try to make the interface easily adaptable to other multisig solutions ([see for example](https://github.com/centrifuge/substrate-pallet-multi-account)), since there is still a lot under development. I also have a few additional comments/remarks:

* I noticed that you did not use the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) for everything. Could you maybe update at least the milestone according to the template. The tables make it easier to evaluate the deliveries later.
* Also could you add some basic documentation/readme to every milestone (see the [guide of the general program as a reference](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md#testing-guide)) 
* If possible integrate unit tests
* What kind of tutorial are you planning to create and in which language(s)?
* Is it possible to reduce the overall costs to 3 BTC?

**Comment by carlhong** [comment]
@Noc2 The adaptable to other multisignature solutions you mentioned is indeed a problem. Our goal is to make a multisignature tool with good compatibility, and there are still many uncertain factors now, so we decided to temporarily delay the project. After the new version of multisignature solutions is determined, we will consider restarting this project.

**Comment by Noc2** [comment]
Thanks for the update. I think this makes a lot of sense at this stage. I will also reach out to you once we feel the multisig modules have reached a certain majority. Feel free to contribute to the PSP in the meantime.

**Comment by Noc2** [comment]
Hi @carlhong Would you still be interested in this? At this stage, I think we would be interested in a better UI specifically for the as_multi module.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for updating the application. Something to be aware of is that we still only payout btc via the open grants program. Could you therefore change the payment to BTC only? If you want to receive DOTs or KSMs, you can always apply for funding via the treasuries. 
An additional question I have is: how are you planning to handle call data. I think that’s currently a big usability problem with polkadot.js.

**Comment by carlhong** [comment]
@Noc2 I've updated payment to receive only BTC. As for call data, we are planing to build an opensourced user-friendly UI to list decoded call data with its hash for users who participated in the multi-signatures. For more convenience, we consider using database or other back-end service to store the index data. Data will be verified by hash on frontend.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Could you change the payment to show the amounts in BTC only. I know this way there is some market price risk, but it’s a requirement of the open grants program. (Alternatively you can also apply via the general grants program.) And could you also integrate the information about the call data into the application?

**Comment by carlhong** [comment]
BTC amount and call data info have been updated in application

**Review by Noc2 — DISMISSED** [review]
Looks good to me.

**Comment by mmagician** [comment]
Hi @carlhong 

As part of our new grant [guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant_application_template.md), we require that the teams submit the designs and specifications as part of the application Project Details. As David mentioned, we are interested in funding your idea, but in order to accept the proposal, we would need to see more specifics. This will also help us evaluate your submission later.

Therefore, please provide:
- the envisioned UI designs
- more technical details on how you plan to use the database/backend

In addition, please note that we require the submission to contain unit tests for the code logic and integration tests for the overall application.

I hope to see an updated proposal soon!

**Comment by carlhong** [comment]
@mmagician Sorry for the late reply. UI design, backend doc and test part have been added.

**Review by Noc2 — APPROVED** [review]

**Comment by mmagician** [comment]
@carlhong Thank you for the updates. It makes it much easier to grasp your proposal now.

**Review by mmagician — APPROVED** [review]

**Review by RouvenP — APPROVED** [review]

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grantspr@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by Noc2** [comment]
@carlhong  any update regarding this grant? You so far only delivered milestone 1 (https://github.com/w3f/Grant-Milestone-Delivery/blob/master/deliveries/multisignature_management_tool_milestone_1.md) Are you still planning to deliver the second milestone? Otherwise we would terminate the grant within the next two weeks.

**Comment by carlhong** [comment]
@Noc2 Sorry for late reply, we've completed the features required in milestone 2,  and the project is in final test stage. We'll pr the delivery as soon as possible after fixing some issues.

**Comment by Noc2** [comment]
Sounds great. Thanks for the quick reply.

**Pull request merged**
