### PR TITLE
RareLink Grant Application

### PR DESCRIPTION
**Pull request by 0x522359**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application via the open grants program. Did you receive the email, which I sent you yesterday and could you integrate my comments?

**Comment by 0x522359** [comment]
@Noc2 Thank you for kind suggestions! We had received your email. Our team will work on revision of our application and update it for your further review. I really appreciate your insights!

**Comment by Noc2** [comment]
Thanks for the update. I just have two additional follow-up questions: 
- Will the web ui be the standard polkadot.js interface or do you try to create your own UI on top of it? Do you already have some mockups or something similar for it? 
- Regarding milestone 1, are you aware of the following implementations https://github.com/danforbes/pallet-nft and https://github.com/w3f-community/nft_parachain  and could you potentially reuse them instead of creating your own solution?

**Comment by 0x522359** [comment]
Thanks for the comments. Please find our response in the below.

> Thanks for the update. I just have two additional follow-up questions:
> 
>     * Will the web ui be the standard polkadot.js interface or do you try to create your own UI on top of it? Do you already have some mockups or something similar for it?

We will create own UI on top of polkadot.js because user needs to setup the dynamic behavior of their dynamic NFTs in our UI. We will build it in our milestone 3. 

> 
>     * Regarding milestone 1, are you aware of the following implementations https://github.com/danforbes/pallet-nft and https://github.com/w3f-community/nft_parachain  and could you potentially reuse them instead of creating your own solution?

Thank you for the reference! We had noticed there are some existing work of nft pallet, which are great references to our project. We will investigate them and potentially add needed functionalities for dynamic NFTs on top of them. Since NFT pallet is a core component in our project, we include it in our milestone 1 to make our plan more self-contained.

**Comment by Noc2** [comment]
Could you integrate in milestone 1 that you will potentially reuse and update existing solutions? And could you integrate the following into the application. 
> create own UI on top of polkadot.js

**Comment by 0x522359** [comment]
@Noc2 Thank you for kind suggestions! We had updated our application (milestone 1 and milestone 3) and included both points. Indeed, they help clarify scope of our work. We really appreciate your insights!

**Review by Noc2 — APPROVED** [review]
Looks good.

**Review by mmagician — APPROVED** [review]
Looks good!

I presume that you will be including [this Chainlink pallet](https://github.com/smartcontractkit/chainlink-polkadot/)? I had worked on it for fun in the past, I think when Substrate was still on version rc5 or rc6 - see my [PR](https://github.com/smartcontractkit/chainlink-polkadot/pull/40). 

As far as I know, the current code in that repo is not compatible anymore with v2.0.0. I might have a go at fixing this in my spare time, but if you reach it first, feel free to contact me in case you have any questions! (matrix: @marcin:web3.foundation)

**Review by RouvenP — APPROVED** [review]

**Comment by 0x522359** [comment]
> Looks good!

@mmagician Thanks for approving our application!
> 
> I presume that you will be including [this Chainlink pallet](https://github.com/smartcontractkit/chainlink-polkadot/)? I had worked on it for fun in the past, I think when Substrate was still on version rc5 or rc6 - see my [PR](https://github.com/smartcontractkit/chainlink-polkadot/pull/40).

Yes, we will use the Chainlink pallet. thanks for sharing the link with us. :)

> As far as I know, the current code in that repo is not compatible anymore with v2.0.0. I might have a go at fixing this in my spare time, but if you reach it first, feel free to contact me in case you have any questions! (matrix: @marcin:web3.foundation)

We are glad to contribute to the work. We will reach out to you when we are working on milestone 2. Look forward to collaborating with you in the near future!

**Comment by alxs** [comment]
@0x522359 care to share a quick update on your progress on the grant, together with an ETA if possible? We usually provide plenty of leniency on delivery dates given how fast the space moves, but your first milestone is 6 months overdue at this point. If you're no longer actively working on the project, we will terminate this grant in the following days.

**Comment by alxs** [comment]
This grant is being terminated due to inactivity. Feel free to apply again if you're still interested.

**Pull request merged**
