### PR TITLE
New proposal: Polkashots.io, a website hosting Polkadot snapshots

### PR DESCRIPTION
**Pull request by nicolasochem**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by BenWhiteJam** [comment]
Been looking for something like that, a few questions:
- Where will those get stored?
- How often will they get updated?
- Polkadot & Kusama?
- How do you create the signature to verify the validity of the snapshot?

**Comment by nicolasochem** [comment]
* snapshots will be stored on a public google cloud storage bucket
* the snapshot generation frequency will be configurable. 24 hours frequency seems reasonable. Nodes typically sync very fast from a 24 hour lag.
* We will be supporting Polkadot and Kusama.
* we can generate sha256sum of the files, so users will have a proof of valid download. Would you like that? I can add this to the requirements if needed.

However, the best way to ensure safety IMO would be to provide an option to `substrate import-blocks --hash 0x37d2713b2a53...` to be able to pass the block hash that you think you are importing. You can match that with what you see on the snapshot website.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late response. This is indeed an interesting application. Could you make the tutorial part of the deliveries. Also could you integrate your reply above in the requirements? And in general define the requirements/milestone a little bit more specific (exact functionality, programming language, framework, etc.)?

**Comment by nicolasochem** [comment]
@Noc2 thanks! All done.

**Review by Noc2 — APPROVED** [review]
Looks good to me. Thanks!

**Review by mmagician — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Pull request merged**
