### PR TITLE
Clover Bridge

### PR DESCRIPTION
**Pull request by brqgoo**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @brqgoo, thank you for your submission and apologies for the late reply.

I am happy to share this application with the rest of the team, except that we recently changed the policy to grant applications having to be denominated in USD (due to the volatility of other currencies). It can still be paid out in DAI or BTC. Could you change the prices to USD?

**Comment by brqgoo** [comment]
> Hi @brqgoo, thank you for your submission and apologies for the late reply.
> 
> I am happy to share this application with the rest of the team, except that we recently changed the policy to grant applications having to be denominated in USD (due to the volatility of other currencies). It can still be paid out in DAI or BTC. Could you change the prices to USD?

Hi @semuelle made the respective changes. Looking forward to your feedback.

**Comment by semuelle** [comment]
Thanks for the follow-up. Two more notes:

- The grants program doesn't fund Solidity smart contract development. 
- Can you be more specific about the deliverables? `Start documenting`, for example, is too vague.

**Comment by brqgoo** [comment]
> Thanks for the follow-up. Two more notes:
> 
> * The grants program doesn't fund Solidity smart contract development.
> * Can you be more specific about the deliverables? `Start documenting`, for example, is too vague.

Hi @semuelle contracts were needed for peg-in and peg-out flows, however are a small part of overall development. Updated the application, thanks.

**Comment by semuelle** [comment]
Thanks for the update. I’m happy to go ahead with the application as it is now and will share it with the rest of the team.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, given that we already have two big ethereum bridges in the ecosystem under development ([ChainBridge](https://github.com/ChainSafe/ChainBridge), [
polkadot-ethereum](https://github.com/Snowfork/polkadot-ethereum)) the grants committee previously was rather reluctant to fund another bridge. Could you point out what’s the advantage of your solution compared to the existing solutions? Additionally all your deliveries are currently in go. Don’t you need to store anything on-chain?

**Comment by brqgoo** [comment]
> Thanks for the application. However, given that we already have two big ethereum bridges in the ecosystem under development ([ChainBridge](https://github.com/ChainSafe/ChainBridge), [ polkadot-ethereum](https://github.com/Snowfork/polkadot-ethereum)) the grants committee previously was rather reluctant to fund another bridge. Could you point out what’s the advantage of your solution compared to the existing solutions? Additionally all your deliveries are currently in go. Don’t you need to store anything on-chain?

Hi @Noc2  thanks for the reply.

Today’s bridges operate under a trusted federation model. ChainBridge is for example, governed by a trusted set of off-chain relayers who await finality, submit events to the other chain and vote on submissions to reach acceptance triggering the appropriate handler. 

Snowfork is on the other hand, allows Ethereum to read state from Polkadot which is a bit more complex, as there are enormous compute/gas cost challenges in doing this. 

The more signatories a bridge accommodates the more decentralized the bridge becomes, however this is also proportional to gas consumption since ecrecover consumes 3000 gas per signatory. Bitcoin script is on the other hand is limited to 15 signatories in a multisig operation and is also expensive in witness units.

Clover Bridge proposes a solution to the pain point of decentralization cost of how a proper cross-chain communication should be operating under scarce resources. We’re proposing a Schnorr-compatible threshold signatory solution which can provide a high level of decentralization by accommodating up to hypothetically unlimited number of signatories while massively reducing the verification cost. With Clover Bridge, the entire bridge operation is compressed into one aggregated public key which can be verified with one custom signature check operation that only consumes 85000 gas in Ethereum VM and 291 weight units in Bitcoin script (with the upcoming BIP-340 upgrade).

We have contract implementations for peg-in/peg-out flows that are separated from the application as W3F Grants Program does cover Solidity contract development.

**Comment by Noc2** [comment]
Thanks for the detailed reply and all the effort you put into the application. However, I’m closing the application for now, since you are currently actively raising money for exactly this implementation, see https://coinlist.co/clover. See our [guidelines](https://github.com/w3f/Open-Grants-Program#guidelines): “We do not award grants for projects that have been the object of a successful token sale.” 
Please integrate this the next time under [additional information section]( https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#additional-information-heavy_plus_sign) In case the toke sale fails, feel free to reapply/reopen the application or  in the meantime feel free to send us an application for another project.

**Comment by Noc2** [comment]
Btw. you probably should remove Polkadot from Strategic Partners. Not sure how you can partner with a decentralized network ;-)

**Comment by Noc2** [comment]
@brqgoo  I also like to point out, that you are still use acala’s code without proper attribution, even after we notified you about it, see 

- https://github.com/clover-network/clover/blob/bcd6a74a8fe422c3a056d29e348183103448301e/modules/evm-accounts/src/lib.rs 
- https://github.com/AcalaNetwork/Acala/blob/4b74d6c622610a4a0a873941b3f1e2d4963f79eb/modules/evm-accounts/src/lib.rs 

Based on this, I’m personally highly likely not going to support any future grant applications of your team.

**Comment by trescorion** [comment]
that's weird

**Comment by superyundad** [comment]
So far, no founder of this project has come out to speak, or even violated the contract of community members. From a personal point of view, I think clover is more like a scammer and a thief.

**Pull request closed without merging**
