### PR TITLE
Pacific store

### PR DESCRIPTION
**Pull request by vlbos**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@vlbos Thank you for the application.
We actually have some NFT teams building on Polkadot already, for example [RareLink](https://github.com/w3f/Open-Grants-Program/pull/86). Perhaps you could briefly comment on how your solution differs from theirs?

**Comment by vlbos** [comment]
> @vlbos Thank you for the application.
> We actually have some NFT teams building on Polkadot already, for example [RareLink](https://github.com/w3f/Open-Grants-Program/pull/86). Perhaps you could briefly comment on how your solution differs from theirs?

Thank you for your review .we update it .add listing on how our solution differs from RaeLink or Others

**Review by mmagician — CHANGES_REQUESTED** [review]
@vlbos I have a couple of questions:
1. > We've already built the largest marketplace for crypto collectibles

Could you provide a link to such marketplace? I never heard of PacificStore and also couldn't find any details online. 

2. Why do you have `Technical specifications and Zenlink DEX Module design` as part of your first milestone?

3. We will need much more details in your milestones than `Creation of integration APIs + documentation`. This doesn't say anything about the code that you'll deliver. This applies to all of your milestones. Please update your grant application with relevant specifications please.

**Review by Noc2 — CHANGES_REQUESTED** [review]
@vlbos Please also specify the programming language/framework, which you are planning to use for each deliverable.

**Comment by vlbos** [comment]
> @vlbos I have a couple of questions:
> 
> 1. > We've already built the largest marketplace for crypto collectibles
> 
> Could you provide a link to such marketplace? I never heard of PacificStore and also couldn't find any details online.
> 
> 1. Why do you have `Technical specifications and Zenlink DEX Module design` as part of your first milestone?
> 2. We will need much more details in your milestones than `Creation of integration APIs + documentation`. This doesn't say anything about the code that you'll deliver. This applies to all of your milestones. Please update your grant application with relevant specifications please.

Thank you for your reviews.I'm sorry for rookie mistakes in the document.we updated it .Add details of the code of our milestones

**Comment by vlbos** [comment]
> @vlbos Please also specify the programming language/framework, which you are planning to use for each deliverable.

Thank you for your reviews.we  added programming language and framework part.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Some of the formatting seems to be off. Additionally could you combine the Deliverables with the programming language/framework in one table?  As Marcin pointed out, the deliverables are still a bit unclear to me: for example “Making Offers”, how will this work. Is it it implemented in the smart contract as well as the UI. And how does “Using ERC-20 tokens” work? Are you referring to tokens on ethereum, when you say erc-20 tokens? And do I understand it correctly, that you want to first create a solidity contract and then compile this with solang into a smart contract for edgware, correct? Did you already start to work on this smart contract? It sounds a little bit like you want to port OpenSea to edgeware with the help of solang. Is this correct?

**Comment by vlbos** [comment]
> Thanks for the update. Some of the formatting seems to be off. Additionally could you combine the Deliverables with the programming language/framework in one table? As Marcin pointed out, the deliverables are still a bit unclear to me: for example “Making Offers”, how will this work. Is it it implemented in the smart contract as well as the UI. And how does “Using ERC-20 tokens” work? Are you referring to tokens on ethereum, when you say erc-20 tokens? And do I understand it correctly, that you want to first create a solidity contract and then compile this with solang into a smart contract for edgware, correct? Did you already start to work on this smart contract? It sounds a little bit like you want to port OpenSea to edgeware with the help of solang. Is this correct?



> Thanks for the update. Some of the formatting seems to be off. Additionally could you combine the Deliverables with the programming language/framework in one table? As Marcin pointed out, the deliverables are still a bit unclear to me: for example “Making Offers”, how will this work. Is it it implemented in the smart contract as well as the UI. And how does “Using ERC-20 tokens” work? Are you referring to tokens on ethereum, when you say erc-20 tokens? And do I understand it correctly, that you want to first create a solidity contract and then compile this with solang into a smart contract for edgware, correct? Did you already start to work on this smart contract? It sounds a little bit like you want to port OpenSea to edgeware with the help of solang. Is this correct?
Thanks for the comment. basically correct.we will merge the tables ,simplify description ,elaborate more details of code.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. But if I understand it correctly, you are not really implementing all these functions and deliverables yourself. You are simply using solang to compile existing evm contracts into the correct wasm format for our contract module. I don’t understand why your deliverables also mention ink!, since it seems you won’t use ink!. Solang only compiles smart contracts to wasm in a way that the contract module can understand it. In general we would only support the parts of the application that focus on software development (that doesn’t already [exist](https://github.com/ProjectOpenSea/opensea-js)) related to Polkadot, Kusama and Substrate. So, I suggest to only focus on the parts that you actually have to implement and that are unique to our ecosystem.

**Comment by vlbos** [comment]
> Thanks for the update. But if I understand it correctly, you are not really implementing all these functions and deliverables yourself. You are simply using solang to compile existing evm contracts into the correct wasm format for our contract module. I don’t understand why your deliverables also mention ink!, since it seems you won’t use ink!. Solang only compiles smart contracts to wasm in a way that the contract module can understand it. In general we would only support the parts of the application that focus on software development (that doesn’t already [exist](https://github.com/ProjectOpenSea/opensea-js)) related to Polkadot, Kusama and Substrate. So, I suggest to only focus on the parts that you actually have to implement and that are unique to our ecosystem.

Thanks for your suggestion. About [wyvern contracts](https://github.com/ProjectOpenSea/wyvern-js/tree/master/src/wyvern-ethereum/contracts)  Rust cargo-contracts implement ,would you support it ?
These are the Ethereum smart contracts for the Wyvern Protocol, the Wyvern ERC20 token (WYV), and the Wyvern DAO.
it also is  base part of opensea-js. as out first step to  implement opensea-js on polkadot.
our future plan is  the have-to implement of  the other part of opensea-js on polkadot.it include opensea-js backend service and auto-generated UI according to a user's deployed contract and metadata.


By the way,
"you are not really implementing all these functions and deliverables yourself"
Our team has four people working part-time in this development.if needed ,we will add developers.

**Comment by Noc2** [comment]
Thanks for the quick response. In this case, what are you developers working on? If you for example need to adapt the existing opensea-js to integrate polkadot.js as well as add unique substrate related features, this would be potentially worth a small grant from us. Other than that, I know that https://moonbeam.network/ wants to launch a grant program soon, which might be better suited for these kinds of projects.

**Comment by vlbos** [comment]
> Thanks for the quick response. In this case, what are you developers working on? If you for example need to adapt the existing opensea-js to integrate polkadot.js as well as add unique substrate related features, this would be potentially worth a small grant from us. Other than that, I know that https://moonbeam.network/ wants to launch a grant program soon, which might be better suited for these kinds of projects.

Thanks for your suggestion.our developers are working on frontend (javascript/typescript) or backend/system(C++/Rust) .
we will update the  application according to your suggestions.
Many thanks

**Review by Noc2 — APPROVED** [review]
Thanks for the update. This looks much better to me and I’m willing to go ahead with it.

**Comment by vlbos** [comment]
> Thanks for the update. This looks much better to me and I’m willing to go ahead with it.

Thanks for the comment.

**Review by RouvenP — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Comment by vlbos** [comment]
Thanks for the grant.

**Comment by alxs** [comment]
@vlbos care to share a quick status update, along with an ETA if possible? The project [repo](https://github.com/vlbos/pacificstore-node) looks inactive and we were hoping to receive your next delivery a bit over 2 months ago now.

As long as you're actively working on the project, delays aren't a big problem, but we'd appreciate it if you could keep us in the loop. Note that if we don't hear from you soon, we will assume you're no longer interested and terminate the agreement.

**Comment by alxs** [comment]
This grant is being terminated due to inactivity. Feel free to apply again if you're still interested.

**Pull request merged**
