### PR TITLE
Ready to submit application for Entropy

### PR DESCRIPTION
**Pull request by dinganc**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. The following links don’t seem to be public: https://github.com/LosslessBattle/Lossless-V2-Core, https://github.com/LosslessBattle/Lossless-V3-Core Could you add more technical details to the deliveries? For example, what programming language/smart contract are you planning to use?  And did you take a look at https://github.com/XPredictMarket and https://github.com/zeitgeistpm/zeitgeist? How is your solution different?

**Comment by Noc2** [comment]
> Thanks for the application. The following links don’t seem to be public: https://github.com/LosslessBattle/Lossless-V2-Core, https://github.com/LosslessBattle/Lossless-V3-Core Could you add more technical details to the deliveries? For example, what programming language/smart contract are you planning to use? And did you take a look at https://github.com/XPredictMarket and https://github.com/zeitgeistpm/zeitgeist? How is your solution different?

**Comment by Noc2** [comment]
Any updates here?

**Comment by dinganc** [comment]
> 
> 
> Thanks for the application. The following links don’t seem to be public: https://github.com/LosslessBattle/Lossless-V2-Core, https://github.com/LosslessBattle/Lossless-V3-Core Could you add more technical details to the deliveries? For example, what programming language/smart contract are you planning to use? And did you take a look at https://github.com/XPredictMarket and https://github.com/zeitgeistpm/zeitgeist? How is your solution different?

Thank you for the review! The project is currently being developed in a private repository. We can add you to our organization so you could review the code. Currently the prediction market logic and economics mechanism are implemented in solidity and deployed on Ethereum Kovan testnet at https://www.entropyfitest.app/. We are planning to deploy on Moonbeam parachain first, but we might also explore the possibility to build as a dedicated parachain.

For the differences between Entropy, Zeitgeist, and XPredictMarket, Entropy is focused on lossless prediction market and asymmetrical prediction market. The goal for Entropy is to provide users a low-risk way to hedge against their position or to insure their position.

Happy to answer any other question :)

**Comment by Noc2** [comment]
Thanks for the reply. Feel free to add me to your repo. Could you still add more technical details to your deliveries? Something you should also be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. It would be nice if you could for example leverage ink! for this grant. If you only want to focus on moonbeam and solidity, you might want to take a look at https://moonbeam.foundation/grants/

**Comment by dinganc** [comment]
> 
> 
> Thanks for the reply. Feel free to add me to your repo. Could you still add more technical details to your deliveries? Something you should also be aware of, is that we usually don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point. It would be nice if you could for example leverage ink! for this grant. If you only want to focus on moonbeam and solidity, you might want to take a look at https://moonbeam.foundation/grants/

Thank you for the feedback! Yes, we are currently talking with Moonbeam team and trying to launch on Moonbeam. I think it makes sense to launch on a EVM-compatible parachain first. I will communicate this with my team.

**Pull request closed without merging**
