### PR TITLE
Application:PPCWallet

### PR DESCRIPTION
**Pull request by ppcwallet**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, at this point it’s difficult to justice to fund the development of another wallet (or basic wallet functions), given that there are already quite a few wallets available in our ecosystem: https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#iphone-explorer-and-wallets I think the most interesting aspect of your application is about making it easier for developers to immediately support different wallets, but to be honest I don’t understand how your inject.js archives this. Could you explain this more detailed? Also it would be nice if you could share some of your previous open source work in this space.

**Comment by ppcwallet** [comment]
@Noc2 
Thanks for the reply
Our demo has been submitted to GitHub

chain-core SDK
https://github.com/ppcwallet-team/Chain-Core
Contains two parts:
1.Engine blockchain basic function module, allowing wallet developers to quickly realize the basic functions of decentralized wallets. The main functions are as follows:
-Get mnemonic words
-Get the private key
-Get the address
-Sign the transaction
-Sign Token transaction
-Sign the message

2. Inject injection module, allowing wallet developers to quickly access DAPP. The main functions are as follows:
-When opening a dapp, inject the compiled inject.js into the dapp page
-Set your own address, chainID, and other information for the page
-When signing transactions inside the dapp, it will be intercepted by the inject module and sent to the app through jsbridge for signing transactions
-Return the hash after the transaction to the dapp page for subsequent logical processing

chain-core-and is a demo example of our Android version
https://github.com/ppcwallet-team/Chain-Core-And

This SDK is for more project-side wallet developers to quickly connect their wallet projects to more mainnets. The multi-chain wallets that have been developed using this SDK include BitKeep, TrueWallet, etc.
This model is very suitable for Polkadot's multi-parachain ecology. The SDK will continue to expand and dock all the parallel chains of Polkadot. Wallet developers only need to introduce this SDK to perfectly support the Polkadot parachain ecology.

**Comment by Noc2** [comment]
Thanks for sharing the code. For your information, [snyk test](https://snyk.io/) revealed a few security issues with your js implementation. But I still don’t understand the benefit of your solution compared to for example https://github.com/polkadot-js, which offers all these features or https://github.com/luniehq (which sadly is no longer maintained).

**Comment by Noc2** [comment]
I’m closing the application for now. Feel free to reopen it or to send us another grant application.

**Pull request closed without merging**
