### PR TITLE
Create bright_treasury.md

### PR DESCRIPTION
**Pull request by aolszewska**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks really good. Could you change the payment to DAI. We probably will change the denomination to USD anyway very soon and DAI makes the payment process a lot easier. And just to clarify, you will implement the user stories in NestJS and React as part of the front end, correct? Maybe you can also clarify this in the application, because currently the term “user story” is a little bit undefined and might cause misunderstandings (for  example you could just provide mockups for the user stories).

**Comment by bufta** [comment]
Thank you very much for your feedback. We changed the currency to DAI as you suggested and added a more descriptive definition of what delivering a user story means (Definition of Done for user stories and milestones as well).

**Review by Noc2 — APPROVED** [review]
Thanks for the update and sorry for the late reply. This looks really good. I’m happy to go ahead with it.

**Comment by mmagician** [comment]
Thanks for all the effort put into this, the mockups look great!

I have only one comment: why have a separate login screen, especially with the accountID as optional? It seems like the accountID is the most critical thing for participating, no? I would have imagined that users would authenticate via polkadot JS, so that their accounts are imported directly to your app.

**Comment by bufta** [comment]
Thank you @mmagician for your comment. When it comes to the login, we assume that indeed most users during the first login will sign up with their blockchain accounts and then will be able to use these to access the app. However, we plan to broaden the audience to people who might not have the blockchain accounts (yet) and allow them to publish their ideas for proposals and take part in the discussions. When they decide to publish a proposal to blockchain, they will need to integrate the in-app account with their blockchain account. I will be happy to provide more details if needed.

**Review by mmagician — APPROVED** [review]
Ok, that makes sense. I'm happy to support the project!

**Review by BenWhiteJam — APPROVED** [review]

**Comment by alxs** [comment]
@Dohkooo care to share a quick status update on the project, together with an ETA if possible? Your first delivery is delayed by several months so if we don't hear something from you soon, we will assume you're no longer working on this and terminate the grant due to inactivity.

**Comment by alxs** [comment]
@bufta apologies from my side, I see you did send us an email at the end of March. Hope your team is doing fine. Happy to hear that and looking forward to your delivery.

**Comment by alxs** [comment]
@bufta @aolszewska checking in again - any updates on the second milestone? It looks like the [project repository](https://github.com/bright/bright-tresury) hasn't been updated since the last delivery. Here as well, if we don't hear anything from you within the next 2 weeks, we'll assume you're no longer interested and terminate the grant.

**Comment by bufta** [comment]
Hi @alxs , I apologise for the delay. Milestone 2 took more time than anticipated. We put a lot of effort and care in this project, we are determined to deliver it as described in the grant proposal. 

Milestone 2 is currently being finished, just a few minor things left right now. You can expect the delivery within 2 weeks. Thank you very much for your patience.

**Comment by alxs** [comment]
Thanks for the update @bufta, please keep us posted if you need more time in the end. No need to rush it.

**Comment by bufta** [comment]
Hi, we’d just like to let you know that (following our "User Story 36 - As a user I can use the Milestone 1 and Milestone 2 features in production environment") BrightTreasury milestone 1 and 2 are already available on production at [treasury.bright.dev](https://treasury.bright.dev/) . It’s fully operational when it comes to the Ideas and Proposals flow. We’re very excited to see it live and ready to gather feedback through github issues :) We will soon follow with deployment of the full version, as we are finishing tasks of Milestone 3.

**Comment by Noc2** [comment]
That’s great to hear! Thanks for the update.

**Pull request merged**
