### PR TITLE
TON BRAINS application Open Grants Program

### PR DESCRIPTION
**Pull request by mvkhokhlov**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by mvkhokhlov** [comment]
TON BRAINS Sign Off

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. But the file is currently difficult to view, because it’s missing “.md” at the end of the name. Also the price is currently above the 30k limit of the open grants program.

**Comment by mvkhokhlov** [comment]
All Fixes have been made. BTC and MD doc price!

**Review by mmagician — CHANGES_REQUESTED** [review]
This sounds like an ambitious project that requires breadth of technical knowledge on how Polkadot operates. Do you have any portfolio of creating educational material around the blockchain technologies? Or perhaps a portfolio of developing code/applications around any of the existing ledgers? (e.g. dapps, smart contracts, runtime modules, clients etc)

Before reviewing your application further, I would like to ask you to submit some sample material, which we would then share with our Technical Education team for relevancy. As it stands now, I didn't catch whether you would be making videos, text-based/interactive tutorials or other forms of educational material, since your description for **Project Details** section is very vague. Please specify exactly what kind of content you're planning to create.

Lastly, perhaps you could outline any shortcomings that you notice in our [wiki](https://wiki.polkadot.network/) which would be addressed by your app.

**Comment by mvkhokhlov** [comment]
> This sounds like an ambitious project that requires breadth of technical knowledge on how Polkadot operates. Do you have any portfolio of creating educational material around the blockchain technologies? Or perhaps a portfolio of developing code/applications around any of the existing ledgers? (e.g. dapps, smart contracts, runtime modules, clients etc)
> 
> Before reviewing your application further, I would like to ask you to submit some sample material, which we would then share with our Technical Education team for relevancy. As it stands now, I didn't catch whether you would be making videos, text-based/interactive tutorials or other forms of educational material, since your description for **Project Details** section is very vague. Please specify exactly what kind of content you're planning to create.
> 
> Lastly, perhaps you could outline any shortcomings that you notice in our [wiki](https://wiki.polkadot.network/) which would be addressed by your app.

We will use what is available right now. No custom modifications or anything like that. The information will be taken from the Polkadot website, youtube, twitter. We have plans to build an Academy. We would like to start with a basic must-have app and extended it with community approval and suggestion. 

Also, TON BRAINS have enough knowledge of Polkadot infrastructure to make a significant investment in the Polkadot economy. 

We have stated clearly our goals: Make Polkadot/Web3Foundation information accessible to everyone anywhere. We strongly believe that educating entry-level users based on Polkadot/Web3Foundation projects is much more valuable than providing other decentralized/blockchain-based projects as an example. 

TON BRAINS would happy to build a long-term relationship with PolkaDot.

**Comment by mmagician** [comment]
I have consulted other members of my team and here is a summary of our conclusions:

> We will use what is available right now. No custom modifications or anything like that.

1. There are already a number of channels which aggregate & summarise Polkadot-related knowledge and we don't see a need for another Polkadot source, especially if it creates no original content. 

2. You haven't provided any portfolio still.

> TON BRAINS have enough knowledge of Polkadot infrastructure to make a significant investment in the Polkadot economy.

3. It's an empty claim unless you can prove this.

4. Lastly, when submitting your next proposal I would strongly advise checking for grammar & spelling mistakes. This is especially true for educational content: poor content of a proposal is a harbinger of poor content for Polkadot enthusiasts, which we definitely don't want.

Due to the points raised I'm closing this application. You are welcome to apply with other proposals in the future.

**Comment by mvkhokhlov** [comment]
Thank you for the response. 

1) There is nothing available on a mobile device with a friendly user interface. Also, people with disabilities can't access your content. You are obligate by law to provide full access to the information to all people. Especially when you are trying to change the Web Industry. 

2)  TON BRAINS in the research and development with Polkadot tech and soon enough will provide all necessary information. 

3) Sorry, we didn't quite get it.  Please specify what do you mean by this statement. 

4) Yes, We have found few spelling mistakes. But nothing critical that would make the proposal misunderstood. 

Finally, we would use internal funding to grant this project without Web3Foundation commitment. 

We suggest creating a list of project categories that you would decline by default based on proposal history. This will help companies to create a strategic focus on what  web3Foundation needs today. Otherwise, a blind guess is just a waste of time for both parties and the rest of the community.

**Comment by mmagician** [comment]
> There is nothing available on a mobile device with a friendly user interface

I'm not a UX expert, but the wiki is in my opinion very well adapted to a mobile version. Furthermore, any modern mobile web browser supports accessibility mode. I've also tried it and the wiki keeps being user & accessibility friendly

We are not rejecting yours, not any other proposal, based on history or preferences, but rather as you see, we invest time to carefully read the application and evaluate it on a case-by-case basis.

**Pull request closed without merging**
