### PR TITLE
Haskell Web3 library

### PR DESCRIPTION
**Pull request by akru**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by akru** [comment]
Sure, thank you @Noc2!
Please let me known decision when ready.

**Comment by Noc2** [comment]
Hi @akru. So the other team just informed me that they currently don’t have the time for it and they would be happy if you work on it. I think your proposal looks good. The only thing that seems rather high to me is your day rate based on the current BTC price. Could you reduce the price a little bit more?

**Comment by akru** [comment]
Hi @Noc2, yep, no problem,
recently BTC is really a bit expensive.

**Comment by RouvenP** [comment]
Thanks for the application. Also fine from a financial point of view.

**Comment by semuelle** [comment]
Hey @akru, are you still planning to submit the fourth milestone? Was there anything technical keeping you from finishing it? We usually terminate projects that are delayed by more than a few months.

**Comment by akru** [comment]
Hello @semuelle, thank you for notice me. 
I’m on final step of this milestone: signing extrinsics, hope to finish it in few weeks. I’ll be happy if you could hold termination process a bit. Sorry for delay.

**Comment by semuelle** [comment]
Glad to hear you are still working on it. :+1: I'll check back in four weeks time if I don't hear from you.

**Comment by akru** [comment]
Hello @semuelle, just want to let you known that I continue to work on it, auctions were a hurry day, yeah. Currently, I'm working on MetadataV13 support, hope to finish it next week. It's out of this grant but required for show demo on latest Polkadot. Hope to make not only a grant but provide fully functional Haskell support for Polkadot.

**Comment by akru** [comment]
Hello @semuelle couple of updates from my side:
* metadata v13 support added but still have some issues of scale decoding, I’m investigating what could be a problem;
* extrinsic signing is almost finish, currently supported ECDSA and ed25519 crypto pairs;

Not implemented yet:
* method call serialization, this is a part of extrinsic payload and should be finished before successful extrinsic sends.

The estimated delivery time moved, sorry for that, currently it is 15th of august. Feel free for any questions.

**Comment by semuelle** [comment]
Thanks for the update, @akru. There is no rush currently. It's good to hear you are still working on it, which is our main concern. Keep us in the loop.

**Comment by akru** [comment]
Hello @semuelle, hope this message finds you well.
I glad to say that Milestone 4 (last) of this project finished and ready for review. PR with results created. 
Thank you very much for your support and patience!

**Pull request merged**
