### PR TITLE
Citadel

### PR DESCRIPTION
**Pull request by citadeldao**
Citadel.one Application

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. It looks really interesting. However, we only fund the development of open source software as part of the grants program. Therefore we wouldn’t support the design/research phase at the very beginning. Also we would only fund your project if the code is actually fully open source and can be used by others. If this is not the case, you could potentially apply for funding via the treasuries: https://github.com/w3f/Open-Grants-Program#treasury If you plan to open source everything, which is developed as part of the project, we would need to have additional information regarding the programming languages/frameworks, unit tests, etc. Additionally we only pay out BTC via the open grants program. So your application needs to contain a certain BTC amount rather than a fiat payment.

**Comment by citadeldao** [comment]
> Thanks for the application. It looks really interesting. However, we only fund the development of open source software as part of the grants program. Therefore we wouldn’t support the design/research phase at the very beginning. Also we would only fund your project if the code is actually fully open source and can be used by others. If this is not the case, you could potentially apply for funding via the treasuries: https://github.com/w3f/Open-Grants-Program#treasury If you plan to open source everything, which is developed as part of the project, we would need to have additional information regarding the programming languages/frameworks, unit tests, etc. Additionally we only pay out BTC via the open grants program. So your application needs to contain a certain BTC amount rather than a fiat payment.

1) From our side, we are ready to make the part associated specifically with Polkadot fully open-source. In case it is a valid option, we will provide necessary information regarding the programming languages/frameworks, unit tests, etc.
2) 2,21 BTC

**Comment by Noc2** [comment]
Yes, if you are indeed willing to open source everything, we would be interested in the application. Feel free to integrate the additional information and also the BTC amount. One additional comment from my side: We usually don’t fund things like launching a node/validator, but instead focus on the development of open source software, which is potentially useful for others. We also don’t want to support a specific validator via the grants program directly. So it would be nice if you could remove this part and instead fully focus on the development of software.

**Comment by citadeldao** [comment]
> Yes, if you are indeed willing to open source everything, we would be interested in the application. Feel free to integrate the additional information and also the BTC amount. One additional comment from my side: We usually don’t fund things like launching a node/validator, but instead focus on the development of open source software, which is potentially useful for others. We also don’t want to support a specific validator via the grants program directly. So it would be nice if you could remove this part and instead fully focus on the development of software.

Thank you for your response! We've just submitted another request - feel free to check it out. Looking forward to receiving your feedback! Can't wait to start our work on Polkadot integration into Citadel.one;)

**Review by Noc2 — APPROVED** [review]
Looks good, I will share it with the rest of the team.

**Review by laboon — APPROVED** [review]
I think this would be a great addition to the ecosystem.

**Review by Lederstrumpf — APPROVED** [review]
Looks good - this promises to be very useful :)

**Review by RouvenP — APPROVED** [review]

**Comment by alxs** [comment]
Hey @citadeldao. Could you give us a quick update on your progress on the grant, together with an ETA if possible? I realise there's no estimate as to the duration of the project in the application, but it has been 7 months with no updates from your side. Unless we hear something from you soon, we will terminate the grant due to inactivity.

**Comment by citadeldao** [comment]
Dear Aleixo! @alxs

Thank you for reaching out. We are moving forward on our Polkadot integration, and we are more than ready to provide you with a showcase version - almost every functionality is operating stably and is being tested. Our marketing team previously contacted Web3 marketing department (via email mentioned on the Grants page) about the announcement and, thus far, we thought that you are aware about our ongoing development process. Upon request, our team will be happy to jump on a call to show the progress to the Web3 Grants Committee. Let us know about the best ways we can submit an update on our development! 

Thank you! 
Best, 
Gregory
Co-founder & CTO at Citadel.one

**Comment by alxs** [comment]
Hi Gregory, very happy to hear that. The Grants PR email address is operated by a separate team and hence we weren't aware of you having reached out. Seeing as you already prepared an announcement, I assume you're close to submitting? As long as you're actively working on the project and the delivery is on your roadmap, there's no issue from our side. Feel free to submit directly via https://github.com/w3f/Grant-Milestone-Delivery once you're ready, and thanks for the update!

**Comment by semuelle** [comment]
Hey @citadeldao. Are you still working on this grant? According to the contract, you planned to submit by March.

**Comment by citadeldao** [comment]
@semuelle Hello, sorry for being late. Currently we have completed the integration, and testing all cases on development version. That's why we are late. At the next week we will show you the working version on our platform. 
Thanks!

**Comment by citadeldao** [comment]
@semuelle Hello Web3 Foundation Team! 
Could you please check our PR please?
https://github.com/citadeldao/Open-Grants-Program/pull/1

**Comment by alxs** [comment]
@citadeldao any updates? According to your amendment, you were planning to submit in May.

**Comment by citadeldao** [comment]
@alxs Hello! We've sent the PR with updated version of our milestones. Also we would like to show you how it works on the production version. Would be great to jump on a call so that you can check how polkadot was integrated by Citadel.One team.

https://github.com/w3f/Grant-Milestone-Delivery/pull/491

**Pull request merged**
