### PR TITLE
Zenlink: cross-chain dex

### PR DESCRIPTION
**Pull request by v-van**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new application and sorry for the late reply. What’s the difference of your current application/deliverables compared to your previous applications, especially the first grant which implemented a DEX pallet? Didn’t you plan to deliver a UI as part of your “third” milestone/grant?

**Comment by v-van** [comment]
Hey @Noc2 
In the past, we indeed delivered two implementations of the Zenlink DEX Protocol. However, they only worked on our own Substrate chains. Our final goal is to help parachain projects to implement the dex functionalities so that we need to deploy it and test it in a relative practice environment. The core parts are the followings:
1. Design a product process that is acceptable to all parties including parachain projects, users, etc.  It requires consideration of both project integration and user experience, as well as practical technical solutions.
2. Though the Rococo v1 hasn’t been completed, we still can work on the latest dev branch of Cumulus, even make some extensions to implement the whole product process.

For the UI part, the Zenlink DEX DApp,  actually, it’s in dev.  Based on some business considerations, we would not like to make it public at this staging, since we wanna deliver a perfect enough product to shock the world.

**Comment by Noc2** [comment]
Sorry again for the late reply and thanks for the additional comment. Could you provide a few more details on what exactly you are implementing as part of the grant? In general it might make sense to wait a little bit longer with this grant. For example see https://github.com/paritytech/xcm-format So, I’m not sure it makes sense that you work on your own Unified Asset ID at this stage.

**Comment by v-van** [comment]
Hey there,
We just found that there were some asset modules that can satisfy us.
I've modified the grant targets and deliverable description.

**Comment by Noc2** [comment]
Thanks for the update. Why do you want to implement a swap module? Also it is currently not part of the deliveries.

**Comment by v-van** [comment]
Actually, we do not intend to implement an additional swap module. Instead, we want to improve the one we built before.
The target is that, on Rococo v1, Zenlink DEX Module is imported to some parachains, and users can complete a cross-chain assets swap.
So we have to integrate the Zenlink DEX Module with some asset modules or even create a new one.

**Comment by Noc2** [comment]
Okay, understood. Could you integrate this (asset module as well as your description of the DEX Module) into the specification table under Milestone 1? Also could you update/reduce the BTC price?

**Comment by v-van** [comment]
Thanks for the feedback. The application has been updated.

**Review by mmagician — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the update. @v-van I think you need to resign the CLA. It was recently updated.

**Comment by v-van** [comment]
> Thanks for the update. @v-van I think you need to resign the CLA. It was recently updated.

Done. Thanks!

**Review by Noc2 — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Review by Lederstrumpf — APPROVED** [review]

**Comment by Lederstrumpf** [comment]
Nice application - looking forward!

**Review by RouvenP — APPROVED** [review]

**Comment by laboon** [comment]
Note that Rococo-v1 has been released ( https://polkadot.network/rococo-v1-a-holiday-gift-to-the-polkadot-community/ ) and parachain registry is opening 11 Jan. I'd recommend joining the Rococo channel on Matrix to keep up-to-date with that.

**Comment by semuelle** [comment]
@v-van, are you still working on this? Otherwise, we would terminate this agreement. You could reapply at a later point if you are still interested in implementing it down the road.

**Comment by alxs** [comment]
This grant is being terminated due to inactivity. As Sebastian said, feel free to apply again if you're still interested.

**Comment by alxs** [comment]
This grant is being terminated due to inactivity. As Sebastian said, feel free to apply again if you're still interested.

**Comment by v-van** [comment]
Hey @semuelle @alxs , actually we've implemented the features we mentioned in this application.
However, due to the fast development of Polkadot ecosystem, we didn't deploy Zenlink DEX to Rococo testnet. Instead, we are focusing on the integration of Kusama network.
For now, the whole features are live on our private testnet(as same as Kusama). We believe that Zenlink DEX DApp will be deployed to Kusama in few weeks.

For this application, we would like to change the deliverables or apply a new one.

**Comment by alxs** [comment]
@v-van happy to hear that. Apologies as this grant was terminated since the delivery was delayed and we hadn't heard from you in a while.

Nevertheless, you're always welcome to apply for another grant.

**Pull request merged**
