### PR TITLE
platdot

### PR DESCRIPTION
**Pull request by platdot**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. If I understand it correctly, you want to create a bridge between polkadot and your own chain. Could you tell me more about the technology of your own chain? Is it based on substrate? In this case you could simply leverage the sub <> sub bridge currently developed by parity. Also you can potentially easily leverage existing bridge projects like [chainbridge](https://github.com/ChainSafe/ChainBridge). Furthermore the price is currently above the 30k limit.

**Comment by platdot** [comment]
Hi @Noc2 
Thank you for your reply，We have added some details in #187. PlatON is not our own chain,
We just go to achieve the bridge between Platdot and PlatON.https://www.platon.network/pdf/en/PlatON_A_High-Efficiency_Trustless_Computing_Network_Whitepaper_EN.pdf?v0.6.6(This is a link to a platon white paper, you get the complete technical details about platon).

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for sharing. I wasn’t aware of the platon and alaya network. Did you already apply for a grant by the LatticeX foundation? In general there are already quite a few bridges under development, including: 

- https://github.com/ChainSafe/ChainBridge
- https://github.com/Snowfork/polkadot-ethereum 

From a quick look Platon seems to be simply based on go ethereum or geth. Therefore it should be fairly simple to reuse the above bridges (once they are finished). So I don’t think it's worth supporting the development of another bridge at this stage, unless there are some benefits of your bridge compared to the above implementations.

**Comment by platdot** [comment]
Thanks for your feedback.Glad to answer these questions.
1，we are communicating with the LatticeX foundation and they are very interested in it.
2，The following are the advantages of our bridge：
      (a):What chainBridge and polkadot-ethereum support is to cross eth to polkadot. What we want to do is to cross dot to platon. When we implement light client, we will cross lat to polkadot, and we can also cross dot to platon.
      (b):ChainBridge and polkadot-ethereum only supports solidity contracts, platon supports wasm contracts and solidity contracts, and our cross-chain will be compatible with platon's wasm contracts.
      (c):ChainBridge and Polkadot-ethereum do not have excellent UI, Platdot focuses on PlatON and Platdot, we will provide a user friendly interface.
      (d):The focus of platon is to do MPC-related work. We hope to combine the features of MPC's security and privacy to achieve some functions.
      (e):polkadot-ethereum needs a running parachain, we want to directly use the multi-signature module on polkadot
      (f):,We will design a game mechanism between alliance members and encourage alliance members to jointly maintain 
           platdot. For users who use cross-chain services, a certain handling fee will be charged, 70% will be used to give the 
           alliance participating in multi-signature transactions an equal share, 30 % Is an incentive fund, used to motivate active 
           alliance members. It is settled every 24 hours. The alliance member who participates in the most transactions will receive 
           half of the incentive fund. The second alliance member will receive 25% of the incentive fund. The third alliance member 
           Members will receive 12.5% ​​of the fund, and the remaining fund will be divided equally among the members who did 
           not receive the reward.

**Comment by platdot** [comment]
> Thanks for sharing. I wasn’t aware of the platon and alaya network. Did you already apply for a grant by the LatticeX foundation? In general there are already quite a few bridges under development, including:
> 
> * https://github.com/ChainSafe/ChainBridge
> * https://github.com/Snowfork/polkadot-ethereum
> 
> From a quick look Platon seems to be simply based on go ethereum or geth. Therefore it should be fairly simple to reuse the above bridges (once they are finished). So I don’t think it's worth supporting the development of another bridge at this stage, unless there are some benefits of your bridge compared to the above implementations.

Thanks for your feedback.Glad to answer these questions.
1，we are communicating with the LatticeX foundation and they are very interested in it.
2，The following are the advantages of our bridge：
(a):What chainBridge and Polkadot-ethereum support is to cross eth to Polkadot. What we want to do is to cross dot to PlatON. When we implement light client, we will cross lat to Polkadot, and we can also cross dot to PlatON.
(b):ChainBridge and Polkadot-ethereum only supports solidity contracts, PlatON supports wasm contracts and solidity contracts, and our cross-chain will be compatible with PlatON's wasm contracts.
(c):ChainBridge and Polkadot-ethereum do not have excellent UI, Platdot focuses on PlatON and Platdot, we will provide a user friendly interface.
(d):The focus of PlatON is to do MPC-related work. We hope to combine the features of MPC's security and privacy to achieve some functions.
(e):Polkadot-ethereum needs a running parachain, we want to directly use the multi-signature module on Polkadot
(f):We will design a game mechanism between alliance members and encourage alliance members to jointly maintain
Platdot. For users who use cross-chain services, a certain handling fee will be charged, 70% will be used to give the
alliance participating in multi-signature transactions an equal share, 30 % Is an incentive fund, used to motivate active
alliance members. It is settled every 24 hours. The alliance member who participates in the most transactions will receive
half of the incentive fund. The second alliance member will receive 25% of the incentive fund. The third alliance member
Members will receive 12.5% ​​of the fund, and the remaining fund will be divided equally among the members who did
not receive the reward.

**Comment by Noc2** [comment]
Thanks for the reply. Could you integrate this information into the deliverables (e.g. specify the user interface and smart contract part)? We generally want to have as many technical details as possible in the deliverables, since these are the “requirements” of the contract. Also something to be aware of is that when it comes to bridges the grants committee usually focuses on trust minimizing solutions and the most important network at this stage. So, I’m not sure if we would support this bridge at the moment. This might change in the coming months, once the development at the other bridges is finished and they are actually ready and can be used for other projects.

**Comment by platdot** [comment]
Thank you for your time, Documentation has been updated.

**Comment by Noc2** [comment]
Thanks. I will share the application with the rest of the team.

**Comment by Noc2** [comment]
Thanks again for the grant application and all the effort you put into this. It seems the rest of the committee is also not willing to support your application at this stage. The main reason is that we already supported a number of bridges and want to see these implemented first. Also a bridge to PlatON is currently not interesting for us. Therefore I’m closing the application. Feel free to apply again for a different project.

**Pull request closed without merging**
