### PR TITLE
Added game-economy.md

### PR DESCRIPTION
**Pull request by Daelon02**
# Grant Application Checklist

- [x] The [game-economy.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/game-economy.md) has been copied, renamed ( "game-economy.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully delivered the first milestone.

### CODE REVIEW

**Comment by semuelle** [comment]
Hi Nikita, thanks for the application. We will look into it next week. In the meantime, could you sign the CLA, please?

Also, we have a number of grantees currently working on gaming-related projects. Feel free to have a look and make sure your application is sufficiently separate from any of them.

#134 #73 #46

**Comment by Daelon02** [comment]
> Hi Nikita, thanks for the application. We will look into it next week. In the meantime, could you sign the CLA, please?
> 
> Also, we have a number of grantees currently working on gaming-related projects. Feel free to have a look and make sure your application is sufficiently separate from any of them.
> 
> #134 #73 #46 

Thank you, we will consider other projects, we will wait for your answer and decision

**Comment by Daelon02** [comment]
> 
> 
> Hi Nikita, thanks for the application. We will look into it next week. In the meantime, could you sign the CLA, please?
> 
> Also, we have a number of grantees currently working on gaming-related projects. Feel free to have a look and make sure your application is sufficiently separate from any of them.
> 
> #134 #73 #46

I sign the CLA

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Could you compare your solution to other existing solutions and applications? Do you already have a demo of Ring of Legends? Why do you want to develop a separate NFT module and don’t use one of the existing solutions? Milestone 2 and 3 are already covered by other teams, see [snowfork](https://github.com/Snowfork/polkadot-ethereum) or [chainbridge](https://github.com/ChainSafe/ChainBridge), so I suggest to remove them. In general, point out what’s unique about your solutions. Currently a lot of the things you listed already exist in one way or another, see the [Polkadot Stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md).

**Comment by Daelon02** [comment]
> 
> 
> Thanks for the application. Could you compare your solution to other existing solutions and applications? Do you already have a demo of Ring of Legends? Why do you want to develop a separate NFT module and don’t use one of the existing solutions? Milestone 2 and 3 are already covered by other teams, see [snowfork](https://github.com/Snowfork/polkadot-ethereum) or [chainbridge](https://github.com/ChainSafe/ChainBridge), so I suggest to remove them. In general point our what’s unique about your solutions. Currently a lot of the things you listed already exist in one way or another, see the [Polkadot Stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md).

Good day! Thanks for the questions.

Among such existing solutions are:
1. alienworlds.io
2. guildofguardians.com
3. illuvium.io
4. myneighboralice.com

Among which are not in development only Alien Worlds. All of them are not related to the Polkadot and Kusama ecosystem.
We believe that our Ring of Legends project is more ambitious.
We also have a demo of the game - play.google.com/store/apps/details?id=com.crypto.battle.royal.cyber.arena
The game will have many changes regarding the visual style and gameplay mechanics.

Our NFT consists not only of hash and id, it also has the characteristics of items as in other online games: League of Legends, DOTA 2 and etc.
A more detailed diagram of our NFTs is attached below.

github.com/Daelon02/realis/blob/main/Screenshot_1.png

We create our own blockchain solution based on a substrate to create a universal logic for introducing the NFT economy into any game.

After the launch of the blockchain on the mainnet, we will transfer 2 of our games (and all subsequent ones) to Realis Blockchain using NFT and tokenized game currency.

1. Merge Cats - play.google.com/store/apps/details?id=com.soul.merge.cat.cute.simulator.adventure
2. Match Dragons - play.google.com/store/apps/details?id=com.dragons.tokens.crypto

After that, we will continue to develop a more global and complex MOBA Ring of Legends using our token and redesigned NFT logic, with functions:

1. Collectibles;
2. Merging;
3. Creation;
4. Burning;
5. NFT staking.

These features will affect the gameplay of our games. We decided to use this solution for NFT as it is clearer and easier to develop.

Our uniqueness lies in the fact that we develop a competitive MOBA game. Our project is the most ambitious among peers.
There is already a wrapper pallet for the API. This will make it easier to interact with the functionality. All basic NFT functions (mint, recording, transfer) will be used in the game. Through the API, we will make requests to create NFT, craft NFT, transfer from one wallet to another, as well as requests to obtain the user's balance, and receive the number of NFT tokens on the account

**Comment by Daelon02** [comment]
> 
> 
> Thanks for the quick reply. So you are the https://cryptosoul.io/ team, correct? And the following is your nft implementation: https://github.com/cryptosoulgame/ReAlis-Network/tree/main/frame/nft, correct? Could you point out why you didn’t use any of the of the existing nft implementation (like [1](https://github.com/open-web3-stack/open-runtime-module-library/tree/master/nft), [2](https://github.com/usetech-llc/nft_pallet_v1/blob/master/pallets/nft/src/lib.rs), [3](https://github.com/danforbes/pallet-nft))? There are a lot of benefits when it comes to interoperability or security, when you use an existing solution that is also used by other teams and potentially even audited. Furthermore, I’m not sure we have an interest in funding another nft implementation at this stage. Also why did you increase the price for the other milestones after you removed milestone 2 and 3? In general you should also be aware that we “do not award grants for projects that have been the object of a successful token sale.”, see the guidelines in the readme. Could you clarify why your previous token sale doesn’t cover this project?

We have changed the cost. Incorrect numbers were entered by mistake. Please check again.

1. Yes, we are a team of a CryptoSoul studio for development of blockchain games. Realis is our new project for development mobile games with our own blockchain using token and NFT.

2. We have already written the NFT pallet for our requests based on the experience of other projects. We are not asking for funding for the development of NFT pallet.

Why didn't we use current NFT solutions?
We did not find a suitable solution for ourselves that would satisfy us 100 percent. Therefore, we made the implementation that seemed to us the most suitable and flexible.

Acala, Darwinia - not suitable as we have the following NFT requirements:

rarity, add characteristics
merge. 3 to 1 another rarity
staking
craft

3. We did not launch an ICO for CryptoSoul. We use our token for ingame sale and utility.

**Comment by Daelon02** [comment]
@Noc2 Please tell me what is the state of our proposal?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update and sorry for the late reply. To be honest, I still think it doesn’t make sense for us to fund another nft implementation (milestone 1). Regarding milestone 3 “develop marketplace” and 4 “ Connect Realis Network with Ring of Legends”, it currently doesn’t seem to contain any development. For example “We start test sell, buy, transfer and send NFT to blockchain” isn't something we can easily test. Generally the milestones should contain the “requirements” of the contract, which we can double-check as part of the milestone evaluation.

**Comment by semuelle** [comment]
I'm with @Noc2 on this. Funding another NFT pallet doesn't make sense for the ecosystem and some of your deliverables are not well defined. The numbering is off as well:
 
```
0c. | Testing Guide | Start work and then testing Marketplace NFT.
4. | Realis chain | We start test sell, buy, transfer and send NFT to blockchain
```

**Comment by Daelon02** [comment]
> 
> 
> I'm with @Noc2 on this. Funding another NFT pallet doesn't make sense for the ecosystem and some of your deliverables are not well defined. The numbering is off as well:
>  
> 
> ```
> 0c. | Testing Guide | Start work and then testing Marketplace NFT.
> 4. | Realis chain | We start test sell, buy, transfer and send NFT to blockchain
> ```

We are not asking for nft-pallet funding, we have a ready-made nft solution, we are asking for funding to link games (not only ours) with a blockchain based on a substrate. Our project is more global than those that already exist. They offer simple casual games, we offer a full-fledged MOBA game with hardcore gameplay. We will provide all the necessary test cases for you to check. You will be able to test all the functionality.

**Comment by Noc2** [comment]
Thanks for the response. However, your milestones don’t reflect this and also still contain non-development work, which is almost impossible for us to evaluate.

**Comment by semuelle** [comment]
To add to David's comment, if you are "not asking for nft-pallet funding", then why is one of your deliverables `pallet-nft`? If you "have a ready-made nft solution", why is that deliverable described as `We start test sell, buy, transfer and send NFT to blockchain`? 

I think you have to make it much, much clearer what exactly you are asking funding for. Since the grant is part of a larger piece of work, please do _not_ put any work that you _don't_ ask for the Web3 Foundation to fund into any of the deliverable specifications. But feel free to keep information about what you have been / are / will be doing _outside the grant_ in the doc, just clearly separated.

**Comment by semuelle** [comment]
Closing due to inactivity. Feel free to continue the conversation, the PR can be reopened when necessary.

**Pull request closed without merging**
