### PR TITLE
Substrate Mobile

### PR DESCRIPTION
**Pull request by wannam2049**
Add Zero-Hybrid-Network

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. It seems you are currently working for kylin network. Are you still working for them or is this a separate start-up? You can also send me more information about it to grants@web3.foundation in case you don’t want to share it publicly. Regarding the project: Could you provide more information about the “Adapt Layer”. Also I think there are already some initiatives to get substrate running on the M1 Mac Mini https://twitter.com/XiliangChen/status/1331129538265300999. Maybe it makes sense to initially focus on this.

**Comment by wannam2049** [comment]
> Thanks for the application. It seems you are currently working for kylin network. Are you still working for them or is this a separate start-up? You can also send me more information about it to [grants@web3.foundation](mailto:grants@web3.foundation) in case you don’t want to share it publicly. Regarding the project: Could you provide more information about the “Adapt Layer”. Also I think there are already some initiatives to get substrate running on the M1 Mac Mini https://twitter.com/XiliangChen/status/1331129538265300999. Maybe it makes sense to initially focus on this.

Hi David, thanks for the quick response. It's a purely personal idea, nothing related to others yet. To run on M1 Mac is just run Substrate with the ARM chip, but not mobile devices. Port Rust for M1 Mac will let Substrate running well. For mobile phone, users are only able to install applications/services which are based on Android/iOS rather than a Rust application. This grant application is aimed to provide an adapt layer using JNI based on Android NDK, it's dedicated to mobile phones. There will be more development works on Android application/services, and need some modification of Substrate to interact with JNI methods to call Android OS system API.  The work of Xiliang Chen is for mac, and this grant application is for mobile phones.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Got it. Could you still integrate more technical details regarding the adapter layer and the Java Native Interface into the application? Also more information about the reason behind the project would be helpful. What is the zerohybrid.network?

**Comment by wannam2049** [comment]
> Got it. Could you still integrate more technical details regarding the adapter layer and the Java Native Interface into the application? Also more information about the reason behind the project would be helpful. What is the zerohybrid.network?

Sure, I will update the application with more tech details.  zerohybrid.network is a new idea of blockchain on mobile phones, this application could be the cornerstone of it. Thank you!

**Comment by wannam2049** [comment]
@Noc2 Hi David, more information added. Please help to review the application. Thank you in advance.

**Comment by Noc2** [comment]
Thanks for the update and sorry for the late reply. Your USD numbers seem to have an additional zero at the end (“20000.000”). What are the exact features/pallets that will be supported by this adapter layer. For example Aura, Balances and/or Timestamp or do you immediately plan to support everything?

**Comment by wannam2049** [comment]
> Thanks for the update and sorry for the late reply. Your USD numbers seem to have an additional zero at the end (“20000.000”). What are the exact features/pallets that will be supported by this adapter layer. For example Aura, Balances and/or Timestamp or do you immediately plan to support everything?

Hi, David, the extra zeros are removed. 

The adapter layer is for those features which should be ported to Android OS. Within Android OS, file, networking, and threading are not the same as on desktop, they are different and only Java interfaces provided by Android OS. So the adapter layer will port those incompatible APIs such as files, network, threading, and so on related API / system-call to Android OS API / system-call. And all of these are based on the idea of this project [https://github.com/rust-windowing/android-ndk-rs](https://github.com/rust-windowing/android-ndk-rs).  This (file)[https://github.com/rust-windowing/android-ndk-rs/blob/master/ndk-sys/src/ffi_arm.rs] shows the ffi examples for Rust. And the Substrate codebase will be changed to adapt to Android OS with porting of libp2p and other libs which use the file/network/threading APIs/System-calls. The whole thing helps to porting is called the adapter layer.

**Comment by wannam2049** [comment]
> > Thanks for the update and sorry for the late reply. Your USD numbers seem to have an additional zero at the end (“20000.000”). What are the exact features/pallets that will be supported by this adapter layer. For example Aura, Balances and/or Timestamp or do you immediately plan to support everything?
> 
> Hi, David, the extra zeros are removed.
> 
> The adapter layer is for those features which should be ported to Android OS. Within Android OS, file, networking, and threading are not the same as on desktop, they are different and only Java interfaces are provided by Android OS. So the adapter layer will port those incompatible APIs such as files, network, threading, and so on related API / system-call to Android OS API / system-call. And all of these are based on the idea of this project https://github.com/rust-windowing/android-ndk-rs. This (file)[https://github.com/rust-windowing/android-ndk-rs/blob/master/ndk-sys/src/ffi_arm.rs] shows the ffi examples for Rust. And the Substrate codebase will be changed to adapt to Android OS with porting of libp2p and other libs which use the file/network/threading APIs/System-calls. The whole thing that helps to port Substrate on Android is so-called the adapter layer as part of the application.


By the way, it not pallet or feature. It's another version of Substrate, we can call it Substrate Mobile.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply. So you won’t support any pallets as part of this grant, but only the basic features of substrate itself, correct? Could specify this more concretely? I still think it makes sense to support at least one or two pallets in order to be able to test the functionality.  Also you should take a look at [smoldot](https://github.com/paritytech/smoldot). In case you haven’t already.

**Comment by wannam2049** [comment]
> Sorry for the late reply. So you won’t support any pallets as part of this grant, but only the basic features of substrate itself, correct? Could specify this more concretely? I still think it makes sense to support at least one or two pallets in order to be able to test the functionality. Also you should take a look at [smoldot](https://github.com/paritytech/smoldot). In case you haven’t already.

Ah, got it! Good suggestion, I never thought about including some pallets for testing purposes.  How do you think of using [node-template](https://github.com/substrate-developer-hub/substrate-node-template) as the test case?

**Comment by wannam2049** [comment]
> > Sorry for the late reply. So you won’t support any pallets as part of this grant, but only the basic features of substrate itself, correct? Could specify this more concretely? I still think it makes sense to support at least one or two pallets in order to be able to test the functionality. Also you should take a look at [smoldot](https://github.com/paritytech/smoldot). In case you haven’t already.
> 
> Ah, got it! Good suggestion, I never thought about including some pallets for testing purposes. How do you think of using [node-template](https://github.com/substrate-developer-hub/substrate-node-template) as the test case?

Hi @Noc2 , sorry to bother you, could you help to continue the review?

**Comment by Noc2** [comment]
Sorry for the late reply. The node template pallet is only a template and doesn't really help with testing. Or do you mean you will support all the pallets imported as dependencies as part of the substrate-node-template repo, like [sc-consensus-babe](https://crates.io/crates/sc-consensus-babe), [sc-finality-grandpa](https://crates.io/crates/sc-finality-grandpa), etc. ?

**Comment by wannam2049** [comment]
> Sorry for the late reply. The node template pallet is only a template and doesn't really help with testing. Or do you mean you will support all the pallets imported as dependencies as part of the substrate-node-template repo, like [sc-consensus-babe](https://crates.io/crates/sc-consensus-babe), [sc-finality-grandpa](https://crates.io/crates/sc-finality-grandpa), etc. ?

Hi @Noc2 , yes, exactly, that's what I mean. The node template will include the basic pallets needed for a simple but usable chain.

**Comment by alxs** [comment]
How large is your team? Would you care to disclose their names and GitHub repos and could you show some prior work?

**Comment by wannam2049** [comment]
> How large is your team? Would you care to disclose their names and GitHub repos and could you show some prior work?

Thanks for your concern. Currently, the team has only one guy, it's me. It's my personal side project to port Substrate on Android / iOS. I used to be a dapp developer and worked as a contractor to develop another Substrate-based project before.

**Comment by alxs** [comment]
Thanks. To be honest, for a one-man-project of this scope I'd rather it be someone _very_ experienced with specific strong past projects to show. Besides, the application still lacks significant technical details.

**Comment by alxs** [comment]
Since your application has been open for a month and failed to raise interest from our side, we will now consider it final in its current state and will give it two more weeks to gather the necessary approval. If no 3 members of the committee approve it within this time, the pull request will be permanently closed. Thank you for your understanding.

**Comment by wannam2049** [comment]
> Since your application has been open for a month and failed to raise interest from our side, we will now consider it final in its current state and will give it two more weeks to gather the necessary approval. If no 3 members of the committee approve it within this time, the pull request will be permanently closed. Thank you for your understanding.

Thanks for the reply. 
First, let me find some teammates to work together on this project.
Second, more tech details will be added after I finish my job. 
We can discuss it in two weeks, and we will see at that time. Hope I can attract your interest. :D

**Comment by alxs** [comment]
I'm closing this for now as per my last comment. Feel free to reopen the application when the mentioned challenges have been addressed.

**Pull request closed without merging**
