### PR TITLE
Add ERC20 address to payment

### PR DESCRIPTION
**Pull request by kevingzhang**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by kevingzhang** [comment]
The original PR has a single BTC address. I've added an ERC 20 (DAI) address.

**Review by semuelle — APPROVED** [review]

**Comment by semuelle** [comment]
Hey Kevin, your comment says `DAI`, but the invoice says `USDT`. Which one would you like? BTC, of course, is also possible.

**Review by alxs — APPROVED** [review]
The invoice actually says `USTD` and invoices usually complains about these things :P So I think you'd need to fix this and I assume it'd make things easier if you just picked one. This is of course for invoice. The amendment looks fine.

**Comment by kevingzhang** [comment]
Sure. I will make a new update in one hour. I would remove the BTC, leave
USDT/DAI only. Is it ok?  Sorry for the confusion

**Review by mmagician — APPROVED** [review]

**Pull request merged**
