### PR TITLE
add BCANN grant request

### PR DESCRIPTION
**Pull request by weitaolee**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by semuelle** [comment]
Thank you for your submission, @weitaolee. We will look into it as soon as possible. 
In the meantime, could you add

- FTEs (see the application template) total and per milestone
- more details on the deliverables (tech stack, function headers, etc.)?

**Comment by semuelle** [comment]
Could you also expand on what you mean by `real internet domain name`? Those controlled by ICANN? How do you plan on managing/modifying those? Do you forward requests to ICANN for your users? I also don't see the point for NFTs here, perhaps you can explain why those are needed? Thanks!

**Comment by weitaolee** [comment]
I will change the request to show more information about it
> Thank you for your submission, @weitaolee. We will look into it as soon as possible.
> In the meantime, could you add
> 
> * FTEs (see the application template) total and per milestone
> * more details on the deliverables (tech stack, function headers, etc.)?

**Comment by weitaolee** [comment]
> Could you also expand on what you mean by `real internet domain name`? Those controlled by ICANN? How do you plan on managing/modifying those? Do you forward requests to ICANN for your users? I also don't see the point for NFTs here, perhaps you can explain why those are needed? Thanks!
Thanks for your feedback,I will change the request to explain it.

**Comment by weitaolee** [comment]
@semuelle I submitted my explanation, please feel free to ask any questions about BCANN.

**Comment by semuelle** [comment]
Thanks for the update.  

To be honest, I don't think it makes sense for the Web3 Foundation to support setting up a centralised DNS <> BCANN service/company, and the NFT functionality produces more risks than benefits. However, I will share the application with the rest of my colleagues.

**Comment by weitaolee** [comment]
@semuelle 
Thanks for your feedback . Perhaps some of the information is not clear enough, we are focused on providing decentralized domain name services and wallet address pointing services. Some centralized tools just simply provide a compatibility for traditional dns and are not our goal. I will update it later.

> Thanks for the update.
> 
> To be honest, I don't think it makes sense for the Web3 Foundation to support setting up a centralised DNS <> BCANN service/company, and the NFT functionality produces more risks than benefits. However, I will share the application with the rest of my colleagues.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Are you aware of the [Nicks Module](https://github.com/paritytech/substrate/tree/v3.0.0/frame/nicks), [Substrate Names](https://github.com/xaya/substrate-names) or [ENS on Substrate](https://github.com/hskang9/substrate-name-service)? Potentially you can reuse some of the existing implementations and focus more on the UI. Do you already have some initial designs/mockups or previous work, which you could share?

**Comment by weitaolee** [comment]
I have updated the application. @Noc2  Thanks for your feedback, we checked the Nicks Module, Substrate Names or ENS on Substrate, we are different from those items. Thanks for check the application again.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Do you have any mock-ups for milestone 2? Given that it’s quite expensive and design focused, it would be nice to have some initial designs. Also milestone 1 is rather expensive for a single substrate module. Could you potentially reduce the price?

**Comment by weitaolee** [comment]
Thanks for your feedback, I will update the application  later

> Thanks for the update. Do you have any mock-ups for milestone 2? Given that it’s quite expensive and design focused, it would be nice to have some initial designs. Also milestone 1 is rather expensive for a single substrate module. Could you potentially reduce the price?

**Comment by weitaolee** [comment]
I have updated the price. Thanks for check the application again.
[mock-ups for milestone 2](https://org.modao.cc/app/4447109c463ec3a36043cb54e1edd7fafcc01c2c?simulator_type=device&sticky)

**Review by Noc2 — DISMISSED** [review]
Looks good and thanks for reducing the price. Could you integrate the mock-up into the application? Independent of it, I’m happy to go ahead with it and will share the application with the rest of the team.

**Comment by weitaolee** [comment]
Thanks for your feedback , I have integrated the mock-up into the application. 
> Looks good and thanks for reducing the price. Could you integrate the mock-up into the application? Independent of it, I’m happy to go ahead with it and will share the application with the rest of the team.

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]
Looks fine, good luck with the project!

**Review by semuelle — APPROVED** [review]

**Comment by weitaolee** [comment]
Thank you very much .@mmagician @semuelle @Noc2  ，We will continue our work and deliver the milestone quickly
> Looks fine, good luck with the project!

**Comment by alxs** [comment]
Hey @witterlee! Care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery a bit over 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but please keep us in the loop. If we don't hear from you soon, we will assume you're no longer interested and terminate the agreement.

**Comment by witterlee** [comment]
Hi @alxs :
    Sorry for the delay in our progress, we are still working on the project, I will summarize the current progress and give a feedback later.

**Comment by witterlee** [comment]
The technical team is promoting the implementation of the project, and its main work is distributed in two parts: the docking and commissioning of various technical modules, and the preparation of protocols and specifications.

We are coding and implementing the sub protocol of bcan protocol. The progress is as follows:

Basic functions of domain name application, management and transfer (80%)

Development of standard parser (48%)

Traditional domain name compatibility and synchronization (50%)

Domain name validity mechanism (50%)

Unit test (30%)

Functional test cases (30%)

In terms of protocols and specifications, the formulation of domain name resolution protocol and protocol documentation are in progress.

It is about to complete the technical scheme design and technical documents of parallel chain, storage layer and protocol layer.

It is difficult to give an exact time point for the public application of bcan n, but according to the development arrangement of the project, the next milestone will appear later this year or earlier next year.

**Comment by alxs** [comment]
@witterlee please see my comment above - without an ETA or insight into your project, we'd still need to terminate the grant.

**Comment by witterlee** [comment]
I'm terribly sorry that we couldn’t be able to update the code because of the inner issue in our team recently. Can we continue to submit it on this grant if we can submit the code in the coming days, or we need to apply for a new grant? Please note that we hope to continue update our code with this grant and complete the previously planned things. Please do give us a chance so we can keep our grant.

**Comment by semuelle** [comment]
Hey @witterlee. We don't usually resurrect grants. I suggest you re-apply and include some form of explanation for the delays and how you are planning to prevent these in the future. You will probably also have to update the `Development Status` section of the application to account for what has been done since the first application, the team if there have been changes and possibly the list of deliverables.

**Pull request merged**
