### PR TITLE
Application: SpiderDAO

### PR DESCRIPTION
**Pull request by NathanSpider**
# Grant Application Checklist

- [X] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] A BTC address for the payment of the milestones is provided inside the application.  
- [X] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [X] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@SpiderDAO-1 Thanks for the application. I noticed that you listed Polkadot & Kusama as partners on your website. You are kindly asked to remove this, as no such partnership has been established. Your application will not be considered until then.

**Comment by SpiderDAO-1** [comment]
@mmagician Thanks for the feedback.  We did ask for permission to show these from Peter at parity which was agreed. To clear the air we are happy to remove them and apologies if we caused any upset here this was completely innocent.

**Comment by mmagician** [comment]
@SpiderDAO-1 Thank you for taking swift action and I'm sorry for any misunderstanding caused regarding the wording. Let me clarify here: If you get a grant, you can say that you are a **grant recipient**, but Polkadot and Kusama are decentralized protocols so you can’t “partner” with them.

**Review by mmagician — CHANGES_REQUESTED** [review]
@SpiderDAO-1 I have a few comments regarding the content of your application:

1. Is the software that would be running on the router open source? How do you guarantee that "one validated router equals one vote"? 

2. > Our routers do have a secured ROM which we can control securely for all units and that's where the essential data will be saved

What is the `essential data`? What do you mean by `control securely`? Are you using open source hardware, or else how do you support the claim that you have a `secured ROM`?

3. > We are going to balance the voting power by only allowing token holders to have one router regardless of how many tokens they hold

Could you elaborate on how you plan to do that? Anyone could just create another address and transfer tokens there, effectively creating another token holder account eligible to use another router.

4. After looking at your milestones, I am still not sure what deliverables I should expect at the end of your project. Could you please provide more technical specifications regarding the modules, e.g.:
`We will be choosing from the runtime pallet of substrate to build our parachain including communication to our hardware routers` -> this provides no information on what will be delivered and therefore, once you finish your grant, it will make its objective evaluation impossible.

**Comment by AnasSpider** [comment]
Thanks for your feedback @mmagician. Regarding your questions:
**1.** 
- Yes, we are going to offer open-source code through our GitHub for the Router and other modules.
- Yes, we can guarantee that 1 router = 1 vote this will be controlled and checked via on-chain and off-chain workers.
**2.** 
- We are going to use Uboot environment variables to set our essential data and the router holder can not change this data. If the end-users run a factory reset of the router the Values of the router other than the MAC Address are removed completely. Then the user would have to initialize the router again.
**3.** 
- Our routers will be connected to a database which assigns the wallet registered when setting up to the router unique id (A combination of encrypted wallet seed + router mac address + router serial number) and every request will include generated unique file md5-check to confirm it's being done through the router.
**4.**
**Milestones**
- Setup DAO framework on Kusama.
- Successfully connect DAO entities (individual voters) to Spider routers. This will include one use case to show the connection is established correctly.
- establish robust communication protocol between Routers and Onchain actions (e.g. pass on a vote form a verified wallet on a verified router as an on-chain vote).
- Prepare a router firmware for all customers with the new module to establish the connection with the DAO entities.
- Pass on a governance decision to move from Kusama towards substrate mainnet. Test vote. Real votes will be done through a bot on our discord server until the solution features are fully fledged.

Let us know if you got any other questions.

**Comment by mmagician** [comment]
@AnasSpider Thanks for taking the time to comment. I am not sure whether my questions were not clear enough or there is another reason, but I feel like your responses did not (in the most part) answer my questions. Let me be clearer then:

> Our routers will be connected to a database which assigns the wallet registered when setting up to the router unique id (A combination of encrypted wallet seed + router mac address + router serial number) and every request will include generated unique file SHA-512 checksum to confirm it's being done through the router.

As far as I can tell, there's still nothing preventing a user from registering a new wallet with a new router, right?

Q: What is the `essential data`? (You haven't really specified what it is)

Q: Are you using open source hardware, or else how do you support the claim that you have a secured ROM?

> Setup DAO framework on Kusama.

How do you plan to do that? Are you going to use runtime modules, or smart contracts?

> establish robust communication protocol

What is this protocol?

_Please keep in mind that the more details you provide, the more likely we are to positively review your application._

**Comment by AnasSpider** [comment]
@mmagician Thanks for your reply, Let me clarify more on your points, Please be assured that we here to help the open-source community as much as we can with our experience.
Going through your questions:

**1. As far as I can tell, there's still nothing preventing a user from registering a new wallet with a new router, right?**

- Yes that's right and it can happen but that will come at a heavy cost for adding more routers and also have to wait for a period of time deemed reasonable to the DAO. Users must have active transactions on the wallet before being able to vote to make sure bots and whales won't get access with ease.

- We will be keeping a log of every MAC Address and serial number for every router we add to our inventory, this we’ll be added to an on-chain ledger or on-chain database. This will help us to identify any clone or anyone trying to spoof/manipulate the hardware. 

- If the essential data mentioned below is not matched to the end-user and they try to spoof or manipulate access. There will be 3 warnings followed by a ban from taking a part in our governance model for a limited time(still to be decided). The ban time will be increased systematically based on the number of times this is identified until the customer is banned indefinitely if the infringement persistently continues.

- We will also be in constant contact with the growing SpiderDAO community and the open-source community for beneficial ideas on how to make the governorate safer and more resilient to whales-resistance. 

**2. Are you using open-source hardware, or else how do you support the claim that you have a secured ROM?**
- Yes as we want to be involved much more in the open-source community, We are going to be using the Uboot environment with its open-source code to save the essential data which would be listed in the next question.
- To go into more detail on that point, We will also be giving our community members the option to choose between Open Source wireless drivers and the closed source ones for them to choose so we can make sure we offer an OpenSource friendly solution.

**3. What is the essential data? (You haven't really specified what it is)**
The essential data is a combination of the following:
- encrypted wallet seed using aes-256-cbc encryption standard with an auto-generated passphrase saved as part of the essential data.
**PS: Please note the passphrase would only be local and will be independent to the requests sent by the router for the governorate operations.**
- Router Mac Address to avoid it being cloned.
- Router serial number which cannot be cloned as it's a part of the chipset code. 
- SHA-512 checksum for a temp file that is created with all the data above which is updated every time the router is rebooted with the timestamp.

**4. How do you plan to do that? Are you going to use runtime modules, or smart contracts?**
-  We are planning to build using smart contracts at the beginning but as we scale up to more transactions, We are most likely to move toward a shared solution so we can cut the costs and take charge of how our blockchain will operate.


**5. What is this protocol? - establish a robust communication protocol.** 
- We are planning to write a substrate faucet to communicate with our discord server for our customers to send the token needed for the vote, Initiate voting, pass on the vote for the voting process that would be operated through our discord server.

**Comment by mmagician** [comment]
@AnasSpider Thank you for a comprehensive response. Would you mind integrating the above comments directly into your application please?

**Comment by SpiderDAO-1** [comment]
@mmagician We have integrated the above comments into the application as requested this is visible on version 2.2. Thanks for the feedback.

**Comment by mmagician** [comment]
Thanks, I'll share your application with my team.

**Comment by mmagician** [comment]
Also, I think it only makes sense to evaluate your solution on the actual hardware. Therefore, in case the grant is approved, please be aware that you might need to send us the router to perform the evaluation on. The details of delivery can be finalised upon completion of your work.

**Comment by SpiderDAO-1** [comment]
@mmagician Thank you for the reply we are really looking forward to contributing to the Polkadot Ecosystem. We are happy to disburse routers for evaluation and we would happy to do that before completion of the milestones,  as we feel your feedback will be very valuable as we start completing our roadmap.

**Review by mmagician — DISMISSED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late response. I have a few questions/comments:

- Could you please reduce the price a little bit more? 
- Could you specify the technical implementation of the smart contracts? Are you planning to use ink!? Are you already working together with a team, that potentially will deploy a smart contract module as a parachain on kusama? 
- Could you integrate a medium article into the deliverables?

**Comment by AnasSpider** [comment]
@Noc2 Thanks for your reply. Regarding your questions:

**1- Could you please reduce the price a little bit more?**
- Sorted

**2- Could you specify the technical implementation of the smart contracts? Are you planning to use ink!? Are you already working together with a team, that potentially will deploy a smart contract module as a parachain on kusama?**
-  We will create smart contract modules that we will use for showing the voting process from our router.
- We are leaning towards using ink yes.
-  We are currently looking to deploy that ourselves.
    
**3- Could you integrate a medium article into the deliverables?**
- Sorted.

Let us know if you got any other questions.

**Comment by Noc2** [comment]
@AnasSpider Thanks for the update. Could integrate ink! into the deliverables as well as specify the programming language/framework for the following deliverable: “Discord Communication”? And feel free to remove “on Kusama for this milestone”, since this is something we can not really enforce/ensure.

**Comment by AnasSpider** [comment]
Thanks for your reply. All requested changes have been added.

Please let us know if you got any other questions.

**Review by Noc2 — APPROVED** [review]
Looks good to me. Thanks for the changes.

**Review by mmagician — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Pull request merged**
