### PR TITLE
Adapt the workflow for DAI

### PR DESCRIPTION
**Pull request by mmagician**
Adapting the GitHub workflow to parse DAI, plus the following improvements:
- Use newer version of [file parser](https://github.com/mmagician/read-file-action), which now supports DAI and is case-insensitive (BTC, DAI, btc & dai will all work)
- Adapted the workflow for easier local testing
- Added a README with instructions for local testing
- Added env files for local testing

TODO: Adapt the google sheet
- Add an extra column for DAI
- Adjust the cost calculator to include DAI

### CODE REVIEW

**Comment by Noc2** [comment]
Do you also want to merge the workflow_testing.md? Also you need to sign the new CLA ;-)

**Comment by mmagician** [comment]
@Noc2 Yes, I would like to keep the `workflow_testing.md` file, this allows anyone to test the workflow locally.

**Comment by mmagician** [comment]
We can also rename it to `.workflow_testing.md` if that's better?

**Comment by Noc2** [comment]
Whatever you prefer. Feel free to merge it whenever you think it’s ready.

**Pull request merged**
