### PR TITLE
Phragmen wasm

### PR DESCRIPTION
**Pull request by derfredy**
# Grant Application Checklist

- [X] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] A BTC address for the payment of the milestones is provided inside the application.  
- [X] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [X] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for sharing the draft. It would be nice if you could add some tests to it as well as documentation for each milestone (see the [Milestone Deliverables Guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/milestone-deliverables-guidelines.md) of the general grants program). And maybe add one or two sentences to each milestone to explain it a little bit more concrete. Additionally, our finance team might ask you to provide an estimated [FTE](https://en.wikipedia.org/wiki/Full-time_equivalent) for the project.

**Comment by kianenigma** [comment]
I have major concerns about this approach and proposal overall. 

1. Offline phragmen is merely a playground like tool and indeed I never intended to see it is an external tool. For now, it is handy and provides json output in case some tools need urgent access to Phragmen results off chain. So, best not to even compare it here. Even once there exists some implementation of Phragmen in wasm, I intend to maintain it with low priority since it allows me to debug a lot of untested features. 

2. This proposal needs to specify which algorithm(s) it will implement. seq-phragen is what the name is implying, yet I must confirm that we are currently far-away from seq-phragmen. What you see on Kusama, is the output of this pipeline: `seq-phragme -> balacing(equalize) -> reduce -> compact -> uncompact` 

(note that we lose accuracy in the compacting part, hence to get the _exact_ same output, you need to take it into account). 

So if this proposal achieves implementing seq-phragmen, I am worried that you will realize that many tools cannot reliably depend on it, because it will output a different result. 

2.1 We are moving even further away from phragmen. web3 foundation research team recently released a new paper about this which I will link below. 

3. The current crate that contains all the phragmen related code in Substrate is already embedded in the runtime, is `no_std` and hence it is in principle possible to compile it directly from rust to wasm. I have not tried this but I think before making an attempt at writing another version of the same code, effort should be put at this. 

With all that being said, 

1. I indeed still see some merit in having different implementations of phragmen. But if the target is wasm, trying to cross-compile rust version to wasm is a lot more sensible. 
2. Even if the output of the chain is not reproducible, such implementations are still worthy for rough prediction and estimations. 

So all in all, I don't think the proposal is sensible as it is, but I don't want to discard it altogether either and be to negative. It needs better planning and re-thinking about what we want to achieve, and better understanding of the current state of phragmen and everything related.  I would be happy to discuss it further offline. 

--- 

Related links: 

- https://research.web3.foundation/en/latest/polkadot/NPoS/
- The Phragmen replacement by Web3: https://github.com/w3f/research-internal/blob/master/papers/NPoS_validator_selection.pdf 
- Current phragmen pipeline (subject to change based on the above) https://www.crowdcast.io/e/sub0-online/7

**Comment by Noc2** [comment]
The team informed me that for now they won’t continue to work on the application.

**Comment by retotrinkler** [comment]
I'd see value in this - even if it's a moving target with the actual validator selection algorithm as long as its primarily a wrapper it should be versatile enough - and the way I read the situation they would likely maintain it if they use it on their site.

I would ask the team to reconsider - I would approve this grant.

**Comment by kianenigma** [comment]
> as long as its primarily a wrapper around substrate pallet it should be versatile enough

Indeed, this is much more maintainable and reasonable.

**Pull request closed without merging**
