### PR TITLE
Add project Donut Blockchain

### PR DESCRIPTION
**Pull request by tolak**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the application @tolak. We will look into it as soon as possible. Could you please sign the terms and conditions?

**Comment by tolak** [comment]
@alxs Thanks, already signed!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few questions/comments: 

- First of all the github repos seems to not exist or be private, e.g.  https://github.com/nutbox-dao/donut-chain or  https://github.com/nutbox-dao/donut-relayer 
- Second, I’m not sure we have an interest in funding a bridge to steem at this stage.  We currently mostly focus on bridges to the bigger ecosystem (ethereum, btc). 
- I guess we have much bigger interest in having a team actually developing something similar to steemit on substrate and improving this based on the unique features of substrate. It looks a little bit like you are also working on this: “On Donut, the communities and parachains on Polkadot ecosystem can build their own incentive social media platforms and support community building and social interaction by providing community token rewards.” Is this correct? Maybe this would be better suited for a grant

**Comment by tolak** [comment]
@Noc2 Sorry for the late reply.

- _First of all the github repos seems to not exist or be private, e.g. https://github.com/nutbox-dao/donut-chain or https://github.com/nutbox-dao/donut-relayer_

  We set it opened now. And an online demo can be found [here](https://donut.nutbox.io) which implemented crosschain exchange between DNUT and STEEM.

- _Second, I’m not sure we have an interest in funding a bridge to steem at this stage. We currently mostly focus on bridges to the bigger ecosystem (ethereum, btc)._
- _I guess we have much bigger interest in having a team actually developing something similar to steemit on substrate and improving this based on the unique features of substrate. It looks a little bit like you are also working on this: “On Donut, the communities and parachains on Polkadot ecosystem can build their own incentive social media platforms and support community building and social interaction by providing community token rewards.” Is this correct? Maybe this would be better suited for a grant_

As the first generation of blockchain, Steem aims to builid an incentivized，blockchain-based，public content platform. has achieved a great success. There are hundreds of communities, and more than 500 Dapps, websites, tools on Steem.  However, rebuild Steem is a long time work, it's not just put social data to blockchain. Besides, we think social media is necessary for projects in Polkadot ecosystem, project especially who wants to join parachain auction can build their incentivized social media in steem through Donut bridge, that means they can distribute their reward to their users not just the parachain asset  but also the asset on Steem blockchain. Users can post twitter or blogs to support the projects.

As we said, Donut bridge just the first step we do to bring social media into polkadot ecosystem. The next step is to rebuild a NEW STEEM based substrate. Where projects in Polkadot ecosystem can not only build their own social media, but also can deploy social media Dapp like NFT on Donut blockchain.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply and thanks for making the repos public. I have a few additional comments/questions:

- Is it correct that you want to implement a steem light client as a substrate module for your bridge? This is something we might be interested in funding as part of the grant. Or does only the relayer validate transactions (“We will implement some import modules of Relayer, so far the relayer: 1) Support validate blocks and transactions”)? In this case the design of the bridge seems to be quite centralized or do I miss something here?. 
- We usually don’t support things like updating your substrate version or integrating an already existing pallet into your chain. The grants program mostly focuses on the development of new open source software that could potentially be used by others. 
- It seems you initially developed the relayer for tron. Is it already used in production? 
- I still think that building a “new steem” in polkadot would be more interesting from a grants perspective.

**Comment by tolak** [comment]
@Noc2 Thanks for your reply.

- Is it correct that you want to implement a steem light client as a substrate module for your bridge? This is something we might be interested in funding as part of the grant. Or does only the relayer validate transactions (“We will implement some import modules of Relayer, so far the relayer: 1) Support validate blocks and transactions”)? In this case the design of the bridge seems to be quite centralized or do I miss something here?.

It's good to answer this question case it's the most import part of our bridge. First we may not call it as a light client case they do just verify blocks and transactions, and yes it is substrate based. Second, it's not a centralized solution, because we would implement our blocks and transactions verification logic based substrate Offchain Worker, that means every validator would submit their validation result to runtime.

- We usually don’t support things like updating your substrate version or integrating an already existing pallet into your chain. The grants program mostly focuses on the development of new open source software that could potentially be used by others.

We think no one had implemented a Steem blockchain verification module based on substrate before, sure we are happy to have others people use it if they need.

- It seems you initially developed the relayer for tron. Is it already used in production?

We have developed a Steem-Tron Defi product last year called **Peanut** , it has no relationship with Donut, they are different, and focus on different things. Now that we are talking about Peanut, it's now the second largest delegation platform, so we are the team that know the Steem blockchain very well.

- I still think that building a “new steem” in polkadot would be more interesting from a grants perspective.

Yes we would build a new steem next step. Considering the funds we applied for this grant and the development cycle, we think build a steem bridge first is more good for things to move forward.

**Comment by Noc2** [comment]
Thanks for the update. Could you please update the deliverables? For example the following is still part of it: “1) Upgrade Donut chain from Substrate v2 to Substrate v3”. Also could you be more specific about your verification of steem on the substrate side. The offchain worker solution currently doesn’t seem to be part of it and I’m actually not sure I understand how it works? The current version you describe with your deliverables seems to be dependent on centralized relayer for the validation. (“relayer: 1) Support validate blocks and transactions”. And I still think that the committee would be more interested in a “new steem” than this bridge, but I will share the application with the rest of the team, once you have updated the deliverables.

**Comment by tolak** [comment]
@Noc2 Sorry for the late reply.

After the discussion with other team members, we finally decide to build a NEW Steem with substrate directly  as you suggested. We would update the entire proposal, that may take  a few days, we are sorry to have kept you waiting.

**Comment by Noc2** [comment]
No problem and that’s great to hear. I’m looking forward to see the updated application.

**Comment by Noc2** [comment]
I’m closing this for now. Let me know if I should reopen it.

**Comment by tolak** [comment]
@Noc2 Hi, i am so sorry haven't given you feedback for such a long time. But today i am very happy to told you that our team finally decide to buid a **New Steem** with substrate as you suggested.  We totally rewrite the proposal, you can see it [here](https://github.com/nutbox-dao/Open-Grants-Program/blob/master/applications/Nutbox_Blockchain.md). The latest commit looks like haven't been added to this PR automatically, maybe because the  PR was closed? Anyway i can reopen a PR if it still doesn't work when you reopen this PR.

It's really a long time that we don't have any feedback yet, sorry again. Actually, during this time, we are busy with buiding [Nutbox Slot Auction Platform](https://polkadot.nutbox.io), it's a decentralized parachain slot auction contribution platform that supports Polkadot and Kusuma network, where users can directly participate in crowdloan for various projects. At present, many popular projects in the Polkadot ecosystem have been listed. As your can see, every parachain and community can create their own contribution card to let their users contribute the projects. It's a gift for projects and community of Polkadot ecosystem, and also this is the vision Nutbox, to link the community to Web3.0.

**Comment by Noc2** [comment]
@tolak Thanks for the update. Sounds good. We recently restructured the whole grant repo, that’s why I’m unable to reopen the PR (“master branch was recreated”), therefore could you create a new PR. Thanks!

**Comment by tolak** [comment]
@Noc2 Thanks, and a new PR already created, see #535

**Pull request closed without merging**
