### PR TITLE
Maru

### PR DESCRIPTION
**Pull request by MaruEntertainment**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by semuelle** [comment]
Thanks for the application, @MaruEntertainment. We will look into it as soon as possible.

In the meantime, can you (and any other contributors to the document) sign the CLA, please?

**Comment by MaruEntertainment** [comment]
> Thanks for the application, @MaruEntertainment. We will look into it as soon as possible.
> 
> In the meantime, can you (and any other contributors to the document) sign the CLA, please?

happy to do it!

**Comment by mmagician** [comment]
Your application is completely missing a deliverables section. Please use the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) and fill in all the sections. I'm closing due to incompleteness, feel free to update it and then we can re-open the PR.

**Comment by MaruEntertainment** [comment]
@mmagician Thank you for your reminder, already add our deliverables section.

**Comment by mmagician** [comment]
@MaruEntertainment Your application contains absolutely no technical details. Furthermore, it seems like you haven't read the [README](https://github.com/w3f/Open-Grants-Program/blob/master/README.md) which clearly states that initial grants are only supported up to $30,000. We focus on the development of software, whereas your application contains deliverables like: "We will organize events to let more people know about this engine". 

Unfortunately, your application doesn't meet any of the criteria outlined in our [guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/README.md#guidelines) and will therefore will be closed indefinitely.

**Pull request closed without merging**
