### PR TITLE
Create JuniDB.md

### PR DESCRIPTION
**Pull request by MikeMS-sys**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @MikeMS-sys, thank you for your application! We will look into it as soon as possible.

On first sight I noticed that the total amount does not match the sum of the milestones. And, can you explain - on a high level - what the benefit of the hash data storage is? Would the hash be the IPFS address of the data?

**Comment by MikeMS-sys** [comment]
Hello @semuelle !

Hash data type is useful to organise data and to fast access for data collection with given key. With hash it's easy to represent object or structures data types. 

Our hashes is almost similar with Redis hashes and will stores ipfs hash of all hash table fields.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late response. Just for reference: Here is a link to your previous application: https://github.com/w3f/Open-Grants-Program/pull/399 
I have a few questions: 

- Are you planning to use the [substrate-front-end-template](https://github.com/substrate-developer-hub/substrate-front-end-template) for the Web application or are you going to develop your own UI? 
- Also are you planning to use offchain worker for this grant to actually run the DB? I think the deliveries are not fully clear on this? 
- How will the encryption module work? 
- Will your database be based on orbitDB and are you going to support various types of databases for different data models and use cases: https://github.com/orbitdb/orbit-db?

**Comment by MikeMS-sys** [comment]
Thank you and greetings @Noc2 , its ok, and really it is my pass to apologize for the long answers, there was a period of vacations and the introduction of a new Anti Covid measures.

We will update the application to fully cover the deliverables.

Answering the questions:
1. Yes, we plan to use substrate-front-end-template for the Web application.
2. Yes, we plan to use offchain worker to run the DB.
3. Encryption module allows user to automatically encrypt and decrypt data with account key.
4. We was brainstorming a lot whats is better to use either OrbitDB based implementation or build a new independent DB based on our requirements. We have decided to build our own solution.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. But I have two follow-up questions: What do you plan to use for the encryption module (e.g. algorithm) and what are the requirements of your database?

**Comment by MikeMS-sys** [comment]
@Noc2 

1. Update the application.
2. Juni::Db requirements - access to IPFS node

**Review by Noc2 — APPROVED** [review]
Regarding requirements, I was more referring to “ build a new independent DB based on our requirements“. Regardless, I’m happy to go ahead with the application and share it with the rest of the team.

**Review by gautamdhameja — APPROVED** [review]

**Comment by MikeMS-sys** [comment]
@Noc2 Perfect, thank you, looking forward for further steps.

By this _“ build a new independent DB based on our requirements“_ i have implied => Db key advantages:

Usability - just integrate and code
Security - built-in encryption
Scaling - ready for changes and big data

**Review by mmagician — APPROVED** [review]
I think it's great that you want to use the `offchain::ipfs` project. Have you tried it out yet to verify whether it is compatible with the current version of substrate? There [hasn't been any development happening there](https://github.com/rs-ipfs/substrate) since a couple of months and substrate has progressed substantially in the meantime.
In case you find that `offchain::ipfs` is outdated to the point of not being usable, I would still rather encourage taking it as a starting point and trying to bring it up to date, rather than building your own solution for interacting with ipfs from scratch. If you find the workload of fixing it to be too large, keep us posted and perhaps we can amend/extend the grant scope to cover it.

**Comment by semuelle** [comment]
Hi @MikeMS-sys, the main deliverable for M3 is a pallet, but if I understand your diagram correctly, decryption happens outside the node. Can you explain how this is achieved? Also, if the _en_cryption happens within the pallet, doesn't that mean that I am exposing my unencrypted data to validating nodes?

**Comment by MikeMS-sys** [comment]
Hello @mmagician!
Ok, I undestand. And much obliged to you for the advise.
We have started today with the 1st Milestone and soon update our prototype up to the latest version of Substrate.

**Comment by MikeMS-sys** [comment]
Hi @semuelle, 

Yes, decryption happens outside the node. We deliver front-end module that supports assymetric data decryption based on the user private key.

Аnd here you are right, data will be unencrypted and maybe it’s a good idea to move all the encryption stuff to the front-end module. It's pleasure to work with you.

We have earlier paid attention to the problem that you voiced and have planing to change the delivarables for the 3d Milestone.

**Comment by semuelle** [comment]
Thanks for the reply, @MikeMS-sys. Feel free to submit an amendment to the contract agreement. Just keep in mind that it requires approval from the committee, so if it _significantly_ deviates from the original, it needs to be justified.

**Comment by MikeMS-sys** [comment]
Hi, @semuelle, sure, i understood you. 
I discussed with my partners applied license GNU GPL v3. 
Does it possible to change it for MIT?

**Comment by semuelle** [comment]
I don't think the committee has ever objected to MIT license. I'd suggest you submit a new PR with the updated licenses in your application document. If anyone from the committee has questions about it, they can raise them there.

**Pull request merged**
