### PR TITLE
add Uniarts_Network grant request

### PR DESCRIPTION
**Pull request by tuminfei**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by tuminfei** [comment]
fixed CLA

**Comment by alxs** [comment]
Hey @tuminfei. Thanks for the application. The bot comment wasn't only referring to the CLA, but to the application in general. Currently the deliverables, which are one of the most important parts of an application, are very minimal. Other sections should be improved too. See the bot's comment for help.

Also if I'm not mistaken you have applied for a General Grant previously, please mention this in the application. Did you get to submit a treasury proposal in the end?

**Comment by tuminfei** [comment]
@alxs 
1.The product prototype design is added to the deliverable product description, which can be used as the basis for final verification.
2.We applied for the General Grant, and after communicating with the project staff, we did not continue to submit it. And it did not submit a treasury plan.
3.We have deleted the content of the website you mentioned

**Comment by alxs** [comment]
I'm closing this since [according to your website](https://uniarts.network/), you recently conducted a token sale for UniArts and the NFT SDK is advertised as a key feature of this project. Unfortunately, we do not awards grants in this case, as pointed out in our [guidelines](https://github.com/w3f/Open-Grants-Program#guidelines).

Apologies for having missed this earlier and thank you for your interest in the grants program.

**Pull request closed without merging**
