### PR TITLE
apply for a new open-grants

### PR DESCRIPTION
**Pull request by MartinBTM**
# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Just a reminder: You need to sign the cla assistant, before we consider your application.

**Comment by MartinBTM** [comment]
hi, now I have signed the cla assistant

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for signing the CLA. In general we would need to have more details about the way you implement the “cross chain gateway”. But I just noticed that you applied for bytom.io and you have your own grants program. So, you are probably not interested in the money aspect of our grants program. I therefore suggest that you send me an email instead at david@web3.foundation and we discuss potential other ways to collaborate.

**Comment by Noc2** [comment]
I’m closing the application for now, as discussed on our call yesterday.

**Pull request closed without merging**
