### PR TITLE
add guidelines for most popular categories

### PR DESCRIPTION
**Pull request by mmagician**
# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Looks good. In general we might want to reduce the amount of words at one point in all the readmes, because people are lazy and have the tendency not to read things (including myself) ;-)

**Review by laboon — APPROVED** [review]

**Review by Lederstrumpf — APPROVED** [review]
Looks good. I'd expect good teams to provide the bulk of category specific requirements intuitively, but nonetheless good to set clear expectations.

**Comment by Noc2** [comment]
@mmagician it seems the auto merge bot doesn’t work. So, I will merge it for now.

**Comment by Noc2** [comment]
@mmagician  Never mind it works, I just remembered that it needs to have the ready for review label.

**Pull request merged**
