### PR TITLE
Sharing Debt Pool

### PR DESCRIPTION
**Pull request by CraftingFinance**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Thank you for the application @CraftingFinance. Linking to your previous ones for reference #338 #342.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application and sorry for the late response. I have a few questions:

- Did you take a look at [laminar-chain](https://github.com/laminar-protocol/laminar-chain)? How is it different from your solution. 
- Could you provide more details about how your SDP contract and your DEX actually work? 
- Did you already conduct a token sale in order to finance this project? 
- Are you aware of the LevSwap application, https://github.com/w3f/Open-Grants-Program/pull/297? Your idea looks a little bit similar.

**Comment by semuelle** [comment]
Hi @CraftingFinance, I also have a few questions.

- What is the `SDP trading mode`?
- Could you add some more specification-type information to deliverables 1.1 and 2.1, such as a list of functions or functionalities that will be implemented?
- There is a lot of overlap of your application with the Coinversation [grant application](https://github.com/w3f/Open-Grants-Program/blob/master/applications/Coinversation.md) and whitepaper? Can you clarify your relationship with this team?
- Is there a codebase, whether it's your own or open source, that you are working off of? And does anyone in your team have experience with open source software development and maintenance?

**Comment by CraftingFinance** [comment]
@Noc2 

1. Our project is quite different from Laminar-chain. The biggest difference is that we use the SDP trading mode but they don’t. We think SDP is the core feature of synthetic assets, so there is no real synthetic asset without SDP. In fact, we think we are the only project with SDP on Polkadot currently. Other minor differences from Laminar include that we support forge all kinds of synthetic assets directly while they need to forge their stablecoin first, and we support all kinds of assets while they focus on gold and foreign exchanges. 

2. Sharing debt pool (SDP) is a trading mode invented by Synthetix. It does not need counterparty and solves the problem of trading depth and liquidity in DEX. Our DEX uses the SDP trading mode. The basic idea of SDP is that, when users forge synthetic assets, the system will give each user their own “fixed” debt ratio which is the ratio of the value of the user's synthetic assets to the value of all synthetic assets in the entire system. "Fixed" means this ratio will not change due to changes in asset prices, and will be used to calculate the user's profit and loss. This ratio will only change when a new user mints new assets or an existing user destroys existing assets. In the entire system, the value of the total debts will always be equal to the value of the total assets. We can get the value of each user’s assets through the amount of synthetic assets they have, and we can get the value of their debt just using their “fixed” debt ratio times the total debt of the system. By subtracting debt from assets, we can calculate the profit and loss of each user. 

3. Not yet. We previously planned to IDO at the end of June. But, as you know, the market crashed, so we postponed it and we want to wait until the market is more stable. 

4. The answer is similar to the first answer. We don’t think Levswap uses SDP which is the core feature of synthetic assets.

**Comment by CraftingFinance** [comment]
@semuelle 

1. Please see the second reply above.

2. We will update the specification-type information as soon as possible.

3. Actually, our project founders are also the co-founder of Coinversation. But we has already quit the Coinversation project because the partners of Coinversation have not fulfilled any initial promises. We have made a public statement before [(105#issuecomment-822124602)](https://github.com/w3f/Open-Grants-Program/pull/105#issuecomment-822124602), so now our project has nothing to do with Coinversation. And as far as we know, Coinversation does not use SDP trading mode any more after we quit the project and they change to AMM instead. So Crafting Finance is the only project using SDP on Polkadot currently.  

4. Our team is participating in the second Polkadot Hackathon competition. We will release the source code soon.

**Comment by CraftingFinance** [comment]
@semuelle

1. Please see the second reply above.

2. We have updated the information, please review.

3. Actually, our project founders are also the co-founder of Coinversation, but we has already quit the Coinversation project . We have made a public statement before (https://github.com/w3f/Open-Grants-Program/pull/105#issuecomment-822124602), so now our project has nothing to do with Coinversation. And as far as we know, Coinversation does not use SDP trading mode any more after we quit the project and they change to AMM instead. So Crafting Finance is the only project using SDP on Polkadot currently.

4. Our team is participating in the second Polkadot Hackathon competition. We will release the source code soon.

**Comment by semuelle** [comment]
Thanks for the follow-up, @CraftingFinance. I will share your application with the rest of the team.

**Comment by semuelle** [comment]
As you probably know, [we discourage submitting the same work at hackathons _and_ as a grant application](https://github.com/w3f/Open-Grants-Program#hackathons). Could you elaborate on which parts of your overall scheme and the part included in the grant application were already done as part of the Parity hackathon?

**Comment by alxs** [comment]
Hi @CraftingFinance. I personally won't support your application as

- I find it quite hard to understand it. About 60% of it consists of examples, yet there is no clear explanation of what "SDP trading" (which I think is a misnomer) is nor do you link to any technical documentation on it etc.
- You provide no verifiable experience for any of the team members. To some extent, we're open to anonymous applications if we're able to verify their experience, but your previous email to us merely contained a list of your team members as in your application and didn't allow us to do so in any way.
- I can't find any code produced by your team other than your submission to ParityAsia's hackathon from yesterday.
- Your whitepaper is an adaptation of Coinversation's one and contains numerous identical sections, as well as parts of the application as Sebastian mentioned. Even if your team were the original authors of Coinversation's whitepaper, I find this very questionable and indicative of bad practices. You also failed to disclose your relationship with said team despite this being clearly relevant to your application and having being [asked about it](https://github.com/w3f/Open-Grants-Program/pull/342#issuecomment-827892552) before.

Nevertheless, other members of the committee may be convinced. Good luck and thank you for your interest.

**Comment by alxs** [comment]
Hi @CraftingFinance. After some consideration, I personally still won't support your application as

- I have a hard time understanding it. About 60% of it consists of examples, yet I can't find a clear explanation of what "SDP trading" is nor do you link to any technical documentation on it etc.
- You provide no verifiable experience for any of the team members. To some extent, we're open to anonymous applications if we're able to verify their experience, but your previous email to us merely contained a list of your team members as in your application and didn't allow us to do so in any way.
- Your whitepaper is an adaptation of Coinversation's one and contains numerous identical sections, as well as parts of the application as Sebastian mentioned. Even if your team were the original authors of Coinversation's whitepaper, I find this very questionable and indicative of bad practices.

Nevertheless, other members of the committee may be convinced. Good luck and thank you for your continued interest.

**Comment by alxs** [comment]
Closing due to inactivity and seeing as there seems to be no interest from other members of the committee either. Thank you one more time.

**Pull request closed without merging**
