### PR TITLE
Open Grant Proposal

### PR DESCRIPTION
**Pull request by labsgroupdev**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
Your milestone 1 doesn't contain any deliverables which are not already part of the ecosystem. 
Similarly with M2, you are stating that you will create modules which already exist (e.g. the EVM module). We might potentially be interested in is the Raft module at some point. It's already been proposed by [another team](https://github.com/w3f/Open-Grants-Program/pull/219) but until certain developments are done in substrate, it's been put on hold.

**Comment by labsgroupdev** [comment]
We are using your substrate to power the security tokens and Defi staking and governance module in our system.  Are you looking for us to build something completely fresh tech wise. I think with us bringing an end to end real estate security token ecosystem along with our real estate focused securities exchange would be an add value to the polkadot ecosystem and its users.  We have already formed partnerships with centrifuge and Polkacover to do lending against our property tokens which would give users a secure physical asset to provide safety for their loans and working with Polkacover to insure liquidation.  We are very open to your suggestions on how we may be able to pass this polkadot grant successfully as we are already building on Polkadot.

**Comment by Noc2** [comment]
The Open Grants Program focuses on funding software development that doesn’t already exist in our ecosystem (and research efforts). So we don’t really look into grant applications from a “marketing/growth perspective”, but rather from a technical perspective. If you need to develop something unique as part of your project, that’s potentially useful for others, we would be interested in supporting it.

**Comment by labsgroupdev** [comment]
OK thanks David,

Understand

Pat

**Comment by Noc2** [comment]
Thanks for the quick response. I’m closing the application for now. Let me know if you want to reopen it.

**Pull request closed without merging**
