### PR TITLE
MediaBox for OpenGrant

### PR DESCRIPTION
**Pull request by cat4fire**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. Looks interesting. Could you delete example-project.md as part of your commit? Also it would be helpful to get more information for the different milestones. For example could you link to your existing solutions (MediaBox, the android version, etc.) and what features they offer or you want to integrate into substrate. Furthermore, are you interested in integrating this solutions potentially as a parachain or parathread? In this case, it might make sense to apply via the [general grants program](https://github.com/w3f/General-Grants-Program) at the moment, since we currently don’t payout DOTs via the open grants program.

**Comment by frankying91** [comment]
Hi David,
we are trying to make a workable build for the application, it will take a few days, since we are still developing the project. We estimate to finish it in the next week.
Do you think we should apply general grants program other than open grant? Thanks.

**Comment by Noc2** [comment]
Thanks for the update. As I said, if you want to receive or are willing to receive DOTs as part of your grant, you should apply via the general grants program for now and close this application. If not, we could proceed with it here, but I think it might make a lot of sense for your project to get part of the grant in DOTs.

**Comment by frankying91** [comment]
I added the link of the android app, you can find the new additional information of this test build at the bottom. We have a test account, it has tokens you can purchase music from marketplace. Or, you can create a new account to browse the features. We will send you a new account for musician, and the admin software for musician, then you will get the full process. 
Currently, we are ok for the OpenGrant, we can purchase DOTs once we are approved by your program. Should we continue to apply for OpenGrant?

**Comment by Noc2** [comment]
Closing this PR due to inactivity. Let me know if I should open it again.

**Pull request closed without merging**
