### PR TITLE
subwallet is a CLI wallet for Polkadot/Substrate

### PR DESCRIPTION
**Pull request by yxf**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi. Thanks for the application. Are you aware of subkey: https://github.com/paritytech/substrate/tree/master/bin/utils/subkey and the various typescript CLI tools here: https://github.com/polkadot-js/tools It would be nice if you could point out the difference of your solution and potentially leverage existing work. I think some of the grant teams also worked on CLI tools, which might be useful.

**Comment by yxf** [comment]
Hi Noc2,
subkey is a simple tool, If i did not write generated seeds and addresses on somewhere, it will gone. It is hard to manage your generated addresses, also are js tools. subwallet is not only a CLI tool, and also is **wallet** that can save generated addresses on local machine, track balances and transactions.

**Comment by Noc2** [comment]
Thanks for the update. I fully understand this. I just think that given that there is already existing work, it might be possible for you to use this work and therefore potentially reduce the price of this application or increase the scope of it.

**Comment by yxf** [comment]
> Thanks for the update. I fully understand this. I just think that given that there is already existing work, it might be possible for you to use this work and therefore potentially reduce the price of this application or increase the scope of it.

Thanks for you reply. I have reduced the price of this application.

**Comment by yxf** [comment]
Hi @Noc2  I want your response 😄.

**Comment by yxf** [comment]
> Thanks for reducing the price and the reminder. I have one last request. Could you add documentation and (unit-) tests to every milestone.
Hi @Noc2,
Updated. Please review it. Thank you.

**Comment by yxf** [comment]
Hi, @Noc2

**Comment by yxf** [comment]
@Noc2 @keorn @RouvenP  Thanks very much.

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grants.communications@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Pull request merged**
