### PR TITLE
Labs Updated

### PR DESCRIPTION
**Pull request by labsdev**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "Labs.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by labsgit — APPROVED** [review]

**Review by labsst — APPROVED** [review]

**Review by labsst — APPROVED** [review]

**Review by labsgit — APPROVED** [review]

**Review by ptang987 — APPROVED** [review]

**Review by ptang987 — APPROVED** [review]

**Review by ptang987 — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the grant application. One of the PR contributors still needs to sign the terms and conditions. And it doesn’t help if you approve your own PR. Furthermore the PR should contain only a single md file.

**Comment by labsgit** [comment]
We will fix this.  Actually we are having some issues with on of the
signers as the email account is tied to the username already but github is
saying it is not . Would it be OK if we remove this organization and use a
new one and re-upload it into a new repository for you?

Thanks

**Comment by Noc2** [comment]
Sure. Feel free to close this application and reapply with an update application which doesn’t contain the contribution from the github user.

**Comment by Noc2** [comment]
Closing since you opened #201

**Comment by ptang987** [comment]
Thanks David

**Pull request closed without merging**
