### PR TITLE
Submit grant application for Unmarshal

### PR DESCRIPTION
**Pull request by manohar-unmarshal**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
@manohar-unmarshal Thanks for your application. I was recently reviewing the delivery of the Aurras project, which also focuses on push notifications. It would be great if you could take a look at their [original application](https://github.com/w3f/Open-Grants-Program/pull/163) and try to point out how your solution compares to it and outline any potential advantages of your approach.

Furthermore, your milestone deliverables are lacking in technical details. For example, `Add module to decode the chain transactions` is unclear and ambiguous. 

Lastly, please provide a more specific description of what tech stack you're planning to use, architecture diagrams etc.

**Comment by manohar-unmarshal** [comment]
@mmagician I have updated the docs to include more details. Please have a look

**Comment by semuelle** [comment]
Hi @manohar-unmarshal, [there is a second account from which changes to the .md file were made](https://github.com/w3f/Open-Grants-Program/pull/262#issuecomment-779133677). This account needs to sign the CLA as well.

**Comment by manohar-unmarshal** [comment]
Done.

**Review by Noc2 — CHANGES_REQUESTED** [review]
The architecture diagram doesn’t load for me. Also it still would be helpful if you could add more technical details. For example, what exactly do you mean with module? Is this a substrate module/pallet?

**Comment by manohar-unmarshal** [comment]
Hi, I have added the Google docs link to the grant application. If Diagram doesn't load in markdown, you can view in google doc. By modules, we mean a subtask of the project. I have added more details regarding each milestone. 

Hope this helps

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update proposal. It would still be helpful if you could provide more details how your solution is different from [Web3 Guardian](https://github.com/open-web3-stack/guardian) and [Aurras Event Manager](https://github.com/HugoByte/aurras-event-manager). For example as far as I know Aurras also uses Apache Kafka. The document you shared seems to be for a solution for the Binance Smart Chain. Did you develop this and is it open source? Regarding polkaswap, we usually don’t support the integration into a specific solution via our grants program. What you can do is to use potentially existing open source code for an example integration. However, last time I checked, polkaswap wasn’t open source. And finally the demo app doesn’t seem to be part of the deliveries at the moment.

**Comment by mmagician** [comment]
Closing due to inactivity. Feel free to re-open the application with a more complete proposal.

**Pull request closed without merging**
