### PR TITLE
substrate identity directory

### PR DESCRIPTION
**Pull request by anamst**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks really cool. Could you also potentially integrate the deliveries 0a. to 0d. from the application template into the milestones: https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules I know it might not make sense to integrate unit tests for the UI.  Also would it be possible to reduce the price a little bit?

**Comment by Noc2** [comment]
Btw. could you ping me once I should take another look at the application?

**Review by Noc2 — DISMISSED** [review]
Thanks for at least reducing the price slightly. I’m happy to go ahead with it and will share the application with the rest of the team.

**Comment by Noc2** [comment]
Let me know once I should take another look at the application.

**Review by Noc2 — APPROVED** [review]

**Review by alxs — APPROVED** [review]
This is and looks cool. Happy to support it too. Will the identities be indexable by search engines?

At risk of coming off petty and since now would be the right time for this feedback, I have to say I dislike the name. Perhaps you can ask for ideas and run a quick survey with the community to see if a different one would be preferred if you care.

**Comment by anamst** [comment]
Thank you for the feedback. We think that the preferred solution for the community would be for identities not to be indexable by search engines. Since the app is SPA, it is by default not search engine friendly, which fits for our case. We will try to make sure our SEO strategy does not reveal identity information in search engines.
About the name, the one we are currently using is a placeholder and we were planning to change it into something more appealing.

**Review by gautamdhameja — APPROVED** [review]
LGTM! I like the idea and the concept.

**Comment by alxs** [comment]
@anamst care to share a quick status update on the project, together with an ETA if possible? It doesn't look like there's been much progress in the past two months https://github.com/Shard-Labs/id. If you're no longer interested, we can terminate the agreement.

**Comment by Jakic007** [comment]
Hi @alxs,

This is the active repository for identity directory app: https://github.com/Shard-Labs/identity-directory
You can see it live and running at https://identity.shardlabs.io 
It is almost done, we are just blocked with waiting for polkadot 0.9.4 release that will support state tracing for older blocks. We need that feature because we are using substrate-archive(https://github.com/paritytech/substrate-archive) to gather data about votes, governance and treasury for specific identities.

Feel free to give feedback for this part. When version 0.9.4 comes out, we just need to sync our nodes again and enable queries from the client app to the postgressql DB.

**Comment by alxs** [comment]
Looks good @Jakic007. It took a few tries until it displayed the identity for a given address, so I assume UI/UX aren't fully finished yet. But as long as you're working on it it's fine. You should submit an amendment if you can't deliver within the next month or so.

**Comment by Jakic007** [comment]
I assume that you were having problems displaying the identity because network was not selected on the dropdown menu on the left side?
We are going to display better message in that case so that users will know to select network first.
If you were having this issue with different flow, please describe it here so we can try to replicate and fix it. @alxs

**Comment by alxs** [comment]
Yes. It also doesn't work without running a different query first if the network is selected after trying once i.e.:

1. Search for identity with no network selected -> identity not found
2. Switch to Polkadot
3. Address is still in the search box, press enter -> nothing happens
4. Delete it or modify it, paste it again, press enter -> nothing happens
5. Search for something else -> works

**Comment by Jakic007** [comment]
@alxs Thanks for your feedback! It is already fixed and deployed.

**Comment by Jakic007** [comment]
We are still not able to gather the data about votes, governance and treasury for specific identities using substrate-archive since polkadot 0.9.7 does not support state tracing for older blocks.

We have seen that there are 3 issues addressing features that we need for this to work:

https://github.com/paritytech/substrate-archive/issues/97
https://github.com/paritytech/substrate-archive/issues/111
https://github.com/paritytech/substrate-archive/issues/132

I would like to propose that you review the current implementation, and we close this grant. When type decoding is implemented, we can do an extension to this grant to support new features.

**Comment by Noc2** [comment]
@Jakic007 Thanks for the update. If you want to close the current grant (get the milestone signed off and be paid for your work), you need to send us a milestone delivery, see https://github.com/w3f/Grant-Milestone-Delivery Let me know if you have any questions regarding this.

**Comment by Jakic007** [comment]
Hi @Noc2 ,
We did everything according to milestone delivery guidelines. Here are the PRs:

https://github.com/w3f/Grant-Milestone-Delivery/pull/229
https://github.com/w3f/Grant-Milestone-Delivery/pull/230

I can see that automated check fails because user "anamst" created this PR and I have opened these PRs for delivery. Ana is not working on this project anymore. I hope that is not an issue.

**Comment by mmagician** [comment]
I just checked whether your payment addresses from the application matches the one in the invoice, and since it does, it is fine that the PRs were submitted by different accounts. Thanks for the information 👍🏼

**Comment by Jakic007** [comment]
@Noc2 @alxs As agreed, we have removed parts from the figma design that are related to Treasury and Governance plugins.
Updated proposal is located here: https://github.com/Shard-Labs/Open-Grants-Program/blob/master/applications/substrate-identity-directory.md
Do we need to add this url somewhere else?

**Comment by alxs** [comment]
Hey @Jakic007. Yes, please create a PR to modify the existing application.

**Comment by MilGard91** [comment]
Hey @alxs this is new [PR](https://github.com/w3f/Grants-Program/pull/583) for this application.

**Comment by alxs** [comment]
@MilGard91 @Jakic007 care to share a quick status update on the last milestone? If you can't deliver it in the next ~2 weeks, we'd again need to amend the application.

**Comment by alxs** [comment]
@MilGard91 @Jakic007 do you still intend to submit the last milestone? Note that since you didn't submit an amendment, the [project repository](https://github.com/Shard-Labs/identity-hub) appears to be unmaintained since your last delivery and the [website](https://identityhub.xyz/) is down, we'll assume you're no longer interested and terminate the grant if we don't hear from you in the next 2 weeks.

**Pull request merged**
