### PR TITLE
Create cryptolab-staking-reward-collector-front-end.md

### PR DESCRIPTION
**Pull request by yktseng**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, your deliverables are simply a copy of the original deliverables of the following application: https://github.com/w3f/Open-Grants-Program/pull/429  and we actually had to refine these, because a lot of information were missing (https://github.com/w3f/Open-Grants-Program/pull/429, https://github.com/w3f/Open-Grants-Program/pull/435). Also in general how is your solution different from the previous solution. For example, we might be interested in funding another solution that doesn’t necessarily rely on subscan and has its own database.

**Comment by yktseng** [comment]
ah.. I thought I have to use the Staking Rewards Collector as the backend as requested? And it is the Staking Rewards Collector which relies on Subscan.

**Comment by yktseng** [comment]
@Noc2, by *we actually had to refine these, because a lot of information were missing* do you mean that we have to add the milestone 0a. to 0d. to the proposal because I thought the original was reasonable. Could you clarify it because we don't get what you mean actually.

Besides, what if we use our database as the data source (which means we don't use the Staking Rewards Collector as the backend) and make the output similar to the requested ones. One side effect is that to do it, we have to parse the chain data to find payout events from the first block, which could take a long time (in our experience, weeks). We have recorded payout events from about 4/1/2021. We can actually run our data collector to save the data before this date.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for updating the deliverables and integrating 0a. to 0d. However, I strongly recommend not just copying the other application, but rather to create your deliverables. For example, could you integrate the back-end into your deliverables. If we fund another solution for staking rewards, it should ideally be different from the first application and have it’s own unique features.

**Comment by yktseng** [comment]
We don't intend to make a new website with just one feature (show staking rewards) but to enhance our website (https://www.cryptolab.network/tools) by utilizing the staking rewards collector. So we don't think it just a copy of current application. The deliverable in this proposal only contains what we plan to do for this feature. There are a lot of things we are doing on the website, but they should not be included in this proposal right?

However, we can actually make it unique by using a different data source (our own database) rather than Staking Rewards Collector (subscan), if the committee accept it, I can modify the proposal.

**Comment by Noc2** [comment]
I know that you have your own website, but your milestone deliverables are currently just a copy of this application: https://github.com/w3f/Open-Grants-Program/blob/master/applications/staking-rewards-collector-front-end.md, which personally tells me that you haven’t put any effort into this application. It would be nice if you make this unique to your application. Creating your own database would also be more interesting for me personal instead of funding the exact same solution twice (apart from the layout of the UI). Obviously I don’t know what the rest of the committee thinks about this.

**Comment by yktseng** [comment]
I got your point, I thought I have to use the milestones as requested. I will modify it later

**Comment by Noc2** [comment]
@yktseng Thanks for the update. Are you still working on the application or should I take another look at it? Could you add more technical details to the deliverables (for example the programming language)?

**Comment by yktseng** [comment]
Yeah I added more detail on milestone days ago, I think you can have a look at it.

As for the programming language, the *cryptolab-backend* is a RUST service, we plan to call the *Staking Rewards Collector* from it

image

**Comment by Noc2** [comment]
Could you integrate this into the deliverables of the application?

**Comment by yktseng** [comment]
It actually is in the proposal. In the Project Detail part.

image

**Comment by yktseng** [comment]
Btw, must we provide the docker environment for the committee to test? Could we provide a test report directly on the living environment? Because in order to test it, you must start all the processes of CryptoLab, and most of them are not related to scope of this proposal.

**Comment by Noc2** [comment]
We usually test the docker environment as well as compiling everything directly from source. Btw. I will share the application with the rest of the team.

**Comment by yktseng** [comment]
I see, we could still provide a docker file to you. The source code are open sourced so compiling should not be an issue. We really appreciate the feedback from you. It actually my first time to submit such a proposal. We learned a lot from it.

**Comment by mmagician** [comment]
> The source code are open sourced so compiling should not be an issue

@yktseng So you do realise that in order for us to fund the project, you will have to provide us access to not only the frontend, but your **backend code + database setup**, so that the solution can be tested locally, end-to-end, upon delivery? I just want to double check that we're on the same page.

**Comment by yktseng** [comment]
Yes I understand

**Review by Noc2 — APPROVED** [review]
Okay. I’m also willing to support it. But I strongly recommend that you keep improving the UI. I think the current implementation is very basic and needs further improvements.

**Review by semuelle — APPROVED** [review]
No further questions from my side. Just out of curiosity: how do you test the browsers? Is that a structured, tool-based testing, or manual?

**Comment by yktseng** [comment]
> Okay. I’m also willing to support it. But I strongly recommend that you keep improving the UI. I think the current implementation is very basic and needs further improvements.

Yeah we actually found a UI/UX designer and a professional front-end develop and plan to improve it (in a Kusama Treasury Proposal not sent out yet)

**Comment by yktseng** [comment]
> No further questions from my side. Just out of curiosity: how do you test the browsers? Is that a structured, tool-based testing, or manual?

manually. We would test on Chrome, firefox, Edge, and for mobile, we would test Safari and Chrome

**Comment by Noc2** [comment]
> > No further questions from my side. Just out of curiosity: how do you test the browsers? Is that a structured, tool-based testing, or manual?
> 
> manually. We would test on Chrome, firefox, Edge, and for mobile, we would test Safari and Chrome

Just fyi: I previously used https://www.browserstack.com/ for manual testing and was usually pretty happy with it.

**Pull request merged**
