### PR TITLE
Open Source NFT Bridge Application

### PR DESCRIPTION
**Pull request by Nokhal**
# Grant Application Checklist

* [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
* [x] A BTC address for the payment of the milestones is provided inside the application.  
* [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
* [x] The total funding amount of the project is below CHF 30k at the time of submission.
* [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. However, your application should only include a single .md file instead of multiples. Also the limit for open grants applications is 30k USD. Additionally we pay teams only in BTC or DAI. Furthermore are you aware of https://github.com/Snowfork/polkadot-ethereum? How does your solution compare to this? And you should take a look at the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules). I’m closing this application, feel free to apply again with an updated application.

**Comment by Nokhal** [comment]
>However, your application should only include a single .md file instead of multiples.
Shall I make 10 pull request instead ?

>Also the limit for open grants applications is 30k USD.
We were advised to specifically segment it this way.

>Additionally we pay teams only in BTC or DAI.
With how volatile BTC is now and our cost being in GBP, we gave what it would cost us, not what we are asking as we are pretty agnostic here. Sure, we can include snapshot of BTC / DAI equivalent.

>https://github.com/Snowfork/polkadot-ethereum      
Yes

>How does your solution compare to this? 
We are provding a fully functional EVM <=> EVM bridge for NFT, not an EVM => Substrate bridge template for arbitrary data. 
If we are talking in term of OSI layers but with chains as endpoints, Snowfork is layer 3-4, we are 5-6-7

As mentioned in the application, the goal is to migrate NFT to NFT compatible platforms, more specifically here mainnet => moonbeam. We are not the moonbeam team, nor it is in the scope of moonbeam to integrate substrate functionalities that could already be provided at the smart contract level.

>And you should take a look at the template.
This template is a highly technical specification for a single piece of software with already predefined and agreed upon specifications. As specified in our application, the first step of our project is a round-table with people at every layer of the NFT space in order to write such specifications.

**Comment by Noc2** [comment]
Thanks for the quick reply. We only fund one grant per team, initially up to 30k via the open grants program, so you can not make 10 PRs. Additionally we require a team to have already a fairly concrete idea. We usually don’t fund things like specification or the initial design phase (including a round table) via grants.  Alternatively you can always apply for funding via the [treasuries](https://github.com/w3f/Open-Grants-Program#rocket-alternative-funding-sources).

**Comment by Nokhal** [comment]
The round table is more of a request for suggestions than an actual cooperative design. 
A standard is a specification. Any bridge protocol is by essence a specification, as you are gonna standardize a communication to transfer a state from a chain to the other. We want to get it rights as once again, interoperability with other implementations is a requirement. Then, we would implement that specification in the specific context of EVM <=> EVM/Substrate migrations.

We wanted to apply for the treasuries at first, but it was suggested to us to instead segment it in many lower grants.

**Comment by Noc2** [comment]
Thanks for the quick reply. I think it makes sense for us to schedule a call and clarify the project and the grants program. My email is david@web3.foundation. Also feel free to contact me via riot @david:web3.foundation

**Pull request closed without merging**
