### PR TITLE
Project Bodhi - Composable & Innovative Stack for EVM on Substrate 

### PR DESCRIPTION
**Pull request by bette7**
# Grant Application Checklist

- [X] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] A BTC address for the payment of the milestones is provided inside the application.  
- [X] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [X] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks good to me. Just one request: Could you change the price to BTC?

**Comment by bette7** [comment]
> Thanks for the application. Looks good to me. Just one request: Could you change the price to BTC?

Done.

**Comment by Noc2** [comment]
Hi @bette7 Could you also update the total cost? Additionally 2 BTC are currently above the 30k limit of the open grants program. Could you please reduce the price or only apply with the first milestone initially?

**Comment by bette7** [comment]
> BTC are currently above the 30k limit of the open grants program. Could you please reduce the price or only apply with the first milestone initially?

Done. Thanks.

**Review by Noc2 — APPROVED** [review]
Looks good.

**Review by laboon — APPROVED** [review]
I think this is a great idea and am looking forward to seeing the first milestone!

**Review by RouvenP — APPROVED** [review]

**Pull request merged**
