### PR TITLE
Web3 Compatible API Grant Application

### PR DESCRIPTION
**Pull request by dtyoo**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. This looks definitely interesting to me and I don’t have anything to add at the moment. I will share it internally also to get a better impression of the required work and the state of the Pallet-EVM.

**Comment by Noc2** [comment]
@dtyoo I tried to get a feeling for the required work. It seems your current estimate is on the upper end and your day rate seems to be relatively high. Could potentially reduce the price?

**Comment by dtyoo** [comment]
@Noc2 I updated the requested amount from 3 BTC to 2.5 BTC.

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grants.communications@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by dtyoo** [comment]
Thank you @Noc2 @gavofyork @retotrinkler 

We will follow up on announcement communications and when we have completed the work.

**Comment by Nittiyadc** [comment]
Where is Mr.Reto Trinkler?? Keep the word with your actions.  It's not good to say it because it makes other people lose their trust and deception every day.Thxx

**Comment by Noc2** [comment]
@Nittiyadc I deleted the comment, since it’s against our [code of conduct](https://github.com/w3f/Open-Grants-Program/blob/master/CODE_OF_CONDUCT.md) and not related to this grant.

**Pull request merged**
