### PR TITLE
Update XPredictMarket.md

### PR DESCRIPTION
**Pull request by XPredictMarket**
Update the grant document, remove part of the cross-chain content, and replace the oracle method used when uploading the results to the sudo method

### CODE REVIEW

**Comment by alxs** [comment]
Hey @XPredictMarket, sincere apologies for the long delay on getting back to you. I'm not sure I understand how what you're proposing would work. I.e. a sudo call can by definition only be made by a specific authority. But then you describe in your future plans that you intend to "develop a graphical operation interface for the common users to upload results through the sudo." Which doesn't sound sudo-like to me at all. Could you clarify?

**Comment by XPredictMarket** [comment]
> Hey @XPredictMarket, sincere apologies for the long delay on getting back to you. We're currently dealing with some significant changes.
> 
> I'm not sure I understand how what you're proposing would work. I.e. a sudo call can by definition only be made by a specific authority. But then you describe in your future plans that you intend to "develop a graphical operation interface for the common users to upload results through the sudo." Which doesn't sound sudo-like to me at all. Could you clarify?

Hi there, we made a mistake when correcting this part. In the future plan, a graphical interface will be developed for nodes to upload the results. Users can upload the results by staking our tokens to become a stake node.  The results confirmed by most of the nodes will become the final node. That is not through sudo.

**Comment by alxs** [comment]
Thank you for the changes. I'll share with the rest of the team.

**Review by alxs — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by mmagician** [comment]
@XPredictMarket While this is not directly related to the milestones, you have removed a paragraph from your `Future plans` section that stated your plan to become a parachain. Could you explain your reasoning behind that? What is now your preferred way to launch your platform, do you want to have a stand-alone chain?

**Comment by XPredictMarket** [comment]
> @XPredictMarket While this is not directly related to the milestones, you have removed a paragraph from your `Future plans` section that stated your plan to become a parachain. Could you explain your reasoning behind that? What is now your preferred way to launch your platform, do you want to have a stand-alone chain?

Hi there, we still intend to become a parachain. It's just that the cross-chain part is not implemented in the current milestone , so cross-chain related content is removed from the grant, but becoming a parachain and cross-chain implementation are still part of our key plans in the future. We want to have a  stand-alone chain and participate in the Kusama auction when we are well prepared.

**Review by mmagician — APPROVED** [review]
Alright, sounds like a plan. Good luck!

**Pull request merged**
