### PR TITLE
Jeton Network follow up grant

### PR DESCRIPTION
**Pull request by darkfriend77**
# Grant Application Checklist

- [X] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [X] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new application. I have a few questions:

- Regarding Schnorrkel, why do you want to reimplement it? Are you aware of the following implementations: https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#black_nib-signatures 
- Do you have plans for integrating state channels or something similar for scaling? It might take some time before we have second order relay chains.  
- Are you also planning to update the website http://www.jeton.network/ and promoting the use of this game engine together with substrate? 
- I personally would also be interested in supporting the “Connect four” milestone, but could you potentially reduce the price of the grant application a little bit. It currently seems quite expensive to me.

**Comment by darkfriend77** [comment]
Thank you for the questions. @Noc2

Answers:
- Schnorrkel solution, was removed from SubstrateNetApi. The "reimplementation" is targeting towards the integration into the SubstrateNetApi, as an alternative to the current Ed25519, I removed it here [LINK](https://github.com/dotmog/SubstrateNetApi/commit/ec305b3213499f7289ff05f36db614a074727fa8), because I was publishing Schnorrkel with a missing Licensing, I cleared things up with use-tech and got the okay to publish Schnorrkel as a NuGet package with the correct licensing and as a separate project, but I will have to reintegrate it into SubstrateNetApi, and write up the tests, back in the days it wasn't working so we only used Ed25519.
- We will create a transition solution so we can launch DOTMog on the Jeton Network and others in the first phase then move over into decoupling it into its own chain, if state channels build an additional benefit or help towards the final solution of a second-order relay chain, we will work on that.  But as for the Grant, it's the basic framework that allows creating a Generic Gaming Blockchain in minutes rather than weeks, not tight to the Jeton Network, open for anyone to fast create a game that profits from its own blockchain, own gas token, runtime upgrades, on-chain code, reusable pallets. Now we still face some big challenges for DOTMog, complex game engine code, hiding opponent's information that would affect gameplay, and so on, they need to be solved and created as reusable patterns to solve recurring problems.
- Yes, of course, the website http://www.jeton.network/ will be updated and will be including the information concerning the generic gaming blockchain and the project itself, I included it in the grant.
- Yes, it's my favorite milestone too, I will lower it to 6000$ hope that fits, if not please make a proposition that would fit. Consider that it has to be playable over a mobile phone, in multiplayer mode, so it showcases the use end-to-end.

Open-Grant Changes:
- added overview Jeton Network vision picture
- clarified Milestone 1, point 2,2a,2b,2c
- added Milestone 1, point 3a, recovery ability for unity mobile user trough SubstrateNetWallet
- added Milestone 7,7a, Jeton Network web appearance, for the Generic Gaming Blockchain.
- lowered price for (optional) Milestone 4 to 6000$.

**Comment by Noc2** [comment]
Thanks for the quick reply. Sounds good. Could you integrate the optional milestone into the grant (e.g. total costs) and simply remove the optional part. Regarding the costs, I was mostly referring to the entire project. Maybe could you also reduce the price of milestone 1-3 at least a little bit?

**Comment by darkfriend77** [comment]
Thank you for the feedback. @Noc2

Here are our adjustments.

Open-Grant Changes:
- pricing update total price to 30'000$ including milestone 4
- pricing update milestone 1, 2, 3 to 8000$
- updated milestone 4 to be not optional
- clarified milestone 4 as a deliverable  mobile multiplayer  game
- updated milestone 4 pallet matchmaker deliverable

**Review by Noc2 — DISMISSED** [review]
Thanks! Looks good to me.

**Comment by alxs** [comment]
Hi @darkfriend77. I liked the work that you did for the first grant and hence I'm also inclined to support this, but I have to say I'm a little bit confused by the application. I've gone through it a couple of times now and, while you describe the general vision that you have and your future plans etc., I'm still not really sure what functionality the deliverables you're actually proposing will provide. For the Game Engine the most helpful description I found was deliverable 1d. "Account, Player, Wallet, Encryption, Mnemonic, Restore, Transfer" which still leaves me with a lot of questions. Will this Game Engine be a collection of C# scripts, Unity assets? How is it different from the SubstrateNetApi? Same goes for the Substrate SDK for Unity, for which the only specification I could find was that it should be "an end to end working Asset that uses the node-template and allows access to alice and bob account and balances in a mobile deployable project on unity". I'd imagine an SDK would allow more than that? What will be part of the SDK and what of the Game Engine? How will the service layer be implemented?

I would be happy to see a more detailed specification/description of these components in general. It might be helpful to focus on describing "what it is we're funding" instead of "what it is you're doing". The deliverables in the milestones also look a bit like to-dos rather than deliverables and some of them are redundant, i.e. you don't need to list unit tests and documentation as separate items for each deliverable since they're covered by 0b-c, many of the separate subdeliverables could be condensed etc.

**Comment by darkfriend77** [comment]
@alxs & @Noc2 Thank you for your feedback.

I clarified the Milestones, to describe what the deliverables are.

It might be a little hard to describe, but as a game developer, you don't want to write against the SubstrateNetApi as it is just not Unity friendly, so that's why we created this abstraction layer, the Game Engine which acts as the Controller layer and decouples a lot of the substrate-based logic into Unity friendly access in C# like transferring storage changes in easily accessible events that can trigger animations in Unity without writing a storage subscription. Unity selfs only acts as a View representation.

Now for a moderate amount of players, the direct access to nodes might be okay over SubstrateNetApi and the storage subscriptions, but if you add up some player at one point you want to create a service layer to avoid everyone accessing the nodes or subscribing to the same storage for the same information, over and over again and again, that's why we are working on the service layer to support scaling for games. I will add you to the current private repos so you can take a look at what we are currently doing and how it will look like.

Please give me feedback if there is more clarification needed.

Regards.

**Review by Noc2 — DISMISSED** [review]

**Comment by darkfriend77** [comment]
Hey @alxs and @Noc2

I added a detailed description and picture of what the UnitySDK will provide to the Unity Developer, I hope this clarifies the milestones and deliverables.

Open-Grant Changes:
- updated UnitySDK for Substrate architecture overview
- updated UnitySDK description of provided features
- updated SubstrateNetService description
- reduced price on milestones that are are already worked on
- added performance test deliverable in milestone 4

**Review by Noc2 — APPROVED** [review]

**Review by alxs — APPROVED** [review]
Thank you for the updates and the explanation @darkfriend77. Seems much clearer to me now and I'm happy to go ahead with the project.

**Review by mmagician — APPROVED** [review]

**Comment by alxs** [comment]
Replicating @semuelle's [comment](https://github.com/w3f/Grants-Program/pull/729#issuecomment-1121509083) here for better visibility:

> Hey @darkfriend77. I see plenty of activity on the Ajuna repos, so I assume you are still working on this grant. Can you give us an estimate of when you are planning to submit the next milestone? It might be worth amending the contract again, or, if you don't know if you can deliver at all, we can cancel the grant for now. You would be able to reapply, of course.

**Comment by darkfriend77** [comment]
@alxs yes, the SDK is being finalized to be without any manual work. We decided to not front running by manually delivering the parts for the grant, should be able to have it done by start of July, after the Decoded.

**Comment by alxs** [comment]
Hi @darkfriend77, same as [last time](https://github.com/w3f/Grants-Program/pull/433#issuecomment-1144882327) for milestone 3 :)

**Comment by darkfriend77** [comment]
Hey Alexio,Working on it, a part of deliverables of the Milestones have been already showed in the Substrats Seminar.https://youtu.be/IAdvCbK0kQIAnd currently we are preparing the rest of it towards our Sub0 Workshop end of November.If possible we would deliver it by first week of Decemeber.Let me k ow if that fits,and apologize for being late again.Best,CedricAm 03.11.2022 12:02 schrieb Aleixo Sanchez ***@***.***>:
Hi @darkfriend77, same as last time for milestone 3 :)

**Comment by alxs** [comment]
Congrats, adding that to my watchlist! Sounds good, as usual keep an amendment in mind if necessary.

**Pull request merged**
