### PR TITLE
IPS Public Chain 

### PR DESCRIPTION
**Pull request by IFS-chain**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, teams that haven’t successfully completed a grant before, can only apply for up to 30k (see [readme](https://github.com/w3f/Open-Grants-Program)). Once you completed the first grant, you can always apply for follow-up grants. Furthermore, we would need to have more details about your project and the concrete implementation. Do you have a whitepaper and/or code, which you can share? Could you describe “IPS mainnet development” a lot more detailed (functions, programming language, ideally some specification, etc.)?

**Comment by IFS-chain** [comment]
Updated the application according to  the comments

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Why did the name of the team lead change? Also under team experience you still have Edward as well as Nelson listed and neither Edward or Nelson are listed in your whitepaper. Could you define “main functions of mainnet” better as part of your first milestone? Also how does your solution compare to filecoin? Did you already develop any code yourself? You github organization so far only contains clones of the work done by protocol labs as far as I can see it.

**Comment by IFS-chain** [comment]
> Thanks for the update. Why did the name of the team lead change? Also under team experience you still have Edward as well as Nelson listed and neither Edward or Nelson are listed in your whitepaper. Could you define “main functions of mainnet” better as part of your first milestone? Also how does your solution compare to filecoin? Did you already develop any code yourself? You github organization so far only contains clones of the work done by protocol labs as far as I can see it.

Thanks for the review. My answers are lines:
Q1> Why did the name of the team lead change? Also under team experience you still have Edward as well as Nelson listed and neither Edward or Nelson are listed in your whitepaper.
 A1>  Corrected the mistake in the new version of PR. The Edward left the team due to personal issues. I used the older version documents when created the PR. The new leader, Nelson, are listed on the whitepaper on page 24. 

Q2>  Could you define “main functions of mainnet” better as part of your first milestone?
A2>   Added the details of the functions in the new PR.

Q3> how does your solution compare to filecoin? 
A3>  1. IPS introduces sub-chain function. Customers/partners could add a sub-chain based on their business needs. They could issue their own token  and customize the incentive program again the sub-chain. In addition, they could  build their own ecosystem surround the sub-chain.
        2.  In Filecoin, one node plays both retrieval and  storage roles. This kind of design leads requirements of nod's hardware is high. As the result, the cost to use Filecoin becomes high too.  In IPS, retrieval node and storage node are separated. By this design, the hardware requirements become lower and performance got better.

Q4>  Did you already develop any code yourself?
A4> Yes.
         + go-ips is modified based on go-ipfs v0.4.21
         + go-ips configuration data structure is modified based on https://github.com/ipfs/go-ipfs-config
         + interface-go-ips-core is modified based on https://github.com/ipfs/interface-go-ipfs-core
         + ips-go-sdk : we built it from scratch
         + ips-file-server: we built it from scratch

Supplement: We started the project 2 years ago  and got a couple of pilot Japanese customers  at the time.  Since we were not good at marketing, the project was suspended for a while. Recently, our pilot customers asked us if we plan to resume the project. Although they are using Filecoin, they complaint about the high staking rate, high hardware spec . From their perspective, IPS has value position in the market.  We got to know the Polkadot is ready to integrate with 3rd party's public chain.  It is an opportunity for us to join Polkadot/Web3 ecosystem to get more business exposure outside of Japan.  Meanwhile we could bring opportunities in Japan to Polkadot/Web3 ecosystem as well.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick and detailed answer. But could you still provide more details regarding what parts are actually included in “IPS mainnet development” and specify this more detailed? For example, adopting the BFT consensus or incentive algorithm is very unspecific. Also, in my personal opinion, I recommend renaming the whole project and focus on the unique parts of your storage solution. IPS sounds like you misspelled IPFS. It’s generally fine to reuse existing open source code for your own project, but you should also properly attribute the work you are using and clearly differentiate yourself. The Web3 Foundation definitely doesn’t want to support a simple IPFS clone. Additionally, I recommend removing the bridge related deliverables. I think developing a storage chain on it's own is already a lot of work.

**Comment by IFS-chain** [comment]
> Thanks for the quick and detailed answer. But could you still provide more details regarding what parts are actually included in “IPS mainnet development” and specify this more detailed? For example, adopting the BFT consensus or incentive algorithm is very unspecific. Also, in my personal opinion, I recommend renaming the whole project and focus on the unique parts of your storage solution. IPS sounds like you misspelled IPFS. It’s generally fine to reuse existing open source code for your own project, but you should also properly attribute the work you are using and clearly differentiate yourself. The Web3 Foundation definitely doesn’t want to support a simple IPFS clone. Additionally, I recommend removing the bridge related deliverables. I think developing a storage chain on it's own is already a lot of work.

Thanks for the kindly reply and suggestion. 
1.  The followings are the mainnet functions in details. Currently development status is the core functions had been finished the 2 years ago. What we are trying to do current is to refine the codes. It will not take too much time.
   - Split the network into 2 layers: Storage layer(Node) and Retrieval layer(Node)
   - Proof of Replication (PoRep) & Proof of Extract (PoE)   
     These are build based on Zero-Knowledge Succinct Non-Interactive Argument of Knowledge (zkSNARK) and the Seal,
enabling storage certification with low resource consumption and high efficiency.
  - Intelligent file split 
     Not like filecoin to split file with the same size of segments. IPS splits file according to pre-defined policy: file size, format, type, level of node (better network/storage conditions will be evaluated as higher level). 
  - Storage quality scan
     The retrieval node scans the stored files in a regular basis. Invalided/duplicated files will be deleted.
  - Storage node evaluation 
     In IPS, the storage nodes will be evaluated to Super Node, Enterprise node and normal miner. The file will be allocated to Super node then enterprise node , normal miner node. As super/enterprise nodes have better network&storage, it is helpful to improve network performance and stability    
   - Storage Raid setup
      Customers can setup raid level based on their needs. 3 Raid levels are provided: 1/3, 1/2, 2/3  

2.  Regarding the project name. Thanks for your valuable suggestion. We didn't realized it!  We will seriously take a consideration to change the name.  If you could suggest the name, it will be highly appreciated. 

3.  Our project is not simply copy of the IPFS. As mentioned above, we spent almost 1 year to build the project and have built functions to address the performance issues and protect the safety of files/data. We filed a patent in Japan and it was approved in March 2020.  
     Patent file: https://github.com/ips-protocol/Documentation/blob/main/JPB%20006671617-000000.pdf
     Sorry it is in Japanese.  English version could be found on the official website here:
      https://www.j-platpat.inpit.go.jp/c1800/PU/JP-6671617/3B6D413CAE14C12C68B3885293948F64078C2C6A55EE6E195512B66991D42CB3/15/en

4. Most of mainnet functions are there. We just need to refine the code a little bit more. We are eager to join Web3/Porlkdot ecosystem and we believe we could contribute to the ecosystem as well.

**Comment by Noc2** [comment]
Sorry for the late response and thanks for the detailed reply. Could you please update the application itself? Also feel free to change the name.

**Comment by semuelle** [comment]
Closing due to inactivity. Happy to reopen should you decide to follow up on David's comment.

**Pull request closed without merging**
