### PR TITLE
Application: Lloyd Protocol

### PR DESCRIPTION
**Pull request by poeticboat**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by mmagician — CHANGES_REQUESTED** [review]
@poeticboat Thanks for your submission.
We actually have another team that received a grant for a similar idea, you can have a look at their proposal [here](https://github.com/w3f/General-Grants-Program/blob/cb6ecf65d9ba11c05f16e56f7af47e38d2fc38f5/grants/speculative/nsure_network.md).
It would be great if you could outline the differences between the two proposals and what new features you're planning to bring to the ecosystem.

**Comment by poeticboat** [comment]
> @poeticboat Thanks for your submission.
> We actually have another team that received a grant for a similar idea, you can have a look at their proposal [here](https://github.com/w3f/General-Grants-Program/blob/cb6ecf65d9ba11c05f16e56f7af47e38d2fc38f5/grants/speculative/nsure_network.md).
> It would be great if you could outline the differences between the two proposals and what new features you're planning to bring to the ecosystem.

Thank you for your reply and have a brief understanding. We have the following advantages
* Allows anyone to create an insurance contract based on any smart contract to insure any asset pool without KYC permission.
* All parameters can be customized, and specific encrypted assets,  such as Dai, ETH, and the corresponding base pool (loan pool, market making pool, staking  pool or multi signature wallet) also can be specified.
* The cost model and rules for triggering / evaluating claims also need to be customized, and the process can be managed by programmable contracts, Dao or centralized agents.

**Comment by mmagician** [comment]
@poeticboat Sorry for a late response. Here are my comments, let me know if you could address these please:

1. Will the project be usable to some extent after Milestone 1 (i.e. as a user, what functionality will I be able to perform after milestone 1 is finished)?

2. The way I understand your proposal, in M1.1 you say that `risk assessor may need to listen for registration events` - but the module for managing risk assessors is only implemented in M2.1. Could you clarify please?

3. > on chain PoA audit

audit of what? 

4. > When a security incident occurs, policy-holder need claims proposal, which need members governance. if has member fraudulently voted, it will slash.

5. How do you decide if a member voted fraudulently?

6. Could you try to provide the details of publicly callable functions for each module? What data will be stored on-chain for each module?

**Comment by jiyilanzhou** [comment]
> @poeticboat Sorry for a late response. Here are my comments, let me know if you could address these please:
> 
> 1. Will the project be usable to some extent after Milestone 1 (i.e. as a user, what functionality will I be able to perform after milestone 1 is finished)?
> 2. The way I understand your proposal, in M1.1 you say that `risk assessor may need to listen for registration events` - but the module for managing risk assessors is only implemented in M2.1. Could you clarify please?
> 3. > on chain PoA audit
> 
> audit of what?
> 
> 4. > When a security incident occurs, policy-holder need claims proposal, which need members governance. if has member fraudulently voted, it will slash.
> 5. How do you decide if a member voted fraudulently?
> 6. Could you try to provide the details of publicly callable functions for each module? What data will be stored on-chain for each module?

@mmagician Thank you for your reply.
 1. In Milestone 1, ordinary token holders can‘t be able to participate.  It deals only with policyholders and risk assessors.  policyholders is required to submit project details，The risk assessor first needs to identify the project and carefully investigate the project to provide an audit report.

 2. This `registration events` is policyholders submiting project details, not risk assessor registration .

 3. Since the risk assessor has the authority to evaluate and review projects,  it needs to be selected from hackers, developers, auditors, analysts and actuaries with relevant experience.

5. If the proposal is approved by a majority, it can be considered true, and those who reject the proposal will be considered guilty of fraudulent voting and will be slash. This makes each auditor responsible for his or her own vote.

6. The following will probably be implemented and more details will be added in the future.
_____________________________________
   * risk assess pallet
       *   project_register(project name, description, assets trigger payment).
       *   assessor_start_deal()
       *   assessor_ submit_audit()
       *   assessor_generate_market()    
`storage` project map, assessor map, audit map, market map, mortgage pool map
  * assessor manager pallet.
      *  assessor_register()
      *  assessor_unregister()    
`storage`  assessor map
  * insurance market pallet
      * policy-holder_ buy_market()
      * user_pledge_promising_project().
      * finilize_rewards().
`storage`   user_pledge map, user reward map, policy-holder fee map,  policy-holder coverage map,
  * claims assess proposals pallet
       * proposal_claims().
       * proposal_governance().
      *  fraudulently_slash().
`storage` proposal map, governance result map, slash map.

**Comment by poeticboat** [comment]
> @poeticboat Sorry for a late response. Here are my comments, let me know if you could address these please:
> 
> 1. Will the project be usable to some extent after Milestone 1 (i.e. as a user, what functionality will I be able to perform after milestone 1 is finished)?
> 2. The way I understand your proposal, in M1.1 you say that `risk assessor may need to listen for registration events` - but the module for managing risk assessors is only implemented in M2.1. Could you clarify please?
> 3. > on chain PoA audit
> 
> audit of what?
> 
> 1. > When a security incident occurs, policy-holder need claims proposal, which need members governance. if has member fraudulently voted, it will slash.
> 2. How do you decide if a member voted fraudulently?
> 3. Could you try to provide the details of publicly callable functions for each module? What data will be stored on-chain for each module?

@mmagician Thank you for your reply.
 1. In Milestone 1, ordinary token holders can‘t be able to participate.  It deals only with policyholders and risk assessors.  policyholders is required to submit project details，The risk assessor first needs to identify the project and carefully investigate the project to provide an audit report.

 2. This `registration events` is policyholders submiting project details, not risk assessor registration .

 3. Since the risk assessor has the authority to evaluate and review projects,  it needs to be selected from hackers, developers, auditors, analysts and actuaries with relevant experience.

5. If the proposal is approved by a majority, it can be considered true, and those who reject the proposal will be considered guilty of fraudulent voting and will be slash. This makes each auditor responsible for his or her own vote.

6. The following will probably be implemented and more details will be added in the future.
_____________________________________
   * risk assess pallet
       *   project_register(project name, description, assets trigger payment).
       *   assessor_start_deal()
       *   assessor_ submit_audit()
       *   assessor_generate_market()    
`storage` project map, assessor map, audit map, market map, mortgage pool map
  * assessor manager pallet.
      *  assessor_register()
      *  assessor_unregister()    
`storage`  assessor map
  * insurance market pallet
      * policy-holder_ buy_market()
      * user_pledge_promising_project().
      * finilize_rewards().
`storage`   user_pledge map, user reward map, policy-holder fee map,  policy-holder coverage map,
  * claims assess proposals pallet
       * proposal_claims().
       * proposal_governance().
      *  fraudulently_slash().
`storage` proposal map, governance result map, slash map.

**Comment by mmagician** [comment]
@poeticboat Sorry for a belated response & thanks for your answers. 

Do you mind integrating the above module specifications into your application `.md` file please?
Last question from my side: did you have any preference to planning your solution via modules (i.e. substrate pallets) instead of smart contracts?
Finally, it would be great if you could reduce the project price, as BTC has gone up substantially since you've made your application.
Thanks!

**Comment by poeticboat** [comment]
> @poeticboat Sorry for a belated response & thanks for your answers.
> 
> Do you mind integrating the above module specifications into your application `.md` file please?
> Last question from my side: did you have any preference to planning your solution via modules (i.e. substrate pallets) instead of smart contracts?
> Finally, it would be great if you could reduce the project price, as BTC has gone up substantially since you've made your application.
> Thanks!

@mmagician Thank you for your reply.

* I has integrated the above module specifications into my application .md file, And also prefer to implement this with pallets.
* The BTC price has been updated.

**Comment by mmagician** [comment]
@poeticboat Sorry if my question wasn't clear - clearly your preference is for modules, since that's what your application states. What I meant to ask is what is the motivation for choosing modules over smart contracts? Have you considered the alternative and its pros & cons?
Otherwise thanks for updating the proposal.

**Comment by poeticboat** [comment]
@mmagician  Sorry, I'm misunderstand.
* In my opinion，smart contract is a Sandbox which  unable to access the network,  contract is not able to modify core blockchain storage or the storage of other contracts directly. The system resource available is limited.
*  Pallet can provide low level access to entire blockchain, make use of system pallet, customlize fees to the different parts of runtime logic. and most importantly it can use offchain worker get the state of the outside world.
*  Insurance needs to be aware of DEFI accidents and other external events, It manage the captical pool by proposal governance.

So for me, the scalability of runtime pallet is stronger so that  I select runtime pallet to implement it,

**Comment by mmagician** [comment]
> In my opinion，smart contract is a Sandbox which unable to access the network

I would suggest having another look at [ink!](https://github.com/paritytech/ink) smart contracts - even in the README they showcase simple usage & access examples of the blockchain storage via a smart contract.

> most importantly it can use offchain worker get the state of the outside world.

And yet you have not mentioned off-chain workers once in your application. Could you explain please why it's so important to you, then?

**Comment by poeticboat** [comment]
* Thank you for advice， I also consider using Ink to implement, when using ink It will a lot easy to maintain blockchain network.
*  If It is a Flight insurance,  which need  to query the information about flight delays,  and if It's a Crop insurance,  which need  to provide the information about  weather data. So I think it's  important to insurance.

**Comment by mmagician** [comment]
@poeticboat Thanks for a swift reply.

> I also consider using Ink to implement, when using ink It will a lot easy to maintain blockchain network.

My feeling is that your team ought to conduct a bit more research on the topic & understand the differences between smart contracts & runtime modules in Substrate.

> So I think it's important to insurance.

If off-chain workers are indeed as important as you say, why is there no mention of fetching off-chain data in your grant application?

Also, am I right in thinking that [this](https://github.com/w3f/Open-Grants-Program/pull/96) application is also coming from your team? Why have you not disclosed this in the additional information section, as outlined in the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#additional-information-heavy_plus_sign)?

We are happy to support multiple grants from one team, but we require a successful delivery of previous work first.

For the above reasons I'm closing this application for the time being. Feel free to apply for another grant once you've completed the previous project.

**Comment by poeticboat** [comment]
> My feeling is that your team ought to conduct a bit more research on the topic & understand the differences between smart contracts & runtime modules in Substrate.

What we designed before is using runtime module  implemented it，not thought of using smart contract，So the understanding of smart contract is not so deep.

> If off-chain workers are indeed as important as you say, why is there no mention of fetching off-chain data in your grant application?

At present, it's just some on chain insurance for smart contract ,runtime pallet, If we expand to some underchain insurance, such as the flight insurance, agricultural insurance listed above, It will important using offchain worker.

> Also, am I right in thinking that [this](https://github.com/w3f/Open-Grants-Program/pull/96) application is also coming from your team? Why have you not disclosed this in the additional information section, as outlined in the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#additional-information-heavy_plus_sign)?

We have nothing to do with this team,  only consulted a member of this team about some questions. We have own development team and decentralized insurance can be done.

**Pull request closed without merging**
