### PR TITLE
add Idavoll Network

### PR DESCRIPTION
**Pull request by jasonberger0**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@jasonberger0 Thank you for the application. It is quite clear and simple, I would be willing to go ahead with it. Before proceeding further though, I have a few comments:

I see you mention that one of your team members holds patents in the areas of blockchain & consensus - would you mind sharing these with us please?

Also, given the current BTC price, the milestone cost seems slightly high (based on the amount of work proposed and comparing to previously accepted grants of similar scope). Would it be possible to reduce the price to, say, 0.65 BTC? 

Lastly, your team website does not seem to function at the moment.

Let me know whether you can address these! Thanks

**Comment by jasonberger0** [comment]
> @jasonberger0 Thank you for the application. It is quite clear and simple, I would be willing to go ahead with it. Before proceeding further though, I have a few comments:
> 
> I see you mention that one of your team members holds patents in the areas of blockchain & consensus - would you mind sharing these with us please?
> 
> Also, given the current BTC price, the milestone cost seems slightly high (based on the amount of work proposed and comparing to previously accepted grants of similar scope). Would it be possible to reduce the price to, say, 0.65 BTC?
> 
> Lastly, your team website does not seem to function at the moment.
> 
> Let me know whether you can address these! Thanks

Thanks for the reply.
We update the milestone cost to 0.65BTC, and remove the websit address, because we have applied the domain name, but the website has not yet finished .
About the patents, could you provide a email or other contract to share these details?
Thank you.

**Comment by mmagician** [comment]
@jasonberger0 Thanks for a prompt reply and for updating the application! You can share the documents with grants@web3.foundation

**Comment by jasonberger0** [comment]
> @jasonberger0 Thanks for a prompt reply and for updating the application! You can share the documents with [grants@web3.foundation](mailto:grants@web3.foundation)

We have sent you relevant patent information

**Comment by jasonberger0** [comment]
> @jasonberger0 Thanks for a prompt reply and for updating the application! You can share the documents with [grants@web3.foundation](mailto:grants@web3.foundation)

Thanks for a prompt reply and we have emailed to you

**Review by mmagician — APPROVED** [review]
I'd be happy to go ahead with your application.

Something to be aware of is another team implementing a DAO solution: https://github.com/w3f/Open-Grants-Program/pull/90
They're using smart contracts, instead of runtime modules like yourselves. It would be interesting to see both solutions deployed!
Also, feel free to discuss ideas between each other.

**Review by Noc2 — APPROVED** [review]
Looks good.

**Review by RouvenP — APPROVED** [review]

**Comment by RouvenP** [comment]
hi @jasonberger0 we just transferred a test transaction. could you confirm if received?

**Comment by RouvenP** [comment]
hi @jasonberger0 we sent a test transaction last week, did you receive it?

**Comment by RouvenP** [comment]
@jasonberger0 following up here - did you receive the test transaction ?

**Comment by mapdev33** [comment]
@RouvenP i received the test transaction.

**Comment by jasonberger0** [comment]
@RouvenP i received the test transaction.

**Comment by jasonberger0** [comment]
@RouvenP yes,i had  received the test transaction.

**Comment by RouvenP** [comment]
hi @jasonberger0 apologies for the delay. due to holidays it will take a few more days. We will let you know as soo as the transfer is out.

**Comment by jasonberger0** [comment]
@RouvenP ok,thanks!

**Comment by RouvenP** [comment]
hi @jasonberger0 we sent the payment today. apologies again for the delay.

**Comment by jasonberger0** [comment]
@RouvenP  thansk again, i had received the payment

**Pull request merged**
