### PR TITLE
zenlink grant application

### PR DESCRIPTION
**Pull request by v-van**
# Zenlink

Based on the prediction of the further growth of the DEX ecosystem in the future and the rapid development of the public blockchain technology, we propose a Polkadot network-based, high-liquidity, cross-chain DEX Network, Zenlink.

It is a decentralized exchange network that consists of Zenlink DEX Module, Zenlink DEX Aggregator and other DEX Application on parachains.

# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Here is some feedback from my side: 

- Your initial application via the general grants program was a little bit cheaper, could you reduce the price. 
- In your email you said, that you initially focus on milestone 1 and want to provide more details regarding the interface later. I therefore suggest to initially only apply for funding for milestone 1 and follow-up with a grant application for milestone 2, once you are ready with it. 
- Regarding AMM, do you already have some initial specification/design for it?

**Comment by v-van** [comment]
@Noc2 Thanks for the feedback.

I've update the grant about the three point you mentioned:
- According to the current btc price(10,554.50 usdt), we reduce the grant price to 0.76 btc(around 8,000 usdt)
- As your suggestion, we are only focusing on the milestone 1.
- The whitepaper has been updated to v0.4 which explain the initial design of AMM mode.

**Comment by Noc2** [comment]
Just one more request from my side, could you add these to the deliverables table and maybe also link to the whitepaper inside the table:
* Technical specifications and Zenlink DEX Module design.
* We will deliver Zenlink DEX Module on a substrate blockchain.
* It will has Automate Market Maker(AMM) function.

**Comment by v-van** [comment]
The deliverables table has been updated.

**Review by Noc2 — APPROVED** [review]
Thanks. Looks good to me.

**Review by mmagician — APPROVED** [review]

**Review by gavofyork — APPROVED** [review]

**Pull request merged**
