### PR TITLE
Fractapp

### PR DESCRIPTION
**Pull request by CryptoBadBoy**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@CryptoBadBoy Thank you for the submission. We will be evaluating it over the upcoming days.

**Comment by mmagician** [comment]
@CryptoBadBoy if you have a look at our [submission guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) you will see that we only support projects which contribute specifically to the Polkadot/Substrate/Kusama stack. I don't see how your milestones reflect the Polkadot community fit.

Also, just looking at the demo video provided, it seems to me that a lot of what the asks for has already been implemented in your hackathon.

**Comment by CryptoBadBoy** [comment]
> @CryptoBadBoy if you have a look at our [submission guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) you will see that we only support projects which contribute specifically to the Polkadot/Substrate/Kusama stack. I don't see how your milestones reflect the Polkadot community fit.
> 
> Also, just looking at the demo video provided, it seems to me that a lot of what the asks for has already been implemented in your hackathon.

The hackathon version is a demo (only testnet and mock bot) web version for ethereum.
We want to create a production-ready mobile app.  We want to create a simple and convenient wallet with payments in chats for Polkadot.
Today we have an only design for mobile app. 

https://elshandzhafarov326555.invisionapp.com/overview/Fractapp---cryptocurrency-wallet-with-messenger-ckeyvvuh70t3j01bx5mg6e7b0/screens

**Comment by CryptoBadBoy** [comment]
> > @CryptoBadBoy if you have a look at our [submission guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) you will see that we only support projects which contribute specifically to the Polkadot/Substrate/Kusama stack. I don't see how your milestones reflect the Polkadot community fit.
> > Also, just looking at the demo video provided, it seems to me that a lot of what the asks for has already been implemented in your hackathon.
> 
> The hackathon version is a demo (only testnet and mock bot) web version for ethereum.
> We want to create a production-ready mobile app. We want to create a simple and convenient wallet with payments in chats for Polkadot.
> Today we have an only design for mobile app.
> 
> https://elshandzhafarov326555.invisionapp.com/overview/Fractapp---cryptocurrency-wallet-with-messenger-ckeyvvuh70t3j01bx5mg6e7b0/screens

Ethereum in design is an example.
The grant version will only have Polkadot.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Sounds quite interesting to me. Could you indeed add more technical details to the application itself. For example: What tech stack are you planning to use for the Staking bot (a botframework?) or the mobile app itself (flutter?). Are you initially planning to support polkadot, kusama or both? In general, the more details you add to the application the better and feel free to also integrate the link to the mockup to the application itself.

**Comment by CryptoBadBoy** [comment]
@Noc2 
Thank you! We updated applications

**Comment by mmagician** [comment]
@CryptoBadBoy Thanks for the details, that looks better. 

One more thing from my side: could you include details of how you plan to publish/distribute your app? You mentioned that you initially plan to support Android, but since you're using React Native, I believe that iOS would only be a step away.
Please specify the app deliverable (Google Play Store, or even better, F-Droid for Android, App Store for iOS). I guess you'd want to do a final distribution for Milestone 3. (for M1 & M2 including .apk files or similar on your github repo would be fine for us)

Thanks, I'm looking forward to seeing your app in action!

**Comment by CryptoBadBoy** [comment]
@mmagician Thank you!

We are planning to publish in Google Play, F-droid, and distributing apk file.

App Store has more strict publishing guidelines. It require own registered organization. We will definitely publish to the App Store but we may not be in time for 3 months.

In M1 and M2 we will distribute apk for android and you may download expo app and scan qr code for running on IOS.

**Comment by mmagician** [comment]
@CryptoBadBoy That's ok. Would you mind including this in your application please? Something like:
M1 & M2: We will provide .apk files for Android
M3: We will publish on F-Droid and/or Google Play

**Comment by CryptoBadBoy** [comment]
@mmagician, Thank you very much! 
 We updated application

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]
Thanks. Looks good to me.

**Review by gavofyork — APPROVED** [review]

**Comment by CryptoBadBoy** [comment]
@mmagician @Noc2 @gavofyork Thank you very much!

**Comment by semuelle** [comment]
Hey @CryptoBadBoy, it's been a while since the last milestone. Are you still working on the grant? If so, could you give an estimate on your next milestone?

**Comment by CryptoBadBoy** [comment]
@semuelle 

Hi, yes

Sorry for delay. We are actively developing Fractapp.

In September we are releasing all the functionality. But we will not have 75% test coverage yet, so we will complete the grant in October.

We already have everything almost ready for release. We are dealing with the elimination of bugs.

**Comment by semuelle** [comment]
Thanks for the update. Please keep us in the loop.

**Comment by CryptoBadBoy** [comment]
@semuelle, @mmagician, @gavofyork

Hi everyone 

We would like to name the exact release date on Google Play. On October 11, we are releasing a staking chat-bot and several code improvements. 

By the end of October, we will submit an application for the latest Milestone. We will need time to finish writing tests with 75% coverage.

Thank you very much for waiting for us. Our team believes in Fractapp and we do our best to develop it. The development turned out to be more difficult than we had planned. We plan to develop Fractapp further and find investments to grow faster.

**Comment by RouvenP** [comment]
hi @CryptoBadBoy we transferred the payment today. Thanks!

**Pull request merged**
