### PR TITLE
Lunie Governance

### PR DESCRIPTION
**Pull request by jbibla**
🎉

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. As I wrote you via email, let me know if you want to go ahead with the open grants proposal or potentially switch to the general grants program or treasury.

**Comment by Noc2** [comment]
Could you change the amount of the grant to btc (fixed amount)? Also we usually don’t pay for the research + design phase (M1+M2), since this isn’t something useful for others and really difficult to evaluate from our side. Additionally it would be nice if you could add support for the treasury as well. But you could also ask the council to get funding for supporting the treasury. This way you also immediately learn more about the process itself and you get potential ideas on how to improve it.

**Comment by jbibla** [comment]
Thanks @Noc2! I just updated our proposal accordingly. 🎉

**Comment by Noc2** [comment]
Thanks for updating the proposal and adding the treasury module to it. I’d be happy to go ahead with it, but I think the day rate is slightly higher than what we usually pay. In order to convince our operations team it might help if you reduce the price a little bit more.

**Comment by jbibla** [comment]
Done! Thanks @Noc2!

**Comment by jbibla** [comment]
Hello @RouvenP!

I believe at the time of submission it was under 30k.

Please let me know what you think.

**Comment by RouvenP** [comment]
> Hello @RouvenP!
> 
> I believe at the time of submission it was under 30k.
> 
> Please let me know what you think.

Hi @jbibla we look at the market price at the time of approval instead of the submission date's rate. With the current btc rate the total amount is again below 30k so no adjustment needed.

**Comment by jbibla** [comment]
Thank you @RouvenP! Great news!

**Comment by jbibla** [comment]
@keorn @Noc2 @RouvenP when should we expect payment for this grant?

**Comment by jbibla** [comment]
Thank you, David. I misunderstood and thought the payment was upfront. No problem at all!

**Pull request merged**
