### PR TITLE
Polkadot UI Web Identicon + Angular Identicon

### PR DESCRIPTION
**Pull request by morgueye4**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by morgueye4** [comment]
> Thank you for submitting a grant application.
> 
> We checked your submission and found that it contains insufficient details in order to be considered for review. We encourage you to improve your application by including as much technical specifications as possible. You will find general guidelines on what we expect from tea©s [here](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#project-details). Depending on what type of software you're building, you may also find [these category specific requirements](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md) useful.
> 
> We hope to see an update from you soon!

@mmagician I have updated the project and moved it into the applications folder

**Comment by mmagician** [comment]
Apologies for the delay in getting back to you. I have a couple of questions:

1. Could you please update the PR title to reflect your idea?
2. Please merge M1 & M2. Also some deliverables in your M1 are repeated.
3. Do you have experience of building Angular components? Could you please share some of your code, as neither your repo nor your organisation has any examples of your previous work?
4. Are you planning to fork any existing repo to base your work on top of it? If so, which one?
5. Am I right in thinking that if you review the code for the React component, you should easily be able to port that to develop an angular component? In the end you won't be creating custom logic, but rewriting existing one, if anything.

**Comment by morgueye4** [comment]
Hello @mmagician, I have updated the application file and changed the PR title. Inside the application  informations about my Angular related experiences have been added. For the logic it will be inspired from the React Identicon component and we will transpose to the coming Angular and Web components.

**Comment by mmagician** [comment]
Thanks. Could you also provide the link to the repo that you're planning to use/fork as your starting point for the development?

**Comment by morgueye4** [comment]
@mmagician  Repositories for both [Angular](https://github.com/RidOne-technologies/polkadot-angular-identicon) and [Web](https://github.com/RidOne-technologies/polkadot-web-identicon) Identicon repositories are added.

**Comment by mmagician** [comment]
There's a misunderstanding. You said you are going to base your work off an existing codebase (probably the repo where the React component). Could you share **that** link?

**Comment by morgueye4** [comment]
@mmagician [React identicon](https://github.com/polkadot-js/ui/tree/master/packages/react-identicon) is the package that i will get inspiration from for the logic (just for inspiration) but the implementation will be done the Angular way.

**Comment by mmagician** [comment]
Ok, sounds good. Just one last thing: would you mind keeping the deliverables 0a-0d from the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) in your milestone? Once that's ready, I'll share your application with other team members.

**Comment by morgueye4** [comment]
Hello @mmagician ! I have updated the deliverable also the Future Plans.

**Review by mmagician — APPROVED** [review]
Let's give it a try!

**Comment by morgueye4** [comment]
> Let's give it a try!

Great

**Review by Noc2 — CHANGES_REQUESTED** [review]
I’m generally happy to support the project, also giving that you are working on your own substrate-based project and therefore you might have an interest in maintaining it. However, would it be possible to reduce the price? The application seems currently rather expensive to me.

**Comment by morgueye4** [comment]
> I’m generally happy to support the project, also giving that you are working on your own substrate-based project and therefore you might have an interest in maintaining it. However, would it be possible to reduce the price? The application seems currently rather expensive to me.

Thank you for the feedback @Noc2. Yes we plan to use it in our projects since Angular and Flutter will play huge role in our front-end stacks. I have updated the grant amount hoping it to look fair.

**Comment by Noc2** [comment]
@morgueye4  Thanks for the update. I’m happy to go ahead with it, but could you also update the costs of the milestone?

**Comment by morgueye4** [comment]
> @morgueye4 Thanks for the update. I’m happy to go ahead with it, but could you also update the costs of the milestone?

Great @Noc2. I just updated this section.

**Review by mmagician — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the update.

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]
lgtm

**Comment by alxs** [comment]
@morgueye4 care to share a quick status update on the project, together with an ETA if possible? It looks rather abandoned judging from the activity on https://github.com/RidOne-technologies. Unless we hear something from you soon, we will assume you're no longer actively working on it and terminate the grant.

**Comment by morgueye4** [comment]
> @morgueye4 care to share a quick status update on the project, together with an ETA if possible? It looks rather abandoned judging from the activity on https://github.com/RidOne-technologies. Unless we hear something from you soon, we will assume you're no longer actively working on it and terminate the grant.

@alxs The project is ongoing . It was paused due to a medical reason (I can share in private. I plan to deliver it this month or at the latest the coming month.

**Comment by alxs** [comment]
Sorry to hear that, hope you're back at full speed and otherwise wish you a speedy recovery. Happy to hear the project hasn't been abandoned. End of July at the latest works for us :+1:

**Comment by morgueye4** [comment]
@alxs  good👍.

**Pull request merged**
