### PR TITLE
Create Crafting Finance.md

### PR DESCRIPTION
**Pull request by CraftingFinance**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update application. I’m just adding a reference to the previous PR, https://github.com/w3f/Open-Grants-Program/pull/338. Do you have some initial code or code of a previous project which you could share? Also we've recently updated the application template to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this? Furthermore could you specify more detailed how your MintR pallet is different from other existing pallets ([see for example](https://github.com/laminar-protocol/laminar-chain/blob/master/modules/synthetic-protocol/src/lib.rs))? Same for the other pallets.

**Comment by alxs** [comment]
And could you please clarify why you stated in your last application that "more than 70% of the team members have a Master degree or a PhD degree" when in the current application only 1 out of the 3 team members has one?

**Comment by alxs** [comment]
Closing due to inactivity.

**Comment by CraftingFinance** [comment]
@Noc2  @alxs  

Sorry, I did not reply in time. Because we have recently communicated with the Acala team, they believe that the Crafting Finance project and Acala are highly complementary. The Acala team recommends that we use the WASM smart contract to complete the project and run it on Acala. Therefore, we have made adjustments to the technical roadmap, and we will upload some of the developed code in the near future.

In fact, the Crafting Finance project is more similar to Synthetix than Laminar. We recently had a conversation with Jordan from the Synthetix team. In the Crafting Finance project, we have upgraded the sharing debts pool model (SDP) proposed by Synthetix. Different from Synthetix, in which users have no choice and can only join the debt pool when forging synthetic assets. We innovatively proposed that users can choose whether to join the debt pool, and found that even if users do not join the debt pool, they can still trade in the system (Kingsman), and bring more possibilities to the entire system. Below we use an example to illustrate.

Suppose there are user A and user B. User A chooses not to join the debt pool when forging synthetic assets, and user B chooses to join the debt pool when forging synthetic assets. Suppose that before A and B forged synthetic assets, there were originally $100 rBTC in the system. Then, A forged $100 of rUSD but did not join the debt pool, and B forged $100 of rBTC and joined the debt pool. Then, the assets and liabilities of the entire system become $200 rBTC in the debt pool, and $100 rUSD outside the debt pool. B accounts for 50% of the system’s liabilities, and A has no debt ratio because he/she has not joined the debt pool.

Now if B buys $100 rUSD from A, and the $100 rUSD is not in the system, can it be traded in the system? The answer is yes. For example, B converts this $100 rUSD to rBTC through our trading system Kingsman, and the assets in the debt pool become a total of $300 rBTC, -$100 rUSD, the total assets and liabilities of the system are still $200, and B’s debt ratio is still 50% which is $100. That is, by allowing the balance of an asset in the debt pool to be negative, we have realized that synthetic assets that are not in the debt pool can also be traded in Kingsman.

Regarding the question "more than 70% of the team members have a Master degree or a PhD degree", because the application only includes technical team members, considering personal privacy, the operation team and marketing team members are not included. If you can provide a channel to ensure privacy, we are willing to verify this.

**Comment by alxs** [comment]
Thank you for the updates.

May I ask what your affiliation with the [Coinversation](https://github.com/w3f/Open-Grants-Program/blob/master/applications/Coinversation.md) team is? We recently noticed that a lot of the information in your last and this application had been copied from theirs.

Regarding a private communications channel, you can find David and me on Element under `@david:web3.foundation` and `@aleixo:web3.foundation`.

**Comment by Noc2** [comment]
Just to add, you can also send us an email to grants@web3.foundation and feel free to reopen and update the application accordingly once you are ready.

**Comment by CraftingFinance** [comment]
@alxs  @Noc2 
Thanks for your reply. After fully communicating with the Acala team and the Synthetix team, we plan to adjust the technology roadmap to focus on upgrading the sharing debts pool model (SDP) invented by Synthetix.

The information of the team members has been sent to grants@web3.foundation, please review it.

**Pull request closed without merging**
