### PR TITLE
NewOmega Application M3/M4

### PR DESCRIPTION
**Pull request by celrisen**
# Grant Application Checklist

- [X] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [X] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @celrisen, 

thanks again for your application. Based on your previous deliveries, I'd be happy to support another grant. Two issues, though:

1. Deployments are not covered by the grants program, so could you please remove Deliverables 3.3, 4.1 and 4.2 and adjust the price accordingly? 
2. As you know, we have a [policy against gambling](https://github.com/w3f/Open-Grants-Program/blob/master/README.md#guidelines), so I'm not certain the committee will approve an application that revolves around betting. Do I understand correctly that it is possible to play the game without betting?

**Comment by celrisen** [comment]
Thanks for the feedback @semuelle, I'll shortly adjust the proposal accordingly to better fit the grant guidelines.

**Comment by celrisen** [comment]
Hi @semuelle, I've pushed the revised proposal for the 2 milestones considering your feedback.
Let me know how it sounds.

**Comment by semuelle** [comment]
Thanks for the update. 

It seems that you are using the word 'module' for two different things here (the 'ship modules' (NFTs), and the 'Market' and 'Universe' modules. Could you elaborate what the latter modules will look like from a technical perspective? Is it a separate smart contract? Or are we talking about runtime modules? I forgot to mention that we also don't fund marketing expenses, so, if possible, please remove Deliverable 4.5 as well.

**Comment by celrisen** [comment]
@semuelle Fair point, I've solved the ambiguity about Module naming. Also provided more technical details about Market and Universe functionalities and removed deliverable 4.5.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new application. Could you specify the programming language for each deliverable. And maybe tell us a little bit about your future plans with this project? Do you have a website for it? Otherwise it looks good to me.

**Review by semuelle — APPROVED** [review]

**Comment by celrisen** [comment]
@Noc2 Thanks for the feedback. I've updated the Future Plans section with links to articles and a little additional writeup. Also specified in more detail the tech stack used for the solution. Let me know if that sounds good to you.

**Review by Noc2 — APPROVED** [review]

**Review by semuelle — APPROVED** [review]

**Review by Lederstrumpf — APPROVED** [review]

**Pull request merged**
