### PR TITLE
Bwarelabs Decentralized API - Web3 grant application

### PR DESCRIPTION
**Pull request by eradus**
# Grant Application Checklist

- [X] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [X] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [X] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [X] The initial PR contains only one commit (squash if needed before submitting your PR).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Looks like the bot is happy now!

I haven't looked at your application in detail, but there are a couple of things you should be aware of since it looks like they _might_ pose a problem:

- All software delivered as part of a grant must be open source, and it also cannot rely on closed-source software for full functionality.
- We don't fund projects for which a token sale has been conducted.
- We don't cover infrastructure costs.

If any of this applies, please update your application.

**Comment by eradus** [comment]
> Looks like the bot is happy now!
> 
> I haven't looked at your application in detail, but there are a couple of things you should be aware of since it looks like they might pose a problem:
> 
> * All software delivered as part of a grant must be open source, and it also cannot rely on closed-source software for full functionality.
> * We don't fund projects for which a token sale has been conducted.
> * We don't cover infrastructure costs.
> 
> If any of this applies, you'll need to update the application.

I can confirm we only use open-source software, we didn't conduct a token sale yet and we only included development costs in the application (no infrastructure cost included)

**Comment by alxs** [comment]
Thanks for clarifying.

Sorry, I should have been more specific here. We don't cover infrastructure _or_ deployment costs, which does apply to some of the deliverables and to the second and fourth items under [Grant Scope](https://github.com/w3f/Open-Grants-Program/blob/be6cf8f8c7c30e1b124f5298270a49eac21aa3c9/applications/Polkadot-support-bwarelabs-platform.md#grant-scope). It might make more sense for you to apply for funding via Treasury instead, which doesn't have such restrictions. See the [relevant section](https://github.com/w3f/Open-Grants-Program#treasury) in our README and if you have any questions, fill out this [form](https://forms.gle/AQRhJ6Wt9nw431DM7) and someone will be in touch with you soon.

Otherwise you're welcome to just remove these deliverables and adjust the cost and we'll provide more feedback. Just to be clear, you're saying the Bwarelabs platform is entirely open-source? Also the links to the repos you provide seem to be broken.

**Comment by eradus** [comment]
> Thanks for clarifying.
> 
> Sorry, I should have been more specific here. We don't cover infrastructure _or_ deployment costs, which does apply to some of the deliverables and to the second and fourth items under [Grant Scope](https://github.com/w3f/Open-Grants-Program/blob/be6cf8f8c7c30e1b124f5298270a49eac21aa3c9/applications/Polkadot-support-bwarelabs-platform.md#grant-scope). It might make more sense for you to apply for funding via Treasury instead, which doesn't have such restrictions. See the [relevant section](https://github.com/w3f/Open-Grants-Program#treasury) in our README and if you have any questions, fill out this [form](https://forms.gle/AQRhJ6Wt9nw431DM7) and someone will be in touch with you soon.
> 
> Otherwise you're welcome to just remove these deliverables and adjust the cost and we'll provide more feedback. Just to be clear, you're saying the Bwarelabs platform is entirely open-source? Also the links to the repos you provide seem to be broken.

hey! thanks for the feedback! I have added those deliverables because they are a necessary part of the project but the cost we have specified in the file doesn't include any cost necessary to host and deploy the Polkadot full nodes or any infrastructure cost whatsoever (that part is entirely supported by Bware Labs). They are strictly development costs or more specifically developer salaries. I have now noticed that there is a 1k difference between milestones costs and total cost but that's a typo, I'll update that part. Regarding the links, they are not working because the repos were not yet made public. We are planning to hold off making the code open source until we complete our token sale later this year.

**Comment by alxs** [comment]
Thanks again. I think in that case we're in a bit of a catch-22 since as long as your project isn't open source, we can't accept the milestones, but if you deliver them after you've conducted the token sale this would put you in the "not eligible" category (in which case you probably wouldn't need the funding anyway, note that we don't pay upfront). So unless you can open-source everything and finish the grant before the sale, I'm afraid I don't see a way for us to support this.

**Comment by alxs** [comment]
Closing due to inactivity and the issue mentioned above. Happy to reopen in case this can be resolved.

**Pull request closed without merging**
