### PR TITLE
PolkaKey

### PR DESCRIPTION
**Pull request by HiZhaoYun**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi. Thanks for the application. I just added your desktop wallet sakura to our tech stack document, see https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#iphone-explorer-and-wallets. In general, multiple wallet providers are currently already working on potentially more secure and more user-friendly solutions (e.g. https://www.parity.io/signer/ or https://github.com/w3f/General-Grants-Program/blob/master/grants/accepted_grant_applications.md). However, given the low total costs of your project, maybe it might be useful as a nice Electron tutorial for our ecosystem. Would you be willing to add a Chinese + English tutorial to your application?

**Comment by HiZhaoYun** [comment]
Hi. Thanks for adding sakura to the tech stack document, but this is still an work-in-progress project, and I can only do this work in my spare time, so there are no exact milestones for this project.

**Comment by zhangyaxing12** [comment]
申请提案后可将提案链接同步到Pr

**Comment by Noc2** [comment]
Hi. Sorry for the late reply. Regarding sakura, it's not an issue that it's still work in progress. The intention behind the document is also to give other people an overview of existing projects so that they could pick it up and leverage it for their own projects. What I meant with the tutorial was to create one for a simple electron app for substrate/polkadot (similar for example to the following https://substrate.dev/docs/en/tutorials/substrate-front-end/). Basically use this project/PolkaKey also to help other developers to get get started with electron plus our tech stack.

**Comment by HiZhaoYun** [comment]
> What I meant with the tutorial was to create one for a simple electron app for substrate/polkadot (similar for example to the following https://substrate.dev/docs/en/tutorials/substrate-front-end/). Basically use this project/PolkaKey also to help other developers to get get started with electron plus our tech stack.

Hi, that's a great idea, and I'd love to do it. But I may need another two weeks to add a Chinese + English tutorial, because I'm very busy recently. I updated the milestone. Please let me know if there are questions.

**Comment by Noc2** [comment]
Hi. Thanks for adding the tutorial. I have one last request, could you specify the milestone section a little bit better. For example add information on how you're going to test the code (e.g. unit tests, which testing framework, etc.), which function are you implementing (e.g. generate a polkadot address via electron), what is the content of the tutorial, where do you plan to publish it, etc..  We will use this milestone section to test your delivery, so it's basically similar to the requirements of regular contracts and therefore should be specified a little bit more detailed.

**Comment by HiZhaoYun** [comment]
Hi. Sorry for the late reply. I added more detail on the milestone. If possible, i hope to publish the tutorial on [Polkaworld](https://www.polkaworld.org/) and [Substrate Dev Hub](https://substrate.dev/en/tutorials).

**Comment by HiZhaoYun** [comment]
Thank you so much! @Noc2 @gavofyork @keorn

**Comment by alxs** [comment]
Hi @HiZhaoYun, any plans on finishing this grant? Otherwise we would just remove milestone 3 from the proposal.

**Pull request merged**
