### PR TITLE
Polkadot.{js} Desktop App

### PR DESCRIPTION
**Pull request by krzysztof-jelski**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by krzysztof-jelski** [comment]
@Noc2 Thanks for the review. I changed the values to BTC.

**Comment by RouvenP** [comment]
thanks for the application. looks fine from a financial point of view.

**Comment by alxs** [comment]
@krzysztof-jelski just checking in: when do you roughly expect to deliver M3?

**Comment by krzysztof-jelski** [comment]
Hi @alxs ! So most of the changes are implemented in open PRs [here](https://github.com/polkadot-js/apps/pulls?q=is%3Apr+is%3Aopen+label%3Agrant-accounts-m3). We hope we can get through them quickly with Jaco :-) . Some 1-2 features are still left. Trying to track the progress [here](https://github.com/wachulski/Grant-Milestone-Delivery/pull/2/files?short_path=8326079#diff-832607979cbb5e1cbbae1211cafbbafcdcb6dacb3404dd87e6d2a2d0bd0c994e), should be relatively up to date. All in all, I believe it's a matter of 2-3 weeks to finish.

**Comment by alxs** [comment]
Lovely, thanks for the update :)

**Pull request merged**
