### PR TITLE
add MathComitia Grant Request

### PR DESCRIPTION
**Pull request by ericfish**
Decentralized discussion board and light-weight community voting system based polkadot address and identity by Math Team

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by semuelle** [comment]
Hi @ericfish, thank you for your submission. We will look into it as soon as possible.

In the meantime, could you (and any other contributors to the PR) sign the CLA?

**Comment by ericfish** [comment]
> Hi @ericfish, thank you for your submission. We will look into it as soon as possible.
> 
> In the meantime, could you (and any other contributors to the PR) sign the CLA?

Thanks, I have signed the CLA.

**Review by mmagician — CHANGES_REQUESTED** [review]
In the current state of the application I don't see anything in your deliverables that points to an integration with substrate. Could you clarify please?

**Comment by alxs** [comment]
I'm not sure I understand that either. You propose to store an on-chain signature for every user action? That would mean users would have to pay a fee for every interaction. I see you mention using NFTs to incentivise users, but I'm not sure that represents a tangible solution. I like the idea behind it but if user engagement is already hard in Web 2.0, I honestly don't see this becoming a vibrant community if users have to pay just to participate, NFT or not.

**Comment by Noc2** [comment]
Just to add something: We are generally quite interested in an on-chain reputation system. So basically combining the UI, which it seems you are planning to develop with a substrate pallet (or multiple pallets).

**Comment by ericfish** [comment]
> In the current state of the application I don't see anything in your deliverables that points to an integration with substrate. Could you clarify please?

This project is more of a dapp which based on substrate address and identity. For deliverables, the frontend will support PolkadotJS login and signature, the backend will support signature verification. And the target is tracking all the related activities based on substrate address and based on that to create the on-chain reputation system.

**Comment by ericfish** [comment]
> I'm not sure I understand that either. You propose to store an on-chain signature for every user action? That would mean users would have to pay a fee for every interaction. I see you mention using NFTs to incentivise users, but I'm not sure that represents a tangible solution. I like the idea behind it but if user engagement is already hard in Web 2.0, I honestly don't see this becoming a vibrant community if users have to pay just to participate, NFT or not.

This is a very good question. We think that's why we need this kind of light-weight voting system, because it is hard to ask the user to pay if he/she just need to contribute some information to a site. In the design of the system, the signature verification is offchain. For example, you can take a look at the vote function on https://www.polkaproject.com/#/project/29 which our team contribute the code. It tracks the vote activities based on substrate address without payment, and based on that we can have an address based the on-chain reputation system.

**Comment by mmagician** [comment]
> tracking all the related activities based on substrate address and based on that to create the on-chain reputation system

So if all your signature verification happens off-chain, how do you plan to turn it into an on-chain reputation system?

In the present state, this looks like a centralised solution having its own backend & MySQL database. The signatures might indeed be collected by your frontend, verified and written to the DB, but what's there to stop the DB owner from just altering the numbers of votes afterwards?

**Comment by alxs** [comment]
I see. So nothing is stored on chain, yeah I guess that's better. But I'd have to agree this is not very decentralised, if the only integration with Substrate is that votes are signed using a Substrate address that might exist somewhere on chain, which no one is gonna verify anyway. And what prevents Sybil attacks?

This is meant to be some healthy criticism by the way, not us tearing your application to pieces ;)

**Comment by semuelle** [comment]
> And what prevents Sybil attacks?

I assume an account's collected reputation will play a role in the weighing of votes. 
That being said, you call it a `decentralized discussion board`, when there is nothing decentralised about it (other than participants receiving NFTs). I don't think that's a dealbreaker, just inaccurate unless I'm misunderstanding something. 

- What is a space admin? Are they identified by on-chain addresses as well? 
- What do `Closed` and `In-Progress` mean exactly? 

Lastly, one big risk I see here is that this particular forum (MathComitia) gets overrun by spam or is insufficiently moderated; in the worst case, misleading or incendiary content gets voted to the top while the `About` page reads `Supported by Web3 Foundation`.  I would very much support a grant building a library that would allow a forum to utilize signatures for identification and on-chain identities for reputation. It would be easier if it was separate from any particular instance.

**Comment by ericfish** [comment]
Thanks for these good questions. 

The background of the project is more focused on collecting feedback / reporting scams / collecting feature requests which can utilize signatures for identification and these activities can be part of on-chain identities for reputation.
1. So for these scenarios the vote is more for reference, not for final decision.
2. We'd like to focus on user participation as higher priority, so instead of putting everything on-chain we would choose to simplify the system at the first stage.
3. All submitters and voters' address information will be displayed, and addresses with verified on-chain identity will be displayed with higher weight.

And we do like @semuelle 's suggestion about 'A library to utilize signatures for identification and on-chain identities for reputation', which can make the outcome of project in common use. We will research what are the common functions for this library and modify the request to this direction.

**Comment by mmagician** [comment]
> We will research what are the common functions for this library and modify the request to this direction.

@ericfish In the meantime, I'm going to close the application. Let us know when you're ready with the research/updates and then we can re-open the application!

**Pull request closed without merging**
