### PR TITLE
Hardware ECDSA for Polkadot JS

### PR DESCRIPTION
**Pull request by akru**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by akru** [comment]
@Noc2 Thank you, David, looking forward to feedback. The price reduced as you suggested.

**Comment by Noc2** [comment]
Hi @akru, we discussed your grant a little bit internally and in general we don’t think it’s currently super useful for our ecosystem. Nevertheless, I would be fine with approving it at half of the current amount (0.7 BTC). I know it’s also partly quite expensive at the moment, because the bitcoin price went up. Would this be interesting for you?

**Comment by akru** [comment]
Hi @Noc2, thank you for your response. I'm glad to hear that you ready to approve this proposal.
The price changes applied, it's a bit low than expected but we ready to make it this time. Thank you!

**Comment by akru** [comment]
Hello @Noc2, do you have any updates?
Can I start working on it?

**Comment by Noc2** [comment]
Hi @akru. The application still needs one more approval. I pinged the whole committee yesterday.

**Comment by akru** [comment]
Got it, thank you David. Looking forward to final decision.

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grantspr@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by akru** [comment]
@Noc2 Thank you very much!

**Comment by alxs** [comment]
@akru @hoonsubin please note that since we haven't heard from you in 3 months, we'll assume you're no longer interested and terminate the grant if we don't hear from you within the next 2 weeks.

**Comment by akru** [comment]
Hello @alxs, I’m apologies for long silence, let me update grant description. Something else we should do for this grant delivery?

**Comment by alxs** [comment]
Thanks. I don't think so, I will get back to you once I've tested it with the updated commit.

**Pull request merged**
