### PR TITLE
PARSIQ Open Grants Proposal

### PR DESCRIPTION
**Pull request by alan-parsiq**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by alxs** [comment]
Hi @alan-parsiq and thank you for your application.

I personally really like your proposal and would like to see something like this funded, but this is up to the committee members to decide.

A few inputs that will make it easier to get your application accepted:

- Please check all checkboxes in the first comment indicating that you've acknowledged these points.
- We usually aim for more detailed and technical deliverables, which also facilitates our task when evaluating the milestones. Could you split your deliverables into smaller ones, specify for each one of these what technologies/languages you will use and expand on the specification? E.g. but not exclusively, deliverable 3 of M2 in which you note "This is a huge step, consisting of many deliverables." Please list each of these. Under specification, please list all requirements that you aim to achieve as part of a deliverable.
- Could you take a minute to compare this project to [Guardian](https://github.com/open-web3-stack/guardian), previously funded by us?
- Also since you specify that you will implement _and open-source_ deliverable 1 of M2, please note that **all** code funded through grants must be open-sourced and also must not rely on closed-source software to function. Is that the case for this project?

**Comment by alanduw** [comment]
> # Grant Application Checklist
> * [ ]  The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
> * [ ]  A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.
> * [ ]  The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
> * [ ]  The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
> * [ ]  The initial PR contains only one commit (squash if needed before submitting your PR).
> * [ ]  The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

# Grant Application Checklist
* [x]  The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
* [x]  A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.
* [x]  The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
* [x]  The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
* [x]  The initial PR contains only one commit (squash if needed before submitting your PR).
* [x]  The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

**Comment by alanduw** [comment]
Hey @alxs !

Thank you for the first reviewal and a useful inputs! 

We will get back to the edits shortly, so that our Proposal eventually matches the open-source policy.

Also, will provide the answers to questions afterwards.

**Comment by alxs** [comment]
Sounds good. I updated your first comment for ease of read.

**Comment by alan-parsiq** [comment]
Hey, @alxs !

In order to match the opne-source policy - we had to rework the Grant proposal! Our Grant proposal will account the costs required for the Blockchain Layer Integration where all implemented components will be open-sourced. However, we are anyway adding the support for necessary Streams of Polkadot & Kusama Balances module events and all the rest features in the Portal to have a complete support for Polkadot and Kusama DOT/KSM Transfers monitoring - but without registering the costs.

Also, regarding the Guardian comparison:
Guardian is based on creating yaml files with the config inside to moitor for specific activities that meet given conditions and to perform actions if necessary. 

PARSIQ on the other hand, provides a tool in the name of ParsiQL - the domain-specific language for manipulating Streams of Events. And in our case - we introduce more opportunities for scriptability and condition definitions. In addition, we have a UI Code Editor on the Portal, comfortable User Data management (to setup monitoring addresses, thresholds and other monitoring/tracking-related configurable information) and the simple setup for Transports (the way how data is delivered).

**The following stays out-of-scope of Grant proposal, but worths to be mentioned, since includes more key points regarding additional Integrations and open-source solutions.**

We will be also performing additional Integrations to support popular Parachains on Polkadot, like Acala or performing on-chain actions.

We as PARSIQ, personally see that despite the fact that currently we have put more effort on creating a Web App (in the name of PARSIQ Portal) with a lot of features hiding complexities (like setting up a Blockchain Node, connecting to it, processing/aggregating/transforming raw information from Blockchain activites to Events, formings Streams of Events, executing Smart-Triggers) - we are also eager to introduce PARSIQ Community Edition where a lot of those things will be possible to do without using the PARSIQ Portal.

It will more remind a simplified version of PARSIQ Platform that can be run on-premise with a simple Dashboard included.

**Comment by alxs** [comment]
Thank you for updating your proposal. As I said, I think this is a cool project and I'm happy to hear that you'll be adding support for Polkadot/Kusama even if it's not accounted for in the grant. However, allow me to highlight again that deliverables also cannot rely on closed-source software to function. So as long as the PARSIQ Platform is closed-source, we cannot fund anything that is meant to be used in conjunction with it.

What we could fund however, would be the development of an open-source monitoring service and a library to work with it (as long as there is interest from the rest of the committee) which I think is what we're talking about here, but this should be unrelated to the PARSIQ platform and at that point I would suggest to close this application and create a new one that solely concerns these. You would then of course be free to use this library for your platform. Looping in @Noc2 who will confirm or provide more feedback.

Besides, I'm not sure there isn't already something that does what you propose, David has a better overview. To be clear:
- Are /block/:blockHash and /block/limits/:from/:limit the only functions that the API would provide?
- What interface would the library expose exactly? The example you provide to compare it against has no documentation.

**Comment by Noc2** [comment]
Another project, which you should be aware of is aurras by HugoByte, see https://github.com/HugoByte and https://github.com/w3f/Open-Grants-Program/blob/master/applications/project_aurras_mvp_phase_1.md

**Comment by alan-parsiq** [comment]
Thank you @alxs & @Noc2 for comments and references!

We have discussed internally and taking into account some factors (i.e. open-souce policy) - we should close the current PR for now and once possible start fresh with a new proposal matching the necessary requirements. 

We are eager to provide the right real-time monitoring solution for the whole ecosystem - we will do our best to find the right approach there.

**Pull request closed without merging**
