### PR TITLE
WebAssembly Runtimes Fuzzing

### PR DESCRIPTION
**Pull request by pventuzelo**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by folsen** [comment]
I just had one point of clarification, this is work that will go into Octopus right? So Octopus will be the tool to test all these wasm execution engines (we tend to call it that to not confuse it with the runtime term used in Polkadot/Substrate which is a wasm blob).

I think this would be very valuable, particular for new development.

> 2.  | CLI tool | Command line tool allowing execution of wasm modules through all runtimes. |  

This would also be quite valuable for us in testing the polkadot runtime (the wasm blob) essentially running a given blob through all possible runtimes and ensuring the result is the same for all.

**Comment by pventuzelo** [comment]
This tool (WebAssembly Runtimes Fuzzing i.e WARF in short) will be focused on testing/fuzzing wasm execution VM implementation. [Octopus](https://github.com/pventuzelo/octopus) is more focused on analysis of wasm module/blob.

This project will be independent of Octopus even if personally I'm planning to use WARF inside octopus to dynamically detect security issues inside wasm module and make in-process fuzzing of wasm module using the CLI tool.

Thx @folsen for the precision regarding polkadot runtime naming.

**Comment by Noc2** [comment]
Hi Patrick. Sorry for the late reply here. As I previously said, I think the tool sounds useful to me and the pricing seems fair. From looking at the milestone again, I have just one additional request. Could you add docker images, delivery reports (e.g. how to install, compile, run, and/or test the deliverable) as well as unit tests if appropriate to the milestones? Just to make it easier for us to test the deliveries ;-). Also which programming language are you planning to use (python)?

**Comment by pventuzelo** [comment]
Hi David, 
I've updated the milestones ;) 

Regarding the programming language used in the project, I think mainly Rust for fuzzing development and Python for scripting.

**Pull request merged**
