### PR TITLE
Raze Network Application

### PR DESCRIPTION
**Pull request by razenetwork**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks interesting. However, your grant is currently above the 30k limit for initial open grant application. I also recommend switching to a payment in DAI, since we will update the BTC payment process in the coming days. Did you previously already work on zkps or could share relevant open source work? Why are you working on your own  cross-chain bridge? Couldn’t you potentially leverage https://github.com/Snowfork/polkadot-ethereum or https://github.com/ChainSafe/ChainBridge? How is your solution different from the above?

**Comment by resovepant8** [comment]
> **Thanks for the application. Looks interesting. However, your grant is currently above the 30k limit for initial open grant application. I also recommend switching to a payment in DAI, since we will update the BTC payment process in the coming days.** 

Thanks for your advice. Already change the total cost to 30k DAI. Please let me know if you have any questions regarding this change.

> **Did you previously already work on zkps or could share relevant open source work?** 

Yes, we have extensive experience in zkps especially in zkps with transparent setup. Our team member has been core members of projects using zkps in the Ethereum ecosystem. Since we intend to keep our identities confidential, I wonder whether there is any chance you could send us your email address so that we could send you an email with the link to our open source work? Thanks.  

> **Why are you working on your own cross-chain bridge? Couldn’t you potentially leverage https://github.com/Snowfork/polkadot-ethereum or https://github.com/ChainSafe/ChainBridge? How is your solution different from the above?**

Thanks for introducing us to the work of ChainBridge. Sounds like a very interesting project. As mentioned in our proposal, a cross-chain bridge mainly aims to map ETH or other ERC-20 tokens to the Polkadot ecosystem and thus is not our core contribution, we will definitely leverage the existing work if it serves our goal.

**Review by resovepant8 — APPROVED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply. Could you share the information with grants@web3.foundation? Also could specify the technical details of the deliveries more concrete?  For example, what exactly are you going to develop as part of  the “cross-chain bridge” or could you provide more information regarding the zkps? Do you also develop an off-chain solution for the zkps (e.g. UI, etc.)?

**Comment by resovepant8** [comment]
**> Sorry for the late reply. Could you share the information with [grants@web3.foundation](mailto:grants@web3.foundation)?** 

Thanks for your information. Already sent you an email to share the link to our repo. Feel free to reply to my email if you have any further questions. 

**> Also could specify the technical details of the deliveries more concrete? For example, what exactly are you going to develop as part of the “cross-chain bridge” or could you provide more information regarding the zkps?** 

We didn't know there already exist a cross-chain bridge project like ChainBridge before submission. We are most likely to invoke their work instead of building a bridge by ourselves since we now know their work. 

You can find the concrete statements of our ZKPs in the third and fourth figures of our proposal. The concrete design of the ZKP algorithms is a twist of the schemes proposed in the last two figures of the Zether paper: https://eprint.iacr.org/2019/191.pdf on Page 41 and 42 respectively. The main difference is that the burn-proof on Page 41 only considers the case where the user withdraws all the money in the account while our statement considers the case where the user might withdraw an amount smaller than the balance and the ConfTransfer proof on Page 42 does not consider the one-out-of-many proof part while ours does.     

> Do you also develop an off-chain solution for the zkps (e.g. UI, etc.)?

The zkp proof generation will be off-chain since the client is responsible for generating the proof, which is part of the transaction to trigger the smart contracts such as Mint, Transfer, and Redeem contracts in the proposal. But the proof verification will be part of the contract, and hence will be run on-chain.

**Review by resovepant8 — APPROVED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for sharing the additional information and the email. Could you integrate the off-chain part into the deliverables as well as the additional information you provided? Also could you update the bridge deliverable accordingly. Furthermore, it would still be nice if you could add more technical details (e.g. programming language) and potentially things like unit tests into the deliverables. The deliveries are basically the requirements of our contracts.

**Comment by resovepant8** [comment]
**> Thanks for sharing the additional information and the email. Could you integrate the off-chain part into the deliverables as well as the additional information you provided?**

Sure, already add "The main statements of the zero-knowledge proof schemes will be identical to those described in the CreateTransferTx and CreateRedeemTx algorithms." in the Milestone 1 deliverables and "...and we will provide a basic UI to take inputs from the users for the relevant algorithms." in the Milestone 2 deliverables. 

Furthermore, I have also added "The concrete design of the ZKP algorithms is a twist of the schemes proposed in the last two figures of the Zether paper: https://eprint.iacr.org/2019/191.pdf on Page 41 and 42 respectively. The main difference is that the burn-proof on Page 41 only considers the case where the user withdraws all the money in the account while our statement considers the case where the user might withdraw an amount smaller than the balance and the ConfTransfer proof on Page 42 does not consider the one-out-of-many proof part while ours does." as an independent paragraph in our proposal. 

**Also could you update the bridge deliverable accordingly. Furthermore, it would still be nice if you could add more technical details (e.g. programming language) and potentially things like unit tests into the deliverables. The deliveries are basically the requirements of our contracts.**

Regarding the language and unit tests, we add "The contracts will be first written in Solidity and then imported to EVM compatible substrate pallets." in the Milestone 1 deliverables and "The client will be written in Javascript..." in the Milestone 2 deliverables. We also add "Perform unit tests on the individual algorithms to ensure their safety. " in the Milestone 2 deliverables. 

Please let me know if there are any other questions.

**Review by resovepant8 — DISMISSED** [review]

**Comment by Noc2** [comment]
Thanks for the update. I shared your application with our researchers, to get a second opinion.

**Comment by razenetwork** [comment]
> Thanks for the update. I shared your application with our researchers, to get a second opinion.

**Comment by Noc2** [comment]
@razenetwork I sent you an email yesterday. Let me know if you haven’t received it.

**Comment by razenetwork** [comment]
> @razenetwork I sent you an email yesterday. Let me know if you haven’t received it.

I did not received your email. Can you send it again to contact@raze.network ?

**Comment by Noc2** [comment]
> > @razenetwork I sent you an email yesterday. Let me know if you haven’t received it.
> 
> I did not received your email. Can you send it again to [contact@raze.network](mailto:contact@raze.network) ?

I already received a reply, but I just forwarded the emails to contact@raze.network as well (Just to double check that I’m not talking with the wrong person)

**Comment by razenetwork** [comment]
> > > @razenetwork I sent you an email yesterday. Let me know if you haven’t received it.
> > 
> > 
> > I did not received your email. Can you send it again to [contact@raze.network](mailto:contact@raze.network) ?
> 
> I already received a reply, but I just forwarded the emails to [contact@raze.network](mailto:contact@raze.network) as well (Just to double check that I’m not talking with the wrong person)

Understand. The forward email is received by contact@raze.network.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Sorry for the late reply and thanks for sharing the additional info via email. However, I have another follow-up questions: I just realized that you want to implement one part as a Solidity smart contract, but it looks like you want to integrate everything else as substrate module in rust. What’s the reason for it? Could you potentially completely focus on substrate modules (or ink! smart contracts) and also provide unit tests for milestone 1? We don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point.

**Comment by resovepant8** [comment]
**> Sorry for the late reply and thanks for sharing the additional info via email. However, I have another follow-up questions: I just realized that you want to implement one part as a Solidity smart contract, but it looks like you want to integrate everything else as substrate module in rust. What’s the reason for it? Could you potentially completely focus on substrate modules (or ink! smart contracts) and also provide unit tests for milestone 1? We don’t fund the development of solidity smart contracts. The reason is that we are no experts when it comes to solidity and it’s very difficult to judge what is new and what does already exist at this point.**

Thanks for pointing out the problem with the language. Already change the language to ink!, and add unit tests for milestone 1. Please let me know if there is any other question.

**Review by Noc2 — DISMISSED** [review]
Looks good. Thanks for the update. I will share the proposal with the rest of the team.

**Comment by mmagician** [comment]
I'm a little unsure about the following statement:
> We will implement the zero-knoweldge proof schemes and create a Substrate module that incorporates the verification logic for the aforementioned modules. The main statements of the zero-knowledge proof schemes will be identical to those described in the CreateTransferTx and CreateRedeemTx algorithms. It will support the verification of mint, transfer, redeem, lock and unlock for mainstream Polkadot tokens such as DOT and KUSAMA and any ERC-20 token. The contracts will be first written in ink! and then imported to EVM compatible substrate pallets.

First you say that you're building a module (i.e. substrate pallet), but then say it's `ink!` - could you please clarify? Or are there two separate things?

In addition, rather than developing your own verification logic for ZKPs, perhaps you could investigate one of the existing solutions, such as [ZeroPool](https://github.com/zeropoolnetwork/zeropool-substrate) - this should speed up your development significantly. 

Regarding M2, could you specify which JS library you're planning to leverage for generating the proofs for `CreateTransferTx` etc.? Also, who's going to run it and where, is it the end-users? If so, can you please describe how the users' experience is going to look like in terms of running the client - is it integrated with a UI or CLI based, or perhaps part of another service?

**Comment by resovepant8** [comment]
**> I'm a little unsure about the following statement:
> 
> > We will implement the zero-knoweldge proof schemes and create a Substrate module that incorporates the verification logic for the aforementioned modules. The main statements of the zero-knowledge proof schemes will be identical to those described in the CreateTransferTx and CreateRedeemTx algorithms. It will support the verification of mint, transfer, redeem, lock and unlock for mainstream Polkadot tokens such as DOT and KUSAMA and any ERC-20 token. The contracts will be first written in ink! and then imported to EVM compatible substrate pallets.
> 
> First you say that you're building a module (i.e. substrate pallet), but then say it's `ink!` - could you please clarify? Or are there two separate things?**

Thanks for pointing this out. There is a mistake here. I have changed the language to Rust. 

**> 
> In addition, rather than developing your own verification logic for ZKPs, perhaps you could investigate one of the existing solutions, such as [ZeroPool](https://github.com/zeropoolnetwork/zeropool-substrate) - this should speed up your development significantly.
>** 

Thanks for pointing out this library. We will definitely check out this library. Since our scheme is based on Zether, we are also considering using some of the existing implementations of the Zether library to speed up the development process. 

**> Regarding M2, could you specify which JS library you're planning to leverage for generating the proofs for `CreateTransferTx` etc.?** 

We will leverage JS library such as bn.js(https://github.com/indutny/bn.js/), crypto(https://nodejs.org/docs/latest-v7.x/api/crypto.html#crypto_class_cipher) and elliptic(https://github.com/indutny/elliptic/) for the basic crypto operations. 

**Also, who's going to run it and where, is it the end-users? If so, can you please describe how the users' experience is going to look like in terms of running the client - is it integrated with a UI or CLI based, or perhaps part of another service?**

Yes, it will be the end-users. There will be a UI, where the clients can select which token they wish to transfer privately. There will be a registration or login page that allows the users to register a raze account and login to the account later. Once the user logins to the raze account, the raze account page will show the balance of anonymized token and native dot token. This page will also allow the users to perform the mint, transfer, and redeem operations.

**Comment by resovepant8** [comment]
> Thanks for fixing the ink! -> Rust part.
> 
**> Are you aware that generating ZKPs is computationally expensive and time consuming? If this is going to happen on the users' side, they will need to possess enough processing power (and time) to be able to perform any useful actions. Have you taken this into account when considering UX?**

Yes, I understand generating ZKP for a complex circuit would be very time-consuming and we do take that into account when considering UX. Since the statement of our ZKP is relatively simple, it actually wouldn't take that much time to generate the proof. For instance, for the case of CreateTransferTx (the most complex ZKP statement in our proposal), the computational cost is dominated by the "one-out-of-many" proof and range proof, which logarithmically depends on the ring size and bit length of the balance respectively. 
> 
**> Furthermore, it seems to me like you haven't researched the options fully regarding the libraries you're going to leverage, neither regarding proof generation on users' side nor verification in Rust. I would be generally happy to support your project, but before giving my approval I would like to ask you to dig a bit deeper into both and see if you can come up with a more concrete execution plan.**

There is indeed one specific project anonymous zether (https://github.com/ConsenSys/anonymous-zether) we have found to be particularly useful. Although the verification isn't written in Rust, we can translate it to Rust.

**Comment by mmagician** [comment]
I see that you're going to implement a Sigma-Bullets proof system, right?

Just a final format note - could you be more precise with the following statement please?
> We will implement the zero-knoweldge proof schemes and create a Substrate module that incorporates the verification logic for the aforementioned modules.

1. Please specify the proof scheme
2. If I understand correctly, creating proofs will happen on client side (JS lib?) & verification in substrate - in this case it might be better to split these into separate deliverables and be explicit about the separation. 

Lastly, I haven't noticed earlier, but it seems like you're still confusing the pallets & smart contracts:
> Raze Substrate module for private payment [...] The contracts will be first written in Rust and then imported to EVM compatible substrate pallets.

Well, you would either write a substrate module (aka pallet) or a smart contract (in `ink!`) which is then deployed to some chain supportive of `ink!` smart contracts. Also there seems to be confusion about the EVM module - you would only need it if you're writing your contract in Solidity. Otherwise, your contract would be deployed to a [contracts](https://github.com/paritytech/substrate/tree/master/frame/contracts) pallet. 

I would be grateful if you could clarify these points before proceeding.

**Comment by resovepant8** [comment]
**> I see that you're going to implement a Sigma-Bullets proof system, right?**

Yes. 

**> Just a final format note - could you be more precise with the following statement please?
> 
> > We will implement the zero-knoweldge proof schemes and create a Substrate module that incorporates the verification logic for the aforementioned modules.
> 
> 1. Please specify the proof scheme**

Sure, already add "We will implement the zero-knoweldge proof schemes presented in the [Zether framework](https://eprint.iacr.org/2019/191) " in m1. 

**> 2. If I understand correctly, creating proofs will happen on client side (JS lib?) & verification in substrate - in this case it might be better to split these into separate deliverables and be explicit about the separation.
>** 

Sure, already add "More specifically, it will support the verification algorithms of zero-knowledge proofs in these modules. " in m1 and "More specifically, it will include all the proof generation algorithms for these transactions. We will also provide the necessary UI to enable the users to interact with the proof generation algorithms." in m2. 

**> Lastly, I haven't noticed earlier, but it seems like you're still confusing the pallets & smart contracts:
> 
> > Raze Substrate module for private payment [...] The contracts will be first written in Rust and then imported to EVM compatible substrate pallets.
> 
> Well, you would either write a substrate module (aka pallet) or a smart contract (in `ink!`) which is then deployed to some chain supportive of `ink!` smart contracts. Also there seems to be confusion about the EVM module - you would only need it if you're writing your contract in Solidity. Otherwise, your contract would be deployed to a [contracts](https://github.com/paritytech/substrate/tree/master/frame/contracts) pallet.
>** 

Thanks for pointing this out. Already change "The contracts will be first written in Rust and then imported to EVM compatible substrate pallets." to "The contracts will be imported to substrate pallets." We will focus on building a substrate module. 

> I would be grateful if you could clarify these points before proceeding.

**Comment by mmagician** [comment]
> The contracts will be imported to substrate pallets.

But you just said "We will focus on building a substrate module." -> so there should be no contracts to speak of, as far as I understand.

The rest looks good

**Comment by resovepant8** [comment]
> > The contracts will be imported to substrate pallets.
> 
> But you just said "We will focus on building a substrate module." -> so there should be no contracts to speak of, as far as I understand.
> 
> The rest looks good

**Oh yeah, you are totally right. I delete the sentence "The contracts will be imported to substrate pallets" since I've mentioned substrate pallets several times in m1.**

**Comment by resovepant8** [comment]
Hey Marcin,

I am glad to hear that the rest of this application looks good. Would you
please let me know how should we proceed with this application? Thanks.

**Comment by alxs** [comment]
HI @resovepant8, apologies for the inactivity from our side. @mmagician has been OOO for the past few days. Are you aware of [Zerochain](https://github.com/LayerXcom/zero-chain)? It is somewhat outdated at this point, but it's also based on Zether. I have the impression you'd be able to leverage a lot of the work done there for milestone 1. Please have a close look at it.

Besides, could you decide on a specific cross-chain bridge for deliverable 2 of milestone 1 and specify how exactly you plan to integrate this? And could you confirm that all algorithms of the Zether paper will be supported as part of milestone 1. Many thanks. All in all, this looks pretty good to me.

**Comment by resovepant8** [comment]
> HI @resovepant8, apologies for the inactivity from our side. @mmagician has been OOO for the past few days. Are you aware of [Zerochain](https://github.com/LayerXcom/zero-chain)? It is somewhat outdated at this point, but it's also based on Zether. I have the impression you'd be able to leverage a lot of the work done there for milestone 1. Please have a close look at it.

**Hey @alxs, thanks for your question. Yes, we know the Zerochain project well even before writing this proposal and will definitely leverage their code in our development if necessary.** 

> Besides, could you decide on a specific cross-chain bridge for deliverable 2 of milestone 1 and specify how exactly you plan to integrate this? 

**We plan to use ChainBridge to map ERC-20 tokens to the Polkadot ecosystem at the moment. After the ERC-20 tokens are mapped to the Polkadot ecosystem, the payment privacy of the mapped token can be protected exactly like the native tokens of the Polkadot ecosystem such as DOT.** 

> And could you confirm that all algorithms of the Zether paper will be supported as part of milestone 1. Many thanks. All in all, this looks pretty good to me.

**Yes, we will support all the algorithms of the Zether paper. Thanks for your questions.**

**Comment by alxs** [comment]
Okay. A few more inputs:

- If you implement this as a substrate module, you won't be able to deploy it just on any chain. You have no plans to deploy your own Substrate chain or a parachain, right? In that case you'll need to talk to teams who may be interested in including your pallet(s) in their parachain. Could you highlight potential candidates and whether you have already reached out to any of them?
- I guess the "bridge integration" then only concerns which currencies your pallet will support, specifically the representation of ERC-20 tokens on Substrate. That is, unless you want to bundle the ChainBridge pallet together with yours, which I would advise against. But let me know if this is your intention. So, in summary, milestone one would be a pallet that supports Zether statements for the network's native asset and ERC-20 tokens?
- Wouldn't offering support for [MultiAssets](https://github.com/paritytech/xcm-format/blob/master/README.md#multiasset-universal-asset-identifiers) be preferable and render deliverable 2 superfluous? You can use ChainBridge's or [Snowfork's](https://github.com/Snowfork/polkadot-ethereum/blob/main/docs/markdown/using-snowchain/building-with-snowbridge/xcm-for-assets.md) ERC-20 representations if you need to do anything different for those, but I don't know why you would.
- Anonymity mining as in, like [Tornado.Cash's](https://github.com/tornadocash/tornado-anonymity-mining)? Do you plan to just port their work or do you have your own ideas in this regard?
- I have serious second thoughts about your future plans and token launch. Could you comment on:
  - How exactly you plan to implement private bridges. This is a hard problem as of yet unsolved AFAIK and it's a bold claim to make.
  - Since Raze will be more of an add-on for other parachains, what's the use of your token exactly? What governance proposals could users possibly vote on? Also none of the other proposed usages convinces me. In general, you seem to be pretty focused on this with a token sale already scheduled for Q2 which I have to say is a big red flag for me.
  - The whitepaper is scheduled for this quarter. Do you have a preliminary version you could share?

**Comment by resovepant8** [comment]
> Okay. A few more inputs:
> 
> * If you implement this as a substrate module, you won't be able to deploy it just on any chain. You have no plans to deploy your own Substrate chain or a parachain, right? 

**NO**

In that case you'll need to talk to teams who may be interested in including your pallet(s) in their parachain. Could you highlight potential candidates and whether you have already reached out to any of them?

**We are talking to teams such as Acala and Equilibrium.** 

> * I guess the "bridge integration" then only concerns which currencies your pallet will support, specifically the representation of ERC-20 tokens on Substrate. 

**Yes.** 

That is, unless you want to bundle the ChainBridge pallet together with yours, which I would advise against. But let me know if this is your intention. So, in summary, milestone one would be a pallet that supports Zether statements for the network's native asset and ERC-20 tokens?

**Yes, this is exactly our goal.** 

> * Wouldn't offering support for [MultiAssets](https://github.com/paritytech/xcm-format/blob/master/README.md#multiasset-universal-asset-identifiers) be preferable and render deliverable 2 superfluous? You can use ChainBridge's or [Snowfork's](https://github.com/Snowfork/polkadot-ethereum/blob/main/docs/markdown/using-snowchain/building-with-snowbridge/xcm-for-assets.md) ERC-20 representations if you need to do anything different for those, but I don't know why you would.

**Yes, the whole point of using Chainbridge in our current design is to map ERC-20 token to the Polkadot ecosystem.** 

> * Anonymity mining as in, like [Tornado.Cash's](https://github.com/tornadocash/tornado-anonymity-mining)? Do you plan to just port their work or do you have your own ideas in this regard?

**The intention of anonymity mining is to attract more users to our ecosystem. If you are talking about token economics for anonymity mining, there are many potential choices and the anonymity mining scheme of Tornado is not necessarily the best.** 

> * I have serious second thoughts about your future plans and token launch. Could you comment on:
>   
>   * How exactly you plan to implement private bridges. This is a hard problem as of yet unsolved AFAIK and it's a bold claim to make.

**We are not trying to implement a private bridge. Our proposal only mentions we are using the existing implementation of bridges that can map ERC-20 tokens to the Polkadot ecosystem.** 

>   * Since Raze will be more of an add-on for other parachains, what's the use of your token exactly? What governance proposals could users possibly vote on? Also none of the other proposed usages convinces me. In general, you seem to be pretty focused on this with a token sale already scheduled for Q2 which I have to say is a big red flag for me.

**As the governance tokens of many DeFi projects, the voters will decide what kind of projects we should work with since our project is a fundamental infrastructure for building privacy-preserving DeFi in Polkadot. The token holders will also be able to receive the economic return of our ecosystem.** 

>   * The whitepaper is scheduled for this quarter. Do you have a preliminary version you could share?

**As you can see from our proposal, our scheme is largely a quite direct application of Zether scheme to the Polkadot ecosystem, you can view [Zether paper](https://eprint.iacr.org/2019/191) as the preliminary version.**

**Comment by alxs** [comment]
Thank you for your answers.

I was rather referring to the design and technical implementation of anonymity mining. As far as I'm aware of, the concept was introduced by Tornado.Cash so it'd make sense if you stated whether you'll be porting their work or if you have a completely different idea in mind. As for the token economics, this is up to you but maybe you could specify if you'll use a similar model of the form zk operations -> points -> minting.

Regarding the private bridge, I was referring to your website since you list a "Secret DeFi Bridge" as a product. I'd still like to hear what you actually mean by this but I guess in the end it isn't directly related to the grant.

I would have liked to see your own whitepaper but I'm cool with nothing for the application.

Lastly, I still think your project would gain a lot in terms of attractiveness if you made it work for _any_ asset instead of just native + ERC-20 and I don't think it would constitute a lot more work, but this is up to you.

Could you add your clarifications from our exchange to the application and just go through it one last time? There are still mentions of a smart contract on it. Then I'd likely go ahead and accept it.

Also just be aware that we've recently started putting extra care into making sure that projects always comply with the appropriate licenses. The fact that you didn't mention projects you'd be basing your work on that you knew about and the re-uploaded repositories on your organisation make me a bit nervous in this regard so I'd like to ask you to please:
  - remove said repositories from your organisation and fork them instead unless you have any reason against this.
  - take extra care to comply with any appropriate licenses of existing projects you'll be leveraging in your work, in case the application is accepted. [Here](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) is a brief overview of what it implies to base your work on projects with specific licenses.

Lastly, just a reminder not to publicly announce the grant or use the badge until we've accepted the first milestone, again, assuming the application is accepted.

**Comment by resovepant8** [comment]
> Thank you for your answers.
> 
> I was rather referring to the design and technical implementation of anonymity mining. As far as I'm aware of, the concept was introduced by Tornado.Cash so it'd make sense if you stated whether you'll be porting their work or if you have a completely different idea in mind. As for the token economics, this is up to you but maybe you could specify if you'll use a similar model of the form zk operations -> points -> minting.
> 

**Thank you for your questions. The general principle of our mining program should be very close to that of Tornado.cash, i.e., to encourage the users to use our product and convert their assets into the anonymized tokens in the raze network. Each time a user converts its token into the anonymized form, he or she should be able to accumulate a certain amount of mining power.** 

> Regarding the private bridge, I was referring to your website since you list a "Secret DeFi Bridge" as a product. I'd still like to hear what you actually mean by this but I guess in the end it isn't directly related to the grant.
> 
> I would have liked to see your own whitepaper but I'm cool with nothing for the application.
> 
> Lastly, I still think your project would gain a lot in terms of attractiveness if you made it work for _any_ asset instead of just native + ERC-20 and I don't think it would constitute a lot more work, but this is up to you.
> 

**At the moment we will focus on native+ERC-20, but we will definitely try to ensure our network is compatible with as many token standards as possible.** 

> Could you add your clarifications from our exchange to the application and just go through it one last time? There are still mentions of a smart contract on it. Then I'd likely go ahead and accept it.
> 

**Thanks for pointing that out. I have replaced all the "contract" in the proposal either with "pallet" or "module".** 

> Also just be aware that we've recently started putting extra care into making sure that projects always comply with the appropriate licenses. The fact that you didn't mention projects you'd be basing your work on that you knew about and the re-uploaded repositories on your organisation make me a bit nervous in this regard so I'd like to ask you to please:
> 
> * remove said repositories from your organisation and fork them instead unless you have any reason against this.

**Thanks for pointing that out. Already remove the said repo. We will definitely take extra care to comply with the license requirements henceforth.** 

> * take extra care to comply with any appropriate licenses of existing projects you'll be leveraging in your work, in case the application is accepted. [Here](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) is a brief overview of what it implies to base your work on projects with specific licenses.
> 
> Lastly, just a reminder not to publicly announce the grant or use the badge until we've accepted the first milestone, again, assuming the application is accepted.

**We will definitely follow your advice on the timing requirement of the public announcement. **

**Comment by alxs** [comment]
I'm afraid I won't support this application after all. I still see a number of red flags with the project and you haven't proven a lot of past experience apart from some work by a team member on a previous project.

Your answer to my question regarding anonymity mining still provides no technical details, nor any of your previous answers for that matter. Also the cloned repositories are still in your organisation.

You've ignored a few of my questions and seem to be unclear on major aspects of your application, which have been amended in the course of the conversation without any significant input from your side.

All in all, although I would have liked to support the development of milestone 1 in specific I won't be considering this any further due to the concerns above.

**Comment by resovepant8** [comment]
> I'm afraid I won't support this application after all. I still see a number of red flags with the project and you haven't proven a lot of past experience apart from some work by a team member on a previous project.
> 
**Sorry to hear that. Regarding our experience, if you could leave me your email address, we will send you my previous email records with @Noc2 in which I have proved to David our experience. We have always worked as a team and we can get things done. **  

> Your answer to my question regarding anonymity mining still provides no technical details, nor any of your previous answers for that matter. 

**Sorry about the confusion. At the moment, it seems the most straightforward way is certainly directly porting the anonymity mining scheme of Tornado.cash. We will update the proposal accordingly if this answer works for you.**

Also the cloned repositories are still in your organisation.

**Would you please let me know which repos you are referring to? We will delete them immediately.** 

> You've ignored a few of my questions and seem to be unclear on major aspects of your application, which have been amended in the course of the conversation without any significant input from your side.
> 
**Sorry for ignoring your question regarding "secret defi bridge" and white paper. As mentioned in my previous answer, we are not trying to implement a secret bridge and this is most likely a misnomer. Regarding the white paper, we don't have an official version yet since our project is a pretty straightforward application of Zether framework to the Polkadot ecosystem. We will definitely send you the whitepaper when it's ready.**  

> All in all, although I would have liked to support the development of milestone 1 in specific I won't be considering this any further due to the concerns above.

**Would it work if we delete Milestone 2 and only ask for 10K-DAI grant for the support of milestone 1? Please let me know. Thanks.**

**Comment by alxs** [comment]
Thanks for addressing my concerns, but my decision is final. Just wanted to add that I'm aware of said conversation and the repositories I was referring to are [this one](https://github.com/Raze-Net/zero-chain) and [this one](https://github.com/Raze-Net/anonymous-zether).

**Comment by alxs** [comment]
I'm closing the application since it's been inactive for the past two weeks and there seems to be no interest from the rest of the committee either. Thank you for your efforts and best of luck with the project.

**Pull request closed without merging**
