### PR TITLE
Add CN Application Template

### PR DESCRIPTION
**Pull request by ansonla3**
# Grant Application Checklist

- [ ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [ ] A BTC address for the payment of the milestones is provided inside the application.  
- [ ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [ ] The total funding amount of the project is below CHF 30k at the time of submission.
- [ ] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by WannaM** [comment]
Do we need Chinese version?

**Comment by Noc2** [comment]
Thanks @ansonla3 . Could you point out that the information still needs to be submitted in English for the rest of the committee and that the template is mostly for informational purposes.

**Comment by ansonla3** [comment]
@Noc2 please check ;)

**Comment by Noc2** [comment]
Thanks!

**Pull request merged**
