### PR TITLE
Coinversation

### PR DESCRIPTION
**Pull request by Coinversation**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application, but we need more details in order to consider your application:

- Which technologies/programming language are you planning to use (e.g. substrate, ink)? 
- Could you take a look at the [polkadot stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#link-chains-and-modules) and point out how your solution is different from existing implementations (especially acala and laminar)? 
- It seems you don’t want to become a parachain of kusama or polkadot in the future and instead create a separate network, which is connected via a bridge, correct? How are you planning to create this bridge?

**Comment by Coinversation** [comment]
@Noc2 Thank you for your response!

> Which technologies/programming language are you planning to use (e.g. substrate, ink)?

We are planning to realize the functions of Coinversation Protocol by ink! smart contract.

> Could you take a look at the polkadot stack and point out how your solution is different from existing implementations (especially acala and laminar)?

The biggest difference between Coinversation Stablecoin and Acala Stablecoin is that there are no stability fees or interest in Coinversation, but stablecoins are issued in a synthetic asset collateral pool. Therefore, the cost that users pay to generate Coinversation Stablecoin (cUSD) through collateral is determined by the relative change of all synthetic assets in the entire system, rather than artificial regulations in other decentralized stablecoins (e.g. Acala). This cost is more market-oriented, and at the same time it is equivalent to the inflation rate of stablecoin to world assets. And the difference between Coinversation and Laminar is that Laminar uses off chain assets as collateral (e.g. US dollars), but Coinversation Protocol will use mainly on-chian assets as collateral. Especially, DOT will be one of the most important collateral in Coinversation, which will boost the usage of DOT. Besides, we will also have off chain assets from Alliance chain. So, basically, Coinversation will support much wider types of assets than Laminar will.

> It seems you don’t want to become a parachain of kusama or polkadot in the future and instead create a separate network, which is connected via a bridge, correct? How are you planning to create this bridge?

Actually, we are not creating a separate network. We will surely run on a parachain of Polkadot. Our technical team is evaluating Acala and Phala and considering working with them, smart contracts will run on these parachains.

**Comment by Noc2** [comment]
Sounds good. Could you integrate this information into the deliverables of the milestones and the application? Also could you potentially add documentation or tutorials to the milestones? And generally try to specify the deliverables as much as possible. These are basically the requirements of the contract.

**Comment by Coinversation** [comment]
@Noc2 Thank you for your reminder. According to your request, we have made changes. Please review again.

**Review by Noc2 — APPROVED** [review]
Looks good to me. Thanks for the update.

**Review by RouvenP — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Comment by coin-pro** [comment]
@Noc2 
I am the team leader and proposer, Dr. Qiuye. Due to cooperation reasons, I withdrew from the Coinversation Protocol project together with the technical team in January 2021. At present, the project is taken over by the original operation team and continues to operate. Whether the subsequent project can complete this Grant and anything related to the project has nothing to do with me and the technical team, hereby declare.

**Comment by Noc2** [comment]
Thanks for the information @coin-pro. Is the @conversationpro github account still controlled by the team working on the application? If not, we probably need to update the grant application. Are you still planning to deliver the project?

**Comment by coin-pro** [comment]
The @conversationpro github account has been handed over to the operation team. I don’t know whether they will continue to deliver the project. I'm sorry, the technical team and I have already withdrawn from the Coinversation Protocol project, and we don't understand the situation of the project anymore.

**Comment by conversationpro** [comment]
Hi David,


This is the CEO of conversation protocol, Lin Chen. It’s really pity that Qiuye couldn’t work with us and withdrew from our program. Qiuye has handed all the team accounts back to the team today.&nbsp;


The good news is a stronger technical team had taken over the development work in Jan 2021, and had already uploaded some part of the code on GitHub. Sure that the @coinversationpro GitHub account is still controlled by our team which is working hard on the application.&nbsp;


I apologize for the trouble caused by didn't updating the personnel adjustment of the team in time with Web3, as the technical team has been fully engaged in the development of smart contracts in the past three months.


Really appreciate for the concern of Coinversation team. Looking forward for the next step of Grant application.




Best,
Lin Chen

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"David ***@***.***&gt;;
Date: &nbsp;Mon, Apr 19, 2021 04:04 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [w3f/Open-Grants-Program] Coinversation (#105)

&nbsp;



 
Thanks for the information @coin-pro. Is the @conversationpro github account still controlled by the team working on the application? If not, we probably need to update the grant application. Are you still planning to deliver the project?

**Comment by Noc2** [comment]
Thanks for the update. Please keep us posted regarding the progress. Also it would be nice if you could already share the code which you uploaded on GitHub with us. We usually terminate grants if teams are delayed and no longer actively working on the project.

**Comment by conversationpro** [comment]
Hi David,

Hope everything goes well. Today we are uploading the latest codes but finding that the grants is closed. As the overall scope of the project doesn’t change, we are still developing following the original plan and plan to deploy on Plasm next month. 
Could you please reopen the grant so that we could continue working on this? Thank you so much.

**Comment by conversationpro** [comment]
Hi David, 

We are now trying to submit the milestone deliverables. We are confused about the steps of the milestone deliverables. 
i. Do we have to send the email to grants@web3.foundation for the deliverable?
ii. In the step 4, there is an invoice form we need to fill, but we don't have the invoice. Could you please tell us where can we get it? or we can skip this step and pull request directly?

Thanks for your help. Looking forward to hear you back!

**Comment by Noc2** [comment]
Hi. You don’t have to send us an email. Simply follow these steps: https://github.com/w3f/Grant-Milestone-Delivery#mailbox-milestone-delivery-process. The invoice should contain all the information, which is mentioned in the google form (e.g. our address), but apart from that we don’t have any specific requirements or a template. Potentially there are additional legal requirements depending on your country, but that is something which we usually don’t check. In general you find a lot of different invoice templates on the internet, which you might be able to use. Let me know if you have any other questions.

**Pull request merged**
