### PR TITLE
Create NuLink.md

### PR DESCRIPTION
**Pull request by pawnz0**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I’m just putting a reference here to your previous application: https://github.com/w3f/Open-Grants-Program/pull/345 Did you talk to nucypther directly? How exactly would a watcher network work? This sounds highly centralized to me. To be honest, I personally think that your previous application was more useful for us, since this would basically implement the same but with an additional (potentially centralized) component integrated.

**Comment by pawnz0** [comment]
Thanks, Noc. Yes, we have met with Nucypher core team several times and they suggest us to reuse their proxy network Ursulas(since there is already a mature workers network, we don't need to reconstruct a similar one in Polkadot). And the watcher network is the current choice. Later we would shift this to Snowbridge or other ETH-Polkadot bridge to make it decentralized. In our last proposal,  your teammate suggest us to bridge Nucypher network to Polkadot instead of rebuilding a whole Nucypher network in Polkadot. We re-consider his suggestion and discussed with Nucypher team to make this new proposal. If you have any other issue please let me know.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the quick reply. I personally disagree with Jeff’s suggestion regarding bridging. I think a direct integration has a lot of advantages and from my experience the grants committee is currently also reluctant to fund bridges, especially if they contain rather centralized components. Independent of it I will share the application with the rest of the team, but I would actually be much more interested in your previous application.

**Comment by cygnusv** [comment]
Hey @Noc2, this is David from the NuCypher team. @pawnz0's team talked to us about this proposal and we gave them some feedback and recommendations. Their original idea implied replicating the NuCypher Network from scratch in Polkadot, which would be by itself a daunting task. But, putting aside this effort, it would also imply attracting, on-boarding and providing support to a collective of node operators to stake in this mirror network, essentially, replicating the supply side of the NuCypher network. After doing this with over 2,000 nodes, we learned how challenging and time-consuming this task is as well. 

Instead, if this project assumes that the supply side is covered, by bridging it from the existing NuCypher network, it can focus exclusively in what users and applications on the Polkadot side need. I do agree that there's a centralized component in this proposal, but in my view it can serve as a first step while ETH-Polkadot bridges consolidate.

**Comment by alxs** [comment]
Hey @cygnusv, thanks for checking in and adding your perspective. Even though I can see where @Noc2 is coming from, what you're saying also makes sense to me and I agree this can indeed serve as a first step.

However I'm also wondering how the watcher network would work exactly, and I'm concerned it's currently not included in the deliverables as, the way I see it, the rest of them are of no use without it.

Nevertheless I also wonder whether this is needed at all. I.e. the watcher network would basically be a number of nodes keeping tabs on the NuCypher smart contracts and then submitting changes, right? So you could potentially simply use something like [ChainBridge](https://moonbeam.network/community/projects/chainbridge-by-chainsafe/) which should soon be available on Kusama anyway. Or how would this watcher network be different from a PoA bridge?

I'm betting by the time this is finished there's already an Ethereum bridge deployed somewhere or close to being deployed, so maybe you can aim straight for this option. Though in all fairness I'm probably being too optimisic.

And lastly: would it be possible to supply both blockchains using the same network of Ursulas? Couldn't this work cross-chain?

**Comment by cygnusv** [comment]
> And lastly: would it be possible to supply both blockchains using the same network of Ursulas? Couldn't this work cross-chain?

Yes! That's why, IMHO, an approach that tries to make use of NuCypher's existing supply of Ursulas shows more potential. NuCypher's ERC20 token and staking information currently lives on Ethereum, but that's something that's part of the work token model, and not important for users and applications. In fact, from that perspective, our network of Ursulas can be blockchain-agnostic, assuming projects like NuLink enabling native collection of service fees in other L1s. In Ethereum, we collect fees on ETH, but here it could be in DOT or even in a stablecoin (I guess depending on which parachain NuLink ends up targeting).

**Comment by pawnz0** [comment]
David, Thanks for your clarification. 

NuLink is exactly trying to supply Polkadot with Ursulas network. And for the watcher network, we original design it as a POA bridge. Some selected relayer nodes would have the authority to update the newest state under multisignature mechanism. We are not aware that Chainbridge would be available on Kusama soon. We could directly use Chainbridge to provide information for mirror pallet instead of the watcher network if you think this is a better option.

**Comment by alxs** [comment]
@pawnz0 @cygnusv how about we discuss this a bit more extensively in a quick call? I'm OOO for the next ~2 weeks, but both tomorrow afternoon or Friday would still work well for me (CET). Feel free to send me an invite to `aleixo@web3.foundation`.

**Comment by mmagician** [comment]
> We will develop a mirror pallet which can retrieve the information of stakers and bonding workers from Nucypher contracts in Ethereum. At current stage we consider constructing a watcher network maintained by NuCypher team. The watcher network would relay such information to the mirror pallet

In general I'd be fine with a **centralised** watched network, as long as it's **trustless**. Basically, what I'm looking for would be a way to ensure correctness and non-forgeability of the data supplied to substrate. Could the pallet-relayer connection support such functionality? Ideally, anyone would be able to just spin up such a watcher and have it supply data to the mirror module, e.g. in case the watcher maintained by a third party is unavailable.

**Comment by pawnz0** [comment]
We have update the proposal and give the design of the watcher network.

**Comment by mmagician** [comment]
So just to re-iterate on my last questions: in case a new user wants to run their own watcher, how easily could they get their PK included in the mirror pallet's storage?

**Comment by pawnz0** [comment]
> So just to re-iterate on my last questions: in case a new user wants to run their own watcher, how easily could they get their PK included in the mirror pallet's storage?

They can not. The watcher network is designed as a stable set. The watcher list is set up when the mirror pallet is deployed. In the future we would substitute the watcher network to a ETH bridge. The mirror pallet would be able to interact with the bridge to get update information of Ursulas nodes then.

**Comment by mmagician** [comment]
But then, isn't verifying 2/3 of the signatures pointless, if these are pre-selected (i.e. centralised?) watchers?

**Comment by pawnz0** [comment]
> But then, isn't verifying 2/3 of the signatures pointless, if these are pre-selected (i.e. centralised?) watchers?

Yes, they are pre-selected nodes. NU cypher team would manage this network. The signature mechanism is in case some nodes is offline.

**Comment by mmagician** [comment]
Just to make sure I understand this correctly: Alice would be able to decide if she wants to set up the policy on Ethereum or Polkadot, and con

**Comment by cygnusv** [comment]
Yes, the idea is that Alices can decide to pay for policies either on the Ethereum side or in the Polkadot side; it's essentially opening a new market for NuCypher workers that currently only can get fees from Ethereum. 

I don't think it has to be necessarily opt-in, as the work itself (i.e. the distributed re-encryption process) is always off-chain and blockchain-agnostic. It may be simpler to just show the workers that Polkadot is an additional source of revenue for them, than introducing an opt-in process that may produce more UX friction for workers .

**Review by mmagician — APPROVED** [review]
Ok, that sounds good. I think I understand your proposal a bit better now and will be happy to support the project!

**Review by mmagician — CHANGES_REQUESTED** [review]
Btw, I still don't think the following makes sense:
> The signature mechanism is in case some nodes is offline.

It's good to have more than one node for availability. But if they are controlled by the same entity, it doesn't matter if there is a 2/3 majority, of a leader-follower model (Raft?) or even just a round robin model that allows one watcher to interact with the network.

**Review by alxs — APPROVED** [review]
Happy to support the current approach. Keep in mind that:
- Seeing as you want to go for pallets as opposed to smart contracts: in case you don't find a parachain project willing to integrate your pallets, it is also an option to launch your own.
- As previously discussed, whether you need to implement and deploy the watcher network at all depends on whether an Ethereum bridge is available on some parachain soon enough. I wouldn't blindly wait for this to happen, but you probably want to look into it.

**Comment by cygnusv** [comment]
> It's good to have more than one node for availability. But if they are controlled by the same entity, it doesn't matter if there is a 2/3 majority, of a leader-follower model (Raft?) or even just a round robin model that allows one watcher to interact with the network.

We at NuCypher would also prefer a more decentralized approach for the watcher nodes. I think current proposed design allows for it anyway, so if NuLink can clarify that part, it would be great.

**Review by Noc2 — APPROVED** [review]

**Comment by pawnz0** [comment]
> It's good to have more than one node for availability. But if they are controlled by the same entity, it doesn't matter if there is a 2/3 majority, of a leader-follower model (Raft?) or even just a round robin model that allows one watcher to interact with the network.

Thanks for the comments. I think maybe we can invole more orgnazations (NuCypher, Web3 foundation, etc.) to maintain this network together to make the watcher network more decentralized. All the watcher nodes can sumbit update request to the mirror pallet seperately with signature. And when the mirror pallet accumulate enough request(reaching the 2/3 threshold), the new state can then be recorded in the parachain.

**Comment by pawnz0** [comment]
> Happy to support the current approach. Keep in mind that:
> 
> * Seeing as you want to go for pallets as opposed to smart contracts: in case you don't find a parachain project willing to integrate your pallets, it is also an option to launch your own.
> * As previously discussed, whether you need to implement and deploy the watcher network at all depends on whether an Ethereum bridge is available on some parachain soon enough. I wouldn't blindly wait for this to happen, but you probably want to look into it.

Thanks a lot for your suggestions. We will keep tracking the newest update of the bridge. Also we would try to launch a parachain by ourselves if we can not find one.

**Review by mmagician — APPROVED** [review]
Ok, sounds good. You can also update the deliverables during the grant should anything change.

**Comment by alxs** [comment]
@pawnz0 would you mind sharing a quick status update, along with an ETA if possible? The [project repo](https://github.com/pawnz0/NuLink) looks inactive and we were hoping to receive your first delivery a bit over 2 months ago now.

As long as you're actively working on the project, delays aren't a big problem, but please keep us in the loop. If you expect the delivery to take longer than 2-3 more weeks, you'll need to submit an amendment.

Note that if we don't hear from you soon, we will assume you're no longer interested and terminate the agreement.

**Comment by alxs** [comment]
@pawnz0 it's good to see that you're still working on this project. When do you expect to submit the first milestone? Note that if you've deviated from the original deliverables or funding requirements, you can always submit an [amendment](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval).

**Comment by alxs** [comment]
@pawnz0 can you please give us some sort of update? Given the current delay of over 6 months, you should submit an amendment to update the timeline.

**Comment by pawnz0** [comment]
Hello, sorry for the delay. And we are ready for delivery of both milestones now. We will submit the delivery soon next week. You can check our project [here](https://github.com/NuLink-network/nulink-chain).

**Comment by alxs** [comment]
That's great news. In that case, you can just deliver the milestones without an amendment.

**Pull request merged**
