### PR TITLE
PHP scale codec lib

### PR DESCRIPTION
**Pull request by gmajor-encrypt**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by gmajor-encrypt** [comment]
Thank you for your review, I saw it through https://github.com/w3f/General-Grants-Program/tree/master/rfp-proposal, I think it is more appropriate to mention proposal here

**Comment by mmagician** [comment]
@gmajor-encrypt Thanks, yes that's the right place to open the PR. We will review it shortly

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks again for the application. Would it be possible to reduce the price? In general I recommend switching to a payment in DAI, since we will probably update the way we pay grant teams in BTC in the coming days. Also it seems you already previously worked on the project. Why did you do this? Are you potentially working on another project that would leverage this implementation?

**Comment by gmajor-encrypt** [comment]
> Thanks again for the application. Would it be possible to reduce the price? In general I recommend switching to a payment in DAI, since we will probably update the way we pay grant teams in BTC in the coming days. Also it seems you already previously worked on the project. Why did you do this? Are you potentially working on another project that would leverage this implementation?

Thank you for your reply. I have replaced the BTC address with an Ethereum address. Yes, I did a part of the PHP scale codec work nearly 1 year ago, but we plan to change the PHP project to use Golang, and this part of the work has stopped. The Spring Festival is approaching recently, and I will have more time to complete the two open-source projects of scale PHP and substrate API

**Comment by Swader** [comment]
I'd like to know more about the long term support commitment. What length are we talking here? Can you commit to keeping it up to date for 1 year since release? If so, I think the price is then fair.

(technically a codec should not care about types that update, it's just for decoding and encoding, but I think the bonus features are worth it)

**Comment by gmajor-encrypt** [comment]
> I'd like to know more about the long term support commitment. What length are we talking here? Can you commit to keeping it up to date for 1 year since release? If so, I think the price is then fair.
> 
> (technically a codec should not care about types that update, it's just for decoding and encoding, but I think the bonus features are worth it)

@Swader hey, scale codec is a long-term maintenance task. Due to changes in the underlying substrate, runtime metadata and other basic data structures will change. If they are not updated in time, disasters will occur. I subscribed to the releases of the Polkadot library and updated it as soon as possible.

I guarantee that this will be maintained for a long time, not just for a year. In addition, I also have a substrate API PHP lib here. I understand that I cannot apply at the same time. I need to do this before applying for the substrate API PHP lib.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. In general I’m willing to go ahead with it and will share it with the rest of the team.

**Comment by Swader** [comment]
I agree with this and would like to proceed.
Maybe I am misunderstanding something though - SCALE is just a way to encode/decode, it has no reliance on types. It *can* be augmented with types (i.e. [scale-info](https://github.com/paritytech/scale-info)), but at its core, the encoding/decoding part should be standalone and long-term support-free just like BASE58 is.

So the way I see this is:

- PHP SCALE: standalone, works forever with basically no maintenance
- Additional types: probably via scale-info, maintained alongside it, useful as an "addon" for the PHP SCALE codec to be automatically compatible with Polkadot / Kusama (at that point it basically becomes PHP API for Substrate, but without the API connection).

This grant is mainly for funding 1), whereas the rest would belong more in the PHP API RFP.

**Comment by gmajor-encrypt** [comment]
@Swader This is indeed the case. SCALE is a basis, but during the development process, the development problems I encountered were all that I needed to obtain the original value from RPC and parse it into a ``Human'' language. In short, DAPP developers were a little bit different. Concerned about the most basic types, and most concerned about what this storage/extrinsic/event is. Thanks again for your reply, I am ready to start tonight

**Review by Swader — APPROVED** [review]
@Noc2 let's merge this and get it going

**Review by mmagician — APPROVED** [review]

**Review by RouvenP — APPROVED** [review]

**Pull request merged**
