### PR TITLE
Update dorahacks-quadratic-funding.md

### PR DESCRIPTION
**Pull request by zhangjiannan**
We completed frontend integration with HackerLink. However due to tight schedules we didn't create a demo page based on the substrate-frontend-template (task #2 of Milestone-2). Another reason why we didn't create the simple page is that HackerLink has a complete infrastructure for user registration, project upload / display, etc. The HackerLink code base is not open source. We would like to provide a complete demo of how quadratic funding grant is functioning on a parachain or potentially on Polkadot / Kusama relaychains in the future. Therefore we would like to still submit a milestone. Given that our frontend is not open source and we are only providing a demonstration site that uses our milestone-1 code to provide a service for quadratic funding grant, we are reducing the price to $0 accordingly.

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
I would have happily told you to leave the price as it was since it was already absurdly cheap, but I guess you're right in that we can't fund anything that isn't open source. What are your plans for after this milestone, will you apply for a follow-up grant?

**Review by alxs — APPROVED** [review]
I would have happily told you to leave the price as it was since it was already absurdly cheap, but I guess you're right in that we can't fund anything that isn't open source. What are your plans for after this milestone, will you apply for a follow-up grant?

**Comment by zhangjiannan** [comment]
We would like to do two things. 1. Discuss possibilities to host KSM / DOT quadratic funding grants with the pallet, just like what we have been doing on HackerLink. 2. We would like to implement MACI on top of it. For this one, we might apply for another grant. We do not necessarily need to use MACI in a real grant, but this is something that we need to build for large-scale quadratic funding practices.

**Review by Noc2 — APPROVED** [review]
I’m also happy to approve this PR and feel free to send us another grant proposal. Regarding maci, you should take a look at: https://github.com/w3f/Open-Grants-Program/pull/232

**Review by semuelle — APPROVED** [review]

**Comment by zhangjiannan** [comment]
@Noc2 Thanks for pointing to #232, it looks great. Do you happen to know current progress of this grant? If it's going well, maybe we can work with him to speed up.

**Comment by Noc2** [comment]
@zhangjiannan I don’t know. It’s probably best to ask the team directly. Feel free to also ping them directly on the PR.

**Pull request merged**
