### PR TITLE
bitCheck

### PR DESCRIPTION
**Pull request by bitcheck**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. This looks quite interesting to me. The only concern I currently have is that milestone 1 is currently quite expensive and doesn’t provide too much value for our ecosystem, given that there are already similar solutions as substrate modules and it shouldn’t be too much work to adapt these. Could you reduce the price of milestone 1 significantly?

**Comment by bitcheck** [comment]
Hi Noc2, we've re-checked the proposal and found these has a calculation mistake. 
Actually we are going to arrange 2 FTEs for Milestone 1, it will cost 0.5BTC(Not 0.75 BTC). And 3FTEs for Milestone 2, it will cost 0.75BTC(not 0.5BTC). 
After we discussed your suggestion and reduced price for milestone 1, That is the new budget:
MS 1: 2FTEs, 0.4BTC
MS 2: 3FTEs, 0.75BTC
MS 3: 2FTEs, 0.25BTC
Ttl: 1.4BTCs

**Comment by Noc2** [comment]
That’s great, but according to the current market price of BTC this would still be above the 30k limit. Could you reduce it a little bit more. Also could you update the price directly inside the application, so I can immediately share it with the rest of the team?

**Comment by bitcheck** [comment]
Okay, application has been updated according to the current BTC price.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Sorry I have a few more follow-up questions: 

- Why do you link to the following twitter account on your homepage: https://twitter.com/wix 
- On what is your zk privacy solution based on? Which project did you potentially reuse for it and is it audited? 
- And what’s the purpose of the DividendPool?

**Comment by bitcheck** [comment]
Hi,
1- Our webpage is built by wix.com for the time being. All our team is focus on the app development now, later we will move to standalone web server. Maybe this link is for promotion purpose by wix :)

2- The zk solution is base on Tornado project. We want to improve it on bitCheck polkadot version.
a- Using PLONK instead of GROTH16 to avoid trusted setup while updating circuits. This will improve the expansibility of DAPP.
b- While we use tornado, front-side calculation of generation proof is too heavy to run on mobile wallet. This will be improved also.
c- Tornado is using classic merkle tree to store/track data onchain, but the cost is so high. We will use new protocol like Shrubs to improve it.
Some functions above is realized on bitCheck Ethereum version, but it will be greater to realize on parachain.

3- For attracting users on Ethereum chain and making up for high gas cost, we made this economic model. If the users stake tokens in the DividendPool contract, they will share the payment fee. But we don't think it is necessary on parachain, if the transaction cost become acceptable.

**Comment by Noc2** [comment]
Thanks for the quick reply. Could you integrate this information (except wix.com) into the application? And in general feel free to add as much technical details for each deliverable as possible. This makes it always easier for us to accept an application.

**Comment by bitcheck** [comment]
Hi, the application has been updated with those informations.

**Comment by Noc2** [comment]
Thanks for adding the additional information, but I actually meant could you update the specification of the deliverables in the table to be more precise, for example “zk-knowledge - Submodules: Verifier/ProofGenerator etc.” What is etc.?  Sorry for the confusion. Also what’s your experience with zkps so far?

**Comment by bitcheck** [comment]
Hi, David, Merry Christmas, we have updated the application which have just added teams members' backgroud to explain our experience. But we still need time to discuss the deliverable details to be sure that everything will be performed on time. Maybe tomorrow can be updated for this matter.

**Comment by mmagician** [comment]
@bitcheck I'm closing this for now, it seems that your application is still missing some details. Feel free to re-open the PR once your proposal is complete.

**Pull request closed without merging**
