### PR TITLE
Stone Index on Substrate proposal

### PR DESCRIPTION
**Pull request by calvinzhou-rockx**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by mmagician — CHANGES_REQUESTED** [review]
The idea of allowing users to create their own indices is interesting. Before I approve your application, however, you'll need to fill in some of the missing details:
1. As specified in our application template: `Deliverables 0a-0d are mandatory and should not be removed`
2. You need to decide whether the payout is DAI or BTC and only provide one address
3. Pallets are missing details: `Indexed basket management`. Take a look at [these guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md#applies-to) for a list of specifications we'd like you to add to the application.

**Comment by calvinzhou-rockx** [comment]
> The idea of allowing users to create their own indices is interesting. Before I approve your application, however, you'll need to fill in some of the missing details:
> 
> 1. As specified in our application template: `Deliverables 0a-0d are mandatory and should not be removed`
> 2. You need to decide whether the payout is DAI or BTC and only provide one address
> 3. Pallets are missing details: `Indexed basket management`. Take a look at [these guidelines](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md#applies-to) for a list of specifications we'd like you to add to the application.

Hi,

Thanks for your comments and we made the changes accordingly for #1 and #3. Regarding to #2, we target to complete this grant within 30k USD, which roughly worths 0.8BTC based on the current market price of BTC, and only BTC address is provided in the proposal 

Thanks

**Comment by mmagician** [comment]
Thanks for the updates. I would be happy to support the project, although I still have some comments:

1. By reading your application, I develop an understanding that the `token module` and the `Indexed basket management` are the same thing (since the latter has `purchase_index` & `redeem_index` callables that mint & burn the token, which seems to be the same functionality as your token module)
2. Rather than building your own DEX module, perhaps you could utilise one of the existing ones? Take a look at the [Polkadot stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#link-chains-and-modules) and you will find a number of DEX modules at various stages of development. I'm confident you will be able to adapt one of these to suit your needs. If this is not the case, you'd need to provide a detailed explanation why. At this point we have quite a lot of DEX modules (and more in development) and unless you are proposing something truly innovative, I'd suggest using one built by the community already.
3. Especially given the above points, the price is way too high for building out one module with the functionality proposed.

**Comment by calvinzhou-rockx** [comment]
> Thanks for the updates. I would be happy to support the project, although I still have some comments:
> 
> 1. By reading your application, I develop an understanding that the `token module` and the `Indexed basket management` are the same thing (since the latter has `purchase_index` & `redeem_index` callables that mint & burn the token, which seems to be the same functionality as your token module)
[CZ] The understanding is correct

> 2. Rather than building your own DEX module, perhaps you could utilise one of the existing ones? Take a look at the [Polkadot stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#link-chains-and-modules) and you will find a number of DEX modules at various stages of development. I'm confident you will be able to adapt one of these to suit your needs. If this is not the case, you'd need to provide a detailed explanation why. At this point we have quite a lot of DEX modules (and more in development) and unless you are proposing something truly innovative, I'd suggest using one built by the community already.
[CZ] Yes, we'd use existing DEX rather than develop by ourselves, the DEX module is more for integration 

> 3. Especially given the above points, the price is way too high for building out one module with the functionality proposed.
[CZ] The concern is valid and we can reduce it to 0.5 BTC, please let us know if it's OK, thanks

Thanks for the response, and replied per question above tagged by [CZ]

**Comment by mmagician** [comment]
In the light of your responses, please update the application accordingly. Regarding the price: since you are reducing your deliverables from 3 modules to 1, I would expect the price to reflect that.

**Comment by calvinzhou-rockx** [comment]
> In the light of your responses, please update the application accordingly. Regarding the price: since you are reducing your deliverables from 3 modules to 1, I would expect the price to reflect that.

Roger that,  I hence reduced it to 0.3 BTC

**Comment by mmagician** [comment]
Thanks, but your deliverables still include creating a DEX module (please change to indicate you will integrate one of already existing ones). Furthermore, please unify the index management & token modules, since they are not two separate deliverables. Thanks!

**Comment by calvinzhou-rockx** [comment]
> Thanks, but your deliverables still include creating a DEX module (please change to indicate you will integrate one of already existing ones). Furthermore, please unify the index management & token modules, since they are not two separate deliverables.
> Looking forward to your updates.

Thanks for the input, and I updated the deliverables accordingly

**Comment by calvinzhou-rockx** [comment]
Hi @mmagician ,

 Would like to check if any update since our last changes for deliverables 

Thanks 
Calvin

**Review by mmagician — APPROVED** [review]
Apologies for a delayed reply. I appreciate the updates and I'll share the application with other team members.

**Review by Noc2 — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Comment by alxs** [comment]
@calvinzhou-rockx care to share a quick status update on the project, together with an ETA if possible? Your first delivery is by now delayed by several months so if we don't hear something from you soon, we would terminate the grant due to inactivity.

**Comment by RouvenP** [comment]
hi @calvinzhou-rockx we transferred the payment for M1 today.

**Comment by calvinzhou-rockx** [comment]
> hi @calvinzhou-rockx we transferred the payment for M1 today.

Hi @RouvenP , this is to confirm the payment of 0.3 BTC is received, thanks a lot

**Pull request merged**
