### PR TITLE
Project 1001

### PR DESCRIPTION
**Pull request by buildtrust**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by mmagician** [comment]
@buildtrust Thanks for the application. The idea of generating a 3d world from speech is an interesting project in itself, though I'm not entirely convinced about turning it into NFT(s) and storing it on blockchain. It seems like the content generation will happen in a traditional, centralised fashion. Also, since you're not asking for any funding, may I ask why you are applying for a Web3 Grant in the first place?

**Comment by alxs** [comment]
@buildtrust just a quick remark here - if you want to keep the wordToWorld project closed-source, the grant you're applying for should be unrelated to it. See our [guidelines](https://github.com/w3f/Open-Grants-Program#guidelines) in this regard, in particular

> All code produced as part of a grant must be open-sourced, and it must also _not rely on closed-source software for full functionality_.

**Comment by buildtrust** [comment]
Hi, @mmagician .

> The wordToWorld project is funded by the accelerator and venture capitals, we will not use the funds here to support wordToWorld development.

First, let me clarify that wordToWorld and 1001 are two different projects, wordToWorld introduced are developed by other group of developers and is used in a traditional education app for kids. But 1001 in this proposal is the application and platform we want to develop and experiment in the crypto space. Also, here we apply for grant of 30,000 USDT. The currently 1001 team has no overlap with wordToWorld team except me and the language processing engine.

@alxs the code mentioned in the deliverable in this proposal and all the substrate related code will be all open-sourced. The language processing engine is completed before and by the wordToWorld team, is based on Google API and Unity, will not be open-sourced.

> It seems like the content generation will happen in a traditional, centralized fashion. 

Here is the reason why we want to have a new game 1001 in crypto space: 
1. Token economy including biding system and decentralized marketplace is more efficient and easy to implement. A innovative user is able to monetize his stories / his imagination and the story ranking and display could totally decided in a decentralized way.
2. The model and story NFTs not only provide the liquidity of assets in the whole crypto world rather than an app itself, but also the composed model NFTs in one story brings new value, imagine characters created has the faces of [Substratepunk](https://ipfs-gateway.usetech.com/ipns/QmaMtDqE9nhMX9RQLTpaCboqg7bqkb6Gi67iCKMe8NDpCE/) and could interact with [Kanaria eggs](https://kanaria.rmrk.app/) in a story. 
3. With the grouped NFT, 1001 benefits from the existed NFTs in the crypto world with big IPs and also introduce them as a grouped NFT into DOT/KSM ecosystem.
4. With the experience in the DeFi field, the team plan in the future to use the grouped NFTs in lending, stacking and etc.

**Comment by alxs** [comment]
@buildtrust sorry to say that in that case this project can't depend on the language processing engine. See the quote above - all code delivered must not rely on closed-source software for full functionality. If you still want to go ahead with the application, please amend it accordingly.

**Comment by softlipaschara** [comment]
> @alxs the code mentioned in the deliverable in this proposal and all the substrate related code will be all open-sourced. 

If you still think that is conflict with the guideline then probably we should apply a general grant program

**Comment by alxs** [comment]
I'm afraid the General Grants Program has the same requirement. You can either amend the application to not mention the language processing engine, or open-source the engine along with the deliverables.

**Comment by buildtrust** [comment]
> I'm afraid the General Grants Program has the same requirement. You can either amend the application to not mention the language processing engine, or open-source the engine along with the deliverables.

@alxs after internal discussion ,  we decide that all the related code include game, language process engine and substrate pallet will be open-sourced, we updated the proposal, please review it again.

**Comment by mmagician** [comment]
Thanks for all the updates. At the moment the deliverables 0a-0d from our template are missing (and have been renamed). These are mandatory so I kindly ask you to incorporate them into your deliverables.

**Comment by buildtrust** [comment]
> Thanks for all the updates. At the moment the deliverables 0a-0d from our template are missing (and have been renamed). These are mandatory so I kindly ask you to incorporate them into your deliverables.

Thanks for your reminder. I have updated our deliverables.

**Review by mmagician — APPROVED** [review]
Thanks for all the updates, the proposal looks better now.
I'm not necessarily in favour of creating another virtual world (personal preference), but it seems like you have a good project plan and the mock-ups seem somewhat promising too. Good luck with the development 👍🏼

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks promising. 

- Are you aware of https://bit.country/ and https://dotmog.com/? Both of these projects might have code that you can potentially reuse. For example see dotmogs work regarding unity: https://github.com/dotmog We also recently signed the following grant with them: https://github.com/w3f/Open-Grants-Program/blob/master/applications/Jeton_Network_follow_up.md 
- Could you add the programming language to the specification of the deliverables for each requirement?  
- Also, did you consider using smart contracts instead of pallets? We are generally interested in supporting the development of more ink! Smart contract projects. Also see the following post: https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract

**Comment by buildtrust** [comment]
> Thanks for the application. Looks promising.
> 
> * Are you aware of https://bit.country/ and https://dotmog.com/? Both of these projects might have code that you can potentially reuse. For example see dotmogs work regarding unity: https://github.com/dotmog We also recently signed the following grant with them: https://github.com/w3f/Open-Grants-Program/blob/master/applications/Jeton_Network_follow_up.md
> * Could you add the programming language to the specification of the deliverables for each requirement?
> * Also, did you consider using smart contracts instead of pallets? We are generally interested in supporting the development of more ink! Smart contract projects. Also see the following post: https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract

@Noc2 Thanks for your suggestions.
1. That helps a lot, definitely would like to re-use the existed module, and the SubstrateNetApi seem very promising.
2.  We will use Rust for pallets code, Ink! for smart contracts and Unity/Typescript for frontend UI.
3. We have considered smart contract, if offers great flexibility for defining the customizable models, as there are so many objects in the game, like words, renders, sounds effects, emojis, use different smart contract would be a preferred way to do that, but as far we can't foresee the implementation, but we will definitely split the game logic on to smart contract after we construct the world, probably we could have clear clue after the 0 and 1 milestones.

**Comment by Noc2** [comment]
@buildtrust  Thanks for the detailed reply. For clarification: which parts will be implemented as smart contracts? Also see https://github.com/gautamdhameja/substrate-runtime-contract-sample, if you want to use smart contracts as well as pallets. I will double check if there is an update version of the repo.

**Comment by buildtrust** [comment]
> @buildtrust Thanks for the detailed reply. For clarification: which parts will be implemented as smart contracts? Also see https://github.com/gautamdhameja/substrate-runtime-contract-sample, if you want to use smart contracts as well as pallets. I will double check if there is an update version of the repo.

@Noc2 Hi, in our development plan, the version of grants applied for will be implemented with pallet. After this version is stable, we want use smart contract to implement exist version.

**Review by Noc2 — APPROVED** [review]
Okay got it.

**Review by mmagician — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Comment by alxs** [comment]
@buildtrust any updates? Are you still planning to deliver the grant?

**Comment by semuelle** [comment]
@buildtrust, @softlipaschara, please provide an update. We will terminate this grant if we don't hear back from you in the next two weeks, as there has been no activity on any of you or your team's repositories.

**Comment by softlipaschara** [comment]
Hi, sorry for the late reply, unfortunately we decide to terminate this project, as our engineer is working on other projects and he doesn't have time on this project anymore. Thanks for giving us this chance and support.

**Comment by semuelle** [comment]
Thanks for the update. Good luck to you and your colleagues going forward!

**Pull request merged**
