### PR TITLE
Create aolink.md

### PR DESCRIPTION
**Pull request by jacklcz**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by jacklcz** [comment]
add aolink

**Comment by semuelle** [comment]
Hi @jacklcz, thanks for your application. A few things:

1. All contributors to your application need to sign the [CLA](https://github.com/w3f/Open-Grants-Program/pull/290#issuecomment-788952127).
2. Can you please provide a roadmap with one or more milestones - with one or more deliverables - each as described in our [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md)?
3. Costs need to be designated in US$ and can only be paid out in BTC or DAI. If you require payment in fiat, you have to apply through the [General Grants program](https://github.com/w3f/General-Grants-Program).

**Comment by jacklcz** [comment]
> Hi @jacklcz, thanks for your application. A few things:
> 
> 1. All contributors to your application need to sign the [CLA](https://github.com/w3f/Open-Grants-Program/pull/290#issuecomment-788952127).
> 2. Can you please provide a roadmap with one or more milestones - with one or more deliverables - each as described in our [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md)?
> 3. Costs need to be designated in US$ and can only be paid out in BTC or DAI. If you require payment in fiat, you have to apply through the [General Grants program](https://github.com/w3f/General-Grants-Program).

Thanks for your reply, I will continue to add

**Review by jacklcz — COMMENTED** [review]
+1

**Comment by semuelle** [comment]
Hi @jacklcz,

- the grant amounts need to be denominated in USD,
- we do not fund company infrastructure (`Purchase Amazon server`),
- the project being funded **must** be open source, so we would not fund a deliverable `Open source and promote`,
- you have to provide more technical specifications. For example, `Use polkadot js to complete the interaction between native and dapp` is too vague and hardly measurable,
- there are already a number of dapp browsers and wallets in existence (cf. our [tech stack](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md)). To fund one of these, we would need a convincing reason, such as unique functionality.
- every milestone needs documentation and testing guidelines,
- I would like to see any kind of open source development and maintenance by the team. The repositories you provided contain the Substrate node template with no visible changes and both Android repos under Ao* organisations have no commits.

**Comment by semuelle** [comment]
Closing due to inactivity. Happy to reopen when the questions are answered.

**Pull request closed without merging**
