### PR TITLE
Application: Dinfra

### PR DESCRIPTION
**Pull request by vonhenry**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However we require more details regarding the exact implementation (e.g. programming language and functionality) For example regarding account and management system, will it support polkdato as well filecoin accounts, in which programming language will it be implemented, how is tested (unit-tests), etc. Also teams should usually have some initial specification of the project before they apply for a grant. Additionally p2p is currently working on a Multiblockhcain ELT (filecoin, polkadot): https://github.com/p2p-org/mbelt-docs How is your solution different from their implementation?

**Comment by vonhenry** [comment]
Thanks for your reply, for your questions and my answers are as follows:

1. regarding account and management system, will it support polkadot as well filecoin accounts?  
Account system refers to the user's account registered on the website, which is used to manage the user's service, balance and other information. The account can contain multiple blockchain accounts of the user, including Polkadot and Filecoin accounts, as required.

2. in which programming language will it be implemented, how is tested?  
We use Golang to implement the main parts of Dinfra. 
In each repo, we will add enough unit tests, and we also have cluster tests.

3. Also teams should usually have some initial specification of the project before they apply for a grant.   
Please refer to https://github.com/Dinfra/specs

4. https://github.com/p2p-org/mbelt-docs How is your solution different from their implementation?  
There are many similarities between these two projects, but we focus on Polkadot and Filecoin ecosystem, We will provide users with as many tools and convenience as possible. For example: 
- Filecoin excellent miners details and credit list
- One click selection of the most suitable filecoin miner for a user
- Data encryption storage
- Convenient exchange token of DOT and FIL
We believe that the combination of the two is enough to support almost any type of DApps, and we provide solutions that can be implemented commercially, we can obtain revenue by charging users service fees, and form a positive business logic. We have rich experience in blockchain research and development, and we believe that we will do the best.

**Comment by Noc2** [comment]
Thanks for the update. Could you integrate this information as well as the existing specification into the grant application and update it accordingly? The more technical details you can provide the better.

**Comment by vonhenry** [comment]
Above information and the specification have been merged into `Dinfra.md`,  and development roadmap has also been updated.

**Comment by mmagician** [comment]
@vonhenry Thanks for the application, I have a couple of comments:

1. Could you please double check the consistency of naming in your application? I'm not sure whether `promisor` & `promoter` are supposed to be the same or different components.
2. What data exactly are you going to store in the reversible & irreversible databases? Will there be continuous data movement between these two, and if so, at which point do you decide that data is safe to move to the irreversible DB?
Also, perhaps you could talk about how Polkadot consensus mechanism affects the finality of your data.
3. Could you list all the libraries that you're planning to integrate into your solution? (perhaps the [Go Substrate RPC Client](https://github.com/centrifuge/go-substrate-rpc-client))
4. > Convenient exchange token of DOT and FIL 

This will be a centralised service, correct? Can you elaborate please?

5. From what I can see, when you compare your solution to [Multiblockchain ETL](https://github.com/p2p-org/mbelt-docs), most of the points from the list regard Filecoin & not Substrate (and please keep in mind this is a Polkadot ecosystem focused grant). I like the idea that a user could pay in DOTs for using your service, perhaps you could add more details on how this solution would be implemented in practice?

**Pull request closed without merging**
