### PR TITLE
Halva [Bootstrapping and Scaffolding]

### PR DESCRIPTION
**Pull request by ByKeks**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Hi @ByKeks. Thanks for the new application. Could you add updating your example https://github.com/halva-suite/halva-test-example to the milestone? Also some unit tests might be useful and in general it would be nice if you could integrate a step by step tutorial (maybe as a medium post) to the deliveries. To be honest, it seems to me currently also rather expensive considering the required amount of work.

**Comment by ByKeks** [comment]
Hi @Noc2. Yes, I think it's my mistake to leave it behind the scenes in our proposal. I will give an update soon. Thanks for your feedback!

**Comment by ByKeks** [comment]
Hi @Noc2, I updated the proposal. Please check it, thank you

**Review by Noc2 — APPROVED** [review]
Thanks for updating the proposal. I still think the price is a little bit expensive, but I would be willing to go ahead with it and will share it with the rest of the committee. To continue to fund your work in the future, it might make sense to also leverage the treasuries and it would be nice if you could come up with a long-term business plan/idea for your project.

**Review by RouvenP — APPROVED** [review]

**Comment by ByKeks** [comment]
@Noc2 Yes, it makes sense and we're following this way, thanks for your advice, it's very helpful. But it will take us time to make it.

**Review by mmagician — APPROVED** [review]

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grantspr@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by stepancher** [comment]
@Noc2 @RouvenP @mmagician Thanks very much!
We will be back soon, with a ready-made solution and all the necessary documentation

**Comment by Noc2** [comment]
@ByKeks and @stepancher What’s the status of this project? Would you be interested in continuing to work on it?

**Pull request merged**
