### PR TITLE
Open-Grants Application for PolkaMusic Project

### PR DESCRIPTION
**Pull request by cryptoshenoy**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed as polkamusic.md and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by mmagician** [comment]
@cryptoshenoy Thanks for the application, as far as I know we haven't had music-focused grants yet, so this could be interesting.
I have plenty of questions, though:
1. Your website www.bitcoinmusic.org doesn't work
2. https://www.polkamusic.io/ Seems to only be a front-end and is in no way connected to a blockchain, right? As far as I can see your [repo](https://github.com/polkamusic/PolkaMusic) is just a plain substrate template node, you haven't added custom code or logic yet.
3. Where is the actual music stored? Obviously putting the recorded data on blockchain is infeasible - but then who's in charge of:
    a) maintaining the list of all songs available (I imagine this is just metadata that can be placed on blockchain)
    b) making sure that data is available for users to stream? Will the artists themselves need to run infrastructure to provide a streaming service of their own songs?
4. The streaming platform will need to, I assume, calculate who streams songs, which songs, for how long, how many times etc. How often does the platform collect this data, and how often does it update the usage information that is written on-chain? 
5. Regarding your milestone deliverable: `Complete the deployment of the basic public PolkaMusic Substrate chain.` May I ask you to please supply all the technical details, such as publicly exposed methods, chain storage and any other specs you are already aware of, as outlined in the [category specific requirements](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md#requirements)?
6. In your application you mention both the smart contracts and modules. These are two very distinct features of the substrate blockchain. In general I don't see a problem with using both, but I would like to make sure you are fully aware of the differences. Could you outline the reasons why sometimes you choose smart contracts and other times modules? [Here](https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract) you will find a good overview of the two.

**Comment by cryptoshenoy** [comment]
Hello @mmagician. We have updated our application. We have answered all your questions in the updated application, and the repo has also been updated with what we're currently working on. Looking forward to your valuable comments. Thanks.

**Comment by mmagician** [comment]
@cryptoshenoy Thank you for updating the proposal, it definitely looks much better now.

---
In my view it's currently a bit expensive for what you're proposing: for example in M1, your pallet seems to focus mostly on the data structure and providing CRUD access to it (though you only mention the "C" part) -> which seems fairly trivial to accomplish. 

---
Moreover, unless I'm mistaken, upon delivering the complete grant the platform won't be fully functional, i.e. at that stage there won't be a possibility to actually upload the music files and to stream them, right? So it's only managing the metadata, not performing the typical user actions.

I would encourage focusing on integrating end-to-end (even if just basic) features and delivering a functional MVP within the scope of this Open Grant.

---
> we will implement decentralized file storage with NFT based access system

I understand that you might want to start with a centralised storage solution in the beginning - however it would be great to see a more detailed plan of how you want to move forward in the future. I believe this is a core concept that should be considered early on. Having at least an idea of how you want to proceed shows that you've thought of these crucial issues.

---
Lastly, I would like to understand a bit more about the Quorum Pallet and why you even need it?

**Comment by cryptoshenoy** [comment]
Hello @mmagician ,

I have updated the costs and a fully functional MVP with royalty payments in the background will be created under the scope of this open-grant. Some more details regarding permissioned decentralized file storage solution has been included in the updated application. 

Regarding the quorum pallet, it is envisioned as a voting mechanism for the public to be involved in the anti-spam efforts of Smart Record Contracts. More research will be required for the best course of action, such as self-verification through an artist's social media account might prove to be a better solution for trust scoring. Quorum pallet will not be worked on in this open-grant. Thanks.

**Comment by mmagician** [comment]
Putting on-hold to figure out the potential overlap with the [hackathon](https://polkadot-buildathon.devfolio.co/)

**Comment by cryptoshenoy** [comment]
We will be participating in the Polkadot Buildathon - India, and I can confirm that what we're working on during the buildathon doesn't overlap with the milestones set in this grant application. The same has been communicated to the organizers of the buildathon and the judges will also be notified so that they judge fairly.

**Review by mmagician — DISMISSED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Looks interesting, but I have a few questions/comments: 

- “PolkaMusic can also process royalties every 24 hours” Why every 24 hours? 
- How do you know someone actually “owns” the music? For example, you can easily change the hash by changing a small part of the data and this way claim music that actually belongs to someone else or am I missing something? 
- I find the term Smart Record Contracts (SRC) a little bit confusing, since it seems to be more of a Decentralized Identifier for music and not a smart contract.

**Comment by cryptoshenoy** [comment]
> Thanks for the application. Looks interesting, but I have a few questions/comments:
> 
> * “PolkaMusic can also process royalties every 24 hours” Why every 24 hours?
> * How do you know someone actually “owns” the music? For example, you can easily change the hash by changing a small part of the data and this way claim music that actually belongs to someone else or am I missing something?
> * I find the term Smart Record Contracts (SRC) a little bit confusing, since it seems to be more of a Decentralized Identifier for music and not a smart contract.

Hello David,

The royalty pool (either through inflation or through membership fee - during SSP initialization, we will provide multiple strategies to choose from) is divided by 365 days to create a daily royalty pool. This reward pool is distributed (as quota) to all the active users (listeners) on the platform in the past 24 hours. The user-centric calculation is done on stream reports and user's quota is distributed to songs the user has actually listened to (as opposed to pro-rata calculation).

For example: 
Royalty Pool = 365 $POLM (pooled in by users as subscription fee)
Daily Reward Pool = 1 $POLM
Active Listeners (in past 24 hours) = 10
Quota per user = 1/10 = 0.1 $POLM

0.1 $POLM is again distributed to the songs actually streamed by the listener.
The traditional streaming platforms process royalties once a month. PolkaMusic will process it once a day. Rolling 24 hour calculation can also be done, however, the results would be more accurate if done once a day. 

----

We cannot be sure if the SRC is created by the original artist, so we will be introducing the "Quorum Pallet", envisioned as a community powered trust score mechanism to weed out bad actors. Trust score will be based on community votes, and uploader will also be able to improve the trust score by authenticating with social media handles.

----

In the offline world, when an artist signs a contract with a record company, it's called Record Contract. Smart Record Contract is a smart version of Record Contract which contains all the meta-data. It's smart for the following reasons:

1) Any currency can be sent to the Royalty Splitter with SRC as the reference, and the currency will be split among the constituent party's wallets.

2) SRC will serve as a copyright for the song as the submission is time-stamped on the blockchain, and the identifier is the hash of the file submitted.  

We could alternatively call it Smart Recording Contract too.

**Comment by Noc2** [comment]
Thanks for the quick reply. Regarding the reward distribution: I would suggest to not distribute the rewards on a daily basis and instead let users take care of the payouts similar to the staking module. Otherwise you run into issues with having a lot of resource requirements at a certain point in time. Btw. the POLM token already exists: https://etherscan.io/token/0x947b4c5f8d551821e17d95da731f88738b19e3a4 So far you haven’t created any token, correct? My recommendation would actually be initially to not focus too much on the token at all.
Regarding the "Quorum Pallet", would it be possible to integrate it into the deliverables, either specification or actually the development of the pallet itself. In general this is an issue that a lot of projects have and it would be nice to have more people working on potential solutions for this problem of decentralized reputation/trust.

**Comment by cryptoshenoy** [comment]
Thanks for your feedback, @Noc2. I have added "Quorum Pallet Specification" under milestone-2. We're interested in solving this issue and will implement this separately. 

--------------
Thanks for the tip regarding efficiency via staking module. We will definitely work in this direction. 

----------------
The token ticker is yet to be decided.

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]
LGTM!

**Comment by alxs** [comment]
@cryptoshenoy care to share a quick status update on milestone 2?

**Comment by semuelle** [comment]
@cryptoshenoy, please note that we will terminate this grant if we don't receive any update in the next two weeks as you haven't replied to our update requests and there has been no activity in your repositories in the past two months.

**Pull request merged**
