### PR TITLE
NFT Collectibles Wallet

### PR DESCRIPTION
**Pull request by GamePowerDev**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general this looks pretty interesting and we want to support more UI focused projects. But I think it makes more sense to use a common and already developed NFT standard ([see for example](https://github.com/danforbes/pallet-nft)) instead of creating another NFT pallet. Btw. there is a [Element](https://app.element.io/#/room/#web3nft:web3.foundation)/[Telegram](http://t.me/rmrkapp) chat group for all things NFT on Kusama and Polkadot. Also something you should be aware is that: A group of devs, PMs and designers, along with artists and NFT creators are working on a NFT strategy for Kusama network (already ongoing: https://kusama.polkassembly.io/post/303). My recommendation would be therefore to initially remove milestone 1 and instead use an existing implementation and potentially even talk directly to teams like [unique network](https://usetech.com/unique/) to work together with them.

**Comment by MikeHuntington** [comment]
Thank you @Noc2 for your feedback. Honestly adjust the scope to be a bit smaller is a relief for us. We agree that utilizing some of the other NFT strategies in the community may be the better direction to take. We follow the element and telegram chat to network with others about the current NFT strategy.

In the mean-time we have adjusted the scope of the project and the cost.

**Comment by Noc2** [comment]
Thanks for the quick update. Looks good to me. I will share it with the rest of the team.

**Review by Noc2 — DISMISSED** [review]

**Review by gautamdhameja — APPROVED** [review]
LGTM!

**Comment by alxs** [comment]
Looks good to me too. Could you renumber the milestones to start from 1?

**Comment by MikeHuntington** [comment]
> Looks good to me too. Could you renumber the milestones to start from 1?

Ahhh thanks for catching that. I've updated the milestone order to account for the original first milestone being removed.

**Review by alxs — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Comment by MikeHuntington** [comment]
@alxs @Noc2 @gautamdhameja and the entire web3 foundation - I just wanted to take a moment to say thank you so much for this opportunity! And we won't let you down!

We will begin work for M1 starting today and if you so choose to follow our progress, the direct repo of M1 will be: https://github.com/GamePowerNetwork/nft-collectibles-wallet

Thank you again! ♥

**Comment by alxs** [comment]
@GamePowerDev hey, checking in here: do you still plan to submit the second milestone and if so could you give us an ETA? Note that if we don't hear from you in the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Comment by GamePowerDev** [comment]
> @GamePowerDev hey, checking in here: do you still plan to submit the second milestone and if so could you give us an ETA? Note that if we don't hear from you in the next two weeks, we'll assume you're no longer interested and terminate the grant.

Hi @alxs Yes we are still working on this grant. We had to shift focus since Apple introduced new restrictions on NFT wallet applications. Any buying, trading or obtaining of NFTs in a wallet app is no longer allowed. As you know our entire work was based about this mobile wallet. So instead we've shifted focus to https://www.neroverse.com which will incorporate many of the features laid out in this proposal, but strictly for the web.

We were about 80% done with milestone 2 when we had to change course so this has set us back on the progress. But if you have any questions on the current process, I'll be happy to answer.

**Comment by alxs** [comment]
@GamePowerDev care to give us another quick update? There seems to have been no activity on your [repos](https://github.com/GamePowerNetwork) for the past two months.

**Comment by semuelle** [comment]
@GamePowerDev, @MikeHuntington, please note that we will terminate this grant if we don't receive any update in the next two weeks.

**Pull request merged**
