### PR TITLE
ZK Rollups Pallet Application

### PR DESCRIPTION
**Pull request by SotaWatanabe**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. NoCtrlZ still needs to sign the CLA. Just for clarification the contract will be implemented in solidity via the evm module, correct? In this case, wouldn’t it be possible to simply use the existing solutions provided by matter labs? What’s the advantage of implementing the sidechain in substrate? Also something you should be aware of, there might be a RedShift verifier and Zinc VM implementation as substrate modules in the future.

**Comment by NoCtrlZ** [comment]
> Just for clarification the contract will be implemented in solidity via the evm module, correct?

Yes, we implement ZK Rollup used on evm pallet.

> In this case, wouldn’t it be possible to simply use the existing solutions provided by matter labs?

Yes, it would but we need to modify some restriction and it takes time.
We'll reestimate the schedule.

> What’s the advantage of implementing the sidechain in substrate?

We can reduce transaction fees and ZK Rollup is faster than other layer2 scaling solutions like Optimistic Rollup and Plasma. Users also don't need to hold the whole sidechain data because of its data availability so we can drastically improve user experience.

And for the Polkadot ecosystem, there are mainly two advantages, architecture combined sharding and Ethereum project migration.

First of all, rollup is [one of the potentially interesting topics](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md) of Web3 Foundation and Vitalik announced [the rollup centric Ethreum roadmap](https://ethereum-magicians.org/t/a-rollup-centric-ethereum-roadmap/4698?fbclid=IwAR1oJyMEwvjFXNy7vCHT19PyXNh27PAHZjvCR4qBRoUB9mKf_nEVOtE4vgk) last month. According to Vitalik, the Ethereum ecosystem is likely to be all-in on rollup (plus some plasma and channels) as a scaling strategy for the near and mid-term future. Sharding plus Rollups will be the future. Polkadot has the sharding ish architecture but it doesn't have Rollups yet. 

Second, a lot of Ethereum projects are interested in migrating from Ethreum to Polkadot. And some of the great Ethereum projects have already started using Rollups. If we could build Rollups on Substeate/Polkadot, we would help these projects migrate smoothly.

> Also something you should be aware of, there might be a RedShift verifier and Zinc VM implementation as substrate modules in the future.

Thank you.

**Comment by NoCtrlZ** [comment]
@Noc2 
Thank you for the review.
I modified milestone and gantt chart according to your review.
Please confirm🚀

**Comment by Noc2** [comment]
Hi @SotaWatanabe and @NoCtrlZ . Thanks for all the updates. The reason I haven’t replied yet is actually because I was waiting for a response by matter labs. I would like to put the application on hold for now and first try to introduce you to them. (They are super busy right now). If they don’t respond within in the next week or something like this we can continue with the application. How does this sound?

**Comment by NoCtrlZ** [comment]
@Noc2 
Thank you for your reply.
It sounds good to me!
I'd like to wait for their response too.
I appreciate your help🙇‍♂️

**Comment by SotaWatanabe** [comment]
@Noc2 Thank you for your introduction. Yeah, they must be busy now. We are happy either to work with them to push their grant forward or to implement ZKR by ourselves.

**Comment by SotaWatanabe** [comment]
@Noc2 Hello David. Did you receive a reply from Matter Lab regarding this topic?

**Comment by Noc2** [comment]
@SotaWatanabe Sorry for the late reply. It seems they have too much to do at the moment. Could you reduce the BTC price of the application (reflecting the current market price)? Also would it be possible to combine milestone 2 and 3 as a single milestone? The dockerfile for example helps us to evaluate the milestone. Additionally you might want to integrate a medium article or something similar into the deliveries. Probably something you want to do anyway.

**Comment by SotaWatanabe** [comment]
Hello, @Noc2 Thank you very much for your review. We have updated the following 3 things.

BTC rate:  (rate: 23 Nov, 10:27am UTC)
Docker and tutorial: We will prepare for both of them in the milestone2
Article: I added deliverable #7. We will publish an article that highlights ZK Rollups on Polkadot. 

Please let us know if you have any questions.

**Review by Noc2 — APPROVED** [review]
Looks good.

**Review by mmagician — APPROVED** [review]
Looking forward to it!

**Review by Lederstrumpf — APPROVED** [review]
lgtm :)

**Comment by SotaWatanabe** [comment]
Thank you very much for accepting the proposal. We started working on this! We will let you know once we finish the milestones.

**Comment by SotaWatanabe** [comment]
Hello @Noc2. Thank you for supporting us. We have accomplished the milestone1 and this is the documentation to prove our  work.
https://docs.google.com/document/d/1o-UoKdevFi9yD2bdvTy5_h-SI8ssEUMRz2hJ1TTYDrM/edit?usp=sharing

It would be great if you could have time to review our work. Feel free to comment on the doc if you have any questions. And please let me know if this is not the right way to submit milestones.

**Comment by mmagician** [comment]
@SotaWatanabe Thanks for the update, great news! We actually have an official process for milestone submission that you may find [here](https://github.com/w3f/Grant-Milestone-Delivery), it would be appreciated if you could open a PR there.

**Comment by SotaWatanabe** [comment]
@mmagician thank you for sharing the doc!! We will create the PR shortly!

**Comment by SotaWatanabe** [comment]
@mmagician Again, thanks for letting us know this. We have created PR here https://github.com/w3f/Grant-Milestone-Delivery/pull/93

**Pull request merged**
