### PR TITLE
P!nkforge Network Application

### PR DESCRIPTION
**Pull request by towerWang**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@towerWang Thanks for the application. We've recently accepted a grant which aims to do a subset of what's included in your proposal as well. Please check out [this PR](https://github.com/w3f/Open-Grants-Program/pull/60) where they're going to implement Uniswap V2 protocol.

While generally we value diversity, I think here we have a significant level of overlap between the two grant applications.
Perhaps you could have a look at the other team's proposal and leave your comments on how (if any) your project differs from them?

Thanks!

**Comment by Dotscan** [comment]
@mmagicianHi， This is a good question. Our whole picture is to combine fundraising and token exchanging smoothly to help foster the Polkadot projects, which you could simply understand it as Bounce + DAICO + Uniswap at the moment.

On the part of the Uniswap, our goal is to create a place for the instant token exchange to solve the price finding problem of parathreads' local currencies, which means Uniswap is our first step due to its self-proving but not our destination. We will keep amending Uniswap or replace it with some other mechanism to better adapt the Polkadot ecosystem.

you can see that from the micro-innovation about Uniswap mentioned in the proposal that we are going to incentivize community to lock token liquidity for the fundraising project, which is a further one step more in contrast with uniswap.

**Review by mmagician — CHANGES_REQUESTED** [review]
@Dotscan We would like to support your project, but first...
In order to get approval for the Open Grants Program, you'd need to provide more concrete and detailed information on what you are planning to develop. E.g.
> We will create a Substrate module that will be 100% functional as the one on eth

First of all, there will be some obvious functional differences, but also Uniswap (any any other protocol) is a moving target. Let's define exactly what functionality you will implement there.

Same goes for other substrate modules. It would be useful if you could define the storage & public methods of each pallet.

Same for M5: 
> A workable web app to do fundraising

Please define exactly what functionality you want to support in the UI & what technologies you'll use to code it. I assume you will be hosting it on IPFS (since you want to do have 100% uniswap functionality)?

Once you have updated your application, I will be happy to ask other committee members to review your application.

**Comment by towerWang** [comment]
Hi @mmagician, sorry to relay late; we were on vacation the last few days. 
Very nice suggestions. We have updated the docs with detailed milestone deliverables. Feel free to ask if you still have any confusion. 😃

**Comment by towerWang** [comment]
Hi @mmagician, we have noticed that you have not updated for a while. Kindly ask that are there any blockers to this proposal?

**Comment by mmagician** [comment]
@towerWang Sorry for late reply.

Thank you for updating the application. The [spec document](https://hackmd.io/6Gp8yViGRH27ofHnloln_A?view=) looks very good, I can see you've done your research!

However, your project proposes more modules than just the Uniswap one. Could you please do a similar exercise for other pallets that you have on the roadmap (e.g. Auction, DAICO & others)? Then we'll be able to move forward.

Many thanks!

**Comment by Noc2** [comment]
I close the PR for now due to inactivity. Feel free to reopen it or send us another application at any time.

**Pull request closed without merging**
