### PR TITLE
SubGame Network

### PR DESCRIPTION
**Pull request by shanfenggood**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@shanfenggood Thanks for the application, but in order to be considered, you will need to provide more specifications regarding your project. You can take a look at [this document](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md) for inspiration. Also, your `architecture` section is not very technical either - perhaps you might want to specify how each component fits into the software stack.

**Comment by shanfenggood** [comment]
> @shanfenggood Thanks for the application, but in order to be considered, you will need to provide more specifications regarding your project. You can take a look at [this document](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md) for inspiration. Also, your `architecture` section is not very technical either - perhaps you might want to specify how each component fits into the software stack.

Thanks for the guidance, let me add the missing documentation

**Comment by shanfenggood** [comment]
> @shanfenggood Thanks for the application, but in order to be considered, you will need to provide more specifications regarding your project. You can take a look at [this document](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md) for inspiration. Also, your `architecture` section is not very technical either - perhaps you might want to specify how each component fits into the software stack.

@mmagician  Adjusted the problem mentioned, whether it meets the requirements 
_69e94949-e8af-46a5-9eff-1d1d48fdf32a

**Comment by shanfenggood** [comment]
@mmagician   Do we need to do anything else

**Comment by mmagician** [comment]
@shanfenggood I'm sorry about the delay. We will get back to you shortly regarding the application.

**Comment by mmagician** [comment]
@shanfenggood I have a couple of comments regarding your application content:
1) Could you please clarify what a game template would include? Please provide some examples if possible, as at the moment I cannot really understand what it would represent. 
2) How do you imagine `play_game` will work? Will the game be played on the blockchain? Is this an offline game? As far as I understand blockchain, users need to interact with the chain in order to write/read data from it - and I imagine all games will need this to store their internal state.
3) If you're planning to be a parachain & have your own SGT token, what's the added benefit of creating an in-game currency (chips? clips?) - couldn't you use the SGT token already for that?
4) If you're applying for a public grant, please make sure to polish your application. For example, I'm not sure whether `chips` and `clips` are supposed to be two separate things or it's a misspelling (across multiple places)?

Thank you!

**Comment by shanfenggood** [comment]
> @shanfenggood I have a couple of comments regarding your application content:
> 
> 1. Could you please clarify what a game template would include? Please provide some examples if possible, as at the moment I cannot really understand what it would represent.

=>The early stage will be based on quiz and probability game templates. For example, you can choose a random factor to create a guessing game and play with your friends. You can also play World Cup quiz with your own friends, and of course you can also buy lottery tickets on it. The above games all exist as templates, you can start the game or participate in other people’s games

> 2. How do you imagine `play_game` will work? Will the game be played on the blockchain? Is this an offline game? As far as I understand blockchain, users need to interact with the chain in order to write/read data from it - and I imagine all games will need this to store their internal state.

=>Yes, you are right. All games are played on the chain. I'm sorry that play_game missed an additional parameter, although some games may not require additional parameters.

> 3. If you're planning to be a parachain & have your own SGT token, what's the added benefit of creating an in-game currency (chips? clips?) - couldn't you use the SGT token already for that?

=>We have considered your suggestion, but the design of the bargaining chip is more expected to be a stable currency, which will not change due to changes in the value of SGT, because it is more convenient for players to participate with other tokens, such as BTC, ETH. Of course, we also thought that the chips can be of multiple types, such as CBTC, CETH. We will upgrade this piece according to actual needs.

> 4. If you're applying for a public grant, please make sure to polish your application. For example, I'm not sure whether `chips` and `clips` are supposed to be two separate things or it's a misspelling (across multiple places)?

=>Yes, this is our mistake, thanks for correcting We have updated
> 
> Thank you!

**Comment by mmagician** [comment]
Thank you for the examples. Further regarding templates, what **information** would a template need to include (min/max number of players? rules of the game? allowed moves? etc.) and what parsing will need to happen (and via which component)   to turn the template into game logic (i.e. where is the game logic implemented)? 

Then, I would like you to describe please, how one of the examples you provided will be implemented & played out end-to-end. For example: the guessing game - how would a template look like; where is the randomness taken from; if/how is the randomness hidden from players; how do the players interact (i.e. what data is available to them about the game & what data do they send).

**Comment by shanfenggood** [comment]
> Thank you for the examples. Further regarding templates, what **information** would a template need to include (min/max number of players? rules of the game? allowed moves? etc.) and what parsing will need to happen (and via which component) to turn the template into game logic (i.e. where is the game logic implemented)?
> 
> Then, I would like you to describe please, how one of the examples you provided will be implemented & played out end-to-end. For example: the guessing game - how would a template look like; where is the randomness taken from; if/how is the randomness hidden from players; how do the players interact (i.e. what data is available to them about the game & what data do they send).

The game template contains all the logic of the game and the necessary parameters of the game. The early games are mainly guessing and probability games, and there will be less interaction between players.
Let me give a simple game template example: All players come together to guess whether the last number of a hash string in a specified future block is greater than 5 or less than 5. Players who guess the right guess can equally divide the chips of the wrong player

design:
1. Random factor: the hash string of the future block
2. Gameplay:
    1. Players create a new game instance and set parameters:
        1. Block number used for guessing
        2. The smallest and largest bet amount
        3. Game fee ratio (ex: 0.1%)
    2. All players can participate in the game and bet before the guessed block appears
    3. When the target block is generated, the game chips are settled according to the game rules on the chain (this logic can be written in decl_module -> on_finalize)

The hash string of the future block: This random factor can actually be modified a lot to make more interesting games, such as lottery games

In addition to the above-mentioned future block hash as a random factor, we can still introduce off-chain data through OCW from the game design, for example, we want to guess the World Cup or NBA

The imagination of the game is endless, but the core of our first phase is to create a fair and reasonable distribution of benefits, and we will continue to increase game templates.

Of course, for the fun of the game, we will develop beautiful front-ends for all our games。

Thank you @mmagician  you can continue to ask me if you have any questions

**Comment by mmagician** [comment]
@shanfenggood That makes sense. Is the above described template the one that you'll be implementing for this grant? If so, then I would like to ask you to include the above details in your application `.md` file please.

> Of course, for the fun of the game, we will develop beautiful front-ends for all our games. 

Do you perhaps have any mock-ups already for this? We usually require teams to submit at least a simple version of the UI mockups (e.g. links to Figma) along with the application. It would also help if you could list the functionality that will be available in such front-ends & any languages/frameworks that you're planning to use for it. This way, we can objectively evaluate your milestones once your grant has been accepted & you've delivered the work.

Thanks!

**Comment by shanfenggood** [comment]
> mockups

@mmagician  Thank you for your reply, we will actively prepare a ui mockups tomorrow, but time is tight, it may be simpler, of course we will continue to improve them. We will prepare immediately and wait for my good news

**Comment by shanfenggood** [comment]
> @shanfenggood That makes sense. Is the above described template the one that you'll be implementing for this grant? If so, then I would like to ask you to include the above details in your application `.md` file please.
> 
> > Of course, for the fun of the game, we will develop beautiful front-ends for all our games.
> 
> Do you perhaps have any mock-ups already for this? We usually require teams to submit at least a simple version of the UI mockups (e.g. links to Figma) along with the application. It would also help if you could list the functionality that will be available in such front-ends & any languages/frameworks that you're planning to use for it. This way, we can objectively evaluate your milestones once your grant has been accepted & you've delivered the work.
> 
> Thanks!

@mmagician   Completed application `.md`detail ,Also added mock-ups https://www.figma.com/file/8bSq6NEYOKfbcdFXLtsmFR/SubGame .   Thank you @mmagician  Only with your help can the document be more perfect, it’s hard work

**Comment by mmagician** [comment]
@shanfenggood Thank you for the mockups, that definitely helps. Could you also use the original milestone price? I would have expected you to reduce the price instead of bumping it up given the recent rise of BTC ;)

**Comment by shanfenggood** [comment]
> @shanfenggood Thank you for the mockups, that definitely helps. Could you also use the original milestone price? I would have expected you to reduce the price instead of bumping it up given the recent rise of BTC ;)

Haha Yesterday BTC has not risen yet, and the cost of implementing the first template has not been considered before. Let me change the cost back, and I will try to overcome it myself. thank you for your help  @mmagician

**Review by mmagician — APPROVED** [review]
Thanks for the changes

**Review by Noc2 — DISMISSED** [review]
Looks good to me. Also I think it might make sense to focus on Kusama with this kind of application. Potentially you can apply for kusama treasury funding, once you have finished the grant.

**Comment by shanfenggood** [comment]
> Looks good to me. Also I think it might make sense to focus on Kusama with this kind of application. Potentially you can apply for kusama treasury funding, once you have finished the grant.

Thank you for your approval  @Noc2 , we redouble our efforts

**Comment by shanfenggood** [comment]
Merry Christmas

**Review by BenWhiteJam — COMMENTED** [review]
@shanfenggood thank you for the application and all the efforts so far, I would still have two more questions to address:
- it got discussed before, but I think it is still unclear what exactly gets stored on-chain? Are you using the chain to transfer tokens between the user bettings only, or do you store the state on chain as well? Like for your example, will you store the bets from all parties on-chain? It would be nice to see what causes a chain state change and what will get handled off chain?
- you are mentioning the OCW usage, I'm just wondering how the validity of the supplied OCW information can be guaranteed? Like for your example, I assume you would like to do a betting on a real NBA game outcome, what would be the source like and how can it be verified against any manipulation?

**Comment by shanfenggood** [comment]
@BenWhiteJam  thank you for your attention, glad to answer you:

* **what exactly gets stored on-chain?**

1. This is a fair game platform, the rules of the game are written on the chain, and the code is auditable
2. All game instance creation and player participation data are stored on the chain, and the rules on the chain need to read these data and then execute the game logic

* **Are you using the chain to transfer tokens between the user bettings only, or do you store the state on chain as well?**

Yes, all actions of users participating in the game are completed through transactions, and the player's participation history will be recorded on the chain. From the design, all game-related links are completed on the chain, and all relevant data is stored on the chain

* **Like for your example, will you store the bets from all parties on-chain? It would be nice to see what causes a chain state change and what will get handled off chain?**

The logic of this game is completely executed regularly on the chain, and no off-chain intervention is required.
1. Players can participate in the game automatically generated by the system. The system game is based on the number of interval blocks to set a timer to settle the current game and generate a new game
2. Players can also participate in games manually generated by other players. The creator creates a new game instance through the front end (we will provide a game template, just set the relevant parameters on the front end call:
> pub fn create_game(origin, template_id:u32, template_data:vec[u8])->dispatch::DispatchResult)
3. When the player is betting, call play_game to complete the data storage to check the timeliness of the game
>pub fn play_game(origin, instance_id:u32, chip:u32,data:u32)->dispatch::DispatchResult) 
4. Regardless of whether it is a system game or a personally created game, the number guess_block_number of the game settlement will be set, and then in the **decl_module -> on_finalize** method of substrate, it is judged that the current block number is greater than guess_block_number+10 to trigger the game to change state.
5. In addition, the random factor of this game is the future block hash.


* **you are mentioning the OCW usage, I'm just wondering how the validity of the supplied OCW information can be guaranteed? Like for your example, I assume you would like to do a betting on a real NBA game outcome, what would be the source like and how can it be verified against any manipulation?**

For international competitions such as the NBA or the World Cup, the results are clear and consensus. The goal of OCW is to collect accurate external data as parameters and store it on the chain for game use. Of course, the interface for collecting data will use multiple authoritative data providers, with at least five guarantees. From the design of the game, we make the draw logic 12 hours later than the result of the game (about 7,200 blocks). If the data is found to be inaccurate before the draw, (although the probability of this situation is very small, it may also occur) Our plan is: initiate a democratic proposal to vote whether the game should stop and whether to compensate the lost players And other interventions. In short, some accidents on the game platform that are difficult to guarantee through computer logic can be supplemented by democratic proposals. This is a decentralized, democratic public chain I believe everyone will contribute to a fair result.

**Comment by mmagician** [comment]
It feels like the OCW part is not yet fleshed out as it sounds easily gameable at this stage. But since off-chain games are not part of the original specification, I think that's fine for now. In the future it might be worth integrating one of the Oracle solutions being developed by other teams.

@shanfenggood Please reduce the milestone cost (e.g. 0.4 BTC) to account for the latest price surge.

@BenWhiteJam Do you have any further comments?

**Comment by laboon** [comment]
As soon as the Bitcoin amount is updated, I'll approve.

**Comment by shanfenggood** [comment]
@laboon @mmagician  Thanks a lot, i update bitccoin amount to 0.4 now

**Review by mmagician — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Review by laboon — APPROVED** [review]

**Pull request merged**
