### PR TITLE
MolochDAO substrate pallets v1 and v2

### PR DESCRIPTION
**Pull request by zhangjiannan**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. This looks good to me and worth supporting. I will share it with the rest of the team.

**Comment by BenWhiteJam** [comment]
@zhangjiannan, thanks for the application and very cool to see this.
1. Reading the whitepaper and the grant application, I wonder if you could elaborate on the expected update/release of the MolochDAO whitepaper as it stated Draft V1.0 and got released in Jan 2019?
2. According to this, what is your strategy to update/maintain the pallet with new findings and/or changing logic?

Maybe you can add a couple of sentences in that regard to the application?
Generally, I'm pleased to support you as well!

**Comment by zhangjiannan** [comment]
Hi @Noc2 @BenWhiteJam thanks for your feedback! I just updated the application (overview and project details) and provided more thoughts on Moloch and our future development plans. In general, in this grant, we do not plan to change the design / structure of Moloch v1 and v2, because we want to keep the simplicity of the mechanism which works well in multiple case cases in the Ethereum ecosystem. However, with the flexibility provided by Substrate, and interoperability provided by Polkadot, we can develop the codebase into an open DAO infrastructure. However, that will be a separate proposal and will depend on a successful delivery of this grant.

**Review by Noc2 — DISMISSED** [review]

**Comment by alxs** [comment]
Hey @zhangjiannan. I haven't looked at this in detail though it looks pretty good to me too. Just one quick request: could you remove the `.DS_Store` file from the PR?

**Review by mmagician — COMMENTED** [review]
Looks good. I'm happy to proceed as soon as the .DS_Store is removed as @alxs pointed out!

**Comment by zhangjiannan** [comment]
The .DS_Store file should have been removed now.

**Review by mmagician — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Pull request merged**
