### PR TITLE
Web3 Grants Application for Polkadex

### PR DESCRIPTION
**Pull request by Gauthamastro**
# Grant Application Checklist

- 

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.

- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. As discussed previously, we are quite interested in the application. Our current block time on kusama and polkadot is six seconds long, so I guess you initially want to create a separate chain, rather than becoming a parachain, correct? Keep in mind that as a parachain/thread, your dex will be immediately connected to all parachains/threads as well as implemented bridges. Also regarding the ethereum bridge, you should take a look at our trustless bridge, which is currently under development here https://github.com/Snowfork. 
Overall, I think it might make more sense for you to initially fully focus on the dex and wait until the bridge is ready. Your current application is also above 30k, so maybe start with M1 as well as M3. What do you think?

**Comment by Noc2** [comment]
And I think we would still be interested in your Pebble consensus, but this could be part of a separate application.

**Comment by Gauthamastro** [comment]
Thanks for your reply, @Noc2 . We are also considering Pebble Consensus for another application. We are currently focused on implementing the DEX. We did check out the Snowfork repository during our research, but we couldn’t find any documentation related to it. That’s why we went ahead with ChainBridge. As you have said, we are happy to integrate Snowfork if we get some documentation about how it functions. 

As you mentioned, our trading engine will be present in a separate independent Substrate chain. We cannot afford to have six-second block time when we want to provide a responsive UI/UX to users. We will be implementing the parachain on Polkadot for bringing in liquidity to our DEX chain using the Substrate-to-Substrate bridge, thereby getting connected to Polkadot.

Based on your suggestion, we will remove the Milestone 2 from our application to focus on the DEX. We will make modifications and commit for your review.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. This looks good to me. Just a general comment: I would still love to see you integrate this as a parachain. Maybe you can leverage things like the memepool or other ideas in order to achieve a quicker “finalization” of transactions (for example based on your own consensus). We would be interested and probably fund ideas to improve this.

**Review by mmagician — APPROVED** [review]

**Comment by Gauthamastro** [comment]
Thank you for your valuable suggestions, but at the moment, we would like to focus on launching the DEX and providing the best trading experience for the crypto community as soon as possible.  We will upgrade our chain to be a parachain once our consensus algorithm is ready or parachains can have shorter block time in Polkadot.

**Review by RouvenP — APPROVED** [review]

**Comment by mmagician** [comment]
@Gauthamastro Could you please email us at grants@web3.foundation and provide some details of your team?
In particular, we would need:
- legal names of a team representative
- address of your legal entity (if individual, then your personal address)

If you're planning to register a company before the submission of the milestones, we can wait and get the company details later. Let me know! 

Thanks

**Comment by Gauthamastro** [comment]
Thank you @Noc2 @mmagician @RouvenP  for selecting us for the web3 foundation grants program !!! We are excited to join the team of people working towards a decentralized web. We will send the details over email and take it forward.

Thank you once again!

Best,
Gautham J

**Pull request merged**
