### PR TITLE
Add application for SubDAO Chrome Extension

### PR DESCRIPTION
**Pull request by WannaM**
Add application for SubDAO Chrome Extension

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by WannaM** [comment]
Hi @Noc2 , we submit a new application for a Chrome Extension which has polkadot wallet integrated. Could you help to review this application?

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. In general, @semuelle should probably also take a look at the application, since he reviewed your last delivery. Regarding the deliveries in the table, could you be more specific in the table itself. For example it currently only says “Source Code: We will provide the source code of this extension.”  That is not something we can really test. What functionality are you going to implement? Which programming language, etc. Why did you choose AGPL instead of Apache, MIT, etc?  Furthermore, could you also add an example DAO to the deliveries, that can be used together with the extension?

**Comment by WannaM** [comment]
> Thanks for the application. In general, @semuelle should probably also take a look at the application, since he reviewed your last delivery. Regarding the deliveries in the table, could you be more specific in the table itself. For example it currently only says “Source Code: We will provide the source code of this extension.” That is not something we can really test. What functionality are you going to implement? Which programming language, etc.

@Noc2 Thanks for your comments. The application is updated. @semuelle  could you please help to continue the review?

> Why did you choose AGPL instead of Apache, MIT, etc?

Since we will use some source code with an AGPL license, we have to follow it and keep it.

> Furthermore, could you also add an example DAO to the deliveries, that can be used together with the extension?

Sure, an example DAO will be provided as default to verify this extension.

**Comment by WannaM** [comment]
> Thanks for the quick reply. Could you integrate the example into the deliveries? Ideally you would also define what “ and so on” means.

Updated. Could you help to check it?

**Review by Noc2 — APPROVED** [review]
Thanks for the update. Looks good to me. I will share it with the rest of the team.

**Review by mmagician — APPROVED** [review]
Looks interesting, good luck!

**Comment by alxs** [comment]
Hey @WannaM. May I ask you to please remove the Web3 Foundation logo from your list of partners [here](https://subdao-network.vercel.app/)? We explicitly don't partner with anyone. Thanks in advance.

**Comment by WannaM** [comment]
> Hey @WannaM. May I ask you to please remove the Web3 Foundation logo from your list of partners [here](https://subdao-network.vercel.app/)? We explicitly don't partner with anyone. Thanks in advance.

Hi @alxs, thanks for the reminder!  It's our test design for the new website, not official yet. The official website is https://subdao.network.  Already the repo is removed from our org, and the link is disabled.

**Comment by WannaM** [comment]
@semuelle  Could you help to continue the review?

**Comment by semuelle** [comment]
I am very excited about a snappy DAO frontend. 

Could you explain why you chose to include Twitter and Facebook integration into it? Their use is not required, correct? In line with the decentralisation theme, wouldn't it make more sense to include a _decentralised_ messaging protocol?

**Comment by WannaM** [comment]
> I am very excited about a snappy DAO frontend.
> 
> Could you explain why you chose to include Twitter and Facebook integration into it? Their use is not required, correct? In line with the decentralisation theme, wouldn't it make more sense to include a _decentralised_ messaging protocol?

Good question! To include Twitter and Facebook is mainly because we would like to let the Web 3.0 world injected into Web 2.0 social networks, and expose the benefits of Web 3.0 technologies. It will let more and more people get involved. We can imagine, people in web 2.0 social networks will be able to use decentralized orgs without interferings from any central governace.

**Comment by semuelle** [comment]
Thanks for the reply, @WannaM. To be honest, I am more of a `Do One Thing And Do It Well` proponent, but that won't block me from approving this grant. As long as it's not a requirement to use either one and people can fork it to produce a barebones version, I'm happy.

**Review by semuelle — APPROVED** [review]

**Comment by WannaM** [comment]
> Thanks for the reply, @WannaM. To be honest, I am more of a `Do One Thing And Do It Well` proponent, but that won't block me from approving this grant. As long as it's not a requirement to use either one and people can fork it to produce a barebones version, I'm happy.

Thanks for your great effort!

**Comment by semuelle** [comment]
@WannaM, your milestone submission (https://github.com/w3f/Grant-Milestone-Delivery/pull/203) has now been inactive for more than six weeks. If you are not planning on continuing the project, we would terminate the grant. Please let us know about the status of your grant-related activities asap.

**Comment by WannaM** [comment]
> @WannaM, your milestone submission ([w3f/Grant-Milestone-Delivery#203](https://github.com/w3f/Grant-Milestone-Delivery/pull/203)) has now been inactive for more than six weeks. If you are not planning on continuing the project, we would terminate the grant. Please let us know about the status of your grant-related activities asap.

Hi @semuelle , Sorry for the late reply on this milestone delivery. I have update the status of milestone [here](https://github.com/w3f/Grant-Milestone-Delivery/pull/203)

**Pull request merged**
