### PR TITLE
Glow simple, secure DApp DSL proposal

### PR DESCRIPTION
**Pull request by zbraiterman**
update glow.md

# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by zbraiterman** [comment]
The Mutual Knowledge Systems team is submitting this application to port our Glow programming language to the Polkadot platform.

**Comment by mmagician** [comment]
@zbraiterman Thanks for the application. I found a number of things that need to be clarified in your application, which also tell me you probably haven't checked the final submitted document properly:
1. It seems like you haven't resolved your git conflicts properly and there's still some leftovers of this in your application.
2. The formatting of your code examples in the Appendix is off.
3. We would need more details for deliverables such as:
```
We will create a Substrate module (in Rust) that will interface with the Glow runtime (in Scheme) such that Glow can interface with Substrate chains, send transactions, create contracts, send messages to contracts, watch messages received by contracts, and marshal data between Substrate and Glow.
```
You say "interface", but this is vague in the context of substrate integration. Please provide more details on how you envision this "interface" to be like. For example, here's a short version of how `ink!` does it:
`ink!` contracts are compiled to WASM and the WASM blob is stored on-chain. The contract can then be instantiated multiple times (if needed) with its own sandboxed storage. Each call made to the contract instance calls one of the APIs exposed by the `pallet-contracts` under the hood, e.g. for storing a value or emitting an event. 

We expect similar information, and ideally not just the short version, for your 
4. You have **redefined** the mandatory deliverables 0a-0d. Please make sure that your application includes the originals. Critically, you have completely skipped any sort of unit/intergration tests.

**Review by mmagician — CHANGES_REQUESTED** [review]
@zbraiterman Thanks for the application. I found a number of things that need to be clarified in your application, which also tell me you probably haven't checked the final submitted document properly:
1. It seems like you haven't resolved your git conflicts properly and there's still some leftovers of this in your application.
2. The formatting of your code examples in the Appendix is off.
3. We would need more details for deliverables such as:
```
We will create a Substrate module (in Rust) that will interface with the Glow runtime (in Scheme) such that Glow can interface with Substrate chains, send transactions, create contracts, send messages to contracts, watch messages received by contracts, and marshal data between Substrate and Glow.
```
You say "interface", but this is vague in the context of substrate integration. Please provide more details on how you envision this "interface" to be like. For example, here's a short version of how `ink!` does it:
`ink!` contracts are compiled to WASM and the WASM blob is stored on-chain. The contract can then be instantiated multiple times (if needed) with its own sandboxed storage. Each call made to the contract instance calls one of the APIs exposed by the `pallet-contracts` under the hood, e.g. for storing a value or emitting an event. 

We expect similar information for the Glow language.

4. You have **redefined** the mandatory deliverables 0a-0d. Please make sure that your application includes the originals. Critically, you have completely skipped any sort of unit/intergration tests.
5. Finally, you still need to sign the CLA.

**Comment by mmagician** [comment]
I'm going to close this PR for now due to incompleteness of the application and inactivity. Feel free to re-open it while you have more details.

**Pull request closed without merging**
