### PR TITLE
IP-Rights compliant NFT bridge protocol

### PR DESCRIPTION
**Pull request by Nokhal**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the new application. I think this is the first research focused application via the open grants program. I already shared it internally with others, who might know more about NFTs in general. Could you integrate the [PSP process](https://github.com/w3f/PSPs) into the application? Or where are you planning to publish your specification and under which license? Also if I understand it correctly the application is not so much about XCMP compatible, but it’s rather about [SPREE](https://wiki.polkadot.network/docs/en/learn-spree#docsNav), correct? Furthermore, since it seems you want to focus on Moonbeam and a solitidity implementation, it might make sense to apply for the solidity specific parts via the [Moonbeam Grants Program](https://moonbeam.network/community/grants/). We usually don’t support solidity code implementations (milestone 4), simply because we are no solidity experts and don’t know what contracts already exist or could provide a lot of valuable feedback regarding the implementation. Let me know if this sounds interesting to you and I will put you in contact with the team.

**Comment by Nokhal** [comment]
Thanks for the quick answer.  
  
>PSP process into the application                 

Of course. It is just a matter of formatting.

>Or where are you planning to publish your specification    

We have nothing too specific in mind yet, as it's targeted toward NFTs as a whole, and not just polkadot or EVM chains. This standard should be able to be used by a web2 API with trusted centralization (a publisher, a bank, a video game company) to migrate their NFT to a public decentralized trustless blockchain.
What we had in mind was a static website/github/Ipfs page we host for the "generic" pseudocode standard, and then version specific to EVMs as an Ethereum EIP and a version specific to Polkadot as a PSP. Once again, it's only a formatting question. Function names, arguments, and their predicate/postulate stay the same, but more environment specific variables such as visibility, throw conditions, stack size limitation, gas cost limits, interface abstractions, available level of trust for relays, etc... might need different wording.

It is to be noted that this standard will have several modules, as redemptions (recovering an original NFT token) and counterfeit prevention need to be platform specific. This initial grant only covers the communication standardization. We then plan on developing the appropriate modules and libraries to implement this standard. Nonetheless other teams should be able to develop their own implementation from the standard alone.

>and under which license?        
      
Unlicense is preferred, MIT/Derivative is acceptable. The bridge needs to be as open as possible in order to reach as many actors as possible.          
       
>but it’s rather about SPREE, correct?        
         
Correct.  More generally : If an NFT exists somewhere, it's owner should be able to bring it to any polkadot parachain and move it around them. The "generic" standard will not enter into the detail of the implementation outside of "must" and "should" of the predicate/postulate of the migration for various cases (namely, is the relay trusted or trustless), but the PSP will get into the finer implementation details as there is a trustless communication channel.
       
>We usually don’t support solidity code implementations (milestone 4), simply because we are no solidity experts and don’t know what contracts already exist or could provide a lot of valuable feedback regarding the implementation.       
         
Any Turing complete language with scope and function definition is fine. We are expecting this standard to be read mostly by developers of NFT platforms, and given the prevalence of Solidity in most NFT projects, it seemed like the natural choice.
       
>Let me know if this sounds interesting to you and I will put you in contact with the team.    
          
Thank you very much for the offer David, we are already in touch with the Moonbeam team. We will be seeking some grant funding for the NFT.com platform from them, but specifically not for the bridge.  This is because the bridge needs to be applicable to all chains (and classic www databases, etc...) and not just to Ethereum Mainnet <=> Moonbeam. This is why we are coming to the Web3 Foundation for the open grant as Polkadot's vision is to become the glue between all blockchains. In the future we want any parachain using NFT's to be able to trivially migrate them to other parachains.

**Comment by Noc2** [comment]
Thanks for the quick and very detailed reply. Makes sense. Could you integrate this into the deliverables (license, psp, website, etc)? Regarding milestone 4, could you replace solidity with ink! for now. Given that ink! is a new smart contract language we have a certain interest in promoting/improving it. Moonbeam potentially could fund the implementation in solidity. This way you would also be able to explore differences between smart contract languages.

**Comment by Nokhal** [comment]
Request changes pushed.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m happy to go ahead with it and will share it with the rest of the team. Maybe the following project might also be interesting for you https://github.com/t3rn/t3rn I could put you in contact with the team in case you are interested in it.

**Review by mmagician — APPROVED** [review]

**Comment by RouvenP** [comment]
thanks for the application @Nokhal. could you please indicate the cost in BTC?

**Comment by laboon** [comment]
Besides the lack of price, looks good to me.

**Comment by RouvenP** [comment]
> thanks for the application @Nokhal. could you please indicate the cost in BTC?

I missed that we also pay in DAI now - please ignore my comment @Nokhal

**Review by RouvenP — APPROVED** [review]

**Comment by alxs** [comment]
Thanks for the update @edouardru, that's good to hear!

Looks quite impressive to be frank, keep up the good work and don't worry about the delay. And feel free to submit the milestones separately, which may allow you to get some feedback (or in case it's accepted straight away, which seems possible by the looks of it, some funding) before you've finalised the project.

**Comment by alxs** [comment]
@edouardru I'm getting the impression that this project is slowly being forgotten - I hope that's not the case? Seeing as this is stretching a bit too far in duration though, could you submit an amendment to update the duration or include an ETA in the application?

Note that if we don't hear from you within the next two weeks, we'll assume you're no longer interested and terminate the grant.

**Comment by edouardru** [comment]
@alxs rest assured this has been far from forgotten! We now have a working bridge (technical demo) and are currently implementing the first relay on that bridge, with the goal of having a finalised NFT migration protocol, backed by a fully operational EVM bridge+ relay by the end of the month. Deciding to implement a full bridge + relay in parallel of this grant has been a lot of work, but this approach was definitely a great choice as it raised some issues that previous versions of the protocol didn't not take into account, and we are very confident of the robustness of the protocol once we'll have updated it. Thanks for following up on this.

**Comment by alxs** [comment]
@edouardru glad to hear that, and thanks for the update! That is definitely no small feat - wish you a successful final stretch, I'm looking forward to the results.

**Comment by edouardru** [comment]
Hello @alxs @Noc2! @Nokhal and I are happy to say after a lot of work, the IP-compliant NFT migration bridge is working! We have deployed the bridge on Rinkeby, Kovan and Moonbase Alpha based on the Protocol, implemented a first relay for these bridges and are running tests. You can access and use it here: https://bridge.mynft.com/

We will now work to update and finalise the [NFT migration protocol](https://docs.google.com/document/d/1c5Uor2By5igFWXimipcKhsWjTAG8OWrl9bSVWTPsi6U/edit?usp=sharing) itself to conclude the work of the grant, and then we will work on a beta release of the bridge on commercial chains.

This is not ready to be shared publicly yet but please don't hesitate to share the bridge URL with people that can give feedback. They can reach out on the NFT migration protocol Telegram channel [here](https://t.me/joinchat/RPmyXRzrh_-AuLfK) or directly at bridge@mynft.com

Thank you for your support and patience so far

Edouard & Guillaume

**Comment by alxs** [comment]
Hey  @edouardru, very happy to hear that! I gave it a quick test run and the experience was mostly seamless - very impressive work. I only hit a wall at "Please sign the migration hash to continue the migration" where I didn't know what it was asking me to do.

Also, a reminder that the scope can be amended. If the development work isn't being funded otherwise, we can compensate you for it as part of the grant.

**Comment by edouardru** [comment]
Thank you @alxs! Yes session persistence is part of the list of features for the next release.

Everything related to the bridge is open-source. I will get back to regarding amending the scope when I have time, we have many more ideas of what needs to be built :)

**Comment by alxs** [comment]
@edouardru any news? I recommend you submit an amendment anyway to update the timeline unless you're planning to submit soon, as the grant was approved now nearly a year ago.

Besides, can I ask you to please remove the grants badge from the list of partners on your [website](https://www.mynft.com/)? Please have a look at its [usage guidelines](https://github.com/w3f/Grants-Program/blob/master/docs/grant-badge-guidelines.md#usage-guidelines-for-the-w3f-grants-program-badge), which specifically state it may only be displayed in the context of the work done for the grant, only after the first milestone has been approved, and that it doesn't represent a partnership. So you ticked almost all the wrong boxes ;)

**Comment by edouardru** [comment]
@alxs we are working on the amendment now. I will let you know when we're ready to submit (probably early next week). 

Otherwise progress is great, by the end of the month we'll have completed the following features/deployment:
* Moonriver deployement
* Ethereum mainnet deployement
* Allow multiple transactions to be sent into one block
* Persist migration data
* User should be able to see his/her NFTs displayed on the page and select, migrate and redeem IOU with a nice UI.
* Add token to wallet at the end of the process so with 2 clicks the newly minted IOU appears in my Metamask 
* Support of private ipfs nodes
* Moonbeam deployment

I also removed the grant badge from the website earlier today, really sorry about this!

**Comment by edouardru** [comment]
Hi @alxs we've finally completed an updated scope. You can find it at the link below. Thank you for your patience and please let me know your thoughts.

[https://docs.google.com/document/d/1bI27scqLmef39nqVGwoMjcC0ztZIHiiRbM2mzbGw9DQ/edit?usp=sharing](https://docs.google.com/document/d/1bI27scqLmef39nqVGwoMjcC0ztZIHiiRbM2mzbGw9DQ/edit?usp=sharing)

Also, all the features mentioned in my previously message are now completed excluding "User should be able to see his/her NFTs displayed on the page and select, migrate and redeem IOU with a nice UI" which still needs testing but almost done.

**Comment by edouardru** [comment]
@alxs  We have added a "Scope Update" section at the end to explain the reasoning and what has changed compared to the original scope. I have also just updated the privileges so you can comment directly on it if you wish.

**Comment by alxs** [comment]
Hey @edouardru. Looks good, thanks for the updates. In order to modify the scope of this grant, you need to create a PR to update the original document. For the rest it looks good, though I advise you to provide a list of deliverables as in the application template, which we'll probably request otherwise. The deliverables should also read more as a specification against which we can verify your delivery, rather than as a timeline.

**Pull request merged**
