### PR TITLE
propose Java client lib

### PR DESCRIPTION
**Pull request by splix**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Comment by Noc2** [comment]
Thanks for the application. It looks really good. Could you maybe add docker images and unit tests?

**Comment by splix** [comment]
@Noc2 sure, I thought unit tests do not need special mention, will add them. Instead of Docker I propose to make a simple Example App, as a code, so anyone can play with it, compile, run.

**Comment by splix** [comment]
@Noc2 added unit tests

**Comment by gautamdhameja** [comment]
Mostly looks good to me too. I would suggest adding a bit more details to Milestone 2 regarding accessing Substrate APIs. Does it cover all RPCs exposed by Substrate node?

**Comment by splix** [comment]
@gautamdhameja that's the tough part. It doesn't seem to be feasible to cover _all_ of the APIs in a single milestone. The goal is to support _most_ of critical APIs. So it's a bit unclear right now, also unclear what is the final list of APIs, I only see them in the implementation right now (would appreciate a link to spec, I guess I missed it). It also makes sense to finalize extrinsic-related APis only with the Milestone 3

**Comment by gautamdhameja** [comment]
Yeah, it makes sense to target sending extrinsics related APIs in milestone 3. In milestone 2, you can target storage reads, system and runtime metadata, and listening to events (subscriptions). 

Here's a list of RPC calls supported by the JS client - https://polkadot.js.org/api/substrate/rpc.html

In the Java client, we might not need all of them right away. For example, at this time, we can safely assume we won't need `engine`, `babe`, and `child storage` categories, I think.

**Comment by splix** [comment]
@gautamdhameja yeah, that's exactly my thoughts. Want to start with the most essential things, and add things one by one when it needed.

**Comment by splix** [comment]
@gautamdhameja @Noc2 I've updated the proposal with RPC details

**Comment by splix** [comment]
Sure, I'll try to do the best I can. Better to overdeliver than overpromise.

**Pull request merged**
