### PR TITLE
Grant Application PolkaCasino Project

### PR DESCRIPTION
**Pull request by PolkaCasinoLab**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Overall I think we are quite interested in this kind of application, since we don’t have something similar in our ecosystem yet. I think it might make sense to initially focus on Kusama for this kind of project. However, I have a few questions/comments related to your application: 

- Could you in general specify the milestones better (e.g. programming language)?
- Could you add things like unit-tests, tutorials etc., see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md 
- Could you specify which game you want to implement initially?
- Could you remove the whitepaper and focus with the website on the substrate-ui part?

**Comment by PolkaCasinoLab** [comment]
> Thanks for the application. Overall I think we are quite interested in this kind of application, since we don’t have something similar in our ecosystem yet. I think it might make sense to initially focus on Kusama for this kind of project. However, I have a few questions/comments related to your application:
> 
> * Could you in general specify the milestones better (e.g. programming language)?
> * Could you add things like unit-tests, tutorials etc., see https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md
> * Could you specify which game you want to implement initially?
> * Could you remove the whitepaper and focus with the website on the substrate-ui part?

Hello, thanks for your reply and the thoughtful questions/comments. We made changes to our application file with respect to the points you made in the questions/comments. Hope you enjoy reading our application.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. Looks good.

**Comment by Noc2** [comment]
Thanks again for the application. We had an internal discussion about your project and we don’t think we should support your application. The Web3 Foundation shouldn’t support projects that focus on gambling or use gambling to generate profits. Therefore I’m closing the application. You are more than welcome to apply again with another project.

**Pull request closed without merging**
