### PR TITLE
xtoken - XCM Implementation for Fungible Assets

### PR DESCRIPTION
**Pull request by bette7**
# Grant Application Checklist

- [x ] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x ] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x ] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x ] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x ] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x ] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Comment by Noc2** [comment]
Thank you for your application. We've recently updated the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this?

**Comment by bette7** [comment]
> Thank you for your application. We've recently updated the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this?

Sure. Do we still need to specify a payable BTC amount?

**Comment by Noc2** [comment]
@bette7 Could you also update the total costs? And I just noticed that the PR currently consists of two applications/files.

**Comment by bette7** [comment]
> @bette7 Could you also update the total costs? And I just noticed that the PR currently consists of two applications/files.

Fixed. Thanks.

**Review by Noc2 — APPROVED** [review]
Looks good to me. I will share it with the rest of the team.

**Review by BenWhiteJam — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Pull request merged**
