### PR TITLE
Polkastarter Grant Application

### PR DESCRIPTION
**Pull request by polkastarter**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the grant application. This sounds really interesting. Do you already have some mockups which you can share? This is usually a requirement for UI focused grant applications. Also in which programming languages do you plan to create the UI. And just to be 100% sure, you are referring to the following [pallet](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/crowdloan.rs), correct?

**Comment by tiagom87** [comment]
Hi David

Thanks for getting back to us so quickly. We are producing low fidelity mockups this week so you can have a glimpse of the look and feel of the UI. Will get back to you soon.

Appreciate it

**Comment by Noc2** [comment]
Great. Thanks for the update.

**Comment by tiagom87** [comment]
Hi David

Here are some low fidelity mockups for the index, show, and join pages:

https://drive.google.com/drive/folders/1ZF_ayMvXmAkqqhBDUDf5-yMjdyzQEklK?usp=sharing

Any questions, I am happy to answer.

ps: The look and feel should be very similar to the [Polkastarter](https://www.polkastarter.com) design language.

**Comment by Noc2** [comment]
Thanks. Could you integrate these into the application? Also I have one more question/request: What kind of user testing are you going to perform as part of milestone 2 and could you maybe integrate a report or something similar about the user testing into milestone 2? Currently it’s quite difficult for us to evaluate this delivery. Additionally maybe add 0a, 0b and 0c to the milestone 2 deliveries. It might make more sense to also have the article ready once you finished the second milestone and not together with the first one.

**Comment by tiagom87** [comment]
David, can you please clarify what you mean by "Could you integrate these into the application?"

Thanks

**Comment by Noc2** [comment]
> David, can you please clarify what you mean by "Could you integrate these into the application?"
> 
> Thanks

Sorry, I meant could you integrate the link to the mockups into the .md file/the application itself.

**Comment by tiagom87** [comment]
Absolutely David. Will do it now

**Comment by Noc2** [comment]
Just a reminder regarding the following: 

> Thanks. Could you integrate these into the application? Also I have one more question/request: What kind of user testing are you going to perform as part of milestone 2 and could you maybe integrate a report or something similar about the user testing into milestone 2? Currently it’s quite difficult for us to evaluate this delivery. Additionally maybe add 0a, 0b and 0c to the milestone 2 deliveries. It might make more sense to also have the article ready once you finished the second milestone and not together with the first one.

@tiagom87 you now also have to sign the the cla

**Comment by tiagom87** [comment]
Hi David, just added your suggestions and signed the cla. Can you please check if everything looks good? Appreciate it

**Review by Noc2 — APPROVED** [review]
Thanks for the update. I’m willing to go ahead with it. Just something you should be aware of: Even though your milestone 2 currently doesn’t have an open source license, we would still expect you to open source the delivery. The default license of our grants program is apache 2. And I suspect that “a battery of” will be more than 2 or 3 ;-)

**Review by RouvenP — APPROVED** [review]

**Comment by tiagom87** [comment]
Hi David. Absolutely, apologies for not defining the battery part. We usually create a quality assurance flow for every possible user outcome accounting for sunny and rainy day scenarios. Appreciate all your help!

**Review by BenWhiteJam — APPROVED** [review]

**Comment by tiagom87** [comment]
@Noc2 Hi David

We just submitted the milestone 1 deliverable but it seems some auto checks failed:
```

Run ./.github/actions/validate_pr
  with:
    targetRepoOwner: w3f
    targetRepo: Open-Grants-Program
    prLink: https://github.com/w3f/Open-Grants-Program/pull/204
    author: tiagom87
Author is tiagom87
Error: Cannot read property '0' of null
```

We initially submitted the grant application with Polkastarter being a github user and now an organization with me owner.

Let me know what we can do

Thank you!

**Comment by alxs** [comment]
Hi @tiagom87. Don't worry about this, thanks for making us aware of it. I think since you were involved in the discussion from the beginning this shouldn't be a problem.

**Comment by tiagom87** [comment]
Thank you for the quick reply @alxs !

**Pull request merged**
