### PR TITLE
Add privacy-preserving decentralized storage scheme to Decredit

### PR DESCRIPTION
**Pull request by Maedamoto**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Comment by Maedamoto** [comment]
This PR is an update to #88 

Hey @Noc2 ! I'm reapplying the grant with a privacy-preserving decentralized storage scheme (PDP) update. We will implement this scheme as our storage infrastructure.

Please kindly let me know if there's any problem or question.

Best,

**Review by mmagician — CHANGES_REQUESTED** [review]
@Maedamoto Thanks for another application. As it stands, your application does not seem to contribute to the Substrate/Polkadot ecosystem. We can only support projects that add value to our ecosystem.
In case I missed something regarding the previous point, then still `Implementation of DeCredit privacy-preserving decentralized storage scheme` is quite vague. Even when I refer to your design docs PDF, it is difficult to foresee what the outcome of such implementation would be - could you be more specific about the deliverables and final outcome of your work please?

**Comment by Maedamoto** [comment]
@mmagician Thanks for the response and your effort to review our PR again. First I want to apologize for any misunderstanding in the description. 

The final outcome of our work for this open grant application will be a decentralized storage network. The features of our network are as follows:

1) It keeps storage correctness: to ensure that there exists no cheating storage node that can pass the audit without indeed storing users’ data intact.
2) It supports public auditing: to allow any Auditor to verify the correctness of the data without retrieving a copy of the whole data or introducing additional network burden.
3) It supports batch auditing:  to enable the Auditor with secure and efficient auditing capability to cope with multiple auditing assignments simultaneously.
4) It is privacy-preserving:  to ensure that the Auditor cannot derive users’ data from the information collected during the auditing process.

We use blockchain to coordinate the User, Storage Node and Auditor in this network. 

In Milestone 1, we will deliver a static data storage network for single user (which means the data owner is also the data consumer) and UI/CLI for the User to upload his/her data. In future plan we will enable data Dynamics (AUD). 

In early stage, our existing users from internet can use DeCredit Network to store their files and data with privacy-preserved. And we would likely share most of the storage capacities with our existing hardware infrastructure.

I image in the future, we can attract many more storage capacities from free contributors by our incentives. And  when DeCredit is on a parachain/thread, it can be used in the whole Polkadot ecosystem to store data from different applications.

**Comment by mmagician** [comment]
So do I understand correctly that the storage nodes will have full access to the stored data? In this case the privacy against Auditors is meaningless, since they could just assume the double role of Storage Nodes and get users' data, no?

It sounds as if your end goal is a Filecoin-like storage solution, where nodes are incentivised to store data.
As far as I understand, the block production mechanism plays the role of the Auditor on Filecoin, forcing the storage nodes to provide proof of storage. In your protocol it would be an actual end-user assuming the Auditor role, yes?
Why would anyone want to be Auditor, i.e. what benefits does it bring?

Could you elaborate on the differences between yourself and Filecoin (or even plain IPFS) please?

> In Milestone 1, we will deliver a static data storage network for single user

Please integrate this into the application. Also please explain what you mean by static data storage. What concrete deliverables will it contain (a binary? substrate module? script?)

Finally, I still don't see how you tie into the Polkadot ecosystem - please detail (technically) how your storage solution will be integrated into Polkadot.

**Comment by Maedamoto** [comment]
>So do I understand correctly that the storage nodes will have full access to the stored data?

It depends on if the User upload the file with encryption. User could choose how to encrypt the file or just upload the unencrypted content.

>In this case the privacy against Auditors is meaningless, since they could just assume the double role of Storage Nodes and get users' data, no?

For the Auditor, he just audit the data correctness but not the content, so he doesn't care wether the file is encrypted or not.

>In your protocol it would be an actual end-user assuming the Auditor role, yes?
Why would anyone want to be Auditor, i.e. what benefits does it bring? 
Could you elaborate on the differences between yourself and Filecoin (or even plain IPFS) please?

Any participate in the network who has made a staking could be chosen as the Auditor. The Auditor could receive incentives (token) by providing honest auditing.

Filecoin (or even plain IPFS) is more like a general storage protocol and our design is more like a specific storage service. And that's why we want to use Substrate to build our own chain for block produce and governance.

>Please integrate this into the application. Also please explain what you mean by static data storage. What concrete deliverables will it contain (a binary? substrate module? script?)

Static data storage means in Milestone 1, the design doesn't support data dynamic. If the User wants to update/modify the file, he must upload another copy. 

The deliverables would contain a binary, API service and a web app. 

>Finally, I still don't see how you tie into the Polkadot ecosystem - please detail (technically) how your storage solution will be integrated into Polkadot.

Our design will provide APIs and CLI tool. Being involved in Polkadot ecosystem, if any application/protocol needs a storage infrastructure, it can use our design as a choice.

**Comment by mmagician** [comment]
Thanks for your answers. In the light of these, let me comment on the features of your solution that you mentioned earlier:

> It keeps storage correctness: to ensure that there exists no cheating storage node that can pass the audit without indeed storing users’ data intact.
> It supports public auditing: to allow any Auditor to verify the correctness of the data without retrieving a copy of the whole data or introducing additional network burden.

These are basically the same

> It supports batch auditing: to enable the Auditor with secure and efficient auditing capability to cope with multiple auditing assignments simultaneously.

It doesn't bring anything new, apart from saying that auditing is efficient 

4. It is privacy-preserving: to ensure that the Auditor cannot derive users’ data from the information collected during the auditing process.

If data is encrypted, they can't gain any information anyway. If it's unencrypted, the Auditor can instead assume the role of a Storage Node and thus gain access to all data.

---
To further comment on your answers:

> Filecoin (or even plain IPFS) is more like a general storage protocol and our design is more like a specific storage service

This is very vague. 

> Static data storage means in Milestone 1, the design doesn't support data dynamic. If the User wants to update/modify the file, he must upload another copy.

That makes sense.

---
Finally: OK, I understand that you'll provide a binary and an API service, but I still don't see how this will integrate into Polkadot. Which component of the Polkadot network (end-users via some wallet/cli clients, validators via substrate off-chain workers?) would interact with your service? If you would like to be considered for the grant, you will need to provide much more technical information than this, it's a requirement of the application process.

**Comment by Maedamoto** [comment]
@mmagician Sorry for the delayed response. Please let me first illustrate the whole image of our project and then introduce the deliveries in MileStone 1.

DeCredit is constructed by Parity’s Substrate framework, its mission is to build an on-chain credit protocol based on the credit data from the real world. DeCredit could be used by any transaction which needs credit analysis for execution. (e.g. Credit Lending, Identity Authentication, Crowdsourcing, etc.)

The final deliveries of the project includes:

Node binary for DeCredit Chain;
Credit Scoring & Credit Matching Algorithm module;
DeCredit APIs;
DeCredit App to interact with the chain;

After DeCredit registering on Polkadot and becoming a parachain, applications in Polkadot ecosystem can use it to do credit evaluation and match their own credit requirements.

In addition, for own application use, in Milestone 1, we will build a storage infrastructure - DeCredit Cloud. In this MileStone, DeCredit Chain is in charge of incentives, punishments and governance of the Node (the Storage Node & Auditor Node) and Off-chain Worker will deal with the storage related work.

The deliveries of MileStone 1 includes:

Node binary  for DeCredit Chain;
Webapp to interact with DeCredit Cloud;
APIs and Cli to interact with DeCredit Cloud;

So after registering on Polkadot, DeCredit could also be used for data storage besides providing credit service.

**Comment by mmagician** [comment]
Again thanks for getting back to me. Given the current state of your application I still can't fully grasp how your solution would work on a technical level, but maybe it's just me failing to understand your project. I will share it with the rest of my team, let's hear about their input.

**Comment by Noc2** [comment]
Thanks for the new application and all the effort you put into this. However, the current milestone contains no deliveries that are in the scope of this grant program, since the application has nothing to do with the polkadot ecosystem in its current form. A decentralized storage network and a user interface for this network is outside of our core expertise. You might also implement a substrate based chain, but as far as I can see it, it’s not part of this project. Maybe you can apply for it via the [filecoin dev grants](https://github.com/filecoin-project/devgrants) or at least part of it. Therefore, I’m closing the application.

**Pull request closed without merging**
