### PR TITLE
create web3games.md 

### PR DESCRIPTION
**Pull request by Zombieliu**
# Grant Application Checklist

- [x] The [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( `project_name.md`) and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] I have read and acknowledged the [Terms and Conditions](https://github.com/w3f/Open-Grants-Program/blob/master/src/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/w3f/Grant-Milestone-Delivery).

### CODE REVIEW

**Comment by alxs** [comment]
Reopening the other PR in order to keep the conversation in one place https://github.com/w3f/Open-Grants-Program/pull/404

**Comment by alxs** [comment]
Thanks for the new submission. A reminder that deliverables `0a-c` in the application template need to be included in all milestones and that deliverables need to be quantifiable, potentially useful to other teams and not already present in the ecosystem. I.e. we won't fund things like deliverable 1 of M1 "Build initial node on Substrate 3.0 framework, customize key files and release testnet". They also need to be much more well-defined and explicit, i.e. deliverable 6 of M2 "Scaffolding for building blockchain games" is not a suitable specification.

Besides, a lot if not all of the modules you propose are already present in the ecosystem and unless you're able to compare them to existing solutions and explain their advantages I don't think we'll be able to support this. Furthermore  the sentence copied from the [SubGame](https://github.com/w3f/Open-Grants-Program/blob/75130602ddfb579e9e4f7c6e95259bb7fed16bf0/applications/SubGame_Network.md) application mentioning  `SubGame` instead of `Web3Games` is still there. What is you relationship to this team/project?

Lastly, you're still using code from multiple other projects without attribution in a number of your repositories. Please add a notice to all adapted files or otherwise make sure to comply with the respective licenses. [Here](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) is a brief overview of what it implies to base your work on projects with different licenses.

**Comment by Zombieliu** [comment]
> Thanks for the new submission. A reminder that deliverables `0a-c` in the application template need to be included in all milestones and that deliverables need to be quantifiable, potentially useful to other teams and not already present in the ecosystem. I.e. we won't fund things like deliverable 1 of M1 "Build initial node on Substrate 3.0 framework, customize key files and release testnet". They also need to be much more well-defined and explicit, i.e. deliverable 6 of M2 "Scaffolding for building blockchain games" is not a suitable specification.
> 
> Besides, a lot if not all of the modules you propose are already present in the ecosystem and unless you're able to compare them to existing solutions and explain their advantages I don't think we'll be able to support this. Furthermore the sentence copied from the [SubGame](https://github.com/w3f/Open-Grants-Program/blob/75130602ddfb579e9e4f7c6e95259bb7fed16bf0/applications/SubGame_Network.md) application mentioning `SubGame` instead of `Web3Games` is still there. What is you relationship to this team/project?
> 
> Lastly, you're still using code from multiple other projects without attribution in a number of your repositories. Please add a notice to all adapted files or otherwise make sure to comply with the respective licenses. [Here](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) is a brief overview of what it implies to base your work on projects with different licenses.

Lastly, you're still using code from multiple other projects without attribution in a number of your repositories. Please add a notice to all adapted files or otherwise make sure to comply with the respective licenses. Here is a brief overview of what it implies to base your work on projects with different licenses.    



> Thanks for the new submission. A reminder that deliverables `0a-c` in the application template need to be included in all milestones and that deliverables need to be quantifiable, potentially useful to other teams and not already present in the ecosystem. I.e. we won't fund things like deliverable 1 of M1 "Build initial node on Substrate 3.0 framework, customize key files and release testnet". They also need to be much more well-defined and explicit, i.e. deliverable 6 of M2 "Scaffolding for building blockchain games" is not a suitable specification.

1-Apologies, there might have been an editorial mistake in the previous file. We are not related to SubGame, we just wanted to clarify that we want to build blockchain games based on Substrate and Polkadot. 
2-Could I please ask which repositories you are referring to?
3-Thank you for the reminder, we will update our application based on your suggestions, as well as add a new section to explain how our pallets work in detail, and their advantages compared to other projects in the Polkadot ecosystem. “Scaffolding for building blockchain games” refers to a framework that will let other game developers quickly import repositories, interact with Substrate and develop blockchain games, which can be understood as a packed Substrate node template. Is this not a suitable specification because of the code, or something else?

**Comment by Zombieliu** [comment]
> Thanks for the new submission. A reminder that deliverables `0a-c` in the application template need to be included in all milestones and that deliverables need to be quantifiable, potentially useful to other teams and not already present in the ecosystem. I.e. we won't fund things like deliverable 1 of M1 "Build initial node on Substrate 3.0 framework, customize key files and release testnet". They also need to be much more well-defined and explicit, i.e. deliverable 6 of M2 "Scaffolding for building blockchain games" is not a suitable specification.
> 
> Besides, a lot if not all of the modules you propose are already present in the ecosystem and unless you're able to compare them to existing solutions and explain their advantages I don't think we'll be able to support this. Furthermore the sentence copied from the [SubGame](https://github.com/w3f/Open-Grants-Program/blob/75130602ddfb579e9e4f7c6e95259bb7fed16bf0/applications/SubGame_Network.md) application mentioning `SubGame` instead of `Web3Games` is still there. What is you relationship to this team/project?
> 
> Lastly, you're still using code from multiple other projects without attribution in a number of your repositories. Please add a notice to all adapted files or otherwise make sure to comply with the respective licenses. [Here](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) is a brief overview of what it implies to base your work on projects with different licenses.

1-Apologies, there might have been an editorial mistake in the previous file. We are not related to SubGame, we just wanted to clarify that we want to build blockchain games based on Substrate and Polkadot. 
2-Could I please ask which repositories you are referring to?
3-Thank you for the reminder, we will update our application based on your suggestions, as well as add a new section to explain how our pallets work in detail, and their advantages compared to other projects in the Polkadot ecosystem. “Scaffolding for building blockchain games” refers to a framework that will let other game developers quickly import repositories, interact with Substrate and develop blockchain games, which can be understood as a packed Substrate node template. Is this not a suitable specification because of the code, or something else?

**Comment by alxs** [comment]
Thanks for the clarification. In that case could you please remove this from the current application?

There is unattributed code at least in the first two repositories you provide, [web3games-blockchain](https://github.com/web3gamesofficial/web3games-blockchain) and [SubGat-Game-Contract-Library](https://github.com/web3gamesofficial/SubGat-Game-Contract-Library).

Sounds good. It's not a suitable specification because it doesn't specify what it does in any way. We should be able to verify that the deliverables match the specification when evaluating a milestone. Therefore, please list all the functionality that each of the deliverables will provide.

**Comment by Zombieliu** [comment]
> Thanks for the clarification. In that case could you please remove this from the current application?
> 
> There is unattributed code at least in the first two repositories you provide, [web3games-blockchain](https://github.com/web3gamesofficial/web3games-blockchain) and [SubGat-Game-Contract-Library](https://github.com/web3gamesofficial/SubGat-Game-Contract-Library).
> 
> Sounds good. The reason I stated that wasn't a suitable specification is that it doesn't describe its functionality. We should be able to verify that the deliverables match the specification when evaluating a milestone. Therefore, please list all the functionality that each of the deliverables will provide.

Thank you for telling us this. During this time, we have added a lot of content including detailed descriptions and features provided by the milestones, as well as some screenshots and recorded videos. If there is any problem, we can continue to discuss. We will modify it again according to the problem until satisfied.

**Comment by Zombieliu** [comment]
> Thanks for the clarification. In that case could you please remove this from the current application?
> 
> There is unattributed code at least in the first two repositories you provide, [web3games-blockchain](https://github.com/web3gamesofficial/web3games-blockchain) and [SubGat-Game-Contract-Library](https://github.com/web3gamesofficial/SubGat-Game-Contract-Library).
> 
> Sounds good. The reason I stated that wasn't a suitable specification is that it doesn't describe its functionality. We should be able to verify that the deliverables match the specification when evaluating a milestone. Therefore, please list all the functionality that each of the deliverables will provide.

Thank you for telling us these suggestions. We have updated a lot of content including functional descriptions, detailed content introductions, pictures and videos. If there is any problem, we will revise it again. Thank you

**Comment by alxs** [comment]
Thank you for the changes @Zombieliu. I have a couple more comments regarding:

#### Licensing

As far as I can see, if anything you've [removed the attribution](https://github.com/web3gamesofficial/web3games-blockchain/commit/78ae1d436cd90cfd69d73d91fe8b979627d68c74) from some of the files. This is obviously not what I meant ;) Please do take some time to go through the article I linked to in my last comment. For example, Apache 2.0 (under which for example the files in the ERC1155 library you use [are licensed](https://github.com/web3gamesofficial/web3games-contract-library/blob/main/example/erc1155/contracts/ERC1155.sol#L1)) is rather strict in this regard and you need to add a notice to every file you replicated or modified. This isn't a lot of work, just copy-paste a notice such as [this](https://pastebin.com/raw/Lz99iTeY) at the beginning of each file. Projects that reuse GPLv3 licensed components also need to be under this license in their entirety, and so on. This might seem fastidious, but we believe it is important to respect the constraints expressed by copyright holders when redistributing their work and we expect grantees to be able to do so.

####  Existing pallets

The application already looks much better, but as I stated in my last comment many of the deliverables already exist in the ecosystem. E.g. lending, staking, NFTs and auctions have already been implemented a number of times. Again, unless you're able to compare your proposed functionality to existing implementations for each of the deliverables, I'm afraid we won't be able to fund their development. Remember, the purpose of the Grants Program is to fund open source projects that _benefit the entire ecosystem_.

#### Team's experience

Neither you nor @wjsxqs are particularly active on GitHub and the Web3Games project has only been created as of recently. Do you have any past project you've worked on that you could share to demonstrate your experience? Your LinkedIn profile also lists no experience but only that you're currently completing a bachelor's degree in IT, and the profiles of the two other team members have no connections. Let it be noted that I don't believe someone's profile on some social media site is directly related to their technical abilities. But with nothing else to judge, I have to say considering this and the other issues I've mentioned I'm unlikely to support your application. However if you want to address my comments I'll be happy to share it with the rest of the team.

**Comment by alxs** [comment]
Closing due to inactivity. Feel free to still get back to me and I'll be happy to reopen the application.

**Pull request closed without merging**
