### PR TITLE
ChainJS Grant application

### PR DESCRIPTION
**Pull request by mblinder**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application! A few questions from my side:
- Do you also plan to support Kusama or general substrate chains? 
- Do you plan to maintain the library on your own? Keeping polkadot-js uptodate is currently a lot of work with all the changes in our ecosystem. 
- Given that https://github.com/polkadot-js already covers a lot of things, the current application seems rather expensive to me. Could you potentially increase the scope or reduce the price?

**Comment by Noc2** [comment]
I’m closing the application for now due to inactivity. Let me know once you are ready and if you want to reopen it.

**Comment by mblinder** [comment]
Updated content to include Kusama and added additional details.

**Comment by Noc2** [comment]
Sorry for the late reply here and thanks for the update. However, it seems currently expensive to me. Could you not just more or less copy the https://github.com/polkadot-js implementation and change the code a little bit for your purpose and exclude certain functionality? 29,700 seems a lot for this. Also do you plan to maintain this library? Anyway, I will share the application already with the rest of the team.

**Comment by mblinder** [comment]
Yes - we will be maintaining the library for the future!

**Comment by Noc2** [comment]
Any comments regarding the price. It seems the rest of the committee isn’t willing to support the application at this price either.

**Comment by mblinder** [comment]
Can you tell us the amount the committee is willing to fund for this project?

**Comment by Noc2** [comment]
Sorry, I don’t have a concrete number for you, since I don’t know what the others think is reasonable for this kind of work. To me personally, it just seems less work (than 2 FTE, 1 month) and the current day rate is already pretty expensive.

**Comment by mblinder** [comment]
I don’t think we can do it necessarily faster with all of the review and testing we do, however we can do it for $20k if that’s easier for you - it’s a much lower day rate that way.

**Comment by semuelle** [comment]
I like the concept of chainjs. And I see it has been actively developed over the past year. Two questions: 

- Since you mention ORE ID at the top of your application: I had a look at the whitepaper, and I'm wondering how the project manages to comply with GDPR. Could you explain that briefly? I thought that an application is in violation as soon as it stores any link between a public address and identifying information on a public blockchain.
- Do you plan on integrating more blockchains after Polkadot & Kusama?

**Comment by mblinder** [comment]
Thank for the support! 

- ORE ID only stores public keys on chain. The off-chain access control of connecting a known login to a public key is forgettable. We’ve had a couple GDPR take down requests in the past. In that case the user’s public keys stay on chain, but the off-chain mapping is erased.
- Yes, we’re talking to a few parachains, and we hope to add many different parachains in the long run. We also don’t support Bitcoin yet, and will likely do that soon!

**Comment by Noc2** [comment]
> I don’t think we can do it necessarily faster with all of the review and testing we do, however we can do it for $20k if that’s easier for you - it’s a much lower day rate that way.

To be honest, it still seems expensive to me. Could you potentially reduce it even further? What kind of work do you need to do as part of the grant? Could you not just more or less copy the https://github.com/polkadot-js implementation and change the code a little bit for your purpose and exclude certain functionality?

**Comment by mblinder** [comment]
Hi David,
We looked at polkadot-js, and it’s not really the same as what we’re trying to accomplish. Let me know if you want to jump on a cal with our CTO to discuss!
Marc

**Comment by semuelle** [comment]
> ORE ID only stores public keys on chain. 

So, is it not related to the ORE blockchain? What happens on the ORE blockchain?

**Comment by mblinder** [comment]
The ORE Blockchain serves as a decentralized repository for the master identity for a user. Marc Blinder, the person, may have key pairs on Ethereum, Polkadot and Kusama using ORE ID. The ORE account is the top level identity that they control, which in turn has the right in our back end to use a variety of keys in a variety of different apps and chains. Although we could have a centralized version of the service, we preferred to architect it around a decentralized set of servers so that it’s true to the spirit of openness and self-sovereignty in the blockchain industry.

**Comment by Noc2** [comment]
> Hi David, We looked at polkadot-js, and it’s not really the same as what we’re trying to accomplish. Let me know if you want to jump on a cal with our CTO to discuss! Marc

I’m generally happy to jump on a call, but it would be easier if you could share the information here or ideally as part of the application. This way the rest of the committee sees it as well.

**Comment by mblinder** [comment]
We are using the Polkadot.js library beneath our ChainJS abstraction layer - it’s a great library. However, it’s still a significant amount of work to build the abstraction layer for applications to use across multiple chains (and eventually parachains). There’s a lot of complexity between different chains that ChainJS hides, and we’re able to simplify all of that complexity for developers. 

Our own ORE ID product is an example of a business that needs to work across Polkadot and parachains. This requires a lot of testing and refinement to manage multiple different encryption curves and other specifics that vary between chains and parachains. Given that parachains have different elements and encryption curves. This complexity creates more work to simplify that down into core use cases that developers can use without understanding substrate and the underlying curves and key pairs. 

It takes two months of a FTE because our developers need to thoroughly understand the polkadot.js library, thoroughly understand how to map across parachains, thoroughly understand all of the encryption curves and then provide a simpler interface for people who don’t have that same basic information.

**Comment by alxs** [comment]
Sounds good. From my side I'd be willing to support this for $20k. If you're gonna be basing your work on Polkadot.js, just make sure to attribute/license properly.

**Comment by mblinder** [comment]
Thank you - we will!

**Comment by alxs** [comment]
Cool. Just update the price in your application and I'll be happy to accept.

Besides, could you tick the checkmarks in your first comment indicating you've acknowledged these points?

**Comment by mblinder** [comment]
Updated!

**Review by alxs — APPROVED** [review]

**Comment by Noc2** [comment]
Thanks for the update and sorry for the late reply. All parachains/curves are currently already supported by polkadot.js, but I understand that the process of simplifying the integration creates some additional work. You mentioned ORE ID: could integrate this or another open source example integration into the deliverables? Alternatively would it be possible to reduce the price to 15k?

**Comment by mblinder** [comment]
I updated th price to $15k - I really want to move forward on this project.

**Review by Noc2 — APPROVED** [review]

**Review by alxs — APPROVED** [review]

**Review by mmagician — APPROVED** [review]
It's a difficult call to make, given that your ORE ID hasn't attracted much traction (yet?) from what I saw. Still, I'd be happy to give it a try, good luck!

**Comment by alxs** [comment]
Hey @mblinder! Care to share a quick status update, along with an ETA if possible? We were hoping to receive your first delivery about 2 months ago now. As long as you're still working on the project, delays aren't a big problem, but if you're no longer interested we would terminate the grant.

**Comment by mblinder** [comment]
Apologies, the engineer who was working on this project got sick and had to leave the company. We’ve hired a new developer who will finish the work. We’re absolutely still going to support Polkadot and Kusama! 

—

Marc Blinder // Chief Executive Officer
△ AIKON △

**Comment by alxs** [comment]
Sounds good, thanks for the update! Please give us a quick heads-up if you can't finish by around end of July.

**Comment by mblinder** [comment]
Hi All,
We’ve hired the new engineer and we’re resuming work on the plug-in. Thanks for your patience!
Marc

—

Marc Blinder // Chief Executive Officer
△ AIKON △

**Comment by mblinder** [comment]
We’re expecting to finish in August, but I don’t think it will be done in the next 2 weeks. 

Current status is:
90% Map Polkadot architecture to ChainJS
50% Implement manifest approach
25% Implement MVP for ChainJS plugin

**Comment by alxs** [comment]
@mblinder that's alright, thanks for keeping us in the loop.

**Comment by mblinder** [comment]
Hey Team - we’ve decided to wrap the entire ChainJS project in automated tests to ensure that it’s highly reliable when developers use it or edit it. This is going to take us longer, but we’re really committed to making this as bullet proof as possible.

**Comment by alxs** [comment]
Sounds good! Thanks for the update.

Could you submit an amendment to update the duration? Make it 5 months (if you delivered today) + however long you think you still need, or just add an ETA.

**Comment by mblinder** [comment]
Great - will do. Thanks for the flexibility.

**Comment by mblinder** [comment]
Updated and did a new PR
—

Marc Blinder // Chief Executive Officer
△ AIKON △ 
+1 415 517 5326
+44 7432 142050

**Comment by mblinder** [comment]
Hi - we’ve been working on it, but there’s been a major rearchitecture to improve stability and usability. Can I update the timeline again?

**Comment by alxs** [comment]
Yes, please. Could you share your current work so far?

**Comment by mblinder** [comment]
Sure - here’s the repo, where you can see active work on the refactoring and testing:
https://github.com/Open-Rights-Exchange/chain-js <https://github.com/Open-Rights-Exchange/chain-js>

We’re doing that underlying work to make the framework more usable for developers and to make it easier for developers to offer changes via PRs. Once that’s done, we’ll upgrade the Polkadot and Kusama work and finish the grant. 

Here’s the original DOT / KSM work:
https://github.com/Open-Rights-Exchange/chain-js/pull/103 <https://github.com/Open-Rights-Exchange/chain-js/pull/103>

**Comment by alxs** [comment]
Thanks, sounds good. Please go ahead and amend the timeline. Besides, please keep in mind that following up and reviewing the amendments takes up resources on our side, so we would expect you to stick to your timeline this time around.

**Comment by mblinder** [comment]
Totally agree and apologize. We’ll bake in extra time with this update, so it doesn’t happened again.

**Comment by semuelle** [comment]
Hey @mblinder. Just checking in here. Are you still planning to submit your milestone this month?

**Comment by alxs** [comment]
@mblinder please note we'll assume you're no longer interested and terminate the grant if we don't hear from you in the next two weeks.

**Comment by mblinder** [comment]
Hi Everyone - I’m so sorry for the delayed response. We’ve been experiencing a lot of growth recently and it’s delayed the work for this grant. We’re still eager to do this work for the Web 3 ecosystem and we’d love to deliver it later this year, but it will be many months to get to it. Are you okay with us pushing out again?
—

Marc Blinder // Chief Executive Officer
△ AIKON △

**Comment by alxs** [comment]
@mblinder I think that should be fine, can you please submit another amendment?

**Comment by keeganquigley** [comment]
Hi @mblinder are you able to give us an update on M1? I believe with the updated timeline the delivery would have been due a month or two ago. Thanks!

**Comment by keeganquigley** [comment]
Pinging @mblinder for a friendly reminder.

**Comment by keeganquigley** [comment]
Hi @mblinder please note that if we don't hear back from you after 2 weeks time, the committee will likely terminate this grant due to inactivity. Let me know if you have any questions.

**Comment by mblinder** [comment]
Apologies! We’re not able to get to this this year. I totally understand if you need to cancel the grant. 

—

Marc Blinder 
CEO
△ AIKON △

**Comment by mblinder** [comment]
Thank you - we still love what you’re doing and want to support in the long run!

—

Marc Blinder 
CEO
△ AIKON △

**Pull request merged**
