### PR TITLE
Manta: A Privacy Preserving Decentralized Exchange

### PR DESCRIPTION
**Pull request by stechu**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@stechu Thanks for adapting your grant application, this new one is currently being reviewed.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the grants application. It looks really interesting. Could you specific the deliverables of the milestones a little bit more concrete? For example what are the substrate pallets you are going to implement and the functions of these? These are basically the “requirements” of the contract. Also could you reduce the price? The grant is currently above 30k.

**Comment by stechu** [comment]
@Noc2, we revised the proposal:
1.  more concrete deliverables in the milestone section 
2. update the BTC value
Please let us know if there are more questions or further details needed.

**Review by Noc2 — APPROVED** [review]
Looks good to me.

**Review by RouvenP — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Comment by stechu** [comment]
@mmagician @Noc2 @RouvenP Thanks for the support.

**Comment by alxs** [comment]
@stechu @zhenfeizhang just a reminder that if you change your plans and would rather move in a different direction than that dictated by milestone 2, an amendment is possible at all times.

In specific, maybe you share my impression regarding deliverable 1 that it's still a bit too early to base any work on a specific cross-chain communication standard. If that's really where you would like to focus at the moment that is absolutely fine and in that case you may want to check out [xtoken](https://github.com/w3f/Grant-Milestone-Delivery/pull/116) by Acala (which you're probably aware of  if you've been talking to them), but there's no guarantee that this will ever be widely adopted or make it to the official implementation. I see you're in the Token Standards Element room so I assume you're familiar with the current state of the discussion.

Otherwise, if you're committed to this goal and would like to get more deeply involved, there is an RFP (meaning: we would fund this as part of a grant) for contributions to XCM [here](https://github.com/w3f/General-Grants-Program/pull/414), which would be an option for a follow-up grant. You can just remove that deliverable from the application and adjust the price accordingly if you decide to focus on that or something else. Your options are open.

**Comment by alxs** [comment]
Hey @stechu @zhenfeizhang. Care to share a quick update on your progress on milestone 2, together with an ETA if possible? Even taking the acceptance date of M1 as the start date, it is now delayed by 7 weeks.

**Comment by stechu** [comment]
@alxs  sorry for the late reply. We are busy with our testnet launch. 
Since the XCM is getting more mature, we plan to deliver the milestone 2 in the middle of August.  Now since the parachain to relay chain transfer is not there yet. We would like to limit the scope of milestone-2 to only minting parachain tokens, e.g. DOT.
More specifically, the revised milestone's delivery will be:
1. A parachain runtime that supports minting DOT in the relay chain to private DOT in the relaychain
2. Related testing and documentations 

Would love to hear your idea about that.

**Comment by mmagician** [comment]
@stechu Feel free to submit an amendment PR to adjust the milestones and reflect the new cost. I believe it should be fine to change the scope now.

**Comment by alxs** [comment]
@stechu a reminder here to update the application via PR, also to include an estimate as for the delivery date.

**Comment by stechu** [comment]
@alxs will do soon!

**Comment by stechu** [comment]
@alxs @stechu  just submit a new PR about the amendment.

**Comment by alxs** [comment]
Hey @stechu, any updates here? The updated ETA would have been at the beginning of the week. Given the already considerable current delay, I think we would prefer to cancel the rest of the grant if you can't deliver within the next ~3 weeks.

**Pull request merged**
