### PR TITLE
SubDAO Network Application

### PR DESCRIPTION
**Pull request by WannaM**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. It looks really interesting. A few questions from my side:

- Regarding the contract, are you planning to develop these with ink! or solidity? Given that we don’t have so many projects currently developing ink! smart contracts, it would be nice if you could leverage ink! and also add this to the milestone deliverables. 
- Could you specify a “a set of contracts to maintain“, what kind of contract and what will be the features of it? 
- Will the web ui be the standard polkadot.js interface or do you try to create your own UI on top of it? Do you already have some mockups or something similar for it?
- Could you make a medium post part of the deliverables?

**Comment by WannaM** [comment]
Thank you for your comments!

> Thanks for the application. It looks really interesting. A few questions from my side:
> 
> * Regarding the contract, are you planning to develop these with ink! or solidity? Given that we don’t have so many projects currently developing ink! smart contracts, it would be nice if you could leverage ink! and also add this to the milestone deliverables.

We are planning to develop most of these contracts with ink! but the user defined templates in future releases will be in solidity as we thought. Regarding the status of ink! 3.0, we may face some problems but still with ink!. 

> * Could you specify a “a set of contracts to maintain“, what kind of contract and what will be the features of it?

We have modify the expression in application. The contract will provide features such as adding new DAO template contract, creating DAO contracts from DAO Template, and store those templates.

> * Will the web ui be the standard polkadot.js interface or do you try to create your own UI on top of it? Do you already have some mockups or something similar for it?

The WebUI will use polkadot.js. We do not have mockups yet.

> * Could you make a medium post part of the deliverables?

Added in deliverables.

**Review by Noc2 — APPROVED** [review]
Thanks for the update. The application looks good to me.

**Review by RouvenP — APPROVED** [review]

**Comment by WannaM** [comment]
> Thanks for the update. The application looks good to me.

Thank you so much!

Let's waiting for review.

**Review by mmagician — APPROVED** [review]
Nice application, looking forward to creating a DAO with your solution 👍

**Comment by mmagician** [comment]
Another potential grantee also wants to implement a DAO solution: #96
They propose a collection of runtime modules instead of smart contracts, so it would be interesting to see both implementations in action.
Feel free to discuss ideas between each other.

**Comment by WannaM** [comment]
> Another potential grantee also wants to implement a DAO solution: #96
> They propose a collection of runtime modules instead of smart contracts, so it would be interesting to see both implementations in action.
> Feel free to discuss ideas between each other.

Thank you!!

Pleasure to see different solutions based on Substrate for DAO.

**Pull request merged**
