### PR TITLE
Application: Olympus Protocol

### PR DESCRIPTION
**Pull request by olympusprotocol**
# Grant Application Checklist

- [X] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] A BTC address for the payment of the milestones is provided inside the application.  
- [X] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [X] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Review by mmagician — CHANGES_REQUESTED** [review]
@olympusprotocol Thank you for your application, it looks very interesting and well written. I would definitely like to see it form part of the Polkadot ecosystem. Before proceeding further, however, I would like to ask you for two things:

1. Could you share your whitepaper with us please? (it is password protected on your website)
2. Since your grant focuses mostly on substrate modules, would it be possible to provide more technical details for these pallets (e.g. orml, aUSD etc.)? You can check a list of requirements [here](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md#runtime-moduleschains).

**Comment by olympusprotocol** [comment]
Clarified the orml implementation (tokens and currencies for multi-currency setup with native token and auxiliary assets). I removed the mention of aUSD since it isn't relevant at this point and shouldn't have been there in the first place; since we are building a test net the assets do not need to be real so we don't need to bring real aUSD onto the runtime yet. I'm honestly not sure how assets will become interoperable on a technical level but I can't imagine it is too difficult and has already been done multiple times by at least Acala and Polkadex.

**Comment by mmagician** [comment]
@olympusprotocol Thanks for a prompt reply.
I still require a password to access your whitepaper via your website.

Also, I still don't see any more details regarding the substrate modules. Have you had a look at requirement list on https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md#runtime-moduleschains?
While we are not asking for a full technical specification, your current application is too vague (e.g. `We will use the orml pallet for the multi-token trait`) and providing the pallet interface as specified in that document would speed up the application process - it also facilitates the evaluation of your deliveries upon completion.
(note that this applies to other modules as well, not just the orml pallet).

Lastly, a cosmetic detail - please keep only one file in your application.

I'd be happy to assist your team in drafting out the specifications or to point you in the right direction. Feel free to reach out to me on matrix: `@marcin:web3.foundation`

**Comment by mmagician** [comment]
I'm closing this PR due to inactivity. Feel free to re-open it with an updated proposal when ready.

**Pull request closed without merging**
