### PR TITLE
add prediction market protocol

### PR DESCRIPTION
**Pull request by ranneen**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@ranneen Thank you for applying, we haven't had that many projects tackling the prediction markets (yet). 
Could you outline the reasons for choosing runtime modules over a set of smart contracts for your project? Perhaps you'll find [the following thread](https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract) useful.

**Comment by ranneen** [comment]
@mmagician Thanks for your advice. I'm considering use a series of smart contract to implement the prediction market protocol. Both Runtime Modules and Smart Contracts can be used to delivery functions of the protocol. Smart contract is simple and easy to develop. The protocol itself is a general market template and does not depend on any customized blockchain feature.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. As @mmagician already pointed out, we so far don’t have a lot of prediction market based solutions in our ecosystem and are rather interested in this. I have a few questions: 

- Could you specific the smart contract language as part of the deliverables? 
- Could you provide more details regarding how the Forecastee’s oracle will work? Are you planning to use some of the existing [oracle modules](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#link-chains-and-modules) in our ecosystem? 
- Could you potentially also integrate a medium article or tutorial as part of the last milestone? 
- What are your plans regarding an interface? It would be nice to have at least a simple solution as part of the grant.

**Comment by ranneen** [comment]
> * Could you specific the smart contract language as part of the deliverables?
> * Could you provide more details regarding how the Forecastee’s oracle will work? Are you planning to use some of the existing [oracle modules](https://github.com/w3f/General-Grants-Program/blob/master/grants/polkadot_stack.md#link-chains-and-modules) in our ecosystem?
> * Could you potentially also integrate a medium article or tutorial as part of the last milestone?
> * What are your plans regarding an interface? It would be nice to have at least a simple solution as part of the grant.

* All the contract will be written in `ink!`
* In milestone 2, we only use a series of authorized accounts to report the outcome of real-world events.  A trustless way to resolve event is need for future plans.
* A tutorial is added to describe how to interact with the contract.
* Other parachain or contract project can integrate prediction market protocol to retrieve probability of the real event through contract api.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. I have a few follow-up questions: 

- All deliverables of the second milestone will also be implemented as ink! smart contracts, correct? 
- Could you integrate a system to manage these “authorized accounts” in a decentralized way. For example a DAO. 
- My question regarding an interface, was actually if you are planning to also develop some kind of UI or if you plan to use for example the extrinsics tab of polkadot.js?

**Comment by ranneen** [comment]
> * All deliverables of the second milestone will also be implemented as ink! smart contracts, correct?
> * Could you integrate a system to manage these “authorized accounts” in a decentralized way. For example a DAO.
> * My question regarding an interface, was actually if you are planning to also develop some kind of UI or if you plan to use for example the [extrinsics tab](https://polkadot.js.org/apps/#/extrinsics) of polkadot.js?

More details about the milestone:

1.  All the contracts in milestone1 and milestone2 will be written in ink!
2. The protocol needs a trustless way to report real world event which will bring complex economic mechanism. It's in our future plan to developing an profit-motivation incentive mechanism to allow anynone to report event result to the protocol. 
3. In milestone 2, the user can only use polkajs developer tab to sign transaction and query state from the deployed contract. A web interface will be implemented in our future plan.

**Review by Noc2 — COMMENTED** [review]
Thanks for the update. I will share your application with the rest of the team. However, I would like to have either more details regarding the report of real world data or a UI as part of the grant, before I would be willing to accept it.

**Comment by laboon** [comment]
I would be very interested in supporting a prediction market, but I would need much more detail before agreeing on this project.

I looked here ( https://github.com/forecastee/forecastee/tree/master ) and see what appears to be a single-commit default Substrate implementation.  So is this going to be a a parachain or a set of smart contracts?

I am also not sure what the following means, and why you wouldn't take advantage of other oracles?  What is the point of the template?

> Forecastee protocol is not identical to other Oracles as it provides oracle factory template to make prediction of all kinds market and has it's own incentive.

**Comment by Noc2** [comment]
I’m closing the application for now due to inactivity and it seems that in the current state the committee isn’t interested in it. Feel free to let me know if I should reopen it or to send us another updated grant application.

**Pull request closed without merging**
