### PR TITLE
Setheum Network Grant Request

### PR DESCRIPTION
**Pull request by JBA-Khalifa**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by JBA-Khalifa** [comment]
Thank you Web3

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. I have a few questions/comments:

- 2.9 BTC is currently above the 30k limit of the open grants program. Could you decrease the price of the grant application
- Could you update the application according to the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules). Specifically the deliveries are currently hard to read. 
- What is the SettPay Wallet UI? Is it simply based on polkadot.js or will it be separate UI? Do you potentially already have mock-ups? Which framework, programming languages are you planning to use for it? 
- How is your project different from [acala](https://github.com/AcalaNetwork/Acala)? 
- Where can I read more about the STP258 and SERP-TES Module?

**Comment by JBA-Khalifa** [comment]
Alright, thank you. 

- I'll reduce the 2.9 BTC to 2.75 BTC;

- Sorry for the deliverables, will fix them just now;

- As for the SettPay Wallet UI, it is not simply based on polkadot.js, it will be separate UI? We currently don't have mock-ups. We are planning to use ReactJS or VueJS frameworks written in JavaScript.

- Acala provides a single multi-collateral USD-pegged stablecoin.
 We offer an elastic stablecoin protocol (SERP-TES) that mints and contracts the supply of SETT based on the Demand Curve of the Collateral Asset and the money itself.
As if it increases in value over it's peg then more is minted as inflation, and the protocol will buy back during contraction.

The stablecoins are backed by the DNAR, just like the gold standard. The DNAR is the Gold.
 A partial derivative stablecoin (SETT) - pegged to 34 fiat-pegged stablecoins (a basket of currencies just like the IMF's SDR).

Setheum also offers a Central Bank type of monetary regime to issue it's elastic stablecoins, but unlike the Central banks, SERP-TES is decentralized and it distributes the new supply of stablecoins as discounts and cashback when users pay with SettPay. SettCard will soon be offered.

The jSETT will be multi-collateral and pegged to the SETT, so you can mint jSETT by locking DOT or KSM et al,  it is still linked to the DNAR, because as jSETT is transacted, DNAR gets transaction fees thus increasing the Value of the DNAR and thus minting more SETT for discounts and cashback. So the jSETT is also far from same with Acala's aUSD.

- The documentation here could help about SERP-TES and the STP258

1. https://github.com/Setheum-Labs/Setheum-Labs-White-Papers/blob/main/Setheum%20White%20Paper%203.0-%20Muhammad%20jibril(1).pdf

2. https://github.com/Setheum-Labs/Setheum-Labs-White-Papers/blob/main/Setheum%20Tokenomics%20White%20Paper(3).pdf

Thank you

**Comment by JBA-Khalifa** [comment]
And we have 2 new team members, Junaid and Hamza. I wish to add them in the changes.

**Comment by JBA-Khalifa** [comment]
Hello,have closed the other PR since this one has the new commit

**Comment by Noc2** [comment]
Thanks for the quick response. I have a few additional questions: 
- Usually we don’t fund or support testnets and mostly focus on open source code that could potentially be used by others in our ecosystem. Could you remove 3,4 and 5 of the milestone 1 and reduce the price accordingly? 
- Also it sounds like Setheum Network Relay is a polkadot competitor and Vegas Canary Network is a kusama competitor? Is this correct? 
- Just a general comment from my side: I think it might make sense to initially focus on the “stablecoin” aspect. I found the term blockchain 5.0 rather confusing.

**Comment by JBA-Khalifa** [comment]
* Sure, we can remove the Vegas network, the testnet. But we really don't intend to compete with polkadot, if you checked our medium post we even acknowledged the Polkadot team and Web3, even mentioned Alistair Stewart. I just thought that we could be another second-standard relaychain on Polkadot and be niche to ecommerce and enterprise dapps especially as in the relaychain would be relatively harder to get a slot in the future. But maybe I was wrong, thanks.

* But we cannot compete with Polkadot, especially when they built Substrate and we are just standing on their shoulders. Polkadot's intrinsic value is in the technology it provides that is almost impossible to replicate. We'd be better off being a part of it. We will build the network without the Relay and Vegas then. 

* I will write an Improvement proposal on that. And the blockchain 5.0 is just a term marketing the push of Setheum to the ecommerce and soon offline commerce transactions as a payment gateway, something dominated by the traditional fintech and cash systems in fiat. 

* We are planning to compete with the likes of Stripe and Paypal, but not Polkadot. We will be a parachain, and will initially focus on the Stablecoin. I'll update the Proposal.
Thank you for the response David. I'm glad you asked.

**Comment by JBA-Khalifa** [comment]
Hey @Noc2 I commit the changes, including the cost brought down to 2.2 BTC.
We'd love to start moving with it as soon as possible to be able to join the community before the upcoming Conference here in China since I'm already here at the moment. I'm counting on the Web3 Conference here in Shanghai on the 29th-30th of this month. Looking forward to meeting the Web3 Community, Sir.
Big thanks and best regards

**Comment by mmagician** [comment]
@JBA-Khalifa Thank you for actively updating the application!

There are also a couple of questions from my side. Your grant proposes a couple of different Substrate modules, for each of these could you please provide the following information (up to the best of current knowledge, I'm aware that such specification is subject to change during the development phase):

- List the publicly exposed methods
- For each method, specify (to the best of present knowledge):
    - Method signature (incl. parameters with their types, return type)
    - Short description (code template)
- Runtime Storage defined by your module
- [Use case diagram](https://www.wikiwand.com/en/Use_case_diagram) with e.g. UML or SysML (or similar tool demonstrating how external users/system components interact with one another)

In addition, it is difficult to decide on funding UI development without any mockups. I hope you understand that we need to at least have an idea of what will be delivered - plus it helps with aligning expectations for the evaluation phase that comes later. While I am not asking for production-grade designs, I believe that sketching out the principal functionality of your wallet would offer us great insight and on top of that, help you further down the line.

Feel free to either attach the above information directly to the grant, or simply insert relevant links pointing to module specs & mockups.

Many thanks!

**Comment by JBA-Khalifa** [comment]
Sure, I will try to provide the requested information, thanks

**Comment by JBA-Khalifa** [comment]
@mmagician @Noc2 Please review again, I hope all is done.. Thanks

**Review by Noc2 — DISMISSED** [review]
Thanks. I would be willing to go ahead with it.

**Comment by JBA-Khalifa** [comment]
Bountiful thanks @Noc2

**Comment by JBA-Khalifa** [comment]
Screenshot 2020-10-30 at 17 17 34 @mmagician I hope this helps.

**Comment by JBA-Khalifa** [comment]
Hello @Noc2, @mmagician, @splix, good happy Tuesday. I hope all is well there.

**Comment by mmagician** [comment]
@JBA-Khalifa Seeing that we are having difficulty getting 3 approvals for your proposal, may I suggest that you split the work and only apply for the first part now? Then, upon successful delivery & evaluation on our side, you could apply for the second milestone.
How does that sound?

If you're OK with this, then you could remove the second milestone from this Pull Request & hopefully we will approve it quicker. I hope this helps 👍

**Comment by JBA-Khalifa** [comment]
Hello

**Comment by JBA-Khalifa** [comment]
Sure

**Comment by mmagician** [comment]
@JBA-Khalifa please also update the total milestone cost

**Comment by JBA-Khalifa** [comment]
Okay thanks

**Review by Noc2 — CHANGES_REQUESTED** [review]
Why did the price for milestone 1 increase? Given the current BTC price, I would rather ask you to reduce the price. Bitcoin went up more than 50% since you sent us the application.

**Comment by JBA-Khalifa** [comment]
Sure David, sorry for that. We are planning to fund just the initial development, just like you advised we will not expect to cover all expenses with the grant. The trophy is more important, sorry for the change. Thank you very much

**Review by mmagician — DISMISSED** [review]

**Comment by mmagician** [comment]
Hey @JBA-Khalifa
As @Noc2 mentioned, since the BTC price has increased significantly since the submission of your application, I would like to ask you to decrease the milestone cost accordingly. You can look at the historical prices and recalculate the new price accordingly.

**Comment by JBA-Khalifa** [comment]
Sure @mmagician

**Review by Noc2 — APPROVED** [review]

**Review by Noc2 — CHANGES_REQUESTED** [review]
You also need to update the total costs.

**Comment by Noc2** [comment]
Thanks for the update. Some people reached out to me and have concerns regarding your application. Mainly because you forked all of our w3f's public repos multiple times: https://github.com/w3f/hs-p4p/network/members and it seems the twitter handle of https://github.com/slixon-technologies posted shopping related things: https://twitter.com/slixon_en. Could you maybe comment on this? In general I also want to point out that grant teams are only allowed to announce a grant once they actually successfully delivered the first milestone. I hope this isn’t an issue.

**Comment by JBA-Khalifa** [comment]
Thanks for the question @Noc2, regarding the forks, its just that I wasn't familiar with the feature where I could just clone a repository and open a pull request when edited, because I wanted to contribute.  I just recently educated myself on more about GitHub and Open Scource Contribution.  If you noticed, this is my first pull request on GitHub.  It's a little embarrassing though, but I'll take care of it.  Plus I was a bit too excited about the future.

Regarding Slixon, it was my dropshipping site that inspired me to build a payment gateway because Paypal and other cheaper and popular options are simply not available in both China (where I live) and Nigeria (where I'm from). 

The initial plan was to just build something simple just for payment on Slixon in a way that we don't have to be a fintech company and pay huge sums for licensing et al. Setheum was meant to be the first use case of Setheum, then I realised it could even be bigger than Slixon itself.  So since we are at loss not selling a thing, we closed shop and focused on Setheum.

And regarding the public announcement of the grant, it's not an issue at all.
I hope you all understand and I hope it is clearer, thank you.

**Review by Noc2 — APPROVED** [review]
Thanks for the explanation. Makes sense. I’m happy to go ahead with the project.

**Review by mmagician — APPROVED** [review]

**Comment by JBA-Khalifa** [comment]
Thanks @Noc2. I'm happy to hear that.

**Comment by JBA-Khalifa** [comment]
Thanks @mmagician

**Review by RouvenP — APPROVED** [review]

**Comment by JBA-Khalifa** [comment]
Thank you so much @Noc2 @mmagician @RouvenP I am so grateful for this lifetime opportunity, we sure will make you proud

**Comment by mmagician** [comment]
Just for reference, I am moving your document from root to the `applications` folder, see this [PR](https://github.com/w3f/Open-Grants-Program/pull/127)

**Pull request merged**
