### PR TITLE
Application: Project Aurras MVP - Phase 1

### PR DESCRIPTION
**Pull request by MuhammedIrfan**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. This looks good to me. I will share it with the rest of the team.

**Review by BenWhiteJam — COMMENTED** [review]
@MuhammedIrfan thanks for the application:
- could you please add more details to 1d. & 1e. in the sense of what components  you will add a Dockerfile for as well as which ones will be part of the Docker Compose config
- you mention to provide YAML files for the deployment of the stack, as you also mention Docker Compose, I would assume the general deployment configuration will target Docker Compose as deployment infrastructure. As there is nothing against using Docker Compose, I'm still wondering if it wouldn't be more beneficial to target Kubernetes as deployment infrastructure? The reason would be that I've heard more node infrastructure provider running the nodes on Kube rather then Docker Compose, but happy to discuss further.

**Comment by MuhammedIrfan** [comment]
@BenWhiteJam Thank you for the suggestions.
> * could you please add more details to 1d. & 1e. in the sense of what components  you will add a Dockerfile for as well as which ones will be part of the Docker Compose config

Sure I will add more details
> * you mention to provide YAML files for the deployment of the stack, as you also mention Docker Compose, I would assume the general deployment configuration will target Docker Compose as deployment infrastructure. As there is nothing against using Docker Compose, I'm still wondering if it wouldn't be more beneficial to target Kubernetes as deployment infrastructure? The reason would be that I've heard more node infrastructure provider running the nodes on Kube rather then Docker Compose, but happy to discuss further.

The YAML file mentioned for the workflow composer component is used to compose multiple tasks/actions and the deployment is done through openwhisk which is different from the general deployment configuration. For deployment configuration we chose Docker Compose for ease of development and deployment since we are doing MVP, But as you pointed out Kubernetes should be used for production deployment infrastructure. We will make the necessary changes in the application to accommodate Kubernetes.

**Comment by MuhammedIrfan** [comment]
> Thanks for the application. This looks good to me. I will share it with the rest of the team.

@Noc2 Thank you.

**Review by BenWhiteJam — DISMISSED** [review]
@MuhammedIrfan thank you for the update, looking forward to it!

**Review by Noc2 — DISMISSED** [review]

**Review by mmagician — CHANGES_REQUESTED** [review]
@MuhammedIrfan The application looks good to me. I would only like to point out that we require teams to include a short write-up as part of the grant, see the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md). You might have forked the repo before this was added, so I'd appreciate you including the appropriate sub-clause in your milestone deliveries. I think in your case it makes sense to add it only for M3, rather than for each milestone. Thanks!

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan The application looks good to me. I would only like to point out that we require teams to include a short write-up as part of the grant, see the [application template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md). You might have forked the repo before this was added, so I'd appreciate you including the appropriate sub-clause in your milestone deliveries. I think in your case it makes sense to add it only for M3, rather than for each milestone. Thanks!

@mmagician Thank you for the suggestion. We will update the application to include a Medium article of our grant journey.

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]

**Comment by mmagician** [comment]
@MuhammedIrfan It's been a while since your last submission. Do you perhaps have any updates on the second milestone? Otherwise the grant will be terminated.

**Comment by MuhammedIrfan** [comment]
> @MuhammedIrfan It's been a while since your last submission. Do you perhaps have any updates on the second milestone? Otherwise the grant will be terminated.

@mmagician we are working on milestone 2 and milestone 3 together as both are of the same component. As there were some unforeseen covid situations we might need a little extra time to submit.

**Comment by mmagician** [comment]
Could you provide links to the repos where you've been actively developing? I've noticed that your `aurras-` related repos have been inactive since your last submission.

**Comment by MuhammedIrfan** [comment]
> Could you provide links to the repos where you've been actively developing? I've noticed that your `aurras-` related repos have been inactive since your last submission.

We are working within our internal repo. Please give us some time to push commits to our upstream aurras- repos

**Comment by MuhammedIrfan** [comment]
@mmagician thank you for considering the extension of deadline. We will submit the target date for M2&M3 combined tomorrow

**Comment by MuhammedIrfan** [comment]
@mmagician Please check the implementation (partial) for milestone 2 and 3. Kindly receive my sincere apology for submitting the project late than the target date.
This is due to unexpected diversion in solution implementation. Still there are few more component need to add to the solution, we working on these components and will delivery as soon as possible and update you regarding the same. Thank you.

**Comment by MuhammedIrfan** [comment]
@mmagician We sincerely apologize for the delay in delivery. We have completed the implementation. Kindly review it. Thank you.

**Pull request merged**
