### PR TITLE
Bit.Country Milestone 2

### PR DESCRIPTION
**Pull request by codemeit**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thank you for your application. We've recently updated the application template to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this?

**Comment by codemeit** [comment]
> Thank you for your application. We've recently updated the application template to reflect the fact that grants now need to be denominated in USD (payment may still be in BTC or DAI). Could you update this?

Thanks David @Noc2  for your time reviewing our application M2. I have updated it accordingly. 

Best Regards,
Ray Lu

**Comment by justinphamnz** [comment]
> Sorry for the very late reply here and thanks for the new application. I quickly looked at your code and it seems that you are using a lot of [pallets](https://github.com/bit-country/Bit-Country-Blockchain/tree/master/pallets) that were originally developed by other teams without any attribution. Could you potentially fix and clarify this? Also which rust version should I use to compile your project (`rustup show)`? Furthermore the code currently seems to have quite a few unused variables/functions, etc.

Hello David @Noc2,

Hope you are well.
Thank you for getting back to us.

Thanks David for the comments, we use ORML as a standard NFT metadata struct and initially included our project under ORML readme. However, we will add the attributions through our readme and comments where appropriate.

In terms of the rustc toolchain, we are using 1.52.0 nightly 2021-02-13.

There are some pallets that we merged from the Rococo parachain branch during integration to our master that haven’t been cleaned up yet, we will remove them and the unused variables.

If you have any further questions, please let us know.

Have a great day, David.

Justin

**Comment by Noc2** [comment]
Thanks for the clarification as well as the additional email.

**Comment by semuelle** [comment]
Hi @codemeit, thanks for the application. 

Since this is a follow-up grant, I would expect the description of the grant to be more in the context of the previous one. This application is a copy of the previous one with just the milestone replaced. Could you remove the general bits about Bit.Country and explain 

- where you stand project-wise today relative to before the first grant (e.g., if your roadmap has changed at all), 
- what was accomplished beyond the contents of the first grant (e.g., did you collect any feedback on what was done in the first grant?),
- what you might have learned since your original application?

Also, could you add a few more technical details? For example, one of your deliverables is `Dapp - Local NFT Market | Develop the decetralized marketplace for local bit country`. This is very vague and very hard to measure from our perspective. Ideally, you would provide a list of features or functions that each component of your milestone implements, which then only needs to be verified by the evaluator after delivery.

Lastly, since David already mentioned it above: please make sure that code you reuse is correctly attributed, especially when you submit it as part of a grant milestone. We had to terminate multiple grant agreements in the last week because we found license infringements.

**Review by semuelle — CHANGES_REQUESTED** [review]
see comment above

**Comment by codemeit** [comment]
> see comment above

Thanks @semuelle for your valuable inputs @justinphamnz and @shannon-christie will get back to you at earliest time possible.

Best Regards,
Ray Lu
P/S, after the M1, we tested the traction, and now gained some interesting KOL leads wanting to use Bit Country for their fans.

**Comment by shannon-christie** [comment]
Hi @semuelle ,

We've just updated the grant application to include more relevant information for the deliverables, an update on our development since the first milestone, and removed irrelevant information.

Please let us know if there are any changes required or further questions.

Have a good one Samuelle.

Kind Regards,
Shannon

**Comment by justinphamnz** [comment]
Hi @semuelle,

Thanks for your comment. We've gone through our code base to ensure it covers all attributions needed. 
We will make sure to follow the attribution practice for any reusable code in the future. If there are any changes required, please let us know. 

Best regards,
Justin.

**Comment by semuelle** [comment]
Hi all, thanks for the update. I will now forward this to the rest of the committee. Just two more things:

- For some deliverables, it's clear what language and tech stack you will be using (e.g., Substrate module). For others, not so much ('search', 'UI', etc.). Could you add some more technical details to those? A section on the general tech stack would be fine, too.
- By 'NFT-native', it sounds like the native currency is non-fungible. Can you clarify what you mean?

**Comment by codemeit** [comment]
Thanks for your speedy feedback @semuelle 

> Hi all, thanks for the update. I will now forward this to the rest of the committee. Just two more things:
> 
> * For some deliverables, it's clear what language and tech stack you will be using (e.g., Substrate module). For others, not so much ('search', 'UI', etc.). Could you add some more technical details to those? A section on the general tech stack would be fine, too.

Yes, we added a general tech stack section. For ease of reading, I copied here
Tech Stack

- Frontend/UI: ReactJs, BabylonJs, HTML, JS, CSS 
- API: C#/.NET Core, NodeJs 
- Blockchain: Substrate/Rust Database: MongoDB

> * By 'NFT-native', it sounds like the native currency is non-fungible. Can you clarify what you mean?

By "NFT native", we wanted to say the network is built for NFT. However, I have changed the wording to be "Our network is designed to support NFT and its promotion. "

Thanks again for your valuable time and comments.

Best Regards,
Ray Lu

**Review by alxs — DISMISSED** [review]

**Comment by gautamdhameja** [comment]
Overall, LGTM! Just one question - in the overview the duration is mentioned as 1 month but under M2 the duration is 6 weeks. Can you fix or clarify that?

**Review by gautamdhameja — DISMISSED** [review]

**Comment by codemeit** [comment]
> Overall, LGTM! Just one question - in the overview the duration is mentioned as 1 month but under M2 the duration is 6 weeks. Can you fix or clarify that?

Thanks, @gautamdhameja for spotting that, we have just updated it to be 6 weeks. 
(Btw, in case you are interested, we made a recent video for the project - [Episode: Continuum - Bit.Country Impression](https://vimeo.com/525945883/6d9bd9dc88) )

**Review by alxs — DISMISSED** [review]

**Review by alxs — APPROVED** [review]

**Review by gautamdhameja — APPROVED** [review]

**Review by Noc2 — APPROVED** [review]

**Comment by codemeit** [comment]
Thanks We3 team for your time, insight and valuable feedback. 

Best Regards,
BC Devs

**Comment by semuelle** [comment]
Hi @codemeit, can I ask for an update on the project? I see a lot of activity on your github repos, but the roadmap suggested a delivery closer to May than September. Thanks in advance.

**Comment by codemeit** [comment]
Hi @semuelle , 

Good day, thanks for the following up. We've done most of the features, we were thinking to claim it when we make our solution publicly accessible e.g. alpha 0.1 testnet. However, we developed further and wanting to make a good first impression, that is why we haven't submit it for review.

In case you are interested, here is a demo video I have recoded on the screen, I wish you like it.
https://vimeo.com/596319609/69984afd5b

We are also working with the brand team at web3 to build Kusama elements in the genesis metaverse :-)

Thanks again for the following up. I will keep you informed with the progress.

Best Regards,
Ray Lu
Bit Country, Metaverse Network

**Comment by semuelle** [comment]
Thanks for the update, @codemeit. Good to hear! Do you have any idea when the testnet release will be? If it's far beyond the timeline of the grant contract, we'd prefer and amendment to the contract. If it's just about a few weeks, no worries.

**Comment by codemeit** [comment]
Hi @semuelle, it will be just weeks. Eg 4 weeks. If the plan changes, I will make sure to inform you in the first instance.  We are looking at the 3rd batch of parachain, so getting things out is our first priority. Again, thanks for your time looking into this. Have a good weekend. Regards Ray

**Comment by alxs** [comment]
@codemeit checking in again - I understand you must all be very busy right now, but if you can't deliver within the next ~2 weeks, we'd ask you to please submit an amendment.

**Comment by codemeit** [comment]
Hi @alxs Thanks for the following, due to Kusama crowdloan. Yes we had a discussion with the web3 team, we will need to make amendment to leave the blockchain part for this application. Would you please let me know the process of making amendment? that would be super helpful. Best Regards, Ray

**Comment by alxs** [comment]
@codemeit oh right, I remember the thread. You can submit an amendment by simply modifying the original application document and opening a PR. Here's the short [section on amendments](https://github.com/w3f/Grants-Program#changes-to-a-grant-after-approval) in our readme. Ideally, you'd include a summary of the changes and link to this PR in the initial comment.

**Comment by codemeit** [comment]
Thanks @alxs we know what we need to do now. We will make the adjustment as soon as possible. Surely will be within the 2 weeks time frame. Thanks again for the follow up.

**Pull request merged**
