### PR TITLE
Mobile Game Framework for Substrate

### PR DESCRIPTION
**Pull request by enfipy**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Small-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below 30k at the time of submission.

### CODE REVIEW

**Review by Noc2 — APPROVED** [review]
Thanks for the application. It looks good to me. I will share it with the rest of the committee. So that they can take a look at it as well and potentially provide additional input.

**Comment by mmagician** [comment]
I like the idea! To understand it a little better, could you please explain how you envision the development of a new mobile game for someone that wants to use your framework? 

Will they be expected to write Swift/Java code (for UI components?) as well as the game logic in Rust? Or perhaps use React Native?

How exactly will the native code interact with Rust? Will the framework generate some kind of wrappers or would it be up to the developer?
I would be happy to have a call regarding your proposal to find out more. I'll reach out to you via email.

Thanks for clarification 👍

**Comment by enfipy** [comment]
@mmagician Sure we can!

Our goal is to make it possible to write mobile games just with Rust-lang and without any knowledge about Swift or Kotlin. This already can be done with the help of several extremely useful libraries like [winit](https://github.com/rust-windowing/winit), [android-ndk](https://github.com/rust-windowing/android-ndk-rs), [cargo-lipo](https://github.com/TimNN/cargo-lipo), [bitcode](https://github.com/getditto/rust-bitcode), etc. There are few articles about how to build rust applications for Android and iOS but it's pretty hard to set up it now (how to build a library to [iOS](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html) and [Android](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-21-rust-on-android.html) from Mozilla). Also, with the latest version of winit, it's possible now to add touch events, rendering, and a lot more to the app through rust. But we want to make this process as simple as build applications to Unix or Windows platforms.

Also, we will try to make it possible to select how you want to generate APK/IPA - fully through our framework or generate platform-specific projects (from templates in our repository with just one call of the utility) and build Android in Android Studio as iOS in XCode.

**Review by mmagician — APPROVED** [review]

**Review by RouvenP — APPROVED** [review]

**Comment by Noc2** [comment]
Congratulations. As part of the Open Grants Program, we want to help winning teams acknowledge their grants publicly while observing the foundation’s guidelines. To that end, we’ve created a badge for grant-winning teams. Here is a link to the [download and guidelines](https://github.com/w3f/General-Grants-Program/blob/master/grants/grant-badge-guidelines.md).<br/> 
If you are interested in making an announcement about your grant and you would like us to broadcast it on our  media channels then please get in touch with us at grantspr@web3.foundation prior to making the announcement (at least two weeks notice is preferred) so that we can coordinate on timing and content.

**Comment by mmagician** [comment]
@enfipy  It's been a while since your last submission. Do you perhaps have any updates on the last milestone? Otherwise the grant will be terminated.

**Comment by enfipy** [comment]
@mmagician We are really sorry for this huge delay! We have finished everything except the final strokes (`Support of CD with Fastlane`) that we will make this week.

We did some big additional libraries to the initial grant project and think that the rust and substrate community will find it very useful:
https://github.com/dodorare/apple-bundle-rs
https://github.com/dodorare/android-manifest-rs

And again sorry for the delay, I think we can schedule a call for the next week.

**Pull request merged**
