### PR TITLE
prex.md

### PR DESCRIPTION
**Pull request by prexfinance**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC or Ethereum (DAI) address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below USD $30k for initial grant applications and $100k for follow-up grants.
- [x] The initial PR contains only one commit (squash if needed before submitting your PR).
- [x] The grant will only be announced once we've successfully [delivered](https://github.com/w3f/Grant-Milestone-Delivery) the first milestone.

### CODE REVIEW

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. However, we recently changed the denomination of the milestones and the total costs to USD. Could you please update this? Furthermore your current milestone 1 doesn’t contain any concrete technical deliverables, which we could evaluate. In general could you provide more technical information? Your website also doesn’t load for me and we usually don’t fund your third milestone, since we don’t support the deployment of a network or the launch. We mostly focus on the development of open source software and research.

**Comment by prexfinance** [comment]
Hi! Thanks for your comments.

I've made the necessary changes and included more technical information.
Apologies for prior exclusion as we were still trying to finalize.

Website FE isn't currently available as we intend to work on the backend
first, hopefully that is ok.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update.  But we would still need more information. For example, what are the functions of your substrate modules? How are you going to implement the (price) oracles? Do you have a mockup for the UI? Did you consider using smart contracts instead of pallets? See https://stackoverflow.com/questions/56040779/when-should-i-build-a-substrate-runtime-module-versus-a-substrate-smart-contract

**Comment by prexfinance** [comment]
Thank you for the response! Still ironing out details for several parts
with dev but here we go.

Substrate modules > We're still refining the mechanics especially for
PREXPools but here are the tentative functions of the modules
- PREXMarkets: Fetches price from oracle and creates a market where user
can choose to predict above or below
- PREXPrediction: Allows user to enter a market with PREX Dollar. If wrong,
he loses PREX Dollar. If correct, he wins a portion of the entire
above+below pools.
- PREXPools: This is still under discussion but this is tentatively for
influencers to create their own pools for users to stake in. If users
choose a smart influencer to stake with, they stand to get a portion of
profits when the influencers prove to be correct. This is to encourage
users to hold PREX Tokens which are required to create pools.

Price oracles > We are planning to use Band Protocol based on the current
available choices available.

UI mockup > We are doing a madlib kind of style for the UI to make it clear
to the user what his predictions are and of course some of the figures are
dynamic and taken from the price oracles. Here's a rough mockup:

[image: image.png]

Smart contracts vs pallets > we did consider using smart contracts but were
tending more towards pallets for speed; we plan to make contracts as simple
as possible to make it easy on the players and have thus
tentatively settled on using pallets.

Might change if we decide the added layer of complexity is necessary to
require smart contracts instead.

Thanks!

**Comment by Noc2** [comment]
Thanks for the quick reply. The image file doesn’t load for me. In general could you integrate this information into the application?

**Comment by prexfinance** [comment]
Thanks for the swift reply!

I have integrated the information into the application and added the image
of the UI mockup as well.

Let me know if it's clearer now!

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the update. Do you have any additional information you could integrate or potentially previous work, before I share the application with the rest of the team? To be honest, given the current level of details and information, I think the application is too expensive.

**Comment by prexfinance** [comment]
Hi David, thanks for letting me know!

To be honest, I was hoping I could rope in one more developer and it's just
so hard to find a good developer here, wasn't planning to keep hardly
anything for myself on this project.

Just really excited about Polkadot and want to get involved!

I guess we will just bootstrap harder and make it work.

I have reduced the application amount. Do you think that would work?

Thanks again for letting me know this critical information!

**Comment by Noc2** [comment]
Thanks for the significant price reduction. That definitely helps a lot. However the total costs currently say 18,000 DAI, but the second milestone only says 1,000 DAI. Also, could you one more time try to provide a little bit more details in the application? For example, how does your solution compare to Augur? Or do you already have a whitepaper or something similar that you could link to (the website still doesn’t load for me) or even previous work?

**Comment by prexfinance** [comment]
Oh gosh, so sorry about the typo! Second one should say 10,000 DAI, I've
corrected it.

I'll take another couple days to flesh things out and let you know again.

Thanks again for being so helpful!

**Comment by prexfinance** [comment]
Hello again David,

I've added in a little more information in the application. Under the
existing ecosystem portion I was actually semi-referring to Augur as an
"existing ETH project" but just didn't want to name them outright.

We are currently working on the whitepaper and will start working on the
website when we have a clearer vision of the UI, sorry I don't have them on
hand.

I'll keep updating as we progress! I hope in its current state we can try
for submission?

Thanks!

**Comment by Noc2** [comment]
Thanks for the updates. I will share the application with the rest of the team. But before I personally approve the PR, I’d still like to have more technical details. It would help quite a lot if you could share a draft of the whitepaper once it’s ready or integrate more information into the application.

**Comment by prexfinance** [comment]
Thanks David!

Will do, I'll share whatever I can as soon as it becomes available.

**Comment by mmagician** [comment]
@prexfinance Closing for now due to inactivity. Once you've gathered the necessary technical details, please let us know and we can re-open this application.

**Pull request closed without merging**
