### PR TITLE
new application update

### PR DESCRIPTION
**Pull request by eva-networks**
# Grant Application Checklist

- [x] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [x] A BTC address for the payment of the milestones is provided inside the application.  
- [x] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [x] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@eva-networks After reading your application, I still don't have a clear picture of what you want to develop. Also, why do you want to implement your own p2p library? There's an [implementation already existing in Rust](https://github.com/libp2p/rust-libp2p).

**Comment by eva-networks** [comment]
In this grant, we would implement a library which support the privacy network protocol, named P2Private, we rename it for the libpp2p is more missleading. With the protocol lib, the substrate node would perform like a private p2p servers and we create a client for user could test it on a limit-range test net. And also more details added so people may understand the development more easier.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the open grants application. In general I’m willing to go ahead with it, but could you integrate unit-tests and an article/documentation according to the template: https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md

**Review by BenWhiteJam — COMMENTED** [review]
@eva-networks thanks for your application:
- are you planning to send all the packages from a single request through the same hop topology or will they get split up into different routes?
- what will be the IP seen by the request server? The last hop?

**Comment by eva-networks** [comment]
> Thanks for the open grants application. In general I’m willing to go ahead with it, but could you integrate unit-tests and an article/documentation according to the template: https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md

@Noc2  Thanks for notification, and the two sections have been added in application.

**Comment by eva-networks** [comment]
@BenWhiteJam thank you for your interest:

> * are you planning to send all the packages from a single request through the same hop topology or will they get split up into different routes?

After the connect created ,all packages would go through the same route, and the topology would be changed according to the arguments setup in the handshark action, if the requester want to thansfer lots of  packages, it would keep a long overdue, if request just want to send a short message, the topology would set to invalid in a shorter time.
 
> * what will be the IP seen by the request server? The last hop?

The request use a string id to identify others. If request hope to connect a specify peer, it should ask a access point node and then a Tor-like message tunnel would create between the two peers. so peers just know the IP of  adjacent points.

**Review by Noc2 — APPROVED** [review]

**Review by mmagician — APPROVED** [review]

**Review by BenWhiteJam — APPROVED** [review]
@eva-networks thanks for the update looking forward to it!

**Comment by alxs** [comment]
Hey @eva-networks, care to share a quick status update on your progress with the grant?

**Comment by eva-networks** [comment]
Hello @alxs, and  sorry for the later update on eva`s grant. 

1. The Rust version privacy protocol client has completed the final self-test;
2. Create a Grant test network and the self-test almost completed, will formally submit the two milestones soon after the documents are ready. 
3. Will launch test activities soon in our community.

Now all code open-source in https://github.com/Evanesco-Labs/WhiteNoise.rs  and https://github.com/Evanesco-Labs/WhiteNoise-For-Substrate

**Comment by alxs** [comment]
Thanks @eva-networks, looking forward to your delivery!

**Pull request merged**
