### PR TITLE
Tetrapay

### PR DESCRIPTION
**Pull request by wbqlove**
# Grant Application Checklist

- [X] The [application-template.md](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md) has been copied, renamed ( "project_name.md") and updated.
- [X] A BTC address for the payment of the milestones is provided inside the application.  
- [X] The software of the project will be released under the Apache license version 2.0 as specified in the [terms and conditions](https://gist.github.com/Noc2/75bc58e8ce9b5d419ff883b0cf2b8c19).
- [X] The total funding amount of the project is below CHF 30k at the time of submission.

### CODE REVIEW

**Comment by mmagician** [comment]
@wbqlove Thank you for your application 👍 . In order for us to consider it, we kindly ask you to sign the CLA agreement. 

Regarding the actual proposal, we require the proposals to contain a bit more information than yours currently does, including the software specifications and the documentation of the protocols, please see [here](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#project-details) for more details. The more specifications you provide, the better!

Let us know once you've updated your application.

**Comment by wbqlove** [comment]
@mmagician Thanks for the reply
The CLA has been signed. At the beginning, we used the internal chain built by the Ethereum node and adopted manual mapping to work. However, due to efficiency issues, we want to develop a mainnet by ourselves, and we want to get your help in the development. In the first phase of the main network, our main focus is to build a chain based on Substrate and implement our stablecoin algorithm on it. At present, our App is in testing. Due to the unstable local currency exchange rate, our project is still very promising. Yesterday we reached a user promotion cooperation with Dukascopy Bank.

**Comment by mmagician** [comment]
@wbqlove Thanks for signing the agreement! As per my previous comment, in order to consider your application:
> we require the proposals to contain a bit more information than yours currently does, including the software specifications and the documentation of the protocols, please see [here](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#project-details) for more details.

**Comment by wbqlove** [comment]
@mmagician  Our application has been reorganized and updated

**Comment by wbqlove** [comment]
@mmagician

> @wbqlove Thanks for signing the agreement! As per my previous comment, in order to consider your application:
> 
> > we require the proposals to contain a bit more information than yours currently does, including the software specifications and the documentation of the protocols, please see [here](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#project-details) for more details.

@mmagician We reorganized the application according to the template and added some information.

**Comment by wbqlove** [comment]
@mmagician Good afternoon, are there any suggestions for revision of our application?

**Comment by mmagician** [comment]
@wbqlove I have a few conceptual doubts:
1. Do I understand correctly that you plan to introduce two tokens: PAYARA, which has a fixed amount, and TetraPay, which has its supply fluctuate over time?
How is PAYARA initially distributed?
When you say TetraPay will be minted & burnt according to its demand, who gets the minted tokens, and who burns them?

2. Apart from that, your application still lacks supporting information. For example, milestone 1.2:

> Implement the multi-currency stablecoin algorithm

What is this algorithm?

> stable volume calculation (the optimal maximum volume to smooth the price difference)

?

> TetraX-TetraY optimal transaction path and volume price calculation.

How do you calculate such path?

This applies to most of your deliverables - they contain a lot of terminology which has not been well defined & I'm not sure how it all fits together.

**Comment by wbqlove** [comment]
@mmagician Below is the answer to your question
1.1Yes. Payara is the auxiliary currency of Tetra, has a stable quantity, and is used to help keep the value of Tetra stable. Tetra is supplied fluctuate over time.
1.2There is an initial reserve of Payara. Part of it came from a reserve at the time of payara's issuance(20%-30%), and part from the miner's collateral. As long as there are transactions in the Tetra system, the miner can receive transaction fees as a return. This non-speculative return will attract miners to mortgage Payara.
1.3About mint & burn
Tetra is minted by mortgage payara, and the minted token is issued to the mortgager. 
When Tetra deflation, the market behavior tends to exchange 1 value payara (worth as much as 1 legal tender) for 1 Tetra. This is also a minting behavior. Additional Tetra issuance will reduce the currency value and further sufficient reserves. 
The burning behavior you mentioned occurs when Tetra is inflation (the system needs to reduce the circulation to increase the value of Tetra). In this case, the system guarantees that users can still exchange 1 Tetra for 1 value payara (market guarantees that this behavior will occurs), which is equivalent to repurchasing Tetra, and then our system will burn some of them.
2.1multi-currency stablecoin algorithm
This actually represents a series of algorithms, our previous description is mainly aimed at a single currency stablecoin system (Payara - Tetra). In this step, we will implement a multi-currency stablecoin system (Payara – TetraX – TetraY …). So first we need to extend the algorithm in the single stablecoin system (in milestone 1.1) to the multi-stablecoin system, we also need to construct the stable volume calculation, TetraX-TetraY optimal transaction path and volume price calculation mentioned later.
2.2stable volume calculation (the optimal maximum volume to smooth the price difference)
We need to have an estimate of the market behavior, the calculation will be based on the current currency circulation and exchange rate, to calculate how many currencies need to be bought/sold in order to restore exchange rate stability.
2.3TetraX-TetraY optimal transaction path and volume price calculation
Assuming that TetraX is currently inflation, holders of TetraX want to exchange their currencies for the sake of stability, while continuing to enjoy the benefits of stablecoin system. 
Our system will calculate and recommend the exchange path of TetraX-payara-TetraY, TetraY maybe deflation. This calculation depends on  stable volume calculation.
In the exchange of this path, the value of the user's assets increases, and it is also beneficial to the exchange rate recovery of TetraX and TetraY.

**Comment by mmagician** [comment]
@wbqlove Thanks for providing answers to my questions.
I have some follow ups:

> There is an initial reserve of Payara. Part of it came from a reserve at the time of payara's issuance(20%-30%)

I still don't undestand who benefits from the initial distributed of Payara, is it the miners? Does it mean that only the miners who participate at network launch will be eligible to receive these tokens?

> [...] and part from the miner's collateral

What do the miners need to put down as collateral in order to receive Payara?

In addition, I fail to see the advantage of having an auxiliary intermediate currency, if at any time `the system guarantees that users can still exchange 1 Tetra for 1 value payara`. I feel like this only adds extra complexity without providing any additional benefits, since effectively they always have the same worth.

**Comment by wbqlove** [comment]
@mmagician Thank you for your reply, 
the following is an explanation of your question:

1, As a matter of fact, there are some misunderstandings. I'll try to explain them clearly.
Let's first explain the initial reserve. 
Tetra system contains a Payara pool which we call the initial reserve. (The necessity of this pool will be discussed in the next question, now let's assume that it must exist, and look at the source of Payara in the pool.)
We first release Payara before the Tetra system runs, 20~30 percent of the total issuance will be placed in the initial reserve. In addition, users who buy and hold Payara can also become miners in the Tetra system, by putting their Payara holdings into the initial reserve. Miners will get rewards such as transaction fees in the Tetra system.

2, Next, let's explain in detail the necessity of the existence of Payara as an auxiliary intermediate currency. In fact, it is an important factor in keeping the value of Tetra stable. 
First of all, we need to make it clear that Payara and Tetra are not equivalent. 
When we’re talking about “system guarantees that users can still exchange 1 Tetra for 1 value Payara”, 1 value means value 1 legal tender, for example, 1 dollar. Here, we don't care what the value of Payara is.
Then, let's take a look at the principle of keeping Tetra stable through the intermediate currency Payara. For ease of understanding, we still use the dollar as an example.
The core principle lies in the sentence you mentioned, “system guarantees that users can still exchange 1 Tetra for 1 value Payara”.
When 1Tetra >1 dollar, users can use Payara worth 1 dollar to exchange 1 Tetra in our system (mint behavior), which will expand the supply of Tetra. Expanding the money supply will result in lower prices. Not only the users in Tetra system, but even the arbitrageurs, who normally fulfill their agreements and exchange currency to the system, will get more income than they exchange currency to the secondary market and continue to lead to exchange rate deviation. 
On the other hand, 1Tetra <1 dollar. Users can use 1 Tetra to exchange Payara worth 1 dollar in our system, the only difference is that the system needs to have sufficient Payara reserves, that is why the initial reserve is necessary, and we reiterate that in the above process, we are not concerned with the price of the Payara.

**Comment by mmagician** [comment]
@wbqlove Okay thanks for another follow up. While I'm personally not convinced about your model, maybe it's just me lacking the necessary knowledge to understand the proposal. Anyway, before I share the application with my colleagues, I must ask you to further expand on your milestones. If I understood you correctly and you are building runtime modules, please refer to [this](https://github.com/w3f/Open-Grants-Program/blob/master/src/grant_guidelines_per_category.md#runtime-moduleschains) section to understand what specifications are required. We don't expect you to know everything at this stage, but the more information you provide, the higher the chances of approval - as it shows that you've done the necessary research into Substrate.

**Comment by wbqlove** [comment]
@mmagician Thank you for your suggestion，We have updated the Interactive diagram and specific interfaces in the document. Regarding our model,Under the COSMOS ecosystem, there is already a stable currency project called Terra, which has completed $32 million in financing in 2018.Terra project and our project use relatively similar algorithm logic and system models. 
We have more advantages and innovations in specific algorithm design. For example, we have introduced a scoring model in the exchange rate oracle. For details, please refer to our proposal again. 
In addition, Terra has only deployed a single stable currency project, and we have completed the project layout and algorithm design of multi- stable currency. For example, the multi-stable currency algorithm you have already asked about. 
We believe that our project will have a better development prospect than Terra.

**Review by Noc2 — CHANGES_REQUESTED** [review]
Thanks for the application. Are you aware of [acala](https://github.com/AcalaNetwork/Acala)? How is your solution different and could you potentially reuse some of their code? If I understand it correctly, you want to leverage [terra](https://terra.money/) for your own project, correct? Could you based on this specify the “Specification” of the milestones? Also it would be helpful to clarify as part of the specification that you plan to implement these features as substrate pallets written in rust. Additionally unit tests, docker and article/tutorials as part of the deliverables would be useful (see the [template](https://github.com/w3f/Open-Grants-Program/blob/master/applications/application-template.md#milestone-1-example--implement-substrate-modules)).

**Comment by wbqlove** [comment]
@Noc2 Thank you for your suggestion. We learned about Acala. Acala is a stablecoin solution based on BTC and ETH over-collateralization. However, some modules such as Oracle and Price modules can be reused. We will use these two modules of Acala and It expands to multiple currencies. We updated the documentation and reduced the development cycle and budget.
Regarding terra, our algorithm design has many similarities, but the system architecture is independently designed by us, and the modules are also planned by ourselves. We will complete it independently based on substrate;
In addition, we have also updated the document specification and delivery you mentioned.

**Comment by wbqlove** [comment]
@Noc2 Thank you for your suggestion. 
The Acala Dollar stablecoin is a multi-collateral-backed cryptocurrency, that it can be created using assets from blockchains connected to the Polkadot network including Bitcoin (BTC) and Ether (ETH) as collaterals. Some modules such as Oracle and Price modules can be reused. We will use these two modules of Acala and expands to multiple currencies. We have updated the documentation and reduced the budget.
Regarding Terra, our algorithm design has many similarities, but the system architecture and modules are designed independently, we will complete it based on substrate.
In addition, we have also updated the document specification and delivery you mentioned.

**Comment by Noc2** [comment]
@wbqlove Sorry for the late reply. We are currently fairly busy. I just have one more question: Could you also integrate some kind of UI into the deliverables, either your own UI (since it looks like you are working on this) or a simple polkadot.js demo?

**Comment by wbqlove** [comment]
@Noc2 Thank you for your reply. We will have a frontend webpage UI when we deliver it. The webpage provides all the  functionalities of TetraPay.

**Review by Noc2 — APPROVED** [review]
Thanks. Looks good to me and I will share the application again with the rest of the team. It would be nice if you could also specify which kind of programming language/framework you are going to use for the frontend.

**Comment by wbqlove** [comment]
@Noc2 Thank you for your affirmation and suggestions. We declared the front-end language and framework in the application: Node.js/Vue

**Review by Noc2 — APPROVED** [review]

**Comment by wbqlove** [comment]
@Noc2@mmagician  Merry Christmas. Is there any new progress in our application?

**Comment by Noc2** [comment]
I just sent a reminder to the rest of the team. It might take longer for them to take a look at the application due to the holidays.

**Comment by wbqlove** [comment]
> I just sent a reminder to the rest of the team. It might take longer for them to take a look at the application due to the holidays.

**Review by BenWhiteJam — APPROVED** [review]

**Comment by Noc2** [comment]
Hi @wbqlove I’m sorry but it seems we don’t get the necessary majority for this grant proposal. Therefore I’m closing the application. Feel free to submit another grant application in the future and I wish you all the best for your project.

**Pull request closed without merging**
